package com.geopista.app.cementerios.business.dao.interfaces;

import com.geopista.app.cementerios.business.vo.AnexoFeatureExample;
import com.geopista.app.cementerios.business.vo.AnexoFeatureKey;

import java.sql.SQLException;
import java.util.List;

public interface AnexoFeatureDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.anexo_feature
	 * @throws SQLException 
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	int deleteByExample(AnexoFeatureExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.anexo_feature
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	int deleteByPrimaryKey(AnexoFeatureKey key) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.anexo_feature
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	void insert(AnexoFeatureKey record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.anexo_feature
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	void insertSelective(AnexoFeatureKey record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.anexo_feature
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	List selectByExample(AnexoFeatureExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.anexo_feature
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	int updateByExampleSelective(AnexoFeatureKey record,
			AnexoFeatureExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.anexo_feature
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	int updateByExample(AnexoFeatureKey record, AnexoFeatureExample example) throws SQLException;
}