/*
 * TecnicosJPanel.java
 *
 * Created on 11 de abril de 2005, 13:06
 */

package com.geopista.app.licencias.tecnicos;

import com.geopista.app.licencias.CConstantesLicencias_LCGIII;
import com.geopista.app.licencias.CMainLicencias;
import com.geopista.app.licencias.CConstantesLicencias;
import com.geopista.app.licencias.CUtilidadesComponentes;
import com.geopista.app.licencias.CUtilidades;
import com.geopista.app.licencias.estructuras.Estructuras;
import com.geopista.app.utilidades.estructuras.ComboBoxEstructuras;
import com.geopista.protocol.licencias.CPersonaJuridicoFisica;
import com.geopista.protocol.licencias.CViaNotificacion;
import com.geopista.protocol.licencias.CDatosNotificacion;
import com.geopista.protocol.licencias.CExpedienteLicencia;
import com.geopista.protocol.licencias.CSolicitudLicencia;
import com.geopista.protocol.administrador.dominios.DomainNode;

import java.util.Vector;
import java.util.Hashtable;
import java.util.Enumeration;
import java.util.ResourceBundle;
import java.awt.*;

import org.apache.log4j.Logger;

import javax.swing.*;

/**
 *
 * @author  charo
 */
public class TecnicosJPanel extends javax.swing.JPanel {

    Logger logger = Logger.getLogger(TecnicosJPanel.class);
    private JFrame desktop;

    /**
     * Datos del Tecnico
     */

    private Hashtable _hListaTecnicos= new Hashtable();
    DefaultListModel _listTecnicosModel= new DefaultListModel();

    private String operacion= "";
    private CExpedienteLicencia expediente= null;
    private boolean emailTecnicoObligatorio= false;


    /** Creates new form TecnicosJPanel */
    public TecnicosJPanel(JFrame desktop, ResourceBundle literales) {
        initComponents();

        this.desktop= desktop;
        configureComponents();
        renombrarComponentes(literales);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        datosPersonalesTecnicoJPanel = new javax.swing.JPanel();
        DNITecnicoJLabel = new javax.swing.JLabel();
        nombreTecnicoJLabel = new javax.swing.JLabel();
        apellido1TecnicoJLabel = new javax.swing.JLabel();
        apellido2TecnicoJLabel = new javax.swing.JLabel();
        buscarDNITecnicoJButton = new javax.swing.JButton();
        colegioTecnicoJLabel = new javax.swing.JLabel();
        visadoTecnicoJLabel = new javax.swing.JLabel();
        titulacionTecnicoJLabel = new javax.swing.JLabel();
        tipoTecnicoJLabel = new javax.swing.JLabel();
        datosNotificacionTecnicoJPanel = new javax.swing.JPanel();
        viaNotificacionTecnicoJLabel = new javax.swing.JLabel();
        faxTecnicoJLabel = new javax.swing.JLabel();
        telefonoTecnicoJLabel = new javax.swing.JLabel();
        movilTecnicoJLabel = new javax.swing.JLabel();
        emailTecnicoJLabel = new javax.swing.JLabel();
        tipoViaTecnicoJLabel = new javax.swing.JLabel();
        nombreViaTecnicoJLabel = new javax.swing.JLabel();
        numeroViaTecnicoJLabel = new javax.swing.JLabel();
        portalTecnicoJLabel = new javax.swing.JLabel();
        plantaTecnicoJLabel = new javax.swing.JLabel();
        escaleraTecnicoJLabel = new javax.swing.JLabel();
        letraTecnicoJLabel = new javax.swing.JLabel();
        cPostalTecnicoJLabel = new javax.swing.JLabel();
        municipioTecnicoJLabel = new javax.swing.JLabel();
        provinciaTecnicoJLabel = new javax.swing.JLabel();
        notificarTecnicoJCheckBox = new javax.swing.JCheckBox();
        notificarTecnicoJLabel = new javax.swing.JLabel();
        annadirTecnicoJButton = new javax.swing.JButton();
        modificarTecnicoJButton = new javax.swing.JButton();
        cancelarTecnicoJButton = new javax.swing.JButton();
        tecnicosJList = new javax.swing.JList();
        eliminarTecnicoJButton = new javax.swing.JButton();
        editarTecnicoJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        datosPersonalesTecnicoJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        datosPersonalesTecnicoJPanel.setBorder(new javax.swing.border.TitledBorder("Datos Personales"));
        DNITecnicoJLabel.setText("(*) DNI/CIF:");
        datosPersonalesTecnicoJPanel.add(DNITecnicoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 90, 20));

        nombreTecnicoJLabel.setText("(*) Nombre:");
        datosPersonalesTecnicoJPanel.add(nombreTecnicoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 15, 80, 20));

        apellido1TecnicoJLabel.setText("Apellido1:");
        datosPersonalesTecnicoJPanel.add(apellido1TecnicoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, 20));

        apellido2TecnicoJLabel.setText("Apellido2:");
        datosPersonalesTecnicoJPanel.add(apellido2TecnicoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 80, 20));

        buscarDNITecnicoJButton.setIcon(new javax.swing.ImageIcon(""));
        buscarDNITecnicoJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buscarDNITecnicoJButton.setPreferredSize(new java.awt.Dimension(30, 30));
        buscarDNITecnicoJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDNITecnicoJButtonActionPerformed(evt);
            }
        });

        datosPersonalesTecnicoJPanel.add(buscarDNITecnicoJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 15, 20, 20));

        colegioTecnicoJLabel.setText("(*) Colegio:");
        datosPersonalesTecnicoJPanel.add(colegioTecnicoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 90, 20));

        visadoTecnicoJLabel.setText("(*) Visado:");
        datosPersonalesTecnicoJPanel.add(visadoTecnicoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 80, 20));

        titulacionTecnicoJLabel.setText("Titulaci\u00f3n:");
        datosPersonalesTecnicoJPanel.add(titulacionTecnicoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 90, 20));

        tipoTecnicoJLabel.setText("T\u00e9cnico:");
        datosPersonalesTecnicoJPanel.add(tipoTecnicoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 90, 20));

        add(datosPersonalesTecnicoJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 525, 140));

        datosNotificacionTecnicoJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        datosNotificacionTecnicoJPanel.setBorder(new javax.swing.border.TitledBorder("Datos Notificaci\u00f3n"));
        viaNotificacionTecnicoJLabel.setText("V\u00eda Notificaci\u00f3n:");
        datosNotificacionTecnicoJPanel.add(viaNotificacionTecnicoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 110, 20));

        faxTecnicoJLabel.setText("Fax:");
        datosNotificacionTecnicoJPanel.add(faxTecnicoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 67, 130, 20));

        telefonoTecnicoJLabel.setText("Tel\u00e9fono:");
        datosNotificacionTecnicoJPanel.add(telefonoTecnicoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 110, 20));

        movilTecnicoJLabel.setText("M\u00f3vil:");
        datosNotificacionTecnicoJPanel.add(movilTecnicoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 45, 80, 20));

        emailTecnicoJLabel.setText("Email:");
        datosNotificacionTecnicoJPanel.add(emailTecnicoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 15, 80, 20));

        tipoViaTecnicoJLabel.setText("(*) Tipo V\u00eda:");
        datosNotificacionTecnicoJPanel.add(tipoViaTecnicoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 110, 20));

        nombreViaTecnicoJLabel.setText("(*) Nombre:");
        datosNotificacionTecnicoJPanel.add(nombreViaTecnicoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 80, 20));

        numeroViaTecnicoJLabel.setText("(*) N\u00famero:");
        datosNotificacionTecnicoJPanel.add(numeroViaTecnicoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 122, 110, 20));

        portalTecnicoJLabel.setText("Portal:");
        datosNotificacionTecnicoJPanel.add(portalTecnicoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 122, 70, 20));

        plantaTecnicoJLabel.setText("Planta:");
        datosNotificacionTecnicoJPanel.add(plantaTecnicoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 122, 80, 20));

        escaleraTecnicoJLabel.setText("Escalera:");
        datosNotificacionTecnicoJPanel.add(escaleraTecnicoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 144, 80, 20));

        letraTecnicoJLabel.setText("Letra:");
        datosNotificacionTecnicoJPanel.add(letraTecnicoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 144, 80, 20));

        cPostalTecnicoJLabel.setText("(*) C\u00f3digo Postal:");
        datosNotificacionTecnicoJPanel.add(cPostalTecnicoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 166, 110, 20));

        municipioTecnicoJLabel.setText("(*) Municipio:");
        datosNotificacionTecnicoJPanel.add(municipioTecnicoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 188, 110, 20));

        provinciaTecnicoJLabel.setText("(*) Provincia:");
        datosNotificacionTecnicoJPanel.add(provinciaTecnicoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 110, 20));

        datosNotificacionTecnicoJPanel.add(notificarTecnicoJCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 30, -1));
        notificarTecnicoJCheckBox.setVisible(false);

        notificarTecnicoJLabel.setText("Notificar t\u00e9cnico:");
        datosNotificacionTecnicoJPanel.add(notificarTecnicoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 110, 20));
        notificarTecnicoJLabel.setVisible(false);
        
        annadirTecnicoJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annadirTecnicoJButtonActionPerformed(evt);
            }
        });

        datosNotificacionTecnicoJPanel.add(annadirTecnicoJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 20, 20));

        modificarTecnicoJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarTecnicoJButtonActionPerformed(evt);
            }
        });

        datosNotificacionTecnicoJPanel.add(modificarTecnicoJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 20, 20));

        cancelarTecnicoJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarTecnicoJButtonActionPerformed(evt);
            }
        });

        datosNotificacionTecnicoJPanel.add(cancelarTecnicoJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 20, 20));

        add(datosNotificacionTecnicoJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 525, 285));

        tecnicosJList.setBorder(new javax.swing.border.TitledBorder("Lista de T\u00e9cnicos"));
        tecnicosJList.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tecnicosJListFocusGained(evt);
            }
        });
        tecnicosJList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                tecnicosJListValueChanged(evt);
            }
        });
        tecnicosJList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tecnicosJListMouseClicked(evt);
            }
        });

        add(tecnicosJList, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 430, 480, 110));

        eliminarTecnicoJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarTecnicoJButtonActionPerformed(evt);
            }
        });

        add(eliminarTecnicoJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, 20, 20));

        editarTecnicoJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarTecnicoJButtonActionPerformed(evt);
            }
        });

        add(editarTecnicoJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 20, 20));

    }//GEN-END:initComponents

    private void tecnicosJListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_tecnicosJListValueChanged
        // TODO add your handling code here:
        setEnabledModificarJButton(false);
        clearTecnicosJPanel(false);

    }//GEN-LAST:event_tecnicosJListValueChanged

    private void cancelarTecnicoJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarTecnicoJButtonActionPerformed
        // TODO add your handling code here:
        clearTecnicosJPanel(false);
        inicializarBotonera();
    }//GEN-LAST:event_cancelarTecnicoJButtonActionPerformed

    private void modificarTecnicoJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarTecnicoJButtonActionPerformed
        // Modificamos los datos del tecnico
        int index= tecnicosJList.getSelectedIndex();
        if (index != -1){
             if ((_hListaTecnicos.size() > 0) && (_hListaTecnicos.size() >= index)){
                 if (camposObligatoriosOK()){
                     CPersonaJuridicoFisica tecnico= getTecnico();
                     _hListaTecnicos.put(new Integer(index), tecnico);
                     // Recargamos el elemento de la lista modificado por si a cambiado el nombre o los apellidos
                     _listTecnicosModel.set(index, CUtilidades.componerCampo(tecnico.getApellido1(), tecnico.getApellido2(), tecnico.getNombre()));
                 }else{
                     mostrarMensaje(CMainLicencias.literales.getString("TecnicosJPanel.mensaje3"));
                }

             }
        }
        clearTecnicosJPanel(false);
        inicializarBotonera();

    }//GEN-LAST:event_modificarTecnicoJButtonActionPerformed

    private void editarTecnicoJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarTecnicoJButtonActionPerformed
        // TODO add your handling code here:
        // deshabilitamos el boton de annadir
        /*
        setEnabledAnnadirJButton(false);
        setEnabledModificarJButton(true);
        */

        int index= tecnicosJList.getSelectedIndex();
        if (index != -1){
             buscarDNITecnicoJButton.setEnabled(false);
            setEnabledAnnadirJButton(false);
            if (getOperacion().equalsIgnoreCase("CONSULTA")){
                setEnabledModificarJButton(false);
            }else{
                setEnabledModificarJButton(true);
            }

             if ((_hListaTecnicos.size() > 0) && (_hListaTecnicos.size() >= index)){
                 CPersonaJuridicoFisica tecnico= (CPersonaJuridicoFisica)_hListaTecnicos.get(new Integer(index));
                 cargarDatosTecnico(tecnico);
             }
        }else{
            if (!getOperacion().equalsIgnoreCase("CONSULTA")){
                setEnabledAnnadirJButton(true);
                setEnabledModificarJButton(false);
                buscarDNITecnicoJButton.setEnabled(true);
            }else{
                setEnabledAnnadirJButton(false);
                setEnabledModificarJButton(false);
                buscarDNITecnicoJButton.setEnabled(false);
            }
        }

    }//GEN-LAST:event_editarTecnicoJButtonActionPerformed

    private void buscarDNITecnicoJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDNITecnicoJButtonActionPerformed
        // TODO add your handling code here:
        tecnicosJList.clearSelection();
        setEnabledEditarJButton(false);
        setEnabledEliminarJButton(false);
        setEnabledModificarJButton(false);
        setEnabledAnnadirJButton(true);

        CUtilidadesComponentes.showPersonaDialog(desktop,CMainLicencias.literales);

        if ((CConstantesLicencias_LCGIII.persona != null) && (CConstantesLicencias_LCGIII.persona.getDniCif() != null)) {
            clearTecnicosJPanel(false);
            cargarDatosTecnico(CConstantesLicencias_LCGIII.persona);
        }

    }//GEN-LAST:event_buscarDNITecnicoJButtonActionPerformed

    private void tecnicosJListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tecnicosJListMouseClicked
        // TODO add your handling code here:
        int index= tecnicosJList.getSelectedIndex();
        if (index != -1){
            if (getOperacion().equalsIgnoreCase("CONSULTA")){
                setEnabledEliminarJButton(false);
                setEnabledEditarJButton(true);
                setEnabledAnnadirJButton(false);
                setEnabledModificarJButton(false);
                buscarDNITecnicoJButton.setEnabled(false);
            }else{
                setEnabledEliminarJButton(true);
                setEnabledEditarJButton(true);
                setEnabledAnnadirJButton(false);
                buscarDNITecnicoJButton.setEnabled(false);
            }
        }
    }//GEN-LAST:event_tecnicosJListMouseClicked

    private void tecnicosJListFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tecnicosJListFocusGained
        // TODO add your handling code here:
        int index= tecnicosJList.getSelectedIndex();
        if (index != -1){
            if (getOperacion().equalsIgnoreCase("CONSULTA")){
                setEnabledEliminarJButton(false);
                setEnabledEditarJButton(true);
                setEnabledAnnadirJButton(false);
                setEnabledModificarJButton(false);
                buscarDNITecnicoJButton.setEnabled(false);
            }else{
                setEnabledEliminarJButton(true);
                setEnabledEditarJButton(true);
                setEnabledAnnadirJButton(false);
                buscarDNITecnicoJButton.setEnabled(false);
            }
        }

    }//GEN-LAST:event_tecnicosJListFocusGained

    private void eliminarTecnicoJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarTecnicoJButtonActionPerformed
        // TODO add your handling code here:

        if (eliminarTecnicoJButton.isEnabled()) {
            int selected = tecnicosJList.getSelectedIndex();
            if (selected != -1) {
                int ok= JOptionPane.showConfirmDialog(this, CMainLicencias.literales.getString("Licencias.confirmarBorrado"), CMainLicencias.literales.getString("Licencias.tittle"), JOptionPane.YES_NO_OPTION);
                if (ok == JOptionPane.NO_OPTION) return;

                _listTecnicosModel.remove(selected);
                /** borramos los datos del panel por si algun tecnico ha sido editado */
                clearTecnicosJPanel(false);

                Hashtable aux= new Hashtable();
                /* reordenamos la hash */
                if (_hListaTecnicos.size() > 0){
                    int j= 0;
                    for (int i= 0; i <_hListaTecnicos.size(); i++ ){
                        CPersonaJuridicoFisica t= (CPersonaJuridicoFisica)_hListaTecnicos.get(new Integer(i));
                        if (i == selected){
                            /** el tecnico borrado corresponde a la posicion i,
                             *  no lo insertamos en aux */
                        }else{
                            aux.put(new Integer(j), t);
                            j++;
                        }
                    }
                }
                _hListaTecnicos= aux;
                /** Comprobamos si algun item de la lista queda seleccionado.
                 *  Si es asi, habilitamos el boton Eliminar, si no, le deshabilitamos
                 */
                if (tecnicosJList.getModel().getSize() > 0) {
                    if (tecnicosJList.getSelectedIndex() != -1) {
                        eliminarTecnicoJButton.setEnabled(true);
                    } else {
                        eliminarTecnicoJButton.setEnabled(false);
                        inicializarBotonera();
                    }
                } else {
                    eliminarTecnicoJButton.setEnabled(false);
                    inicializarBotonera();
                }
            } else { // no ha seleccionado ningun item
                Toolkit.getDefaultToolkit().beep();
            }
        }

    }//GEN-LAST:event_eliminarTecnicoJButtonActionPerformed

    private void annadirTecnicoJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annadirTecnicoJButtonActionPerformed
        // TODO add your handling code here:
        if ((expediente != null) || (operacion.equalsIgnoreCase("CREACION"))){
            if (camposObligatoriosOK()){
                int index= _hListaTecnicos.size();
                CPersonaJuridicoFisica tecnico= getTecnico();
                if (tecnico != null){
                    _hListaTecnicos.put(new Integer(index), tecnico);
                    _listTecnicosModel.add(_hListaTecnicos.size()-1, CUtilidades.componerCampo(tecnico.getApellido1(), tecnico.getApellido2(), tecnico.getNombre()));
                    clearTecnicosJPanel(false);
                }
            }else{
                mostrarMensaje(CMainLicencias.literales.getString("TecnicosJPanel.mensaje1"));
            }
        }
    }//GEN-LAST:event_annadirTecnicoJButtonActionPerformed

    public void setEnabledAnnadirJButton(boolean b){
        annadirTecnicoJButton.setEnabled(b);
    }

    public void setEnabledEliminarJButton(boolean b){
        eliminarTecnicoJButton.setEnabled(b);
    }

    public void setEnabledEditarJButton(boolean b){
        editarTecnicoJButton.setEnabled(b);
    }

    public void setEnabledCancelarJButton(boolean b){
        cancelarTecnicoJButton.setEnabled(b);
    }

    public void setEnabledModificarJButton(boolean b){
        modificarTecnicoJButton.setEnabled(b);
    }


    private void configureComponents(){

        buscarDNITecnicoJButton.setIcon(com.geopista.app.licencias.CUtilidadesComponentes.iconoZoom);

        /** datos personales */
        DNITecnicoTField= new com.geopista.app.utilidades.TextField(CConstantesLicencias.MaxLengthDNI);
        datosPersonalesTecnicoJPanel.add(DNITecnicoTField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 15, 140, -1));
        nombreTecnicoTField= new com.geopista.app.utilidades.TextField(CConstantesLicencias.MaxLengthNombre);
        datosPersonalesTecnicoJPanel.add(nombreTecnicoTField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 15, 160, -1));
        apellido1TecnicoTField= new com.geopista.app.utilidades.TextField(CConstantesLicencias.MaxLengthApellido);
        datosPersonalesTecnicoJPanel.add(apellido1TecnicoTField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 37, 160, -1));
        apellido2TecnicoTField= new com.geopista.app.utilidades.TextField(CConstantesLicencias.MaxLengthApellido);
        datosPersonalesTecnicoJPanel.add(apellido2TecnicoTField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 37, 160, -1));
        colegioTecnicoTField= new com.geopista.app.utilidades.TextField(CConstantesLicencias.MaxLengthColegio);
        datosPersonalesTecnicoJPanel.add(colegioTecnicoTField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 67, 160, -1));
        visadoTecnicoTField= new com.geopista.app.utilidades.TextField(CConstantesLicencias.MaxLengthVisado);
        datosPersonalesTecnicoJPanel.add(visadoTecnicoTField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 67, 160, -1));
        titulacionTecnicoTField= new com.geopista.app.utilidades.TextField(CConstantesLicencias.MaxLengthTitulacion);
        datosPersonalesTecnicoJPanel.add(titulacionTecnicoTField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 89, 160, -1));

        /** datos notificacion */
        emailTecnicoTField= new com.geopista.app.utilidades.TextField(CConstantesLicencias.MaxLengthEmail);
        datosNotificacionTecnicoJPanel.add(emailTecnicoTField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 15, 150, -1));
        escaleraTecnicoTField= new com.geopista.app.utilidades.TextField(CConstantesLicencias.MaxLengthPlanta);
        datosNotificacionTecnicoJPanel.add(escaleraTecnicoTField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 144, 70, -1));
        letraTecnicoTField= new com.geopista.app.utilidades.TextField(CConstantesLicencias.MaxLengthLetra);
        datosNotificacionTecnicoJPanel.add(letraTecnicoTField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 144, 70, -1));
        municipioTecnicoTField= new com.geopista.app.utilidades.TextField(CConstantesLicencias.MaxLengthMunicipio);
        datosNotificacionTecnicoJPanel.add(municipioTecnicoTField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 188, 300, -1));
        provinciaTecnicoTField= new com.geopista.app.utilidades.TextField(CConstantesLicencias.MaxLengthProvincia);
        datosNotificacionTecnicoJPanel.add(provinciaTecnicoTField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 300, -1));
        nombreViaTecnicoTField= new com.geopista.app.utilidades.TextField(CConstantesLicencias.MaxLengthNombreVia);
        datosNotificacionTecnicoJPanel.add(nombreViaTecnicoTField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 150, -1));
        plantaTecnicoTField= new com.geopista.app.utilidades.TextField(CConstantesLicencias.MaxLengthPlanta);
        datosNotificacionTecnicoJPanel.add(plantaTecnicoTField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 122, 70, -1));
        portalTecnicoTField= new com.geopista.app.utilidades.TextField(CConstantesLicencias.MaxLengthPortal);
        datosNotificacionTecnicoJPanel.add(portalTecnicoTField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 122, 70, -1));

        cPostalTecnicoTField= new com.geopista.app.utilidades.JNumberTextField(com.geopista.app.utilidades.JNumberTextField.NUMBER, new Integer(99999), true);
        datosNotificacionTecnicoJPanel.add(cPostalTecnicoTField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 166, 70, -1));
        numeroViaTecnicoTField= new com.geopista.app.utilidades.JNumberTextField(com.geopista.app.utilidades.JNumberTextField.NUMBER, new Integer(99999), true);
        datosNotificacionTecnicoJPanel.add(numeroViaTecnicoTField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 122, 70, -1));
        telefonoTecnicoTField= new com.geopista.app.utilidades.JNumberTextField(com.geopista.app.utilidades.JNumberTextField.NUMBER, new Integer(999999999), true);
        datosNotificacionTecnicoJPanel.add(telefonoTecnicoTField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 45, 150, -1));
        movilTecnicoTField= new com.geopista.app.utilidades.JNumberTextField(com.geopista.app.utilidades.JNumberTextField.NUMBER, new Integer(999999999), true);
        datosNotificacionTecnicoJPanel.add(movilTecnicoTField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 45, 150, -1));
        faxTecnicoTField= new com.geopista.app.utilidades.JNumberTextField(com.geopista.app.utilidades.JNumberTextField.NUMBER, new Integer(999999999), true);
        datosNotificacionTecnicoJPanel.add(faxTecnicoTField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 150, -1));
 
        tipoViaNotificacionTecnicoEJCBox= new ComboBoxEstructuras(Estructuras.getListaTiposViaINE(), null, CMainLicencias.currentLocale.toString(), false);
        datosNotificacionTecnicoJPanel.add(tipoViaNotificacionTecnicoEJCBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 150, 20));
        viaNotificacionTecnicoEJCBox= new ComboBoxEstructuras(Estructuras.getListaViasNotificacion(), null, CMainLicencias.currentLocale.toString(), false);
        viaNotificacionTecnicoEJCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viaNotificacionTecnicoEJCBoxActionPerformed();}});

        datosNotificacionTecnicoJPanel.add(viaNotificacionTecnicoEJCBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 15, 150, -1));
        tipoTecnicoEJCBox= new ComboBoxEstructuras(Estructuras.getListaTiposTecnico(), null, CMainLicencias.currentLocale.toString(), false);
        datosPersonalesTecnicoJPanel.add(tipoTecnicoEJCBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 111, 160, -1));

        /** Modelo para la lista de Tecnicos */
        tecnicosJList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tecnicosJList.setModel(_listTecnicosModel);

        /** botonera */
        annadirTecnicoJButton.setIcon(com.geopista.app.licencias.CUtilidadesComponentes.iconoAdd);
        eliminarTecnicoJButton.setIcon(com.geopista.app.licencias.CUtilidadesComponentes.iconoRemove);
        editarTecnicoJButton.setIcon(com.geopista.app.licencias.CUtilidadesComponentes.iconoEditar);
        modificarTecnicoJButton.setIcon(com.geopista.app.licencias.CUtilidadesComponentes.iconoOK);
        cancelarTecnicoJButton.setIcon(com.geopista.app.licencias.CUtilidadesComponentes.iconoDeleteParcela);

    }

    public void renombrarComponentes(ResourceBundle literales)
    {
        try{
            /** Etiquetas - datos personales */
            DNITecnicoJLabel.setText(CUtilidadesComponentes.getLabelConAsterisco(literales.getString("TecnicosJPanel.DNITecnicoJLabel.text")));
            apellido1TecnicoJLabel.setText(literales.getString("TecnicosJPanel.apellido1TecnicoJLabel.text"));
            apellido2TecnicoJLabel.setText(literales.getString("TecnicosJPanel.apellido2TecnicoJLabel.text"));
            cPostalTecnicoJLabel.setText(CUtilidadesComponentes.getLabelConAsterisco(literales.getString("TecnicosJPanel.cPostalTecnicoJLabel.text")));
            colegioTecnicoJLabel.setText(literales.getString("TecnicosJPanel.colegioTecnicoJLabel.text"));
            /** Etiquetas - datos de notificacion */
            datosNotificacionTecnicoJPanel.setBorder(new javax.swing.border.TitledBorder(literales.getString("TecnicosJPanel.datosNotificacionTecnicoJPanel.TitleBorder")));
            datosPersonalesTecnicoJPanel.setBorder(new javax.swing.border.TitledBorder(literales.getString("TecnicosJPanel.datosPersonalesTecnicoJPanel.TitleBorder")));
            emailTecnicoJLabel.setText(literales.getString("TecnicosJPanel.emailTecnicoJLabel.text"));
            escaleraTecnicoJLabel.setText(literales.getString("TecnicosJPanel.escaleraTecnicoJLabel.text"));
            faxTecnicoJLabel.setText(literales.getString("TecnicosJPanel.faxTecnicoJLabel.text"));
            letraTecnicoJLabel.setText(literales.getString("TecnicosJPanel.letraTecnicoJLabel.text"));
            movilTecnicoJLabel.setText(literales.getString("TecnicosJPanel.movilTecnicoJLabel.text"));
            municipioTecnicoJLabel.setText(CUtilidadesComponentes.getLabelConAsterisco(literales.getString("TecnicosJPanel.municipioTecnicoJLabel.text")));
            nombreTecnicoJLabel.setText(CUtilidadesComponentes.getLabelConAsterisco(literales.getString("TecnicosJPanel.nombreTecnicoJLabel.text")));
            nombreViaTecnicoJLabel.setText(CUtilidadesComponentes.getLabelConAsterisco(literales.getString("TecnicosJPanel.nombreViaTecnicoJLabel.text")));
            notificarTecnicoJLabel.setText(literales.getString("TecnicosJPanel.notificarTecnicoJLabel.text"));
            numeroViaTecnicoJLabel.setText(CUtilidadesComponentes.getLabelConAsterisco(literales.getString("TecnicosJPanel.numeroViaTecnicoJLabel.text")));
            plantaTecnicoJLabel.setText(literales.getString("TecnicosJPanel.plantaTecnicoJLabel.text"));
            portalTecnicoJLabel.setText(literales.getString("TecnicosJPanel.portalTecnicoJLabel.text"));
            provinciaTecnicoJLabel.setText(CUtilidadesComponentes.getLabelConAsterisco(literales.getString("TecnicosJPanel.provinciaTecnicoJLabel.text")));
            tecnicosJList.setBorder(new javax.swing.border.TitledBorder(literales.getString("TecnicosJPanel.tecnicosJList.TitleBorder")));
            telefonoTecnicoJLabel.setText(literales.getString("TecnicosJPanel.telefonoTecnicoJLabel.text"));
            tipoViaTecnicoJLabel.setText(CUtilidadesComponentes.getLabelConAsterisco(literales.getString("TecnicosJPanel.tipoViaTecnicoJLabel.text")));
            titulacionTecnicoJLabel.setText(literales.getString("TecnicosJPanel.titulacionTecnicoJLabel.text"));
            viaNotificacionTecnicoJLabel.setText(literales.getString("TecnicosJPanel.viaNotificacionTecnicoJLabel.text"));
            visadoTecnicoJLabel.setText(literales.getString("TecnicosJPanel.visadoTecnicoJLabel.text"));
            tipoTecnicoJLabel.setText(literales.getString("TecnicosJPanel.tipoTecnicoJLabel.text"));

            /** botonera */
            annadirTecnicoJButton.setToolTipText(literales.getString("TecnicosJPanel.annadirTecnicoJButton.ToolTipText.text"));
            eliminarTecnicoJButton.setToolTipText(literales.getString("TecnicosJPanel.eliminarTecnicoJButton.ToolTipText.text"));
            editarTecnicoJButton.setToolTipText(literales.getString("TecnicosJPanel.editarTecnicoJButton.ToolTipText.text"));
            modificarTecnicoJButton.setToolTipText(literales.getString("TecnicosJPanel.modificarTecnicoJButton.ToolTipText.text"));
            cancelarTecnicoJButton.setToolTipText(literales.getString("TecnicosJPanel.cancelarTecnicoJButton.ToolTipText.text"));
            buscarDNITecnicoJButton.setToolTipText(literales.getString("TecnicosJPanel.buscarDNITecnicoJButton.ToolTipText.text"));

        }catch(Exception e){
            logger.error("Error:",e);
        }
    }


    private void viaNotificacionTecnicoEJCBoxActionPerformed() {
        String index= viaNotificacionTecnicoEJCBox.getSelectedPatron();
        if (index.equalsIgnoreCase(CConstantesLicencias.patronNotificacionEmail)){
            emailTecnicoJLabel.setText(CUtilidadesComponentes.getLabelConAsterisco(CMainLicencias.literales.getString("TecnicosJPanel.emailTecnicoJLabel.text")));
            emailTecnicoObligatorio= true;
        }else{
            emailTecnicoJLabel.setText(CMainLicencias.literales.getString("TecnicosJPanel.emailTecnicoJLabel.text"));
            emailTecnicoObligatorio= false;
        }

    }


    public boolean camposObligatoriosOK() {
        // Chequeamos que el usuario haya rellenado los campos obligatorios
        /** Comprobamos los datos del tecnico */
        // leemos los datos referentes al tecnico
        try{
            String DNI_CIF_Tecnico = DNITecnicoTField.getText();
            String nombreTecnico = nombreTecnicoTField.getText();
            String nombreViaTecnico = nombreViaTecnicoTField.getText();
            String numeroViaTecnico = numeroViaTecnicoTField.getNumber().toString();
            String cPostalTecnico = cPostalTecnicoTField.getNumber().toString();
            String municipioTecnico = municipioTecnicoTField.getText();
            String provinciaTecnico = provinciaTecnicoTField.getText();

            if ((DNI_CIF_Tecnico.trim().length() == 0) || (nombreTecnico.trim().length() == 0))
                return false;

            if (    (nombreViaTecnico.trim().length() == 0) ||
                    (numeroViaTecnico.trim().length() == 0) || (cPostalTecnico.trim().length() == 0) ||
                    (municipioTecnico.trim().length() == 0) || (provinciaTecnico.trim().length() == 0))
                return false;

            /** si ha seleccionado el tipo de notificacion por email, el campo email es obligatorio */
            if (emailTecnicoObligatorio){
                if (emailTecnicoTField.getText().trim().length() == 0) return false;
            }

        }catch(Exception e){
            return false;
        }

        return true;
    }

    private CPersonaJuridicoFisica getTecnico(){
        try{
            /* Leemos el tecnico insertado */
            // Datos personales
            int viaNotificacionIndex = new Integer(viaNotificacionTecnicoEJCBox.getSelectedPatron()).intValue();
            CViaNotificacion viaNotificacion= new CViaNotificacion(viaNotificacionIndex, "");

           /* Recogemos los datos JNumberTextField */
            String telefonoTecnico= "";
            String movilTecnico= "";
            String faxTecnico= "";
            String numeroViaTecnico= "";
            String cPostalTecnico= "";

            try{
                telefonoTecnico= telefonoTecnicoTField.getNumber().toString();
            }catch (Exception e){}
            try{
                movilTecnico= movilTecnicoTField.getNumber().toString();
            }catch (Exception e){}
            try{
                faxTecnico= faxTecnicoTField.getNumber().toString();
            }catch (Exception e){}
            try{
                numeroViaTecnico= numeroViaTecnicoTField.getNumber().toString();
            }catch (Exception e){}
            try{
                cPostalTecnico= cPostalTecnicoTField.getNumber().toString();
            }catch (Exception e){}

            CDatosNotificacion datosNotificacion = new CDatosNotificacion(DNITecnicoTField.getText().trim(),
                    viaNotificacion,
                    faxTecnico,
                    telefonoTecnico,
                    movilTecnico,
                    emailTecnicoTField.getText().trim(),
                    tipoViaNotificacionTecnicoEJCBox.getSelectedPatron(),
                    nombreViaTecnicoTField.getText().trim(),
                    numeroViaTecnico,
                    portalTecnicoTField.getText().trim(),
                    plantaTecnicoTField.getText().trim(),
                    escaleraTecnicoTField.getText().trim(),
                    letraTecnicoTField.getText().trim(),
                    cPostalTecnico,
                    municipioTecnicoTField.getText().trim(),
                    provinciaTecnicoTField.getText().trim(),
                    (notificarTecnicoJCheckBox.isSelected() ? "1" : "0"));

            logger.info("viaNotificacion.getIdViaNotificacion(): " + viaNotificacion.getIdViaNotificacion());
            logger.info("datosNotificacion.getNotificar(): " + datosNotificacion.getNotificar());

            CPersonaJuridicoFisica tecnico = new CPersonaJuridicoFisica(DNITecnicoTField.getText().trim(),
                    nombreTecnicoTField.getText().trim(),
                    apellido1TecnicoTField.getText().trim(),
                    apellido2TecnicoTField.getText().trim(),
                    colegioTecnicoTField.getText().trim(),
                    visadoTecnicoTField.getText().trim(),
                    titulacionTecnicoTField.getText().trim(),
                    datosNotificacion);
            tecnico.setPatronPerfil(tipoTecnicoEJCBox.getSelectedPatron());

            return tecnico;
        }catch (Exception e){
            return null;
        }

    }

    public void cargarDatosTecnico(CPersonaJuridicoFisica tecnico){

        clearTecnicosJPanel(false);
        if (tecnico != null){
            DNITecnicoTField.setText(tecnico.getDniCif());
            nombreTecnicoTField.setText(tecnico.getNombre());
            apellido1TecnicoTField.setText(tecnico.getApellido1());
            apellido2TecnicoTField.setText(tecnico.getApellido2());
            colegioTecnicoTField.setText(tecnico.getColegio());
            visadoTecnicoTField.setText(tecnico.getVisado());
            titulacionTecnicoTField.setText(tecnico.getTitulacion());
            viaNotificacionTecnicoEJCBox.setSelectedPatron(new Integer(tecnico.getDatosNotificacion().getViaNotificacion().getIdViaNotificacion()).toString());
            // tipo de via: calle, plaza ...
            try{
                tipoViaNotificacionTecnicoEJCBox.setSelectedPatron(tecnico.getDatosNotificacion().getTipoVia());
            }catch(Exception e){
                DomainNode auxNode=Estructuras.getListaTiposViaINE().getDomainNodeByTraduccion(tecnico.getDatosNotificacion().getTipoVia());
                if (auxNode!=null)
                        tipoViaNotificacionTecnicoEJCBox.setSelected(auxNode.getIdNode());
            }
            tipoTecnicoEJCBox.setSelectedPatron(tecnico.getPatronPerfil());

            faxTecnicoTField.setText(tecnico.getDatosNotificacion().getFax());
            telefonoTecnicoTField.setText(tecnico.getDatosNotificacion().getTelefono());
            movilTecnicoTField.setText(tecnico.getDatosNotificacion().getMovil());
            emailTecnicoTField.setText(tecnico.getDatosNotificacion().getEmail());
            nombreViaTecnicoTField.setText(tecnico.getDatosNotificacion().getNombreVia());
            numeroViaTecnicoTField.setText(tecnico.getDatosNotificacion().getNumeroVia());
            plantaTecnicoTField.setText(tecnico.getDatosNotificacion().getPlanta());
            portalTecnicoTField.setText(tecnico.getDatosNotificacion().getPortal());
            escaleraTecnicoTField.setText(tecnico.getDatosNotificacion().getEscalera());
            letraTecnicoTField.setText(tecnico.getDatosNotificacion().getLetra());
            try{
                cPostalTecnicoTField.setNumber(new Integer(tecnico.getDatosNotificacion().getCpostal()));
            }catch(Exception e){cPostalTecnicoTField.setText("");}
            municipioTecnicoTField.setText(tecnico.getDatosNotificacion().getMunicipio());
            provinciaTecnicoTField.setText(tecnico.getDatosNotificacion().getProvincia());
            /*
            if (tecnico.getDatosNotificacion().getNotificar().equalsIgnoreCase("1"))
               notificarTecnicoJCheckBox.setSelected(true);
            else notificarTecnicoJCheckBox.setSelected(false);
            */
        }

    }

    public Vector getListaTecnicos(){
        Vector v= new Vector();

        for (Enumeration e= _hListaTecnicos.elements(); e.hasMoreElements();){
            CPersonaJuridicoFisica tecnico= (CPersonaJuridicoFisica)e.nextElement();
            v.add(tecnico);
        }
         return v;
    }


    public void cargarListaTecnicos(Vector v){

        if (v != null){
            _hListaTecnicos= new Hashtable();
            int index= 0;
            for (Enumeration e= v.elements(); e.hasMoreElements();){
                CPersonaJuridicoFisica tecnico= (CPersonaJuridicoFisica)e.nextElement();
                if (tecnico != null){
                    _hListaTecnicos.put(new Integer(index), tecnico);
                    //_listTecnicosModel.add(index, ((tecnico.getApellido1()==null)?"":tecnico.getApellido1().toUpperCase().trim()) + " " + ((tecnico.getApellido2()==null)?"":tecnico.getApellido2().toUpperCase().trim()) + " " + tecnico.getNombre().toUpperCase().trim());
                    _listTecnicosModel.add(index, CUtilidades.componerCampo(tecnico.getApellido1(), tecnico.getApellido2(), tecnico.getNombre()));
                    index++;
                }
            }
        }
    }

    public boolean hayTecnicos(){

        if ((_hListaTecnicos != null) && (_hListaTecnicos.size() > 0)){
            return true;
        }
        return false;
    }

    public void inicializarBotonera(){
        /** inicializar botonera */
        tecnicosJList.clearSelection();
        if (getOperacion().equalsIgnoreCase("CONSULTA")){
            setEnabledEditarJButton(false);
            setEnabledEliminarJButton(false);
            setEnabledModificarJButton(false);
            setEnabledAnnadirJButton(false);
            buscarDNITecnicoJButton.setEnabled(false);
        }else{
            setEnabledEditarJButton(false);
            setEnabledEliminarJButton(false);
            setEnabledModificarJButton(false);
            setEnabledAnnadirJButton(true);
            buscarDNITecnicoJButton.setEnabled(true);
        }
    }

    public void clearTecnicosJPanel(boolean all){
        /** borramos campos */
        DNITecnicoTField.setText("");
        nombreTecnicoTField.setText("");
        apellido1TecnicoTField.setText("");
        apellido2TecnicoTField.setText("");
        colegioTecnicoTField.setText("");
        visadoTecnicoTField.setText("");
        titulacionTecnicoTField.setText("");
        faxTecnicoTField.setText("");
        telefonoTecnicoTField.setText("");
        movilTecnicoTField.setText("");
        emailTecnicoTField.setText("");
        nombreViaTecnicoTField.setText("");
        numeroViaTecnicoTField.setText("");
        plantaTecnicoTField.setText("");
        portalTecnicoTField.setText("");
        escaleraTecnicoTField.setText("");
        letraTecnicoTField.setText("");
        cPostalTecnicoTField.setText("");
        municipioTecnicoTField.setText("");
        provinciaTecnicoTField.setText("");
        notificarTecnicoJCheckBox.setSelected(false);
        if (all){
            _listTecnicosModel.removeAllElements();
            _hListaTecnicos= new Hashtable();
        }

    }

    public void setOperacion(String op){
        this.operacion= op;
    }

    public String getOperacion(){
        return operacion;
    }

    public void setEnabledDatosPersonalesTecnico(boolean b){
        DNITecnicoTField.setEnabled(b);
        nombreTecnicoTField.setEnabled(b);
        apellido1TecnicoTField.setEnabled(b);
        apellido2TecnicoTField.setEnabled(b);
        colegioTecnicoTField.setEnabled(b);
        visadoTecnicoTField.setEnabled(b);
        titulacionTecnicoTField.setEnabled(b);
        tipoTecnicoEJCBox.setEnabled(b);

    }


    public void setEnabledDatosNotificacionTecnico(boolean b){
        faxTecnicoTField.setEnabled(b);
        telefonoTecnicoTField.setEnabled(b);
        movilTecnicoTField.setEnabled(b);
        emailTecnicoTField.setEnabled(b);
        nombreViaTecnicoTField.setEnabled(b);
        numeroViaTecnicoTField.setEnabled(b);
        plantaTecnicoTField.setEnabled(b);
        portalTecnicoTField.setEnabled(b);
        escaleraTecnicoTField.setEnabled(b);
        letraTecnicoTField.setEnabled(b);
        cPostalTecnicoTField.setEnabled(b);
        municipioTecnicoTField.setEnabled(b);
        provinciaTecnicoTField.setEnabled(b);
        notificarTecnicoJCheckBox.setEnabled(b);
        tipoViaNotificacionTecnicoEJCBox.setEnabled(b);
        viaNotificacionTecnicoEJCBox.setEnabled(b);
    }

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(desktop, mensaje);
    }

    public void setExpediente(CExpedienteLicencia expedienteLicencia){
        expediente= expedienteLicencia;
    }

    public void setModificacion()
    {
        setOperacion("MODIFICACION");
        setEnabledEliminarJButton(false);
        setEnabledEditarJButton(false);
        setEnabledModificarJButton(false);
    }
    public void setConsulta()
    {
        setOperacion("CONSULTA");
        setEnabledDatosPersonalesTecnico(false);
        setEnabledDatosNotificacionTecnico(false);
        setEnabledEliminarJButton(false);
        setEnabledEditarJButton(false);
        setEnabledModificarJButton(false);
        setEnabledAnnadirJButton(false);
    }

    public void load(CExpedienteLicencia expediente,CSolicitudLicencia solicitud)
    {
        clearTecnicosJPanel(true);
        setExpediente(expediente);
        inicializarBotonera();
        cargarListaTecnicos(solicitud.getTecnicos());
    }

    /* Variables propias */
    private com.geopista.app.utilidades.TextField DNITecnicoTField;
    private com.geopista.app.utilidades.TextField apellido1TecnicoTField;
    private com.geopista.app.utilidades.TextField apellido2TecnicoTField;
    private com.geopista.app.utilidades.TextField colegioTecnicoTField;
    private com.geopista.app.utilidades.TextField visadoTecnicoTField;
    private com.geopista.app.utilidades.TextField emailTecnicoTField;
    private com.geopista.app.utilidades.TextField escaleraTecnicoTField;
    private com.geopista.app.utilidades.TextField letraTecnicoTField;
    private com.geopista.app.utilidades.TextField municipioTecnicoTField;
    private com.geopista.app.utilidades.TextField provinciaTecnicoTField;
    private com.geopista.app.utilidades.TextField nombreTecnicoTField;
    private com.geopista.app.utilidades.TextField nombreViaTecnicoTField;
    private com.geopista.app.utilidades.TextField plantaTecnicoTField;
    private com.geopista.app.utilidades.TextField portalTecnicoTField;
    private com.geopista.app.utilidades.TextField titulacionTecnicoTField;
    private ComboBoxEstructuras tipoViaNotificacionTecnicoEJCBox;
    private ComboBoxEstructuras viaNotificacionTecnicoEJCBox;
    private ComboBoxEstructuras tipoTecnicoEJCBox;


    private com.geopista.app.utilidades.JNumberTextField cPostalTecnicoTField;
    private com.geopista.app.utilidades.JNumberTextField numeroViaTecnicoTField;
    private com.geopista.app.utilidades.JNumberTextField telefonoTecnicoTField;
    private com.geopista.app.utilidades.JNumberTextField movilTecnicoTField;
    private com.geopista.app.utilidades.JNumberTextField faxTecnicoTField;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DNITecnicoJLabel;
    private javax.swing.JButton annadirTecnicoJButton;
    private javax.swing.JLabel apellido1TecnicoJLabel;
    private javax.swing.JLabel apellido2TecnicoJLabel;
    private javax.swing.JButton buscarDNITecnicoJButton;
    private javax.swing.JLabel cPostalTecnicoJLabel;
    private javax.swing.JButton cancelarTecnicoJButton;
    private javax.swing.JLabel colegioTecnicoJLabel;
    private javax.swing.JPanel datosNotificacionTecnicoJPanel;
    private javax.swing.JPanel datosPersonalesTecnicoJPanel;
    private javax.swing.JButton editarTecnicoJButton;
    private javax.swing.JButton eliminarTecnicoJButton;
    private javax.swing.JLabel emailTecnicoJLabel;
    private javax.swing.JLabel escaleraTecnicoJLabel;
    private javax.swing.JLabel faxTecnicoJLabel;
    private javax.swing.JLabel letraTecnicoJLabel;
    private javax.swing.JButton modificarTecnicoJButton;
    private javax.swing.JLabel movilTecnicoJLabel;
    private javax.swing.JLabel municipioTecnicoJLabel;
    private javax.swing.JLabel nombreTecnicoJLabel;
    private javax.swing.JLabel nombreViaTecnicoJLabel;
    private javax.swing.JCheckBox notificarTecnicoJCheckBox;
    private javax.swing.JLabel notificarTecnicoJLabel;
    private javax.swing.JLabel numeroViaTecnicoJLabel;
    private javax.swing.JLabel plantaTecnicoJLabel;
    private javax.swing.JLabel portalTecnicoJLabel;
    private javax.swing.JLabel provinciaTecnicoJLabel;
    private javax.swing.JList tecnicosJList;
    private javax.swing.JLabel telefonoTecnicoJLabel;
    private javax.swing.JLabel tipoTecnicoJLabel;
    private javax.swing.JLabel tipoViaTecnicoJLabel;
    private javax.swing.JLabel titulacionTecnicoJLabel;
    private javax.swing.JLabel viaNotificacionTecnicoJLabel;
    private javax.swing.JLabel visadoTecnicoJLabel;
    // End of variables declaration//GEN-END:variables
    
}
