/**
 * GeopistaEntidadesMunicipiosDAOImpl.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.localgis.web.core.dao.sqlmap;

import com.ibatis.dao.client.DaoManager;
import com.ibatis.dao.client.template.SqlMapDaoTemplate;
import com.localgis.web.core.dao.GeopistaEntidadesMunicipiosDAO;
import com.localgis.web.core.model.GeopistaEntidadesMunicipiosKey;

public class GeopistaEntidadesMunicipiosDAOImpl extends SqlMapDaoTemplate implements GeopistaEntidadesMunicipiosDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table public.entidades_municipios
	 * @ibatorgenerated  Thu Mar 31 17:21:03 CEST 2011
	 */
	public GeopistaEntidadesMunicipiosDAOImpl(DaoManager daoManager) {
		super(daoManager);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table public.entidades_municipios
	 * @ibatorgenerated  Thu Mar 31 17:21:03 CEST 2011
	 */
	public int deleteByPrimaryKey(GeopistaEntidadesMunicipiosKey key) {
		int rows = delete(
				"geopista_entidades_municipios.ibatorgenerated_deleteByPrimaryKey",
				key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table public.entidades_municipios
	 * @ibatorgenerated  Thu Mar 31 17:21:03 CEST 2011
	 */
	public void insert(GeopistaEntidadesMunicipiosKey record) {
		insert("geopista_entidades_municipios.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table public.entidades_municipios
	 * @ibatorgenerated  Thu Mar 31 17:21:03 CEST 2011
	 */
	public void insertSelective(GeopistaEntidadesMunicipiosKey record) {
		insert("geopista_entidades_municipios.ibatorgenerated_insertSelective",
				record);
	}
	
	public GeopistaEntidadesMunicipiosKey selectByPrimaryKey(Integer idMunicipio) {
		GeopistaEntidadesMunicipiosKey key = new GeopistaEntidadesMunicipiosKey();
		key.setIdMunicipio(idMunicipio);
		GeopistaEntidadesMunicipiosKey record = (GeopistaEntidadesMunicipiosKey) queryForObject(
				"geopista_entidades_municipios.ibatorgenerated_selectByPrimaryKey",
				key);
		return record;
	}
}