/**
 * GeopistaEntidadSupramunicipalDAOImpl.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.localgis.web.core.dao.sqlmap;

import java.util.List;
import java.util.HashMap;
import java.util.Map;

import com.ibatis.dao.client.DaoManager;
import com.ibatis.dao.client.template.SqlMapDaoTemplate;
import com.localgis.web.core.dao.GeopistaEntidadSupramunicipalDAO;
import com.localgis.web.core.model.GeopistaEntidadSupramunicipal;

public class GeopistaEntidadSupramunicipalDAOImpl extends SqlMapDaoTemplate implements GeopistaEntidadSupramunicipalDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table public.entidad_supramunicipal
     *
     * @ibatorgenerated Thu Jul 09 10:50:43 CEST 2009
     */
    public GeopistaEntidadSupramunicipalDAOImpl(DaoManager daoManager) {
        super(daoManager);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table public.entidad_supramunicipal
     *
     * @ibatorgenerated Thu Jul 09 10:50:43 CEST 2009
     */
    public GeopistaEntidadSupramunicipal selectByPrimaryKey(Integer idEntidad) {
        GeopistaEntidadSupramunicipal key = new GeopistaEntidadSupramunicipal();
        key.setIdEntidad(idEntidad);
        GeopistaEntidadSupramunicipal record = (GeopistaEntidadSupramunicipal) queryForObject("public_entidad_supramunicipal.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /*
     * (non-Javadoc)
     * @see com.localgis.web.core.dao.GeopistaEntidadSupramunicipalDAO#selectAll()
     */
    public List selectAll() {
		Map params = new HashMap();
        List list = queryForList("public_entidad_supramunicipal.selectAll",params);
        return list;
    }
}