package com.geopista.app.contaminantes.arbolado;
/**
 * The GEOPISTA project is a set of tools and applications to manage
 * geographical data for local administrations.
 *
 * Copyright (C) 2004 INZAMAC-SATEC UTE
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
 USA.
 *
 * For more information, contact:
 *
 *
 * www.geopista.com
 *
 *
 */

import org.apache.log4j.Logger;

import javax.swing.*;
import javax.swing.table.TableColumn;

import java.util.HashMap;
import java.util.Map;
import java.util.ResourceBundle;
import java.util.Vector;
import java.util.Enumeration;
import java.util.Hashtable;
import java.awt.*;
import java.io.*;
import java.sql.Driver;
import java.sql.DriverManager;

import com.geopista.app.AppContext;
import com.geopista.app.reports.GenerarInformeExterno;
import com.geopista.app.utilidades.TableSorted;
import com.geopista.app.utilidades.estructuras.ComboBoxEstructuras;
import com.geopista.app.contaminantes.estructuras.Estructuras;
import com.geopista.app.contaminantes.util.CUtilidades;
import com.geopista.protocol.contaminantes.CConstantes;
import com.geopista.protocol.contaminantes.Contaminante;
import com.geopista.protocol.contaminantes.OperacionesContaminantes;
import com.geopista.protocol.contaminantes.Arbolado;
import com.geopista.protocol.CResultadoOperacion;
import com.geopista.protocol.contaminantes.CPlantilla;


/**
 *
 * @author  charo
 */
public class JFrameInformes extends javax.swing.JInternalFrame{

    Logger logger = Logger.getLogger(JFrameInformes.class);
    private ResourceBundle messages;
    private JFrame frame;
    ArboladoTableModel modelArbolado;
    Vector _vArbolado= null;
    private TableSorted sorter;

    private static AppContext aplicacion = (AppContext) AppContext.getApplicationContext();
    /*
     * Almacenamos el listado con el num_expediente que utilizaremos en el ireport:
     * */
    private String lista_expedientes = "";
    
    /** Creates new form JFrameInformes */
    public JFrameInformes(ResourceBundle messages, JFrame frame) {
        this.frame=frame;
        this.messages = messages;
        initComponents();
        initComboBoxesEstructuras();

        String[] columnNames = {messages.getString("jMenuItemArboladoInformes.jTableListado.column1"),
                                messages.getString("jMenuItemArboladoInformes.jTableListado.column2"),
                                messages.getString("jMenuItemArboladoInformes.jTableListado.column3")};

        ArboladoTableModel.setColumnNames(columnNames);
        modelArbolado= new ArboladoTableModel();
        jTableListado.setModel(modelArbolado);
        cargarArbolado();
        cargarPlantillas();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanelPrincipal = new javax.swing.JPanel();
        jPanelTotal = new javax.swing.JPanel();
        //jPanelBotonera = new javax.swing.JPanel();
        jButtonGenerarInformes= new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jTabbedPaneDatos = new javax.swing.JTabbedPane();
        jPanelDatos = new javax.swing.JPanel();
        jPanelListado = new javax.swing.JPanel();
        jScrollPaneListado = new javax.swing.JScrollPane();
        jTableListado = new javax.swing.JTable();
        /*
        nombreInformeJLabel= new javax.swing.JLabel();
        nombreInformeJTField= new javax.swing.JTextField();
        */
        plantillaJCBox = new javax.swing.JComboBox();
        plantillaJLabel= new javax.swing.JLabel();
//        formatoJLabel= new javax.swing.JLabel();
        //formatoSalidaEJCBox= new ComboBoxEstructuras(Estructuras.getListaFormatosSalida(), null, com.geopista.app.contaminantes.init.Constantes.Locale, false);


        jPanelPrincipal.setLayout(new java.awt.BorderLayout());
        /*
        jPanelBotonera.add(jButtonGenerarInformes);
        jButtonGenerarInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarInforme();
            }
        });
        */

        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir();
            }
        });
        jPanelTotal.add(jButtonSalir);
        //jPanelPrincipal.add(jPanelBotonera, java.awt.BorderLayout.SOUTH);
        jTabbedPaneDatos.setBorder(new javax.swing.border.EtchedBorder());
        jPanelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        /*
        nombreInformeJLabel.setText(messages.getString("jMenuItemArboladoInformes.nombreInformeJLabel"));
        jPanelDatos.add(nombreInformeJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
        jPanelDatos.add(nombreInformeJTField, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 30, 290, -1));
        */
        jPanelDatos.add(jButtonGenerarInformes, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));
        jButtonGenerarInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarInforme();
            }
        });

        plantillaJLabel.setText(messages.getString("jMenuItemArboladoInformes.plantillaJLabel"));
        jPanelDatos.add(plantillaJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
        jPanelDatos.add(plantillaJCBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 30, 290, -1));

//        formatoJLabel.setText(messages.getString("jMenuItemArboladoInformes.formatoJLabel"));
//        jPanelDatos.add(formatoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        //jPanelDatos.add(formatoSalidaEJCBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 290, -1));

        jPanelListado.setLayout(new java.awt.BorderLayout());
        jScrollPaneListado.setViewportView(jTableListado);
        jPanelListado.add(jScrollPaneListado, java.awt.BorderLayout.CENTER);
        JPanel auxPanel= new JPanel();
        auxPanel.setLayout(new java.awt.BorderLayout());
        auxPanel.add(jPanelDatos,java.awt.BorderLayout.SOUTH);
        auxPanel.add(jPanelListado,java.awt.BorderLayout.CENTER);
        jTabbedPaneDatos.addTab(messages.getString("jMenuItemArboladoInformes.jTabbedPaneDatos"), auxPanel);
        jPanelPrincipal.add(jTabbedPaneDatos, java.awt.BorderLayout.CENTER);
        changeScreenLang(messages);
        jPanelPrincipal.setMinimumSize(new Dimension(600,600));

        //getContentPane().add(jPanelPrincipal, java.awt.BorderLayout.WEST);
        getContentPane().add(jPanelPrincipal, java.awt.BorderLayout.CENTER);
        getContentPane().add(jPanelTotal, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents


      private void cargarArbolado(){

        try{
             _vArbolado= (new OperacionesContaminantes(com.geopista.app.contaminantes.init.Constantes.url)).getArbolados();
             if (_vArbolado == null){
                 logger.warn("No existen zonas arboladas en el sistema");
                 mostrarMensaje(messages.getString("jMenuItemArboladoInformes.mensaje1"), messages.getString("jMenuItemArboladoInformes.mensajeTittle1"));
                 jButtonGenerarInformes.setEnabled(false);
             }else{
           	  lista_expedientes = "";
        	  for (int i = 0; i < _vArbolado.size(); i++) {
                  Arbolado arbolado = (Arbolado) _vArbolado.elementAt(i);
                  lista_expedientes += "'"+arbolado.getId()+"'";
                  if (i < _vArbolado.size()-1){
                  	lista_expedientes += ", ";
                  }
              }     
                 actualizarModelo();
             }

        }catch(Exception e){
            StringWriter sw = new StringWriter();
            PrintWriter pw = new PrintWriter(sw);
            e.printStackTrace(pw);
            logger.error("Exception: " + sw.toString());
		 }
    }


    private void salir(){
        /** volvemos a registrar el driver GEOPISTADriver */
        String classForName= "com.geopista.sql.GEOPISTADriver";
        try{
            Driver dPista= (Driver)Class.forName(classForName).newInstance();
            DriverManager.registerDriver(dPista);
        }catch(Exception e){
            logger.debug(".................Class.forNmae " + classForName + " " + e.getMessage());
        }

        dispose();
    }

     public void changeScreenLang(ResourceBundle messages){
         try
         {
            this.messages=messages;
            setTitle(messages.getString("jMenuItemArboladoInformes.tittle"));
            jButtonGenerarInformes.setText(messages.getString("jMenuItemArboladoInformes.jButtonGenerarInformes"));
            jButtonSalir.setText(messages.getString("jMenuItemArboladoInformes.jButtonSalir"));

             jButtonGenerarInformes.setToolTipText(messages.getString("jMenuItemArboladoInformes.jButtonGenerarInformes"));
             jButtonSalir.setToolTipText(messages.getString("jMenuItemArboladoInformes.jButtonSalir"));

             plantillaJLabel.setText(messages.getString("jMenuItemArboladoInformes.plantillaJLabel"));
//             formatoJLabel.setText(messages.getString("jMenuItemArboladoInformes.formatoJLabel"));

             /** Headers de la tabla eventos */
             TableColumn tableColumn= jTableListado.getColumnModel().getColumn(0);
             tableColumn.setHeaderValue(messages.getString("jMenuItemArboladoInformes.jTableListado.column1"));
             tableColumn= jTableListado.getColumnModel().getColumn(1);
             tableColumn.setHeaderValue(messages.getString("jMenuItemArboladoInformes.jTableListado.column2"));
             tableColumn= jTableListado.getColumnModel().getColumn(2);
             tableColumn.setHeaderValue(messages.getString("jMenuItemArboladoInformes.jTableListado.column3"));

             jTabbedPaneDatos.setTitleAt(0, messages.getString("jMenuItemArboladoInformes.jTabbedPaneDatos"));
         }catch(Exception e)
         {}
     }

    private void actualizarModelo(){
        modelArbolado.setModelData(_vArbolado);
        sorter = new TableSorted(modelArbolado);
        sorter.setTableHeader(jTableListado.getTableHeader());
        jTableListado.setModel(sorter);
        jTableListado.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
    }



    /**
     * Informes
     */

    /** Fuente de datos Charsep File */
    /*
        private void generarInforme(){
        try{

            if ((_vArbolado != null) && (_vArbolado.size() > 0) ){

                boolean error= false;

                // De toda la informacion generada, mostraremos informe de la arboleda seleccionada
                Vector arboledaSelected= new Vector();

                int[] selected= jTableListado.getSelectedRows();
                if (selected.length > 0){
                    for (int i=0; i<selected.length; i++){
                        int index= selected[i];
                        arboledaSelected.addElement(_vArbolado.get(index));
                    }
                }else{
                    arboledaSelected= _vArbolado;
                }

                if ((arboledaSelected != null) && (arboledaSelected.size() > 0)){
                    // si no existe, creamos el directorio
                    File f= new File(com.geopista.protocol.contaminantes.CConstantes.PLANTILLAS_PATH_ARBOLADO + "datos.csv");
                    if (!f.getParentFile().exists()) {
                      f.getParentFile().mkdirs();
                    }
                    // Si ya existe, borramos el fichero de datos
                    if (f.exists()) {
                      f.delete();
                    }

                    // creamos el fichero de datos delimitado por comas
                    Writer stream  = new FileWriter(com.geopista.protocol.contaminantes.CConstantes.PLANTILLAS_PATH_ARBOLADO +"datos.csv", true);
                    String charsep= ",";
                    for (int j=0; j<arboledaSelected.size(); j++){
                        Arbolado arbolado= (Arbolado)arboledaSelected.get(j);
                        String datos= arbolado.getId() + charsep + arbolado.getExt() + charsep + arbolado.getObs();

                        stream.write(datos);
                        // salto de linea
                        stream.write(10);
                    }
                    stream.close();

                    // Generamos el informe con la informacion

                    // bajamos del servidor la plantilla seleccionada por el usuario
                    // y el fichero de parámetros, que siempre sera el mismo
                    // independientemente de la plantilla seleccionada
                    CPlantilla p= new CPlantilla();
                    p.setPath(com.geopista.protocol.contaminantes.CConstantes.PLANTILLAS_PATH_ARBOLADO);
                    p.setFileName((String)plantillaJCBox.getSelectedItem());
                    Vector v= CUtilidades.bajarXMLFiles(p);
                    if ((v != null) && (v.size() > 0)){
                        try {

                            String nombreInforme= nombreInformeJTField.getText();
                            if ((nombreInforme.trim().length() == 0) || (nombreInforme.startsWith("."))) nombreInforme= "output";

                            String formato= formatoSalidaEJCBox.getSelectedPatron();
                            CUtilidades.crearReportCharSepSource(v, com.geopista.protocol.contaminantes.CConstantes.PLANTILLAS_PATH_ARBOLADO, nombreInforme, formato);

                        }catch (Exception e) {
                            error= true;
                            mostrarMensaje(messages.getString("jMenuItemArboladoInformes.mensaje2"), messages.getString("jMenuItemArboladoInformes.mensajeTittle1"));
                            e.printStackTrace();
                            logger.error("exception thrown: " + e);
                        }

                        if ((!error) && (new Integer(formatoSalidaEJCBox.getSelectedPatron()).intValue() != com.geopista.app.contaminantes.init.Constantes.formatoPREVIEW)){
                            mostrarMensaje(messages.getString("jMenuItemArboladoInformes.mensaje3"), messages.getString("jMenuItemArboladoInformes.mensajeTittle1"));
                        }
                    }
                }else{
                    mostrarMensaje(messages.getString("jMenuItemArboladoInformes.mensaje4"), messages.getString("jMenuItemArboladoInformes.mensajeTittle1"));
                }
            }
        }catch(Exception e){
            mostrarMensaje(messages.getString("jMenuItemArboladoInformes.mensaje2"), messages.getString("jMenuItemArboladoInformes.mensajeTittle1"));
            StringWriter sw = new StringWriter();
            PrintWriter pw = new PrintWriter(sw);
            e.printStackTrace(pw);
            logger.error("Exception: " + sw.toString());
        }

        }

    private void generarInforme(){
                
        try{
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

            if ((_vArbolado != null) && (_vArbolado.size() > 0) ){

                boolean error= false;

                    // Generamos el informe con la informacion

                    // bajamos del servidor la plantilla seleccionada por el usuario
                    // y el fichero de parámetros, que siempre sera el mismo
                    // independientemente de la plantilla seleccionada
                    CPlantilla p= new CPlantilla();
                    p.setPath(com.geopista.protocol.contaminantes.CConstantes.PLANTILLAS_PATH_ARBOLADO);
                    p.setFileName((String)plantillaJCBox.getSelectedItem());
                    Hashtable h= CUtilidades.bajarXMLFiles(p);
                    if ((h != null) && (h.size() > 0)){
                        try {
                            // Abrimos el dialogo showSaveDialog en el caso de que el formato no sea PREVIEW
                            boolean b= (new Integer(formatoSalidaEJCBox.getSelectedPatron()).intValue() == com.geopista.app.contaminantes.init.Constantes.formatoPREVIEW)?false:true;
                            File file= CUtilidades.showSaveFileDialog(b, messages, frame, formatoSalidaEJCBox.getSelectedPatron());
                            if ((file == null) && (b)) return;

                            String nombreInforme= "";
                            String path= "";
                            if (file != null){
                                nombreInforme= file.getName();
                                int index= nombreInforme.indexOf(".");
                                if (index != -1){
                                    nombreInforme= nombreInforme.substring(0, index);
                                }
                                path= file.getAbsolutePath();
                                index= path.indexOf(nombreInforme);
                                if (index != -1){
                                    path= path.substring(0, index);
                                }
                                // Si ya existe, borramos el fichero de datos
                                if (file.exists()) {
                                  file.delete();
                                }
                            }

                            CUtilidades.crearReportBDSource(h, com.geopista.protocol.contaminantes.CConstantes.PLANTILLAS_PATH_ARBOLADO, nombreInforme, formatoSalidaEJCBox.getSelectedPatron(), path, "ARBOLADO");

                        }catch (Exception e) {
                            error= true;
                            mostrarMensaje(messages.getString("jMenuItemArboladoInformes.mensaje2"), messages.getString("jMenuItemArboladoInformes.mensajeTittle1"));
                            e.printStackTrace();
                            logger.error("exception thrown: " + e);
                        }

                        if ((!error) && (new Integer(formatoSalidaEJCBox.getSelectedPatron()).intValue() != com.geopista.app.contaminantes.init.Constantes.formatoPREVIEW)){
                            mostrarMensaje(messages.getString("jMenuItemArboladoInformes.mensaje3"), messages.getString("jMenuItemArboladoInformes.mensajeTittle1"));
                        }
                    }
                }else{
                  mostrarMensaje(messages.getString("jMenuItemArboladoInformes.mensaje4"), messages.getString("jMenuItemArboladoInformes.mensajeTittle1"));
            }

        }catch(Exception e){
            mostrarMensaje(messages.getString("jMenuItemArboladoInformes.mensaje2"), messages.getString("jMenuItemArboladoInformes.mensajeTittle1"));
            StringWriter sw = new StringWriter();
            PrintWriter pw = new PrintWriter(sw);
            e.printStackTrace(pw);
            logger.error("Exception: " + sw.toString());
        }
        this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));

    }
*/
    
    private void generarInforme(){
    	String pathDestino = "";
        try{
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

            if ((_vArbolado != null) && (_vArbolado.size() > 0) ){


                    // Generamos el informe con la informacion

                    // bajamos del servidor la plantilla seleccionada por el usuario

                    CPlantilla p= new CPlantilla();
                    p.setPath(CConstantes.PLANTILLAS_PATH_ARBOLADO);
                    
                    String localPath = aplicacion.getUserPreference(AppContext.PREFERENCES_DATA_PATH_KEY,AppContext.DEFAULT_DATA_PATH, true);
                    pathDestino = localPath + aplicacion.REPORT_DIR_NAME + File.separator + CConstantes.PLANTILLAS_PATH_ARBOLADO + (String)plantillaJCBox.getSelectedItem();
                    
                    p.setFileName((String)plantillaJCBox.getSelectedItem());
                    boolean encontrado = CUtilidades.bajarInformeFiles(p, CConstantes.PLANTILLAS_PATH_ARBOLADO);

                    if (encontrado){
                        try {

                        	Map parametros = obtenerParametros();			

    						GenerarInformeExterno giep=new GenerarInformeExterno(pathDestino, parametros);
    					}catch (Exception e) {
                            mostrarMensaje(messages.getString("jMenuItemArboladoInformes.mensaje2"), messages.getString("jMenuItemArboladoInformes.mensajeTittle1"));
                            e.printStackTrace();
                            logger.error("exception thrown: " + e);
                        }

                    }
                }else{
                  mostrarMensaje(messages.getString("jMenuItemArboladoInformes.mensaje4"), messages.getString("jMenuItemArboladoInformes.mensajeTittle1"));
                }

            }catch(Exception e){
                mostrarMensaje(messages.getString("jMenuItemArboladoInformes.mensaje2"), messages.getString("jMenuItemArboladoInformes.mensajeTittle1"));
                StringWriter sw = new StringWriter();
                PrintWriter pw = new PrintWriter(sw);
                e.printStackTrace(pw);
                logger.error("Exception: " + sw.toString());
            }

            this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
     }

    
    public void cargarPlantillas(){
        try {
            CPlantilla p= new CPlantilla();
            p.setPath(com.geopista.protocol.contaminantes.CConstantes.PLANTILLAS_PATH_ARBOLADO);
            CResultadoOperacion ro= new OperacionesContaminantes(com.geopista.app.contaminantes.init.Constantes.url).getPlantillas(p);
            Vector plantillas= ro.getVector();
            if (plantillas != null){
                Enumeration enumeration = plantillas.elements();
                while (enumeration.hasMoreElements()) {
                    CPlantilla plantilla= (CPlantilla) enumeration.nextElement();
                    logger.debug("plantilla.getFileName="+plantilla.getFileName());
                    plantillaJCBox.addItem(plantilla.getFileName());
                }
            }
        } catch (Exception ex) {
            StringWriter sw = new StringWriter();
            PrintWriter pw = new PrintWriter(sw);
            ex.printStackTrace(pw);
            logger.error("Exception: " + sw.toString());
        }
    }


    public void initComboBoxesEstructuras(){
        while (!Estructuras.isCargada())
        {
            if (!Estructuras.isIniciada()) Estructuras.cargarEstructuras();
            try {Thread.sleep(500);}catch(Exception e){}
        }

//        formatoSalidaEJCBox= new ComboBoxEstructuras(Estructuras.getListaFormatosSalida(), null, com.geopista.app.contaminantes.init.Constantes.Locale, false);
//        jPanelDatos.add(formatoSalidaEJCBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 50, 290, -1));

    }

    public void mostrarMensaje(String mensaje, String tittle) {
        JOptionPane.showMessageDialog(jPanelDatos, mensaje, tittle, JOptionPane.INFORMATION_MESSAGE);
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGenerarInformes;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel plantillaJLabel;
    private javax.swing.JComboBox plantillaJCBox;
//    private javax.swing.JLabel formatoJLabel;
//    private ComboBoxEstructuras formatoSalidaEJCBox ;
    /*
    private javax.swing.JLabel nombreInformeJLabel;
    private javax.swing.JTextField nombreInformeJTField;
    */

    //private javax.swing.JPanel jPanelBotonera;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelListado;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelTotal;
    private javax.swing.JScrollPane jScrollPaneListado;
    private javax.swing.JTabbedPane jTabbedPaneDatos;
    private javax.swing.JTable jTableListado;
    // End of variables declaration//GEN-END:variables

    private Map obtenerParametros(){
        
		Map parametros = new HashMap();
		parametros.put("lista_expedientes", lista_expedientes);
		parametros.put("locale", aplicacion.getI18NResource().getLocale().toString());
		parametros.put("id_municipio", aplicacion.getIdMunicipio());
		return parametros;
    }
    
}
