package com.geopista.app.cementerios.business.vo;

public class AnexoCementerio extends AnexoCementerioKey {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cementerio.anexo_cementerio.tipo
     *
     * @ibatorgenerated Mon Jul 11 14:45:21 CEST 2011
     */
    private String tipo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cementerio.anexo_cementerio.subtipo
     *
     * @ibatorgenerated Mon Jul 11 14:45:21 CEST 2011
     */
    private String subtipo;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cementerio.anexo_cementerio.tipo
     *
     * @return the value of cementerio.anexo_cementerio.tipo
     *
     * @ibatorgenerated Mon Jul 11 14:45:21 CEST 2011
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cementerio.anexo_cementerio.tipo
     *
     * @param tipo the value for cementerio.anexo_cementerio.tipo
     *
     * @ibatorgenerated Mon Jul 11 14:45:21 CEST 2011
     */
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cementerio.anexo_cementerio.subtipo
     *
     * @return the value of cementerio.anexo_cementerio.subtipo
     *
     * @ibatorgenerated Mon Jul 11 14:45:21 CEST 2011
     */
    public String getSubtipo() {
        return subtipo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cementerio.anexo_cementerio.subtipo
     *
     * @param subtipo the value for cementerio.anexo_cementerio.subtipo
     *
     * @ibatorgenerated Mon Jul 11 14:45:21 CEST 2011
     */
    public void setSubtipo(String subtipo) {
        this.subtipo = subtipo;
    }
}