package com.geopista.app.cementerios.business.vo;

import java.math.BigDecimal;

public class ElemFeature {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.elem_feature.id
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.elem_feature.id_elem
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	private Integer idElem;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.elem_feature.id_layer
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	private String idLayer;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.elem_feature.id_cementerio
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	private Integer idCementerio;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.elem_feature.tipo
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	private String tipo;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.elem_feature.subtipo
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	private String subtipo;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.elem_feature.nombre
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	private String nombre;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.elem_feature.entidad
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	private String entidad;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.elem_feature.id_feature
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	private Integer idFeature;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.elem_feature.id_municipio
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	private Integer idMunicipio;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.elem_feature.id
	 * @return  the value of cementerio.elem_feature.id
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.elem_feature.id
	 * @param id  the value for cementerio.elem_feature.id
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.elem_feature.id_elem
	 * @return  the value of cementerio.elem_feature.id_elem
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	public Integer getIdElem() {
		return idElem;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.elem_feature.id_elem
	 * @param idElem  the value for cementerio.elem_feature.id_elem
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	public void setIdElem(Integer idElem) {
		this.idElem = idElem;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.elem_feature.id_layer
	 * @return  the value of cementerio.elem_feature.id_layer
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	public String getIdLayer() {
		return idLayer;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.elem_feature.id_layer
	 * @param idLayer  the value for cementerio.elem_feature.id_layer
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	public void setIdLayer(String idLayer) {
		this.idLayer = idLayer;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.elem_feature.id_cementerio
	 * @return  the value of cementerio.elem_feature.id_cementerio
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	public Integer getIdCementerio() {
		return idCementerio;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.elem_feature.id_cementerio
	 * @param idCementerio  the value for cementerio.elem_feature.id_cementerio
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	public void setIdCementerio(Integer idCementerio) {
		this.idCementerio = idCementerio;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.elem_feature.tipo
	 * @return  the value of cementerio.elem_feature.tipo
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	public String getTipo() {
		return tipo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.elem_feature.tipo
	 * @param tipo  the value for cementerio.elem_feature.tipo
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.elem_feature.subtipo
	 * @return  the value of cementerio.elem_feature.subtipo
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	public String getSubtipo() {
		return subtipo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.elem_feature.subtipo
	 * @param subtipo  the value for cementerio.elem_feature.subtipo
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	public void setSubtipo(String subtipo) {
		this.subtipo = subtipo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.elem_feature.nombre
	 * @return  the value of cementerio.elem_feature.nombre
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.elem_feature.nombre
	 * @param nombre  the value for cementerio.elem_feature.nombre
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.elem_feature.entidad
	 * @return  the value of cementerio.elem_feature.entidad
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	public String getEntidad() {
		return entidad;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.elem_feature.entidad
	 * @param entidad  the value for cementerio.elem_feature.entidad
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	public void setEntidad(String entidad) {
		this.entidad = entidad;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.elem_feature.id_feature
	 * @return  the value of cementerio.elem_feature.id_feature
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	public Integer getIdFeature() {
		return idFeature;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.elem_feature.id_feature
	 * @param idFeature  the value for cementerio.elem_feature.id_feature
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	public void setIdFeature(Integer idFeature) {
		this.idFeature = idFeature;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.elem_feature.id_municipio
	 * @return  the value of cementerio.elem_feature.id_municipio
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	public Integer getIdMunicipio() {
		return idMunicipio;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.elem_feature.id_municipio
	 * @param idMunicipio  the value for cementerio.elem_feature.id_municipio
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	public void setIdMunicipio(Integer idMunicipio) {
		this.idMunicipio = idMunicipio;
	}
}