/**
 * CamposBusquedaFiltro.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.geopista.app.inventario;

import java.util.ArrayList;
import java.util.Collections;

import com.geopista.protocol.inventario.CampoFiltro;
import com.geopista.protocol.inventario.Const;

/**
 * Created by IntelliJ IDEA.
 * User: charo
 * Date: 06-oct-2006
 * Time: 11:46:58
 * To change this template use File | Settings | File Templates.
 */
public class CamposBusquedaFiltro {

    private static ArrayList campos;

    public static final int UsoJuridico=0;
    public static final int FormaAdquisicion=1;
    public static final int Propiedad=2;
    public static final int EstadoConservacion=3;
    public static final int TipoConstruccion=4;
    public static final int Cubierta=5;
    public static final int Carpinteria=6;
    public static final int Fachada=7;
    public static final int Aprovechamiento=8;
    public static final int TipoAmortizacion=9;
    public static final int UsoFuncional=10;
    public static final int Documentos=11;
    public static final int Concepto=12;
    public static final int Raza=13;
    public static final int CodigoVia=14;
    public static final int TipoVehiculo=15;
    public static final int Traccion=16;
    public static final int ClaseValorMobiliario=17;
    public static final int Arrendamiento=18;
    public static final int CatTransmision=19;
    public static final int ClaseCredito=20;
    public static final int SubclaseCredito=21;
    public static final int ClaseDchoReales=22;
    public static final int ClaseMuebles=23;
    public static final int ClaseUrbano=24;
    public static final int ClaseRustico=25;
    /* Si se añade alguna constante para algun dominio, mirar la clase FiltroJPanel para añadirlo */
    
    private static void getCamposBienesInventario(){
        CampoFiltro campo= new CampoFiltro();
        campo.setNombre("borrado");
        campo.setTabla("bienes_inventario");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("descripcion");
        campo.setDescripcion("descripcion del bien");
        campo.setTabla("bienes_inventario");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("fecha_alta");
        campo.setTabla("bienes_inventario");
        campo.setDate();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("fecha_baja");
        campo.setTabla("bienes_inventario");
        campo.setDate();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("fecha_ultima_modificacion");
        campo.setTabla("bienes_inventario");
        campo.setDate();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("nombre");
        campo.setTabla("bienes_inventario");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("numinventario");
        campo.setTabla("bienes_inventario");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("organizacion");
        campo.setTabla("bienes_inventario");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("uso");
        campo.setDescripcion("uso juridico del bien");
        campo.setTabla("bienes_inventario");
        campo.setIsDominio();
        campo.setDominio(UsoJuridico);
        campos.add(campo);

    }

    private static void getCamposSeguro(){
        CampoFiltro campo= new CampoFiltro();
        campo.setNombre("descripcion");
        campo.setDescripcion("descripcion del seguro");
        campo.setTabla("seguros_inventario");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("fecha_inicio");
        campo.setDescripcion("fecha_inicio del seguro");
        campo.setTabla("seguros_inventario");
        campo.setDate();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("fecha_vencimiento");
        campo.setDescripcion("fecha_vencimiento del seguro");
        campo.setTabla("seguros_inventario");
        campo.setDate();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("poliza");
        campo.setDescripcion("poliza del seguro");
        campo.setTabla("seguros_inventario");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("prima");
        campo.setDescripcion("prima del seguro");
        campo.setTabla("seguros_inventario");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("nombre");
        campo.setDescripcion("nombre de la compañia aseguradora");
        campo.setTabla("compannia_seguros");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("descripcion");
        campo.setDescripcion("descripcion de la compañia aseguradora");
        campo.setTabla("compannia_seguros");
        campo.setVarchar();
        campos.add(campo);

    }

    private static void getCamposCContable(){
        CampoFiltro campo= new CampoFiltro();
        campo.setNombre("descripcion");
        campo.setDescripcion("descripcion de la cuenta contable");
        campo.setTabla("contable");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("cuenta");
        campo.setDescripcion("cuenta contable");
        campo.setTabla("contable");
        campo.setVarchar();
        campos.add(campo);

    }

    private static void getCamposCAmortizacion(){
        CampoFiltro campo= new CampoFiltro();
        campo.setNombre("cuenta");
        campo.setDescripcion("cuenta amortizacion");
        campo.setTabla("amortizacion");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("descripcion");
        campo.setDescripcion("descripcion de la cuenta de amortizacion");
        campo.setTabla("amortizacion");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("anios");
        campo.setDescripcion("años de amortizacion");
        campo.setTabla("amortizacion");
        campo.setNumeric();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("porcentaje");
        campo.setDescripcion("porcentaje de amortizacion");
        campo.setTabla("amortizacion");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("total_amortizado");
        campo.setTabla("amortizacion");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("tipo_amortizacion");
        campo.setTabla("amortizacion");
        campo.setIsDominio();
        campo.setDominio(TipoAmortizacion);
        campos.add(campo);
    }

    private static void getCamposObservacion(){
        CampoFiltro campo= new CampoFiltro();
        campo.setNombre("descripcion");
        campo.setDescripcion("observacion");
        campo.setTabla("observaciones_inventario");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("fecha");
        campo.setDescripcion("fecha entrada observacion");
        campo.setTabla("observaciones_inventario");
        campo.setDate();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("fecha_ultima_modificacion");
        campo.setDescripcion("fecha_ultima_modificacion observacion");
        campo.setTabla("observaciones_inventario");
        campo.setDate();
        campos.add(campo);

    }

    private static void getCamposMejora(){
        CampoFiltro campo= new CampoFiltro();
        campo.setNombre("descripcion");
        campo.setDescripcion("mejora");
        campo.setTabla("mejoras_inventario");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("fecha");
        campo.setDescripcion("fecha entrada mejora");
        campo.setTabla("mejoras_inventario");
        campo.setDate();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("fecha_ejecucion");
        campo.setDescripcion("fecha_ejecucion mejora");
        campo.setTabla("mejoras_inventario");
        campo.setDate();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("fecha_ultima_modificacion");
        campo.setDescripcion("fecha_ultima_modificacion mejora");
        campo.setTabla("mejoras_inventario");
        campo.setDate();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("importe");
        campo.setDescripcion("importe mejora");
        campo.setTabla("mejoras_inventario");
        campo.setDouble();
        campos.add(campo);

    }

    private static void getCamposUsoFuncional(){
        CampoFiltro campo= new CampoFiltro();
        campo.setNombre("uso");
        campo.setDescripcion("uso funcional");
        campo.setTabla("usos_funcionales_inventario");
        campo.setIsDominio();
        campo.setDominio(UsoFuncional);
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("superficie");
        campo.setDescripcion("superficie funcional");
        campo.setTabla("usos_funcionales_inventario");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("fecha");
        campo.setDescripcion("fecha uso funcional");
        campo.setTabla("usos_funcionales_inventario");
        campo.setDate();
        campos.add(campo);

    }

    private static void getCamposRefCatastral(){
        CampoFiltro campo= new CampoFiltro();
        campo.setNombre("ref_catastral");
        campo.setDescripcion("ref_catastral del bien");
        campo.setTabla("refcatastrales_inventario");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("descripcion");
        campo.setDescripcion("descripcion de la referencia catastral");
        campo.setTabla("refcatastrales_inventario");
        campo.setVarchar();
        campos.add(campo);

    }

    private static void getCamposDocumento(){
        CampoFiltro campo= new CampoFiltro();
        campo.setNombre("nombre");
        campo.setDescripcion("nombre del documento");
        campo.setTabla("documento");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("comentario");
        campo.setDescripcion("comentario del documento");
        campo.setTabla("documento");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("oculto");
        campo.setDescripcion("documento oculto");
        campo.setTabla("documento");
        campo.setBoolean();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("fecha_alta");
        campo.setDescripcion("fecha_alta documento");
        campo.setTabla("documento");
        campo.setDate();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("fecha_modificacion");
        campo.setDescripcion("fecha_modificacion documento");
        campo.setTabla("documento");
        campo.setDate();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("is_imgdoctext");
        campo.setDescripcion("tipo documento");
        campo.setTabla("documento");
        campo.setIsDominio();
        campo.setDominio(Documentos);
        campos.add(campo);

    }

    public static ArrayList getCamposBienesMueble(){
        return getCamposMueble(Const.PATRON_BIENES_MUEBLES);
    }
    public static ArrayList getCamposMuebleHistArt(){
         return getCamposMueble(Const.PATRON_MUEBLES_HISTORICOART);
    }

    private static ArrayList getCamposMueble(String patron){
        campos= new ArrayList();

        CampoFiltro campo= new CampoFiltro();
        campo.setNombre("adquisicion");
        campo.setTabla("muebles");
        campo.setIsDominio();
        campo.setDominio(FormaAdquisicion);
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("caracteristicas");
        campo.setTabla("muebles");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("coste_adquisicion");
        campo.setTabla("muebles");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("destino");
        campo.setTabla("muebles");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("estadoconservacion");
        campo.setTabla("muebles");
        campo.setIsDominio();
        campo.setDominio(EstadoConservacion);
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("fecha_adquisicion");
        campo.setTabla("muebles");
        campo.setDate();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("frutos");
        campo.setTabla("muebles");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("importe_frutos");
        campo.setTabla("muebles");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("propiedad");
        campo.setTabla("muebles");
        campo.setIsDominio();
        campo.setDominio(Propiedad);
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("ubicacion");
        campo.setTabla("muebles");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("valor_actual");
        campo.setTabla("muebles");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("clase");
        campo.setTabla("muebles");
        campo.setIsDominio();
        campo.setDominio(ClaseMuebles);
        campos.add(campo);
        if (patron.equalsIgnoreCase(Const.PATRON_BIENES_MUEBLES)){
            campo= new CampoFiltro();
            campo.setNombre("fecha_fin_garantia");
            campo.setTabla("muebles");
            campo.setDate();
            campos.add(campo);
            campo= new CampoFiltro();
            campo.setNombre("marca");
            campo.setTabla("muebles");
            campo.setVarchar();
            campos.add(campo);
            campo= new CampoFiltro();
            campo.setNombre("num_serie");
            campo.setTabla("muebles");
            campo.setVarchar();
            campos.add(campo);
            campo= new CampoFiltro();
            campo.setNombre("modelo");
            campo.setTabla("muebles");
            campo.setVarchar();
            campos.add(campo);

            getCamposCAmortizacion();

        }else if (patron.equalsIgnoreCase(Const.PATRON_MUEBLES_HISTORICOART)){
            campo= new CampoFiltro();
            campo.setNombre("autor");
            campo.setTabla("muebles");
            campo.setVarchar();
            campos.add(campo);
            campo= new CampoFiltro();
            campo.setNombre("direccion");
            campo.setTabla("muebles");
            campo.setVarchar();
            campos.add(campo);
            campo= new CampoFiltro();
            campo.setNombre("material");
            campo.setTabla("muebles");
            campo.setVarchar();
            campos.add(campo);
        }

        getCamposBienesInventario();
        getCamposCContable();
        getCamposSeguro();
        getCamposObservacion();
        getCamposDocumento();

        Collections.sort(campos);
        return campos;

    }

    public static ArrayList getCamposSemovientes(){
        campos= new ArrayList();

        CampoFiltro campo= new CampoFiltro();
        campo.setNombre("adquisicion");
        campo.setTabla("semoviente");
        campo.setIsDominio();
        campo.setDominio(FormaAdquisicion);
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("conservacion");
        campo.setTabla("semoviente");
        campo.setIsDominio();
        campo.setDominio(EstadoConservacion);
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("coste_adquisicion");
        campo.setTabla("semoviente");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("descripcion");
        campo.setDescripcion("descripcion del semoviente");
        campo.setTabla("semoviente");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("destino");
        campo.setTabla("semoviente");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("especie");
        campo.setTabla("semoviente");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("fecha_adquisicion");
        campo.setTabla("semoviente");
        campo.setDate();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("fecha_nacimiento");
        campo.setTabla("semoviente");
        campo.setDate();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("frutos");
        campo.setTabla("semoviente");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("identificacion");
        campo.setTabla("semoviente");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("importe_frutos");
        campo.setTabla("semoviente");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("propiedad");
        campo.setTabla("semoviente");
        campo.setIsDominio();
        campo.setDominio(Propiedad);
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("raza");
        campo.setTabla("semoviente");
        campo.setIsDominio();
        campo.setDominio(Raza);
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("valor_actual");
        campo.setTabla("semoviente");
        campo.setDouble();
        campos.add(campo);

        getCamposBienesInventario();
        getCamposCContable();
        getCamposSeguro();
        getCamposObservacion();
        getCamposDocumento();

        Collections.sort(campos);
        return campos;
    }

    public static ArrayList getCamposCreditosDerechos(){
        campos= new ArrayList();

        CampoFiltro campo= new CampoFiltro();
        campo.setNombre("adquisicion");
        campo.setTabla("credito_derecho");
        campo.setIsDominio();
        campo.setDominio(FormaAdquisicion);
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("concepto");
        campo.setTabla("credito_derecho");
        campo.setIsDominio();
        campo.setDominio(Concepto);
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("concepto_desc");
        campo.setTabla("credito_derecho");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("descripcion");
        campo.setDescripcion("descripcion del credito");
        campo.setTabla("credito_derecho");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("destino");
        campo.setTabla("credito_derecho");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("deudor");
        campo.setTabla("credito_derecho");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("importe");
        campo.setTabla("credito_derecho");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("fecha_adquisicion");
        campo.setTabla("credito_derecho");
        campo.setDate();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("fecha_vencimiento");
        campo.setTabla("credito_derecho");
        campo.setDate();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("arrendamiento");
        campo.setTabla("credito_derecho");
        campo.setIsDominio();
        campo.setDominio(Arrendamiento);
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("clase");
        campo.setTabla("credito_derecho");
        campo.setIsDominio();
        campo.setDominio(ClaseCredito);
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("subclase");
        campo.setTabla("credito_derecho");
        campo.setIsDominio();
        campo.setDominio(SubclaseCredito);
        campos.add(campo);
        
        getCamposBienesInventario();
        getCamposCContable();
        getCamposObservacion();
        getCamposDocumento();

        Collections.sort(campos);
        return campos;
    }

    public static ArrayList getCamposDerechosReales(){
        campos= new ArrayList();

        CampoFiltro campo= new CampoFiltro();
        campo.setNombre("adquisicion");
        campo.setTabla("derechos_reales");
        campo.setIsDominio();
        campo.setDominio(FormaAdquisicion);
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("bien");
        campo.setDescripcion("caracteristicas derecho real");
        campo.setTabla("derechos_reales");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("coste");
        campo.setTabla("derechos_reales");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("destino");
        campo.setTabla("derechos_reales");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("fecha_adquisicion");
        campo.setTabla("derechos_reales");
        campo.setDate();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("frutos");
        campo.setTabla("derechos_reales");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("importe_frutos");
        campo.setTabla("derechos_reales");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("registro_finca");
        campo.setTabla("derechos_reales");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("registro_folio");
        campo.setTabla("derechos_reales");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("registro_inscripcion");
        campo.setTabla("derechos_reales");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("registro_libro");
        campo.setTabla("derechos_reales");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("registro_notario");
        campo.setTabla("derechos_reales");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("registro_propiedad");
        campo.setTabla("derechos_reales");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("registro_protocolo");
        campo.setTabla("derechos_reales");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("registro_tomo");
        campo.setTabla("derechos_reales");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("valor");
        campo.setTabla("derechos_reales");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("clase");
        campo.setTabla("derechos_reales");
        campo.setIsDominio();
        campo.setDominio(ClaseDchoReales);
        campos.add(campo);
        
        getCamposBienesInventario();
        getCamposCContable();
        getCamposObservacion();
        getCamposDocumento();

        Collections.sort(campos);
        return campos;

    }

    public static ArrayList getCamposInmuebleUrbano(){
        return getCamposInmueble(Const.PATRON_INMUEBLES_URBANOS);
    }

    public static ArrayList getCamposInmuebleRustico(){
        return getCamposInmueble(Const.PATRON_INMUEBLES_RUSTICOS);
    }

    private static ArrayList getCamposInmueble(String patron){
        campos= new ArrayList();

        CampoFiltro campo= new CampoFiltro();
        campo.setNombre("adquisicion");
        campo.setTabla("inmuebles");
        campo.setIsDominio();
        campo.setDominio(FormaAdquisicion);
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("carpinteria");
        campo.setTabla("inmuebles");
        campo.setIsDominio();
        campo.setDominio(Carpinteria);
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("cubierta");
        campo.setTabla("inmuebles");
        campo.setIsDominio();
        campo.setDominio(Cubierta);
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("estadoconservacion_desc");
        campo.setDescripcion("descripcion del estado de conservacion");
        campo.setTabla("inmuebles");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("tipoconstruccion_desc");
        campo.setDescripcion("descripcion del tipo de construccion");
        campo.setTabla("inmuebles");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("carpinteria_desc");
        campo.setDescripcion("descripcion de la carpinteria");
        campo.setTabla("inmuebles");
        campo.setVarchar();
        campos.add(campo);
        campo.setNombre("cubierta_desc");
        campo.setDescripcion("descripcion de la cubierta");
        campo.setTabla("inmuebles");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("fachada_desc");
        campo.setDescripcion("descripcion de la fachada");
        campo.setTabla("inmuebles");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("derechospersonales");
        campo.setDescripcion("derechos personales");
        campo.setTabla("inmuebles");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("derechosrealescontra");
        campo.setDescripcion("derechos reales en contra");
        campo.setTabla("inmuebles");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("derechosrealesfavor");
        campo.setDescripcion("derechos reales a favor");
        campo.setTabla("inmuebles");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("destino");
        campo.setTabla("inmuebles");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("direccion");
        campo.setTabla("inmuebles");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("edificabilidad");
        campo.setTabla("inmuebles");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("estadoconservacion");
        campo.setTabla("inmuebles");
        campo.setIsDominio();
        campo.setDominio(EstadoConservacion);
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("fachada");
        campo.setTabla("inmuebles");
        campo.setIsDominio();
        campo.setDominio(Fachada);
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("fecha_adquisicion");
        campo.setTabla("inmuebles");
        campo.setDate();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("fecha_adquisicion_suelo");
        campo.setTabla("inmuebles");
        campo.setDate();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("fechaobra");
        campo.setTabla("inmuebles");
        campo.setDate();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("frutos");
        campo.setTabla("inmuebles");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("importe_frutos");
        campo.setTabla("inmuebles");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("lindero_norte");
        campo.setTabla("inmuebles");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("lindero_sur");
        campo.setTabla("inmuebles");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("lindero_este");
        campo.setTabla("inmuebles");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("lindero_oeste");
        campo.setTabla("inmuebles");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("num_plantas");
        campo.setTabla("inmuebles");
        campo.setNumeric();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("propiedad");
        campo.setTabla("inmuebles");
        campo.setIsDominio();
        campo.setDominio(Propiedad);
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("registro");
        campo.setTabla("inmuebles");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("registro_finca");
        campo.setTabla("inmuebles");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("registro_folio");
        campo.setTabla("inmuebles");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("registro_inscripcion");
        campo.setTabla("inmuebles");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("registro_libro");
        campo.setTabla("inmuebles");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("registro_notario");
        campo.setTabla("inmuebles");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("registro_propiedad");
        campo.setTabla("inmuebles");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("registro_protocolo");
        campo.setTabla("inmuebles");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("registro_tomo");
        campo.setTabla("inmuebles");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("superficie_catastral_suelo");
        campo.setTabla("inmuebles");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("superficie_real_construccion");
        campo.setTabla("inmuebles");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("superficie_real_suelo");
        campo.setTabla("inmuebles");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("superficie_catastral_construccion");
        campo.setTabla("inmuebles");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("superficie_construida_construccion");
        campo.setTabla("inmuebles");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("superficie_enplanta_construccion");
        campo.setTabla("inmuebles");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("superficie_ocupada_construccion");
        campo.setTabla("inmuebles");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("superficie_registral_construccion");
        campo.setTabla("inmuebles");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("superficie_registral_suelo");
        campo.setTabla("inmuebles");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("tipoconstruccion");
        campo.setTabla("inmuebles");
        campo.setIsDominio();
        campo.setDominio(TipoConstruccion);
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("valor_actual_construccion");
        campo.setTabla("inmuebles");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("valor_actual_inmueble");
        campo.setTabla("inmuebles");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("valor_actual_suelo");
        campo.setTabla("inmuebles");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("valor_adquisicion_construccion");
        campo.setTabla("inmuebles");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("valor_adquisicion_inmueble");
        campo.setTabla("inmuebles");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("valor_adquisicion_suelo");
        campo.setTabla("inmuebles");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("valor_catastral_construccion");
        campo.setTabla("inmuebles");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("valor_catastral_suelo");
        campo.setTabla("inmuebles");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("valor_derechos_contra");
        campo.setDescripcion("valor derechos en contra");
        campo.setTabla("inmuebles");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("valor_derechos_favor");
        campo.setDescripcion("valor derechos a favor");
        campo.setTabla("inmuebles");
        campo.setDouble();
        campos.add(campo);
        if (patron.equalsIgnoreCase(Const.PATRON_INMUEBLES_RUSTICOS)){
            campo= new CampoFiltro();
            campo.setNombre("paraje");
            campo.setTabla("inmuebles_rusticos");
            campo.setVarchar();
            campos.add(campo);
            campo= new CampoFiltro();
            campo.setNombre("poligono");
            campo.setTabla("inmuebles_rusticos");
            campo.setVarchar();
            campos.add(campo);
            campo= new CampoFiltro();
            campo.setNombre("aprovechamiento");
            campo.setTabla("inmuebles_rusticos");
            campo.setIsDominio();
            campo.setDominio(Aprovechamiento);
            campos.add(campo);
            campo= new CampoFiltro();
            campo.setNombre("clase");
            campo.setTabla("inmuebles");
            campo.setIsDominio();
            campo.setDominio(ClaseRustico);
            campos.add(campo);
        }else if (patron.equalsIgnoreCase(Const.PATRON_INMUEBLES_URBANOS)){
            campo= new CampoFiltro();
            campo.setNombre("manzana");
            campo.setTabla("inmuebles_urbanos");
            campo.setVarchar();
            campos.add(campo);
            campo= new CampoFiltro();
            campo.setNombre("clase");
            campo.setTabla("inmuebles");
            campo.setIsDominio();
            campo.setDominio(ClaseUrbano);
            campos.add(campo);
        }

        getCamposBienesInventario();
        getCamposCContable();
        getCamposCAmortizacion();
        getCamposSeguro();
        getCamposObservacion();
        getCamposMejora();
        getCamposRefCatastral();
        getCamposUsoFuncional();
        getCamposDocumento();

        Collections.sort(campos);
        return campos;

    }

    public static ArrayList getCamposViaUrbana(){
        return getCamposVia(Const.PATRON_VIAS_PUBLICAS_URBANAS);
    }

    public static ArrayList getCamposViaRustica(){
        return getCamposVia(Const.PATRON_VIAS_PUBLICAS_RUSTICAS);
    }

    private static ArrayList getCamposVia(String patron){
        campos= new ArrayList();

        CampoFiltro campo= new CampoFiltro();
        campo.setNombre("fecha_adquisicion");
        campo.setTabla("vias_inventario");
        campo.setDate();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("adquisicion");
        campo.setTabla("vias_inventario");
        campo.setIsDominio();
        campo.setDominio(FormaAdquisicion);
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("categoria");
        campo.setTabla("vias_inventario");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("codigo");
        campo.setTabla("vias_inventario");
        campo.setIsDominio();
        campo.setDominio(CodigoVia);
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("nombre");
        campo.setDescripcion("nombre de la via");
        campo.setTabla("vias_inventario");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("inicio");
        campo.setDescripcion("inicio de la via");
        campo.setTabla("vias_inventario");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("fin");
        campo.setDescripcion("fin de la via");
        campo.setTabla("vias_inventario");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("destino");
        campo.setDescripcion("destino de la via");
        campo.setTabla("vias_inventario");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("num_apliques");
        campo.setTabla("vias_inventario");
        campo.setNumeric();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("num_bancos");
        campo.setTabla("vias_inventario");
        campo.setNumeric();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("num_papeleras");
        campo.setTabla("vias_inventario");
        campo.setNumeric();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("metros_pavimentados");
        campo.setTabla("vias_inventario");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("metros_no_pavimentados");
        campo.setTabla("vias_inventario");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("zonas_verdes");
        campo.setTabla("vias_inventario");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("longitud");
        campo.setDescripcion("longitud de la via");
        campo.setTabla("vias_inventario");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("ancho");
        campo.setDescripcion("ancho de la via");
        campo.setTabla("vias_inventario");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("valor_actual");
        if (patron.equalsIgnoreCase(Const.PATRON_VIAS_PUBLICAS_RUSTICAS))
            campo.setDescripcion("valor regularizado");
        campo.setTabla("vias_inventario");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("clase");
        campo.setTabla("vias");
        campo.setIsDominio();
        if (patron.equalsIgnoreCase(Const.PATRON_VIAS_PUBLICAS_RUSTICAS)){     	
            campo.setDominio(ClaseRustico);
        }
        else
        	if (patron.equalsIgnoreCase(Const.PATRON_VIAS_PUBLICAS_URBANAS)){
                campo.setDominio(ClaseUrbano);
        	}
        campos.add(campo);
        
        getCamposBienesInventario();
        getCamposCContable();
        getCamposSeguro();
        getCamposObservacion();
        getCamposMejora();
        getCamposDocumento();

        Collections.sort(campos);
        return campos;
    }

    public static ArrayList getCamposVehiculo(){
        campos= new ArrayList();

        CampoFiltro campo= new CampoFiltro();
        campo.setNombre("fecha_adquisicion");
        campo.setTabla("vehiculo");
        campo.setDate();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("adquisicion");
        campo.setTabla("vehiculo");
        campo.setIsDominio();
        campo.setDominio(FormaAdquisicion);
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("matricula_vieja");
        campo.setTabla("vehiculo");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("matricula_nueva");
        campo.setTabla("vehiculo");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("num_bastidor");
        campo.setTabla("vehiculo");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("marca");
        campo.setTabla("vehiculo");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("motor");
        campo.setTabla("vehiculo");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("fuerza");
        campo.setTabla("vehiculo");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("servicio");
        campo.setTabla("vehiculo");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("destino");
        campo.setTabla("vehiculo");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("tipo");
        campo.setDescripcion("tipo de vehiculo");
        campo.setTabla("vehiculo");
        campo.setIsDominio();
        campo.setDominio(TipoVehiculo);
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("estado_conservacion");
        campo.setTabla("vehiculo");
        campo.setIsDominio();
        campo.setDominio(EstadoConservacion);
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("traccion");
        campo.setTabla("vehiculo");
        campo.setIsDominio();
        campo.setDominio(Traccion);
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("propiedad");
        campo.setTabla("vehiculo");
        campo.setIsDominio();
        campo.setDominio(Propiedad);
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("frutos");
        campo.setTabla("vehiculo");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("importe_frutos");
        campo.setTabla("vehiculo");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("coste_adquisicion");
        campo.setTabla("vehiculo");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("valor_actual");
        campo.setTabla("vehiculo");
        campo.setDouble();
        campos.add(campo);

        getCamposBienesInventario();
        getCamposCContable();
        getCamposCAmortizacion();
        getCamposSeguro();
        getCamposObservacion();
        getCamposDocumento();

        Collections.sort(campos);
        return campos;
    }

    public static ArrayList getCamposValorMobiliario(){
        campos= new ArrayList();

        CampoFiltro campo= new CampoFiltro();
        campo.setNombre("fecha_adquisicion");
        campo.setTabla("valor_mobiliario");
        campo.setDate();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("adquisicion");
        campo.setTabla("valor_mobiliario");
        campo.setIsDominio();
        campo.setDominio(FormaAdquisicion);
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("depositado_en");
        campo.setTabla("valor_mobiliario");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("emitido_por");
        campo.setTabla("valor_mobiliario");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("numero");
        campo.setTabla("valor_mobiliario");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("serie");
        campo.setTabla("valor_mobiliario");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("num_titulos");
        campo.setTabla("valor_mobiliario");
        campo.setNumeric();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("destino");
        campo.setTabla("valor_mobiliario");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("clase");
        campo.setTabla("valor_mobiliario");
        campo.setIsDominio();
        campo.setDominio(ClaseValorMobiliario);
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("coste_adquisicion");
        campo.setTabla("valor_mobiliario");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("valor_actual");
        campo.setTabla("valor_mobiliario");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("precio");
        campo.setTabla("valor_mobiliario");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("capital");
        campo.setTabla("valor_mobiliario");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("importe_frutos");
        campo.setTabla("valor_mobiliario");
        campo.setDouble();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("frutos");
        campo.setTabla("valor_mobiliario");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("fecha_acuerdo");
        campo.setTabla("valor_mobiliario");
        campo.setVarchar();
        campo.setDate();
        campos.add(campo);

        getCamposBienesInventario();
        getCamposCContable();
        getCamposSeguro();
        getCamposObservacion();
        getCamposDocumento();

        Collections.sort(campos);
        return campos;
    }
    
    public static ArrayList getCamposLotes(){
        campos= new ArrayList();

        CampoFiltro campo= new CampoFiltro();
        campo.setNombre("nombre_lote");
        campo.setTabla("lote");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("seguro");
        campo.setTabla("lote");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("descripcion");
        campo.setTabla("lote");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("destino");
        campo.setTabla("lote");
        campo.setVarchar();
        campos.add(campo);
        Collections.sort(campos);
        return campos;
    }

    public static ArrayList getCamposBienesRevertibles(){
        campos= new ArrayList();

        CampoFiltro campo= new CampoFiltro();
        campo.setNombre("num_inventario");
        campo.setTabla("bien_revertible");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("fecha_inicio");
        campo.setTabla("bien_revertible");
        campo.setDate();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("fecha_vencimiento");
        campo.setTabla("bien_revertible");
        campo.setDate();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("fecha_transmision");
        campo.setTabla("bien_revertible");
        campo.setDate();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("poseedor");
        campo.setTabla("bien_revertible");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("titulo_posesion");
        campo.setTabla("bien_revertible");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("condiciones_reversion");
        campo.setTabla("bien_revertible");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("detalles");
        campo.setTabla("bien_revertible");
        campo.setVarchar();
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("cat_transmision");
        campo.setTabla("bien_revertible");
        campo.setIsDominio();
        campo.setDominio(CatTransmision);
        campos.add(campo);
        campo= new CampoFiltro();
        campo.setNombre("importe");
        campo.setTabla("bien_revertible");
        campo.setDate();
        campos.add(campo);
        Collections.sort(campos);
        return campos;
    }

}
