DROP INDEX COUNTRY_SPATIAL_IDX;
SELECT DropGeometryColumn ('','country', 'geom');
DROP TABLE SUBJECT CASCADE;
DROP TABLE BOOK CASCADE;
DROP TABLE PHILOSOPHER CASCADE;
DROP TABLE IS_FRIEND_OF CASCADE;
DROP TABLE PLACE CASCADE;
DROP TABLE COUNTRY CASCADE;
DROP SEQUENCE FID_seq;
