package com.geopista.app.licencias;

/**
 * The GEOPISTA project is a set of tools and applications to manage
 * geographical data for local administrations.
 *
 * Copyright (C) 2004 INZAMAC-SATEC UTE
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
 USA.
 *
 * For more information, contact:
 *
 *
 * www.geopista.com
 *
 *
 */

import com.geopista.protocol.licencias.COperacionesLicencias;
import com.geopista.protocol.licencias.CReferenciaCatastral;
import com.geopista.app.licencias.tableModels.CSearchDialogTableModel;
import com.geopista.app.licencias.estructuras.Estructuras;
import com.geopista.app.utilidades.JNumberTextField;
import com.geopista.app.utilidades.TableSorted;
import org.apache.log4j.Logger;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import java.awt.*;
import java.util.Hashtable;
import java.util.Vector;
import java.util.ResourceBundle;
import java.io.StringWriter;
import java.io.PrintWriter;

/**
 * @author avivar
 */
public class CAddressJDialog extends javax.swing.JDialog {
	Logger logger = Logger.getLogger(CAddressJDialog.class);
    private ResourceBundle literales;
    private Vector referenciasCatastrales= new Vector();

    TableSorted addressesJTModelSorted= new TableSorted();

	/**
	 * Creates new form JSearch
	 */
	public CAddressJDialog(java.awt.Frame parent, boolean modal, ResourceBundle literales) {
		super(parent, modal);
        this.literales=literales;
		initComponents();
		configureComponents();
	}

	private void configureComponents() {
        addressesJTableModel = new CSearchDialogTableModel(new String[]{literales.getString("CAddressJDialog.addressesJTableModel.text.column1"),literales.getString("CAddressJDialog.addressesJTableModel.text.column2"),literales.getString("CAddressJDialog.addressesJTableModel.text.column3"),literales.getString("CAddressJDialog.addressesJTableModel.text.column4"),literales.getString("CAddressJDialog.addressesJTableModel.text.column5"),literales.getString("CAddressJDialog.addressesJTableModel.text.column6"),literales.getString("CAddressJDialog.addressesJTableModel.text.column7"),literales.getString("CAddressJDialog.addressesJTableModel.text.column8"),literales.getString("CAddressJDialog.addressesJTableModel.text.column9"), literales.getString("CAddressJDialog.addressesJTableModel.text.column10")});
		addressesJTable.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
		addressesJTable.setRowSelectionAllowed(true);
		addressesJTable.setColumnSelectionAllowed(false);
        addressesJTable.getTableHeader().setReorderingAllowed(false);
        addressesJTModelSorted= new TableSorted(addressesJTableModel);
        addressesJTModelSorted.setTableHeader(addressesJTable.getTableHeader());
		addressesJTable.setModel(addressesJTModelSorted);

        numeroNumberTField=  new com.geopista.app.utilidades.JNumberTextField(JNumberTextField.NUMBER, new Integer(99999), true);
        numeroNumberTField.setEditable(true);
        jPanel1.add(numeroNumberTField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 100, -1));


        cPostalNumberTField=  new com.geopista.app.utilidades.JNumberTextField(JNumberTextField.NUMBER, new Integer(99999), true);
        cPostalNumberTField.setEditable(true);
        jPanel1.add(cPostalNumberTField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 100, -1));

		renombrarComponentes();
	}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        aceptarJButton = new javax.swing.JButton();
        cancelarJButton = new javax.swing.JButton();
        buscarJButton = new javax.swing.JButton();
        addressesJScrollPane = new javax.swing.JScrollPane();
        addressesJTable = new javax.swing.JTable();
        nombreViaJLabel = new javax.swing.JLabel();
        numeroViaJLabel = new javax.swing.JLabel();
        nombreViaJTextField = new javax.swing.JTextField();
        cPostalJLabel = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Di\u00e1logo de busqueda");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.EtchedBorder());
        aceptarJButton.setText("Aceptar");
        aceptarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarJButtonActionPerformed();
            }
        });

        jPanel1.add(aceptarJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, -1, -1));

        cancelarJButton.setText("Cancelar");
        cancelarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarJButtonActionPerformed();
            }
        });

        jPanel1.add(cancelarJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, -1, -1));

        buscarJButton.setText("Buscar");
        buscarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarJButtonActionPerformed();
            }
        });

        jPanel1.add(buscarJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));

        addressesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo vía", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Nombre vía", "Nº"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });

        addressesJTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        addressesJTable.setFocusCycleRoot(true);
        addressesJTable.setSurrendersFocusOnKeystroke(true);
        addressesJTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mostrarAddressSeleccionada();
            }
        });
        addressesJTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mostrarAddressSeleccionada();
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mostrarAddressSeleccionada();
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mostrarAddressSeleccionada();
            }
        });

        addressesJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarAddressSeleccionada();
            }
        });
        addressesJTable.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mostrarAddressSeleccionada();
            }
        });

        addressesJScrollPane.setViewportView(addressesJTable);

        jPanel1.add(addressesJScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 680, 170));

        nombreViaJLabel.setText("Nombre v\u00eda:");
        jPanel1.add(nombreViaJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 200, 20));

        numeroViaJLabel.setText("N\u00famero:");
        jPanel1.add(numeroViaJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 200, 20));

        jPanel1.add(nombreViaJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 330, -1));

        cPostalJLabel.setText("C\u00f3digo postal:");
        jPanel1.add(cPostalJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 200, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 380));

        pack();
    }//GEN-END:initComponents

	private void buscarJButtonActionPerformed() {//GEN-FIRST:event_buscarJButtonActionPerformed


		try {

			CUtilidadesComponentes.clearTable(addressesJTableModel);
			this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

            String numero= "";
            try{
                numero= numeroNumberTField.getNumber().toString();
            }catch(Exception e){}
            String cpostal= "";
            try{
                cpostal= cPostalNumberTField.getNumber().toString();
            }catch(Exception e){}

			Hashtable hash = new Hashtable();
			hash.put("nombrecatastro", nombreViaJTextField.getText());
			hash.put("c.primer_numero", numero);
			hash.put("c.codigo_postal", cpostal);

			referenciasCatastrales = COperacionesLicencias.getSearchedAddresses(hash);
			logger.info("referenciasCatastrales.size(): " + referenciasCatastrales.size());

			this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));

            if (referenciasCatastrales.size() > 0){
                for (int i = 0; i < referenciasCatastrales.size(); i++) {
                    CReferenciaCatastral referenciaCatastral = (CReferenciaCatastral) referenciasCatastrales.elementAt(i);

                    String tipoVia= "";
                    if ((referenciaCatastral.getTipoVia() != null) && (!referenciaCatastral.getTipoVia().trim().equalsIgnoreCase(""))){
                        tipoVia= Estructuras.getListaTiposViaINE().getDomainNode(referenciaCatastral.getTipoVia()).getTerm(literales.getLocale().toString());
                    }

                    //"Ref.", "Tipo vía", "Nombre vía", "Nº", "Letra","Bloque","Esc.","Planta","Puerta"
                    addressesJTableModel.addRow(new String[]{referenciaCatastral.getReferenciaCatastral(),
                                                             tipoVia,
                                                             referenciaCatastral.getNombreVia(),
                                                             referenciaCatastral.getPrimerNumero(),
                                                             referenciaCatastral.getPrimeraLetra(),
                                                             referenciaCatastral.getBloque(),
                                                             referenciaCatastral.getEscalera(),
                                                             referenciaCatastral.getPlanta(),
                                                             referenciaCatastral.getPuerta(),
                                                             referenciaCatastral.getCPostal()});
                }

            }else{
                mostrarMensaje(literales.getString("CAddressJDialog.mensaje1"));
            }
		} catch (Exception ex) {
			this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
			logger.error("Exception: " + ex.toString());
		}

	}//GEN-LAST:event_buscarJButtonActionPerformed

	private void cancelarJButtonActionPerformed() {//GEN-FIRST:event_cancelarJButtonActionPerformed
        CConstantesLicencias.referenciasCatastrales= new Hashtable();
		dispose();

	}//GEN-LAST:event_cancelarJButtonActionPerformed

    private void mostrarAddressSeleccionada(){
        if(addressesJTable.getSelectedRowCount() == 1){
            int seleccion = addressesJTable.getSelectedRow();
            if (seleccion != -1){
                nombreViaJTextField.setText((String) addressesJTModelSorted.getValueAt(seleccion, 2));
                numeroNumberTField.setText((String) addressesJTModelSorted.getValueAt(seleccion, 3));
                cPostalNumberTField.setText((String) addressesJTModelSorted.getValueAt(seleccion, 9));
            }
        }

    }


	private void aceptarJButtonActionPerformed() {//GEN-FIRST:event_aceptarJButtonActionPerformed

        CConstantesLicencias.referenciasCatastrales= new Hashtable();

		for (int i = 0; i < addressesJTable.getSelectedRows().length; i++) {
			int selectedRow = addressesJTable.getSelectedRows()[i];

            String tipoVia= "";
            try{
                tipoVia= Estructuras.getListaTiposViaINE().getDomainNodeByTraduccion(((String) addressesJTModelSorted.getValueAt(selectedRow, 1))).getPatron();
            }catch (Exception e){}


			CReferenciaCatastral referenciaCatastral = new CReferenciaCatastral((String) addressesJTModelSorted.getValueAt(selectedRow, 0),
                    //(String)((CReferenciaCatastral)referenciasCatastrales.get(selectedRow)).getTipoVia(),
                    tipoVia,
					(String) addressesJTModelSorted.getValueAt(selectedRow, 2),
					(String) addressesJTModelSorted.getValueAt(selectedRow, 3),
					(String) addressesJTModelSorted.getValueAt(selectedRow, 4),
					(String) addressesJTModelSorted.getValueAt(selectedRow, 5),
					(String) addressesJTModelSorted.getValueAt(selectedRow, 6),
					(String) addressesJTModelSorted.getValueAt(selectedRow, 7),
					(String) addressesJTModelSorted.getValueAt(selectedRow, 8));
            referenciaCatastral.setCPostal((String) addressesJTModelSorted.getValueAt(selectedRow, 9));


			CConstantesLicencias.referenciasCatastrales.put(addressesJTModelSorted.getValueAt(selectedRow, 0),referenciaCatastral);

		}
		dispose();
	}//GEN-LAST:event_aceptarJButtonActionPerformed

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this.getParent(), mensaje);
    }


	private DefaultTableModel addressesJTableModel;
    private com.geopista.app.utilidades.JNumberTextField numeroNumberTField;
    private com.geopista.app.utilidades.JNumberTextField cPostalNumberTField;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarJButton;
    private javax.swing.JScrollPane addressesJScrollPane;
    private javax.swing.JTable addressesJTable;
    private javax.swing.JButton buscarJButton;
    private javax.swing.JLabel cPostalJLabel;
    private javax.swing.JButton cancelarJButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombreViaJLabel;
    private javax.swing.JTextField nombreViaJTextField;
    private javax.swing.JLabel numeroViaJLabel;
    // End of variables declaration//GEN-END:variables


	private void renombrarComponentes() {

		try {
			setTitle(literales.getString("CAddressJDialog.JInternalFrame.title"));

			nombreViaJLabel.setText(literales.getString("CAddressJDialog.nombreViaJLabel.text"));
			numeroViaJLabel.setText(literales.getString("CAddressJDialog.numeroViaJLabel.text"));
			cPostalJLabel.setText(literales.getString("CAddressJDialog.cPostalJLabel.text"));

			buscarJButton.setText(literales.getString("CAddressJDialog.buscarJButton.text"));
			cancelarJButton.setText(literales.getString("CAddressJDialog.cancelarJButton.text"));
			aceptarJButton.setText(literales.getString("CAddressJDialog.aceptarJButton.text"));

		} catch (Exception ex) {
			StringWriter sw = new StringWriter();
			PrintWriter pw = new PrintWriter(sw);
			ex.printStackTrace(pw);
			logger.error("Exception: " + sw.toString());
		}
	}


}
