/**
 * CCalendarJDialog.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
/*
 * JSearch.java
 *
 * Created on 4 de mayo de 2004, 12:04
 */

package com.geopista.app.ocupaciones.panel;


import org.apache.log4j.Logger;

import com.geopista.app.ocupaciones.CUtilidades;

/**
 * @author avivar
 */
public class CCalendarJDialog extends javax.swing.JDialog {
	Logger logger = Logger.getLogger(CCalendarJDialog.class);
    private String fechaSelected= "";

	/**
	 * Creates new form JSearch
	 */
	public CCalendarJDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);

		initComponents();
		configureComponents();
	}

	private void configureComponents() {
        fechaSelected= "";
	}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents() {//GEN-BEGIN:initComponents
		jCalendar = new com.toedter.calendar.JCalendar();
		jPanel1 = new javax.swing.JPanel();
		cancelarJButton = new javax.swing.JButton();
		aceptarJButton = new javax.swing.JButton();

		getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Di\u00e1logo de busqueda");
		jCalendar.setBorder(new javax.swing.border.EtchedBorder());
		getContentPane().add(jCalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 230));

		jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jPanel1.setBorder(new javax.swing.border.EtchedBorder());
		cancelarJButton.setText("Cancelar");
		cancelarJButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cancelarJButtonActionPerformed(evt);
			}
		});

		jPanel1.add(cancelarJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

		aceptarJButton.setText("Aceptar");
		aceptarJButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				aceptarJButtonActionPerformed(evt);
			}
		});

		jPanel1.add(aceptarJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

		getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 240, 40));

		pack();
	}//GEN-END:initComponents

	private void cancelarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarJButtonActionPerformed

		fechaSelected= "";
		dispose();

	}//GEN-LAST:event_cancelarJButtonActionPerformed

	private void aceptarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarJButtonActionPerformed

        /*
		DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
		fechaSelected= df.format(jCalendar.getCalendar().getTime());
        */
        fechaSelected= CUtilidades.formatFecha(jCalendar.getCalendar().getTime());

		dispose();

	}//GEN-LAST:event_aceptarJButtonActionPerformed

    public String getFechaSelected(){
         return fechaSelected;
    }


	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		new CSearchJDialog(new javax.swing.JFrame(), true).show();
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton aceptarJButton;
	private javax.swing.JButton cancelarJButton;
	private com.toedter.calendar.JCalendar jCalendar;
	private javax.swing.JPanel jPanel1;
	// End of variables declaration//GEN-END:variables

}
