UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_saneam_tem"."GEOMETRY" , ?T) as "GEOMETRY", id, id_municipio, eiel_configuracion_shp.fase, eiel_c_saneam_tem.clave, eiel_c_saneam_tem.codprov, eiel_c_saneam_tem.codmunic, eiel_c_saneam_tem.tramo_em, material, estado FROM eiel_configuracion_shp,"eiel_c_saneam_tem", eiel_t_saneam_tem LEFT JOIN eiel_t_padron_ttmm ON eiel_t_padron_ttmm.codprov::text = eiel_t_saneam_tem.codprov::text AND eiel_t_padron_ttmm.codmunic::text = eiel_t_saneam_tem.codmunic::text WHERE eiel_t_padron_ttmm.total_poblacion_a1 >= 50000 AND (eiel_t_saneam_tem.codmunic::text || eiel_t_saneam_tem.tramo_em::text IN ( SELECT DISTINCT v_emisario_nucleo.em_municip::text || v_emisario_nucleo.orden_emis::text FROM v_emisario_nucleo ORDER BY v_emisario_nucleo.em_municip::text || v_emisario_nucleo.orden_emis::text)) AND eiel_t_padron_ttmm.revision_expirada = 9999999999::bigint::numeric AND eiel_t_saneam_tem.tramo_em::text = eiel_c_saneam_tem.tramo_em::text AND eiel_t_saneam_tem.revision_expirada = 9999999999::bigint::numeric and eiel_t_saneam_tem.clave::text = eiel_c_saneam_tem.clave::text AND eiel_t_saneam_tem.codprov::text = eiel_c_saneam_tem.codprov::text AND eiel_t_saneam_tem.codmunic::text = eiel_c_saneam_tem.codmunic::text AND eiel_c_saneam_tem.revision_expirada = 9999999999::bigint::numeric AND id_municipio IN (?M)  and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY''' where id_layer = (SELECT id_layer from layers where name = 'TRAMO_EMISARIO_M50_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_abast_tp"."GEOMETRY" , ?T) as "GEOMETRY", "eiel_c_abast_tp".id, "eiel_c_abast_tp".id_municipio, eiel_configuracion_shp.fase, "eiel_c_abast_tp".clave, "eiel_c_abast_tp".codprov, "eiel_c_abast_tp".codmunic, "eiel_c_abast_tp".orden_tp FROM eiel_configuracion_shp,"eiel_c_abast_tp" LEFT JOIN eiel_t_padron_ttmm ON eiel_t_padron_ttmm.codprov::text = eiel_c_abast_tp.codprov::text AND eiel_t_padron_ttmm.codmunic::text = eiel_c_abast_tp.codmunic::text WHERE eiel_t_padron_ttmm.total_poblacion_a1 >= 50000 AND (eiel_c_abast_tp.codmunic::text || eiel_c_abast_tp.orden_tp::text IN ( SELECT DISTINCT v_trat_pota_nucleo.po_munipi::text || v_trat_pota_nucleo.orden_trat::text FROM v_trat_pota_nucleo ORDER BY v_trat_pota_nucleo.po_munipi::text || v_trat_pota_nucleo.orden_trat::text)) AND eiel_c_abast_tp.revision_expirada = 9999999999::bigint::numeric AND eiel_t_padron_ttmm.revision_expirada = 9999999999::bigint::numeric AND id_municipio IN (?M)  and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY''' where id_layer = (SELECT id_layer from layers where name = 'POTABILIZACION_ENC_M50_SHP');
UPDATE lcg_nodos_capas_campos SET dominio = 'eiel_Señaliza'  where campo_bd ='senaliza';




delete from version where id_version = 'MODELO R39';
insert into version (id_version, fecha_version) values('MODELO R39', DATE '2014-03-03');
