/**
 * MapParameterDialog.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
/*
 * MapParameterDialog.java
 *
 * Created on 14 de noviembre de 2007, 18:13
 */

package com.geopista.reports.gui;

import java.awt.Frame;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import com.geopista.reports.parameters.IReportParameterManager;

/**
 * IMPORTANTE: La clase Java ya no esta sincronizada con el fichero .form asociado.
 * @author  jpolo
 */
public class MapParameterDialog extends javax.swing.JDialog {
    
    /** Creates new form MapParameterDialog */
    public MapParameterDialog() {
        initComponents();
        postInitComponents();
    }
    
    public MapParameterDialog(Frame owner){
        super(owner);
        initComponents();
        postInitComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelMapName = new javax.swing.JLabel();
        jTextFieldMapName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonCancel = new javax.swing.JButton();
        jButtonOk = new javax.swing.JButton();

        setTitle("Nuevo parametro");
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 10));

        jLabelMapName.setText("Nombre del parametro");
        jPanel1.add(jLabelMapName);

        jTextFieldMapName.setMinimumSize(new java.awt.Dimension(150, 19));
        jTextFieldMapName.setPreferredSize(new java.awt.Dimension(165, 19));
        jPanel1.add(jTextFieldMapName);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jButtonCancel.setText("Cancelar");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCancel);

        jButtonOk.setText("Aceptar");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonOk);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void postInitComponents() {
        jTextFieldMapName.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent documentevent) {
                jTextFieldMapNameChanged(documentevent);
            }
            
            public void removeUpdate(DocumentEvent documentevent) {
                jTextFieldMapNameChanged(documentevent);
            }
            
            public void changedUpdate(DocumentEvent documentevent) {
            }
        });
    }

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkMouseClicked
        String name = jTextFieldMapName.getText();
        if (name != null && name.length() > 0){
            IReportParameterManager.addMapParameter(name);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jTextFieldMapNameChanged(DocumentEvent evt) {
        if (!jTextFieldMapName.getText().equals("")){
            jButtonOk.setEnabled(true);
        }
        else {
            jButtonOk.setEnabled(false);
        }
    }

    public void setVisible(boolean visible){
    	if (visible == true){
            jTextFieldMapName.setText("");
            jButtonOk.setEnabled(false);
    	}
    	
        setLocationRelativeTo(null);        
    	super.setVisible(visible);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MapParameterDialog().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabelMapName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldMapName;
    // End of variables declaration//GEN-END:variables
    
}
