/*
 * JFrameHistoricoContaminantes.java
 *
 * Created on 19 de abril de 2005, 9:56
 */

package com.geopista.app.contaminantes;


import org.apache.log4j.Logger;

import javax.swing.*;
import javax.swing.table.TableColumn;
import java.util.ResourceBundle;
import java.util.Vector;
import java.util.Enumeration;
import java.text.SimpleDateFormat;
import java.io.StringWriter;
import java.io.PrintWriter;
import java.io.File;
import java.awt.*;


import com.geopista.app.utilidades.TableSorted;
import com.geopista.app.utilidades.CalendarButton;
import com.geopista.app.utilidades.estructuras.ComboBoxEstructuras;
import com.geopista.app.contaminantes.panel.JDialogApunte;
import com.geopista.app.contaminantes.utils.CUtilidades;
import com.geopista.protocol.contaminantes.PeticionBusquedaHistorico;
import com.geopista.protocol.contaminantes.OperacionesContaminantes;
import com.geopista.protocol.contaminantes.Historico;
import com.geopista.protocol.administrador.dominios.DomainNode;
import com.geopista.protocol.CResultadoOperacion;

/**
 *
 * @author  angeles
 */
public class JFrameHistoricoContaminantes extends javax.swing.JInternalFrame {
    public static Logger logger= Logger.getLogger(JFrameHistoricoContaminantes.class);
    private ResourceBundle messages;
	private JFrame frame;
    HistoricoTableModel modelHistorico;
    Vector listaHistoricos = null;
    private Historico historicoSelected=null;
    private TableSorted sorter;
    private static final int TIPO_ANOTACION=3;



    /** Creates new form JFrameHistoricoContaminantes */
    public JFrameHistoricoContaminantes(ResourceBundle messages, JFrame frame) {
		this.frame = frame;
		this.messages = messages;
		initComponents();
        actualizarModelo();
        changeScreenLang(messages);

    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        while (!com.geopista.app.contaminantes.Estructuras.isCargada()) {
            if (!com.geopista.app.contaminantes.Estructuras.isIniciada()) com.geopista.app.contaminantes.Estructuras.cargarEstructuras();
            try {
                Thread.sleep(500);
            } catch (Exception e) {
            }
        }
        jPanelBotonera = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();
        jPanelPrincipal = new javax.swing.JPanel();
        jPanelDato = new javax.swing.JPanel();
        jPanelListado = new javax.swing.JPanel();
        jScrollPaneListado = new javax.swing.JScrollPane();
        jTableListado = new javax.swing.JTable();
        jPanelApunte = new javax.swing.JPanel();
        jLabelApunte = new javax.swing.JLabel();
        jScrollPaneApunte = new javax.swing.JScrollPane();
        jTextAreaApunte = new javax.swing.JTextArea();
        jTextAreaApunte.setEditable(false);

        jPanelBusqueda = new javax.swing.JPanel();
        jLabelTipoBusqueda = new javax.swing.JLabel();
        jComboBoxTipoBusqueda = new ComboBoxEstructuras(com.geopista.app.contaminantes.Estructuras.getListaTipoMedioambiental(),null,
                com.geopista.app.contaminantes.Constantes.Locale);
        jButtonBuscar = new javax.swing.JButton();
        jLabelFechaDesde = new javax.swing.JLabel();
        jTextFieldFechaDesde = new JFormattedTextField((new SimpleDateFormat("dd-MM-yyyy")));
        jTextFieldFechaDesde.setEditable(false);
        jButtonFechaDesde = new CalendarButton(jTextFieldFechaDesde);

        jLabelFechaHasta = new javax.swing.JLabel();
        jTextFieldFechaHasta = new JFormattedTextField((new SimpleDateFormat("dd-MM-yyyy")));
        jTextFieldFechaHasta.setEditable(false);
        jLabelAccion = new javax.swing.JLabel();
        jComboBoxAccion = new ComboBoxEstructuras(com.geopista.app.contaminantes.Estructuras.getListaTipoAccion(),null,
                com.geopista.app.contaminantes.Constantes.Locale);
        jButtonFechaHasta = new CalendarButton(jTextFieldFechaHasta);
        jPanelComandos = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonGenerarFicha= new javax.swing.JButton();

        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				borrar();
			}
		});
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				salir();
			}
		});
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadir();
            }
        });

        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buscar();
			}
		});
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				modificar();
			}
		});

        jButtonGenerarFicha.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				generarFicha();
			}
		});


        jPanelBotonera.add(jButtonGenerarFicha);
        jPanelBotonera.add(jButtonAdd);
        jPanelBotonera.add(jButtonModificar);
        jPanelBotonera.add(jButtonBorrar);
        jPanelBotonera.add(jButtonSalir);
        
        getContentPane().add(jPanelBotonera, java.awt.BorderLayout.SOUTH);

        jPanelPrincipal.setLayout(new java.awt.BorderLayout());

        jPanelDato.setLayout(new java.awt.BorderLayout());

        jPanelListado.setLayout(new java.awt.BorderLayout());

        //jPanelListado.setPreferredSize(new java.awt.Dimension(100, 200));
        jScrollPaneListado.setBorder(new javax.swing.border.EtchedBorder());
        //jScrollPaneListado.setPreferredSize(new java.awt.Dimension(300, 200));
        jTableListado.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				seleccionar();
			}
		});
        jScrollPaneListado.setViewportView(jTableListado);

        jPanelListado.add(jScrollPaneListado, java.awt.BorderLayout.CENTER);
        jPanelDato.add(jPanelListado, java.awt.BorderLayout.CENTER);
        //jPanelApunte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelApunte.setLayout(new BorderLayout());
        jPanelApunte.setPreferredSize(new java.awt.Dimension(400, 150));
        jScrollPaneApunte.setViewportView(jTextAreaApunte);
        jPanelApunte.add(jLabelApunte, BorderLayout.NORTH);
        //jPanelApunte.add(jScrollPaneApunte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10,30 , 480, 90));
        jPanelApunte.add(jScrollPaneApunte, BorderLayout.CENTER);
        jPanelDato.add(jPanelApunte, java.awt.BorderLayout.SOUTH);
        jPanelBusqueda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelBusqueda.setBorder(new javax.swing.border.EtchedBorder());
        //jPanelBusqueda.setPreferredSize(new java.awt.Dimension(34, 150));
        jPanelBusqueda.setPreferredSize(new java.awt.Dimension(34, 130));
        
        jPanelBusqueda.add(jLabelTipoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jPanelBusqueda.add(jComboBoxTipoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 140, -1));
        jPanelBusqueda.add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));
        jPanelBusqueda.add(jLabelFechaDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, -1));
        jPanelBusqueda.add(jTextFieldFechaDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 120, -1));
        jPanelBusqueda.add(jLabelFechaHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 100, -1));
        jPanelBusqueda.add(jTextFieldFechaHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 120, -1));
        jPanelBusqueda.add(jLabelAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));
        jPanelBusqueda.add(jComboBoxAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 140, -1));
        jPanelBusqueda.add(jButtonFechaDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 20, 20));
        jPanelBusqueda.add(jButtonFechaHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 20, 20));
        
        
        jPanelBusqueda.add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));
        jPanelDato.add(jPanelBusqueda, java.awt.BorderLayout.NORTH);
        jPanelPrincipal.add(jPanelDato, java.awt.BorderLayout.CENTER);
        getContentPane().add(jPanelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    private void actualizarModelo() {
		modelHistorico = new HistoricoTableModel();
		modelHistorico.setModelData(listaHistoricos);
		sorter = new TableSorted(modelHistorico);
		sorter.setTableHeader(jTableListado.getTableHeader());
		jTableListado.setModel(sorter);
		jTableListado.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

	}
     private void buscar() {
        try
        {
                if (!com.geopista.security.SecurityManager.isLogged()) return;
                PeticionBusquedaHistorico peticion= new PeticionBusquedaHistorico();
                if (jTextFieldFechaDesde.getText().length()>0) peticion.setFechaDesde(jButtonFechaDesde.getCalendar().getTime());
                if (jTextFieldFechaHasta.getText().length()>0) peticion.setFechaHasta(jButtonFechaHasta.getCalendar().getTime());
                if (jComboBoxAccion.getSelectedIndex()!=0)
                  try{ peticion.setAccion(new Integer(((DomainNode)jComboBoxAccion.getSelectedItem()).getPatron()));}catch(Exception ex){};
               if (jComboBoxTipoBusqueda.getSelectedIndex()!=0)
                  try{ peticion.setTipo(new Integer(((DomainNode)jComboBoxTipoBusqueda.getSelectedItem()).getPatron()));}catch(Exception ex){};

                listaHistoricos= new OperacionesContaminantes(com.geopista.app.contaminantes.Constantes.url).getHistorico(peticion);
                actualizarModelo();
                historicoSelected=null;
        }catch (Exception e){
            logger.error("Error al hacer la peticion de busqueda: "+e.toString());
            JOptionPane optionPane= new JOptionPane("Error al hacer la búsqueda \n"+e.getMessage(),JOptionPane.INFORMATION_MESSAGE);
            JDialog dialog =optionPane.createDialog(frame,"ERROR");
            dialog.show();
        }
	}


    public void changeScreenLang(ResourceBundle messages) {
        try
        {
            this.messages = messages;
            jButtonSalir.setText(messages.getString("JFrameHistorico.jButtonSalir"));
            jButtonBorrar.setText(messages.getString("JFrameHistorico.jButtonBorrar"));
            jButtonModificar.setText(messages.getString("JFrameHistorico.jButtonModificar"));
            jButtonAdd.setText(messages.getString("JFrameHistorico.jButtonAdd"));
            jButtonGenerarFicha.setText(messages.getString("JFrameHistorico.jButtonGenerarFicha"));
            jLabelAccion.setText(messages.getString("JFrameHistorico.jLabelAccion"));
            jLabelFechaHasta.setText(messages.getString("JFrameHistorico.jLabelFechaHasta"));
            jLabelFechaDesde.setText(messages.getString("JFrameHistorico.jLabelFechaDesde"));
            jLabelTipoBusqueda.setText(messages.getString("JFrameHistorico.jLabelTipoBusqueda"));
            jButtonBuscar.setText(messages.getString("JFrameHistorico.jButtonBuscar"));
            jLabelApunte.setText(messages.getString("JFrameHistorico.jLabelApunte")+":");
            setTitle(messages.getString("JFrameHistorico.title"));

            jButtonSalir.setToolTipText(messages.getString("JFrameHistorico.jButtonSalir"));
            jButtonBorrar.setToolTipText(messages.getString("JFrameHistorico.jButtonBorrar"));
            jButtonModificar.setToolTipText(messages.getString("JFrameHistorico.jButtonModificar"));
            jButtonAdd.setToolTipText(messages.getString("JFrameHistorico.jButtonAdd"));
            jButtonGenerarFicha.setToolTipText(messages.getString("JFrameHistorico.jButtonGenerarFicha"));
            jButtonBuscar.setToolTipText(messages.getString("JFrameHistorico.jButtonBuscar"));
            jButtonFechaDesde.setToolTipText(messages.getString("JFrameHistorico.jButtonFechaDesde"));
            jButtonFechaHasta.setToolTipText(messages.getString("JFrameHistorico.jButtonFechaHasta"));

            /** Headers de la tabla eventos */
            TableColumn tableColumn= jTableListado.getColumnModel().getColumn(0);
            tableColumn.setHeaderValue(messages.getString("historicoTableModel.FECHA"));
            tableColumn= jTableListado.getColumnModel().getColumn(1);
            tableColumn.setHeaderValue(messages.getString("historicoTableModel.USUARIO"));
            tableColumn= jTableListado.getColumnModel().getColumn(2);
            tableColumn.setHeaderValue(messages.getString("historicoTableModel.TIPO"));
            tableColumn= jTableListado.getColumnModel().getColumn(3);
            tableColumn.setHeaderValue(messages.getString("historicoTableModel.ACCION"));
            tableColumn= jTableListado.getColumnModel().getColumn(4);
            tableColumn.setHeaderValue(messages.getString("historicoTableModel.APUNTE"));
            tableColumn= jTableListado.getColumnModel().getColumn(5);
            tableColumn.setHeaderValue(messages.getString("historicoTableModel.SISTEMA"));
            tableColumn= jTableListado.getColumnModel().getColumn(6);
            tableColumn.setHeaderValue(messages.getString("historicoTableModel.ID_ELEMENTO"));
            tableColumn= jTableListado.getColumnModel().getColumn(7);
            tableColumn.setHeaderValue(messages.getString("historicoTableModel.ID"));

        }catch (Exception e)
        {
            logger.error("Error al cargar las etiquetas:", e);
        }
    }
    private void salir() {
		dispose();
	}
    private void seleccionar() {
        try {
            int row = jTableListado.getSelectedRow();
            if (row != -1) {
                jTextAreaApunte.setText((String) jTableListado.getValueAt(row, HistoricoTableModel.IND_APUNTE));
            }
            Long id=(Long) jTableListado.getValueAt(row, HistoricoTableModel.IND_ID);
            historicoSelected= getHistorico(id);

        } catch (Exception ex) {
            StringWriter sw = new StringWriter();
            PrintWriter pw = new PrintWriter(sw);
            ex.printStackTrace(pw);
            logger.error("Exception: " + sw.toString());
        }
    }
    private void anadir()
    {
        Historico historico=new Historico();
        historico.setId_historico(-1);
        historico.setTipo_medioambiental(-1);
        JDialogApunte dialogApunte = new JDialogApunte(this.frame,true, messages,historico);
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        dialogApunte.setSize(400,250);
        dialogApunte.setLocation(d.width/2 - dialogApunte.getSize().width/2, d.height/2 - dialogApunte.getSize().height/2);
        dialogApunte.setResizable(false);
        dialogApunte.show();
        if (dialogApunte.isAceptado())
        {
            historico=dialogApunte.getHistorico();
            historico.setAccion(TIPO_ANOTACION);
            historico.setSistema(0);
            historico.setNombre_Usuario(com.geopista.security.SecurityManager.getUserPrincipal().getName());
            try
            {
                CResultadoOperacion result=new OperacionesContaminantes((com.geopista.app.contaminantes.Constantes.url)).gestionarHistorico(historico);
                if (result.getResultado()&&result.getVector()!=null&&result.getVector().size()>=1)
                {
                    historico=(Historico)result.getVector().elementAt(0);
                    listaHistoricos=ponerElPrimero(historico);
                    actualizarModelo();
                }
            }catch(Exception e)
            {
                logger.error("Error al insertar un dato en el historico",e);
            }
        }
        dialogApunte=null;
    }

    private void modificar()
    {
        if (historicoSelected==null) return;
        JDialogApunte dialogApunte = new JDialogApunte(this.frame,true, messages,historicoSelected);
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        dialogApunte.setSize(400,250);
        dialogApunte.setLocation(d.width/2 - dialogApunte.getSize().width/2, d.height/2 - dialogApunte.getSize().height/2);
        dialogApunte.setResizable(false);
        dialogApunte.enabledCombo(false);
        dialogApunte.show();
        if (dialogApunte.isAceptado())
        {
            historicoSelected=dialogApunte.getHistorico();
            try
            {
                CResultadoOperacion result=new OperacionesContaminantes((com.geopista.app.contaminantes.Constantes.url)).gestionarHistorico(historicoSelected);
                if (result.getResultado())
                {
                    listaHistoricos=actualizarListado(historicoSelected);
                    actualizarModelo();
                }
            }catch(Exception e)
            {
                logger.error("Error al insertar un dato en el historico");
            }
        }
        dialogApunte=null;
    }
    private void borrar()
    {
        if (historicoSelected==null) return;
        try
        {
            if (historicoSelected.esSistema())
            {
                JOptionPane optionPane = new JOptionPane(messages.getString("JFrameHistorico.mensaje.essistema"), JOptionPane.ERROR_MESSAGE);
                JDialog dialog = optionPane.createDialog(frame, "INFORMACION");
                dialog.show();
                return;
            }

            int ok= JOptionPane.showConfirmDialog(this, messages.getString("JFrameHistorico.mensajeBorrar.text"), messages.getString("JFrameHistorico.mensajeBorrar.tittle"), JOptionPane.YES_NO_OPTION);
            if (ok == JOptionPane.YES_OPTION){
                historicoSelected.setBorrar(true);
                CResultadoOperacion result=new OperacionesContaminantes((com.geopista.app.contaminantes.Constantes.url)).gestionarHistorico(historicoSelected);
                if (result.getResultado())
                {
                        jTextAreaApunte.setText("");
                        listaHistoricos=actualizarListado(historicoSelected);
                        actualizarModelo();
                }
                historicoSelected=null;
            }

        }catch(Exception e)
        {
            logger.error("Error al insertar un dato en el historico");
        }
    }


    private Historico getHistorico(Long id) {
        if (listaHistoricos == null || id == null) return null;
        for (Enumeration e = listaHistoricos.elements(); e.hasMoreElements();) {
            Historico aux = (Historico) e.nextElement();
            if (id.longValue()==aux.getId_historico())
                return aux;
        }
        return null;
    }
      private Vector actualizarListado(Historico historico) {
		Vector vector = new Vector();
		for (int i = 0; i < listaHistoricos.size(); i++) {
			Historico aux = (Historico) listaHistoricos.elementAt(i);
			if (aux.getId_historico()== new Long(historico.getId_historico()).longValue()) {
				if (!historico.isBorrar()) {
					vector.add(historico);
				}
				continue;
			}
			vector.add(aux);
		}
		return vector;
	}
    private Vector ponerElPrimero(Historico historico) {
		Vector vector = new Vector();
        vector.add(historico);
        if (listaHistoricos==null) return vector;
		for (int i = 0; i < listaHistoricos.size(); i++) {
            Historico aux=(Historico)listaHistoricos.get(i);
			vector.add(aux);
		}
		return vector;
	}


    private void generarFicha(){
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try{
            if (listaHistoricos != null){
                JFileChooser chooser = new JFileChooser();
                com.geopista.app.utilidades.GeoPistaFileFilter filter= new com.geopista.app.utilidades.GeoPistaFileFilter();
                filter.addExtension("txt");
                filter.setDescription("Fichero TXT");
                chooser.setFileFilter(filter);
                /** Permite multiples selecciones */
                chooser.setMultiSelectionEnabled(false);

                int returnVal = chooser.showSaveDialog(this);

                if (returnVal == JFileChooser.APPROVE_OPTION) {
                   File selectedFile= chooser.getSelectedFile();
                   CUtilidades.generarFichaHistoricoMenu(frame, listaHistoricos, selectedFile, messages);
                }
            }else{
                JOptionPane.showMessageDialog(frame, messages.getString("JFrameHistorico.mensaje3"));
            }
       }catch(Exception e){
           logger.error("Error al generar la ficha: ",e);
       }

       this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonBuscar;
    private CalendarButton jButtonFechaDesde;
    private CalendarButton jButtonFechaHasta;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox jComboBoxAccion;
    private javax.swing.JComboBox jComboBoxTipoBusqueda;
    private javax.swing.JLabel jLabelAccion;
    private javax.swing.JLabel jLabelApunte;
    private javax.swing.JLabel jLabelFechaDesde;
    private javax.swing.JLabel jLabelFechaHasta;
    private javax.swing.JLabel jLabelTipoBusqueda;
    private javax.swing.JPanel jPanelApunte;
    private javax.swing.JPanel jPanelBotonera;
    private javax.swing.JPanel jPanelBusqueda;
    private javax.swing.JPanel jPanelComandos;
    private javax.swing.JPanel jPanelDato;
    private javax.swing.JPanel jPanelListado;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPaneApunte;
    private javax.swing.JScrollPane jScrollPaneListado;
    private javax.swing.JTable jTableListado;
    private javax.swing.JTextArea jTextAreaApunte;
    private JFormattedTextField jTextFieldFechaDesde;
    private JFormattedTextField jTextFieldFechaHasta;
    private javax.swing.JButton jButtonGenerarFicha;
     // End of variables declaration//GEN-END:variables
    
}
