package com.geopista.app.cementerios.business.dao.interfaces;

import java.sql.SQLException;
import java.util.List;

import com.geopista.app.cementerios.business.vo.Concesion;
import com.geopista.app.cementerios.business.vo.ConcesionExample;

public interface ConcesionDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.concesion
	 * @throws SQLException 
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.concesion
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	Integer insert(Concesion record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.concesion
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	Integer insertSelective(Concesion record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.concesion
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	List selectByExample(ConcesionExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.concesion
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	Concesion selectByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.concesion
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	int updateByPrimaryKeySelective(Concesion record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.concesion
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	int updateByPrimaryKey(Concesion record) throws SQLException;

	/**
	 * Set the iBATIS Database Layer SqlMapClient to work with.
	 * @param sqlMapper
	 */
//	void setSqlMapClient(SqlMapClient sqlMapper) throws SQLException;

	
	public int selectByLastSeqKey() throws SQLException;
	
	Concesion selectByUnidad (Integer id_unidad) throws SQLException;
	
	
	public List selectAll () throws SQLException;
	
	
}