package com.geopista.app.cementerios.business.dao.interfaces;

import java.sql.SQLException;
import java.util.List;

import com.geopista.app.cementerios.business.vo.Exhumacion;
import com.geopista.app.cementerios.business.vo.ExhumacionExample;

public interface ExhumacionDAO {
    /**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.exhumacion
     * @throws SQLException 
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	int deleteByExample(ExhumacionExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.exhumacion
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.exhumacion
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	Integer insert(Exhumacion record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.exhumacion
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	Integer insertSelective(Exhumacion record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.exhumacion
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	List selectByExample(ExhumacionExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.exhumacion
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	Exhumacion selectByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.exhumacion
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	int updateByExampleSelective(Exhumacion record, ExhumacionExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.exhumacion
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	int updateByExample(Exhumacion record, ExhumacionExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.exhumacion
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	int updateByPrimaryKeySelective(Exhumacion record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.exhumacion
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	int updateByPrimaryKey(Exhumacion record) throws SQLException;

	int selectByLastSeqKey() throws SQLException;
	
	List selectAll() throws SQLException;
}