package com.geopista.app.cementerios.business.dao.interfaces;

import com.geopista.app.cementerios.business.vo.HistoricoPropiedad;
import com.geopista.app.cementerios.business.vo.HistoricoPropiedadExample;

import java.sql.SQLException;
import java.util.List;

public interface HistoricoPropiedadDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cementerio.historico_propiedad
     * @throws SQLException 
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    int deleteByExample(HistoricoPropiedadExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cementerio.historico_propiedad
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cementerio.historico_propiedad
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    Integer insert(HistoricoPropiedad record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cementerio.historico_propiedad
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    Integer insertSelective(HistoricoPropiedad record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cementerio.historico_propiedad
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    List selectByExample(HistoricoPropiedadExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cementerio.historico_propiedad
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    HistoricoPropiedad selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cementerio.historico_propiedad
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    int updateByExampleSelective(HistoricoPropiedad record, HistoricoPropiedadExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cementerio.historico_propiedad
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    int updateByExample(HistoricoPropiedad record, HistoricoPropiedadExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cementerio.historico_propiedad
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    int updateByPrimaryKeySelective(HistoricoPropiedad record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cementerio.historico_propiedad
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    int updateByPrimaryKey(HistoricoPropiedad record) throws SQLException;
    
	List  selectByTitular (String dniTitular) throws SQLException;
}