package com.geopista.app.cementerios.business.dao.interfaces;

import com.geopista.app.cementerios.business.vo.Inhumacion;
import com.geopista.app.cementerios.business.vo.InhumacionExample;

import java.sql.SQLException;
import java.util.List;

public interface InhumacionDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.inhumacion
	 * @throws SQLException 
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	int deleteByExample(InhumacionExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.inhumacion
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.inhumacion
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	Integer insert(Inhumacion record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.inhumacion
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	Integer insertSelective(Inhumacion record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.inhumacion
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	List selectByExample(InhumacionExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.inhumacion
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	Inhumacion selectByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.inhumacion
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	int updateByExampleSelective(Inhumacion record, InhumacionExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.inhumacion
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	int updateByExample(Inhumacion record, InhumacionExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.inhumacion
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	int updateByPrimaryKeySelective(Inhumacion record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.inhumacion
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	int updateByPrimaryKey(Inhumacion record) throws SQLException;

	int selectByLastSeqKey() throws SQLException;
	
	List selectAll() throws SQLException;
}