SET statement_timeout = 0;
SET client_encoding = 'UTF-8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET default_with_oids = true;

SET client_min_messages TO WARNING;

insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22001,'ABIEGO',0,0,0,0,1,10,11);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22002,'ABIZANDA',0,0,0,3,0,11,14);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22003,'ADAHUESCA',0,0,0,1,0,5,6);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22004,'AGUERO',0,0,0,0,1,9,10);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22006,'AISA',0,0,0,1,0,4,5);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22007,'ALBALATE DE CINCA',0,0,0,0,0,11,11);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22008,'ALBALATILLO',1,0,0,0,0,4,5);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22009,'ALBELDA',0,0,0,2,0,8,10);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22011,'ALBERO ALTO',0,0,0,1,0,6,7);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22012,'ALBERO BAJO',0,0,0,0,1,0,1);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22013,'ALBERUELA DE TUBO',0,0,0,2,0,6,8);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22014,'ALCALA DE GURREA',0,0,0,0,1,4,5);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22015,'ALCALA DEL OBISPO',0,0,0,1,2,7,10);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22016,'ALCAMPELL',1,0,0,0,0,5,6);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22017,'ALCOLEA DE CINCA',1,0,0,0,0,4,5);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22018,'ALCUBIERRE',0,0,0,1,0,9,10);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22019,'ALERRE',0,0,0,2,0,8,10);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22020,'ALFANTEGA',0,0,0,2,1,2,5);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22021,'ALMUDEVAR',0,0,0,1,1,11,13);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22022,'ALMUNIA DE SAN JUAN',0,0,0,0,0,9,9);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22023,'ALMUNIENTE',0,0,0,1,0,13,14);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22024,'ALQUEZAR',0,0,0,2,1,7,10);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22025,'ALTORRICON',0,0,1,2,0,3,6);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22027,'ANGÜES',0,0,0,1,0,7,8);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22028,'ANSO',0,0,0,0,0,8,8);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22029,'ANTILLON',0,0,0,0,0,11,11);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22032,'ARAGÜES DEL PUERTO',0,0,0,0,0,12,12);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22035,'AREN',0,1,0,2,2,17,22);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22036,'ARGAVIESO',2,0,0,0,0,7,9);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22037,'ARGUIS',0,0,0,1,0,3,4);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22039,'AYERBE',0,0,0,2,0,5,7);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22040,'AZANUY-ALINS',0,0,0,1,0,8,9);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22041,'AZARA',0,0,0,1,0,14,15);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22042,'AZLOR',0,0,0,0,2,6,8);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22043,'BAELLS',1,0,0,2,0,7,10);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22044,'BAILO',0,0,0,5,0,6,11);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22045,'BALDELLOU',0,0,0,1,2,8,11);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22046,'BALLOBAR',0,0,0,1,1,7,9);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22047,'BANASTAS',0,0,0,0,0,15,15);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22048,'BARBASTRO',0,0,0,4,1,9,14);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22049,'BARBUES',0,0,0,3,0,9,12);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22050,'BARBUÑALES',0,0,0,2,0,4,6);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22051,'BARCABO',0,0,0,2,0,12,14);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22052,'BELVER DE CINCA',0,0,0,1,0,17,18);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22053,'BENABARRE',0,0,0,0,2,15,17);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22054,'BENASQUE',0,0,0,0,0,7,7);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22055,'BERBEGAL',0,0,0,3,2,7,12);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22057,'BIELSA',0,0,0,2,0,8,10);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22058,'BIERGE',0,0,0,1,3,4,8);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22059,'BIESCAS',0,0,0,4,1,13,18);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22060,'BINACED',0,0,0,1,1,7,9);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22061,'BINEFAR',0,0,0,2,1,9,12);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22062,'BISAURRI',0,0,0,1,0,7,8);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22063,'BISCARRUES',0,1,0,1,1,9,12);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22064,'BLECUA Y TORRES',0,0,2,1,0,8,11);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22066,'BOLTAÑA',0,0,0,1,1,5,7);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22067,'BONANSA',0,0,0,2,0,5,7);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22068,'BORAU',0,0,0,0,0,7,7);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22069,'BROTO',0,1,0,4,3,10,18);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22072,'CALDEARENAS',1,0,0,2,0,7,10);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22074,'CAMPO',0,0,0,3,1,6,10);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22075,'CAMPORRELLS',0,0,0,1,1,9,11);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22076,'CANAL DE BERDUN',0,0,0,4,0,9,13);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22077,'CANDASNOS',2,0,0,0,1,6,9);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22078,'CANFRANC',0,0,0,2,0,6,8);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22079,'CAPDESASO',0,0,0,1,0,11,12);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22080,'CAPELLA',0,0,0,4,0,12,16);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22081,'CASBAS DE HUESCA',0,0,0,3,0,10,13);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22082,'CASTEJON DEL PUENTE',0,0,0,5,1,8,14);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22083,'CASTEJON DE MONEGROS',0,0,0,0,0,9,9);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22084,'CASTEJON DE SOS',0,0,0,1,3,8,12);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22085,'CASTELFLORITE',0,0,0,2,0,8,10);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22086,'CASTIELLO DE JACA',0,0,0,1,3,6,10);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22087,'CASTIGALEU',0,0,0,0,0,5,5);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22088,'CASTILLAZUELO',0,0,0,2,1,5,8);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22089,'CASTILLONROY',0,0,0,1,0,7,8);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22090,'COLUNGO',0,0,0,0,0,12,12);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22094,'CHALAMERA',1,0,0,1,0,8,10);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22095,'CHIA',0,0,0,3,0,5,8);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22096,'CHIMILLAS',0,0,1,3,0,3,7);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22099,'ESPLUS',0,0,0,2,0,4,6);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22102,'ESTADA',2,0,0,0,0,4,6);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22103,'ESTADILLA',0,0,0,2,0,15,17);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22105,'ESTOPIÑAN DEL CASTILLO',0,0,0,1,0,5,6);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22106,'FAGO',0,0,1,0,0,3,4);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22107,'FANLO',0,0,0,0,0,2,2);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22109,'FISCAL',0,0,0,1,1,11,13);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22110,'FONZ',0,0,0,1,1,5,7);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22111,'FORADADA DEL TOSCAR',0,0,0,2,0,7,9);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22112,'FRAGA',0,0,0,0,0,18,18);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22113,'FUEVA, LA',0,0,0,1,3,17,21);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22114,'GISTAIN',0,0,0,3,1,4,8);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22115,'GRADO, EL',0,0,0,0,0,8,8);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22116,'GRAÑEN',0,0,0,2,1,11,14);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22117,'GRAUS',0,0,0,1,1,11,13);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22119,'GURREA DE GALLEGO',0,0,0,1,0,12,13);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22122,'HOZ DE JACA',0,1,0,1,1,4,7);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22124,'HUERTO',0,0,0,4,0,7,11);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22125,'HUESCA',0,0,0,0,0,3,3);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22126,'IBIECA',0,0,0,1,0,5,6);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22127,'IGRIES',0,0,0,0,0,8,8);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22128,'ILCHE',0,0,0,1,0,4,5);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22129,'ISABENA',0,0,0,1,1,12,14);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22130,'JACA',0,0,0,2,2,6,10);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22131,'JASA',0,1,0,0,0,3,4);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22133,'LABUERDA',0,0,0,3,0,10,13);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22135,'LALUENGA',0,0,0,0,1,14,15);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22136,'LALUEZA',0,0,0,2,0,12,14);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22137,'LANAJA',0,0,0,1,0,15,16);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22139,'LAPERDIGUERA',0,0,0,0,0,7,7);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22141,'LASCELLAS-PONZANO',0,0,0,0,0,6,6);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22142,'LASCUARRE',0,0,0,2,0,7,9);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22143,'LASPAULES',0,0,0,1,1,9,11);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22144,'LASPUÑA',0,0,0,1,0,7,8);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22149,'LOARRE',0,0,0,0,1,5,6);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22150,'LOPORZANO',0,0,0,1,0,9,10);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22151,'LOSCORRALES',0,0,0,0,0,9,9);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22155,'MONESMA Y CAJIGAR',0,0,0,0,0,5,5);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22156,'MONFLORITE-LASCASAS',0,0,0,1,0,7,8);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22157,'MONTANUY',0,0,0,5,0,2,7);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22158,'MONZON',0,0,0,1,0,8,9);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22160,'NAVAL',0,0,0,1,1,13,15);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22162,'NOVALES',0,0,0,2,0,5,7);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22163,'NUENO',0,0,0,1,0,11,12);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22164,'OLVENA',0,0,0,0,0,3,3);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22165,'ONTIÑENA',0,0,0,1,0,6,7);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22167,'OSSO DE CINCA',0,0,0,2,1,13,16);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22168,'PALO',0,0,0,1,0,5,6);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22170,'PANTICOSA',0,0,0,0,1,11,12);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22172,'PEÑALBA',0,0,0,1,2,5,8);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22173,'PEÑAS DE RIGLOS, LAS',0,0,0,0,2,10,12);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22174,'PERALTA DE ALCOFEA',0,0,0,3,1,5,9);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22175,'PERALTA DE CALASANZ',0,0,0,0,0,3,3);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22176,'PERALTILLA',0,0,0,0,0,11,11);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22177,'PERARRUA',0,0,0,0,0,5,5);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22178,'PERTUSA',0,0,0,0,0,6,6);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22181,'PIRACES',0,0,0,2,0,6,8);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22182,'PLAN',0,1,0,5,0,5,11);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22184,'POLEÑINO',0,0,0,3,0,7,10);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22186,'POZAN DE VERO',0,0,0,1,0,10,11);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22187,'PUEBLA DE CASTRO, LA',0,0,0,2,0,5,7);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22188,'PUENTE DE MONTAÑANA',0,0,0,2,0,4,6);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22189,'PUERTOLAS',0,0,0,1,0,8,9);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22190,'PUEYO DE ARAGUAS, EL',0,0,0,1,0,9,10);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22193,'PUEYO DE SANTA CRUZ',0,0,0,3,0,5,8);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22195,'QUICENA',0,1,0,2,0,2,5);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22197,'ROBRES',1,0,0,0,1,6,8);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22199,'SABIÑANIGO',0,0,0,2,2,9,13);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22200,'SAHUN',0,0,0,0,1,7,8);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22201,'SALAS ALTAS',0,0,0,3,0,8,11);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22202,'SALAS BAJAS',0,0,0,2,0,6,8);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22203,'SALILLAS',0,0,0,0,1,4,5);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22204,'SALLENT DE GALLEGO',0,1,1,2,0,9,13);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22205,'SAN ESTEBAN DE LITERA',0,0,0,1,0,11,12);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22206,'SANGARREN',0,0,0,1,0,5,6);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22207,'SAN JUAN DE PLAN',0,0,0,0,1,5,6);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22208,'SANTA CILIA',0,0,0,2,0,7,9);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22209,'SANTA CRUZ DE LA SEROS',0,0,0,0,0,9,9);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22212,'SANTALIESTRA Y SAN QUILEZ',0,0,0,2,0,13,15);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22213,'SARIÑENA',0,0,0,2,1,18,21);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22214,'SECASTILLA',1,0,0,1,0,6,8);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22215,'SEIRA',0,0,0,3,0,7,10);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22217,'SENA',0,0,0,2,0,4,6);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22218,'SENES DE ALCUBIERRE',0,0,0,1,0,6,7);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22220,'SESA',0,0,0,1,0,5,6);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22221,'SESUE',0,0,0,1,1,6,8);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22222,'SIETAMO',0,0,0,1,1,7,9);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22223,'SOPEIRA',0,0,0,1,1,5,7);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22225,'TAMARITE DE LITERA',0,0,0,2,0,9,11);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22226,'TARDIENTA',0,0,0,4,2,10,16);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22227,'TELLA-SIN',0,0,0,2,0,5,7);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22228,'TIERZ',0,0,0,1,0,10,11);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22229,'TOLVA',0,0,0,4,0,8,12);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22230,'TORLA',0,0,0,0,1,7,8);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22232,'TORRALBA DE ARAGON',0,0,0,1,0,3,4);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22233,'TORRE LA RIBERA',0,0,0,1,1,12,14);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22234,'TORRENTE DE CINCA',0,0,0,1,0,6,7);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22235,'TORRES DE ALCANADRE',0,0,0,0,0,5,5);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22236,'TORRES DE BARBUES',0,0,0,2,0,7,9);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22239,'TRAMACED',0,0,0,0,2,5,7);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22242,'VALFARTA',1,0,0,0,0,4,5);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22243,'VALLE DE BARDAGI',0,0,0,1,1,5,7);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22244,'VALLE DE LIERP',0,0,0,4,1,3,8);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22245,'VELILLA DE CINCA',0,0,0,1,0,14,15);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22246,'VERACRUZ',0,0,0,2,0,9,11);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22247,'VIACAMP Y LITERA',0,0,0,2,1,9,12);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22248,'VICIEN',0,0,0,3,0,6,9);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22249,'VILLANOVA',0,0,0,2,0,4,6);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22250,'VILLANUA',0,0,0,2,1,3,6);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22251,'VILLANUEVA DE SIGENA',0,0,0,1,0,9,10);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22252,'YEBRA DE BASA',0,0,0,1,1,11,13);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22253,'YESERO',0,0,0,2,0,5,7);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22254,'ZAIDIN',0,0,0,2,0,4,6);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22901,'VALLE DE HECHO',0,0,0,2,2,15,19);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22902,'PUENTE LA REINA DE JACA',0,0,0,2,0,3,5);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22903,'SAN MIGUEL DEL CINCA',0,0,0,1,0,15,16);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22904,'SOTONERA, LA',0,0,0,1,0,8,9);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22905,'LUPIÑEN-ORTILLA',0,0,0,1,3,4,8);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22906,'SANTA MARIA DE DULCIS',0,0,0,3,0,5,8);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22907,'AINSA-SOBRARBE',0,0,0,2,2,13,17);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22908,'HOZ Y COSTEAN',1,0,0,0,0,7,8);
insert into estado_obras (id_municipio, nomayto, autorizadas, anuladas, revocadas, contratadas, enejecucion, liquidadas, total ) values (22909,'VENCILLON',0,0,0,0,0,16,16);
