/**
 * AnexoFeatureKey.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.geopista.app.cementerios.business.vo;

public class AnexoFeatureKey {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.anexo_feature.id_documento
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	private String idDocumento;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.anexo_feature.id_layer
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	private Integer idLayer;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.anexo_feature.id_feature
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	private Integer idFeature;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.anexo_feature.id_documento
	 * @return  the value of cementerio.anexo_feature.id_documento
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	public String getIdDocumento() {
		return idDocumento;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.anexo_feature.id_documento
	 * @param idDocumento  the value for cementerio.anexo_feature.id_documento
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	public void setIdDocumento(String idDocumento) {
		this.idDocumento = idDocumento;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.anexo_feature.id_layer
	 * @return  the value of cementerio.anexo_feature.id_layer
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	public Integer getIdLayer() {
		return idLayer;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.anexo_feature.id_layer
	 * @param idLayer  the value for cementerio.anexo_feature.id_layer
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	public void setIdLayer(Integer idLayer) {
		this.idLayer = idLayer;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.anexo_feature.id_feature
	 * @return  the value of cementerio.anexo_feature.id_feature
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	public Integer getIdFeature() {
		return idFeature;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.anexo_feature.id_feature
	 * @param idFeature  the value for cementerio.anexo_feature.id_feature
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	public void setIdFeature(Integer idFeature) {
		this.idFeature = idFeature;
	}
}