/**
 * AnexoCementerioKey.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.geopista.app.cementerios.business.vo;

public class AnexoCementerioKey {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.anexo_cementerio.id_documento
	 * @ibatorgenerated  Mon Jul 11 14:45:21 CEST 2011
	 */
	private String idDocumento;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.anexo_cementerio.id_elemcementerio
	 * @ibatorgenerated  Mon Jul 11 14:45:21 CEST 2011
	 */
	private Integer idElemcementerio;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.anexo_cementerio.id_documento
	 * @return  the value of cementerio.anexo_cementerio.id_documento
	 * @ibatorgenerated  Mon Jul 11 14:45:21 CEST 2011
	 */
	public String getIdDocumento() {
		return idDocumento;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.anexo_cementerio.id_documento
	 * @param idDocumento  the value for cementerio.anexo_cementerio.id_documento
	 * @ibatorgenerated  Mon Jul 11 14:45:21 CEST 2011
	 */
	public void setIdDocumento(String idDocumento) {
		this.idDocumento = idDocumento;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.anexo_cementerio.id_elemcementerio
	 * @return  the value of cementerio.anexo_cementerio.id_elemcementerio
	 * @ibatorgenerated  Mon Jul 11 14:45:21 CEST 2011
	 */
	public Integer getIdElemcementerio() {
		return idElemcementerio;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.anexo_cementerio.id_elemcementerio
	 * @param idElemcementerio  the value for cementerio.anexo_cementerio.id_elemcementerio
	 * @ibatorgenerated  Mon Jul 11 14:45:21 CEST 2011
	 */
	public void setIdElemcementerio(Integer idElemcementerio) {
		this.idElemcementerio = idElemcementerio;
	}
}