/**
 * Bloque.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.geopista.app.cementerios.business.vo;

public class Bloque {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.bloque.id
	 * @ibatorgenerated  Wed Jun 01 17:30:57 CEST 2011
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.bloque.tipo_bloque
	 * @ibatorgenerated  Wed Jun 01 17:30:57 CEST 2011
	 */
	private Integer tipoBloque;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.bloque.num_filas
	 * @ibatorgenerated  Wed Jun 01 17:30:57 CEST 2011
	 */
	private Integer numFilas;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.bloque.num_columnas
	 * @ibatorgenerated  Wed Jun 01 17:30:57 CEST 2011
	 */
	private Integer numColumnas;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.bloque.descripcion
	 * @ibatorgenerated  Wed Jun 01 17:30:57 CEST 2011
	 */
	private String descripcion;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.bloque.id_feature
	 * @ibatorgenerated  Wed Jun 01 17:30:57 CEST 2011
	 */
	private Integer idFeature;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.bloque.id_elemcementerio
	 * @ibatorgenerated  Wed Jun 01 17:30:57 CEST 2011
	 */
	private Integer idElemcementerio;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.bloque.id
	 * @return  the value of cementerio.bloque.id
	 * @ibatorgenerated  Wed Jun 01 17:30:57 CEST 2011
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.bloque.id
	 * @param id  the value for cementerio.bloque.id
	 * @ibatorgenerated  Wed Jun 01 17:30:57 CEST 2011
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.bloque.tipo_bloque
	 * @return  the value of cementerio.bloque.tipo_bloque
	 * @ibatorgenerated  Wed Jun 01 17:30:57 CEST 2011
	 */
	public Integer getTipoBloque() {
		return tipoBloque;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.bloque.tipo_bloque
	 * @param tipoBloque  the value for cementerio.bloque.tipo_bloque
	 * @ibatorgenerated  Wed Jun 01 17:30:57 CEST 2011
	 */
	public void setTipoBloque(Integer tipoBloque) {
		this.tipoBloque = tipoBloque;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.bloque.num_filas
	 * @return  the value of cementerio.bloque.num_filas
	 * @ibatorgenerated  Wed Jun 01 17:30:57 CEST 2011
	 */
	public Integer getNumFilas() {
		return numFilas;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.bloque.num_filas
	 * @param numFilas  the value for cementerio.bloque.num_filas
	 * @ibatorgenerated  Wed Jun 01 17:30:57 CEST 2011
	 */
	public void setNumFilas(Integer numFilas) {
		this.numFilas = numFilas;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.bloque.num_columnas
	 * @return  the value of cementerio.bloque.num_columnas
	 * @ibatorgenerated  Wed Jun 01 17:30:57 CEST 2011
	 */
	public Integer getNumColumnas() {
		return numColumnas;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.bloque.num_columnas
	 * @param numColumnas  the value for cementerio.bloque.num_columnas
	 * @ibatorgenerated  Wed Jun 01 17:30:57 CEST 2011
	 */
	public void setNumColumnas(Integer numColumnas) {
		this.numColumnas = numColumnas;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.bloque.descripcion
	 * @return  the value of cementerio.bloque.descripcion
	 * @ibatorgenerated  Wed Jun 01 17:30:57 CEST 2011
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.bloque.descripcion
	 * @param descripcion  the value for cementerio.bloque.descripcion
	 * @ibatorgenerated  Wed Jun 01 17:30:57 CEST 2011
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.bloque.id_feature
	 * @return  the value of cementerio.bloque.id_feature
	 * @ibatorgenerated  Wed Jun 01 17:30:57 CEST 2011
	 */
	public Integer getIdFeature() {
		return idFeature;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.bloque.id_feature
	 * @param idFeature  the value for cementerio.bloque.id_feature
	 * @ibatorgenerated  Wed Jun 01 17:30:57 CEST 2011
	 */
	public void setIdFeature(Integer idFeature) {
		this.idFeature = idFeature;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.bloque.id_elemcementerio
	 * @return  the value of cementerio.bloque.id_elemcementerio
	 * @ibatorgenerated  Wed Jun 01 17:30:57 CEST 2011
	 */
	public Integer getIdElemcementerio() {
		return idElemcementerio;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.bloque.id_elemcementerio
	 * @param idElemcementerio  the value for cementerio.bloque.id_elemcementerio
	 * @ibatorgenerated  Wed Jun 01 17:30:57 CEST 2011
	 */
	public void setIdElemcementerio(Integer idElemcementerio) {
		this.idElemcementerio = idElemcementerio;
	}
}