/**
 * Cementerio.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.geopista.app.cementerios.business.vo;

public class Cementerio {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.cementerio.id
	 * @ibatorgenerated  Thu Jun 02 17:44:12 CEST 2011
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.cementerio.nombre
	 * @ibatorgenerated  Thu Jun 02 17:44:12 CEST 2011
	 */
	private String nombre;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.cementerio.id
	 * @return  the value of cementerio.cementerio.id
	 * @ibatorgenerated  Thu Jun 02 17:44:12 CEST 2011
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.cementerio.id
	 * @param id  the value for cementerio.cementerio.id
	 * @ibatorgenerated  Thu Jun 02 17:44:12 CEST 2011
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.cementerio.nombre
	 * @return  the value of cementerio.cementerio.nombre
	 * @ibatorgenerated  Thu Jun 02 17:44:12 CEST 2011
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.cementerio.nombre
	 * @param nombre  the value for cementerio.cementerio.nombre
	 * @ibatorgenerated  Thu Jun 02 17:44:12 CEST 2011
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
}