/**
 * CementerioFeatureKey.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.geopista.app.cementerios.business.vo;

public class CementerioFeatureKey {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.cementerio_feature.id_elem
	 * @ibatorgenerated  Fri Jun 10 13:16:00 CEST 2011
	 */
	private Integer idElem;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.cementerio_feature.id_layer
	 * @ibatorgenerated  Fri Jun 10 13:16:00 CEST 2011
	 */
	private String idLayer;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.cementerio_feature.id_feature
	 * @ibatorgenerated  Fri Jun 10 13:16:00 CEST 2011
	 */
	private Integer idFeature;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.cementerio_feature.id_elem
	 * @return  the value of cementerio.cementerio_feature.id_elem
	 * @ibatorgenerated  Fri Jun 10 13:16:00 CEST 2011
	 */
	public Integer getIdElem() {
		return idElem;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.cementerio_feature.id_elem
	 * @param idElem  the value for cementerio.cementerio_feature.id_elem
	 * @ibatorgenerated  Fri Jun 10 13:16:00 CEST 2011
	 */
	public void setIdElem(Integer idElem) {
		this.idElem = idElem;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.cementerio_feature.id_layer
	 * @return  the value of cementerio.cementerio_feature.id_layer
	 * @ibatorgenerated  Fri Jun 10 13:16:00 CEST 2011
	 */
	public String getIdLayer() {
		return idLayer;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.cementerio_feature.id_layer
	 * @param idLayer  the value for cementerio.cementerio_feature.id_layer
	 * @ibatorgenerated  Fri Jun 10 13:16:00 CEST 2011
	 */
	public void setIdLayer(String idLayer) {
		this.idLayer = idLayer;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.cementerio_feature.id_feature
	 * @return  the value of cementerio.cementerio_feature.id_feature
	 * @ibatorgenerated  Fri Jun 10 13:16:00 CEST 2011
	 */
	public Integer getIdFeature() {
		return idFeature;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.cementerio_feature.id_feature
	 * @param idFeature  the value for cementerio.cementerio_feature.id_feature
	 * @ibatorgenerated  Fri Jun 10 13:16:00 CEST 2011
	 */
	public void setIdFeature(Integer idFeature) {
		this.idFeature = idFeature;
	}
}