/**
 * Concesion.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.geopista.app.cementerios.business.vo;

import java.util.Date;

public class Concesion {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.concesion.id
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.concesion.localizado
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	private String localizado;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.concesion.fecha_ini
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	private Date fechaIni;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.concesion.fecha_fin
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	private Date fechaFin;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.concesion.ultima_renova
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	private Date ultimaRenova;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.concesion.ultimo_titular
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	private String ultimoTitular;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.concesion.id_tarifa
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	private Integer idTarifa;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.concesion.id_unidad
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	private Integer idUnidad;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.concesion.estado
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	private Integer estado;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.concesion.tipo_concesion
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	private Integer tipoConcesion;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.concesion.descripcion
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	private String descripcion;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.concesion.codigo
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	private String codigo;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.concesion.precio_final
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	private String precioFinal;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.concesion.bonificacion
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	private String bonificacion;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.concesion.id
	 * @return  the value of cementerio.concesion.id
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.concesion.id
	 * @param id  the value for cementerio.concesion.id
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.concesion.localizado
	 * @return  the value of cementerio.concesion.localizado
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public String getLocalizado() {
		return localizado;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.concesion.localizado
	 * @param localizado  the value for cementerio.concesion.localizado
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public void setLocalizado(String localizado) {
		this.localizado = localizado;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.concesion.fecha_ini
	 * @return  the value of cementerio.concesion.fecha_ini
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public Date getFechaIni() {
		return fechaIni;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.concesion.fecha_ini
	 * @param fechaIni  the value for cementerio.concesion.fecha_ini
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public void setFechaIni(Date fechaIni) {
		this.fechaIni = fechaIni;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.concesion.fecha_fin
	 * @return  the value of cementerio.concesion.fecha_fin
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public Date getFechaFin() {
		return fechaFin;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.concesion.fecha_fin
	 * @param fechaFin  the value for cementerio.concesion.fecha_fin
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.concesion.ultima_renova
	 * @return  the value of cementerio.concesion.ultima_renova
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public Date getUltimaRenova() {
		return ultimaRenova;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.concesion.ultima_renova
	 * @param ultimaRenova  the value for cementerio.concesion.ultima_renova
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public void setUltimaRenova(Date ultimaRenova) {
		this.ultimaRenova = ultimaRenova;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.concesion.ultimo_titular
	 * @return  the value of cementerio.concesion.ultimo_titular
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public String getUltimoTitular() {
		return ultimoTitular;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.concesion.ultimo_titular
	 * @param ultimoTitular  the value for cementerio.concesion.ultimo_titular
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public void setUltimoTitular(String ultimoTitular) {
		this.ultimoTitular = ultimoTitular;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.concesion.id_tarifa
	 * @return  the value of cementerio.concesion.id_tarifa
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public Integer getIdTarifa() {
		return idTarifa;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.concesion.id_tarifa
	 * @param idTarifa  the value for cementerio.concesion.id_tarifa
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public void setIdTarifa(Integer idTarifa) {
		this.idTarifa = idTarifa;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.concesion.id_unidad
	 * @return  the value of cementerio.concesion.id_unidad
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public Integer getIdUnidad() {
		return idUnidad;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.concesion.id_unidad
	 * @param idUnidad  the value for cementerio.concesion.id_unidad
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public void setIdUnidad(Integer idUnidad) {
		this.idUnidad = idUnidad;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.concesion.estado
	 * @return  the value of cementerio.concesion.estado
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public Integer getEstado() {
		return estado;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.concesion.estado
	 * @param estado  the value for cementerio.concesion.estado
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.concesion.tipo_concesion
	 * @return  the value of cementerio.concesion.tipo_concesion
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public Integer getTipoConcesion() {
		return tipoConcesion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.concesion.tipo_concesion
	 * @param tipoConcesion  the value for cementerio.concesion.tipo_concesion
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public void setTipoConcesion(Integer tipoConcesion) {
		this.tipoConcesion = tipoConcesion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.concesion.descripcion
	 * @return  the value of cementerio.concesion.descripcion
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.concesion.descripcion
	 * @param descripcion  the value for cementerio.concesion.descripcion
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.concesion.codigo
	 * @return  the value of cementerio.concesion.codigo
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public String getCodigo() {
		return codigo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.concesion.codigo
	 * @param codigo  the value for cementerio.concesion.codigo
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.concesion.precio_final
	 * @return  the value of cementerio.concesion.precio_final
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public String getPrecioFinal() {
		return precioFinal;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.concesion.precio_final
	 * @param precioFinal  the value for cementerio.concesion.precio_final
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public void setPrecioFinal(String precioFinal) {
		this.precioFinal = precioFinal;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.concesion.bonificacion
	 * @return  the value of cementerio.concesion.bonificacion
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public String getBonificacion() {
		return bonificacion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.concesion.bonificacion
	 * @param bonificacion  the value for cementerio.concesion.bonificacion
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public void setBonificacion(String bonificacion) {
		this.bonificacion = bonificacion;
	}
}