/**
 * DatosFallecimiento.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.geopista.app.cementerios.business.vo;

import java.util.Date;

public class DatosFallecimiento {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.datosfallecimiento.id
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.datosfallecimiento.lugar
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	private String lugar;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.datosfallecimiento.poblacion
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	private String poblacion;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.datosfallecimiento.causa_fundamental
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	private String causaFundamental;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.datosfallecimiento.causa_inmediata
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	private String causaInmediata;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.datosfallecimiento.fecha
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	private Date fecha;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.datosfallecimiento.medico
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	private String medico;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.datosfallecimiento.num_colegiado
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	private String numColegiado;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.datosfallecimiento.registro_civill
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	private String registroCivill;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.datosfallecimiento.referencia
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	private String referencia;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.datosfallecimiento.id
	 * @return  the value of cementerio.datosfallecimiento.id
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.datosfallecimiento.id
	 * @param id  the value for cementerio.datosfallecimiento.id
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.datosfallecimiento.lugar
	 * @return  the value of cementerio.datosfallecimiento.lugar
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	public String getLugar() {
		return lugar;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.datosfallecimiento.lugar
	 * @param lugar  the value for cementerio.datosfallecimiento.lugar
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.datosfallecimiento.poblacion
	 * @return  the value of cementerio.datosfallecimiento.poblacion
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	public String getPoblacion() {
		return poblacion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.datosfallecimiento.poblacion
	 * @param poblacion  the value for cementerio.datosfallecimiento.poblacion
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	public void setPoblacion(String poblacion) {
		this.poblacion = poblacion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.datosfallecimiento.causa_fundamental
	 * @return  the value of cementerio.datosfallecimiento.causa_fundamental
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	public String getCausaFundamental() {
		return causaFundamental;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.datosfallecimiento.causa_fundamental
	 * @param causaFundamental  the value for cementerio.datosfallecimiento.causa_fundamental
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	public void setCausaFundamental(String causaFundamental) {
		this.causaFundamental = causaFundamental;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.datosfallecimiento.causa_inmediata
	 * @return  the value of cementerio.datosfallecimiento.causa_inmediata
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	public String getCausaInmediata() {
		return causaInmediata;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.datosfallecimiento.causa_inmediata
	 * @param causaInmediata  the value for cementerio.datosfallecimiento.causa_inmediata
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	public void setCausaInmediata(String causaInmediata) {
		this.causaInmediata = causaInmediata;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.datosfallecimiento.fecha
	 * @return  the value of cementerio.datosfallecimiento.fecha
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	public Date getFecha() {
		return fecha;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.datosfallecimiento.fecha
	 * @param fecha  the value for cementerio.datosfallecimiento.fecha
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.datosfallecimiento.medico
	 * @return  the value of cementerio.datosfallecimiento.medico
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	public String getMedico() {
		return medico;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.datosfallecimiento.medico
	 * @param medico  the value for cementerio.datosfallecimiento.medico
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	public void setMedico(String medico) {
		this.medico = medico;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.datosfallecimiento.num_colegiado
	 * @return  the value of cementerio.datosfallecimiento.num_colegiado
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	public String getNumColegiado() {
		return numColegiado;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.datosfallecimiento.num_colegiado
	 * @param numColegiado  the value for cementerio.datosfallecimiento.num_colegiado
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	public void setNumColegiado(String numColegiado) {
		this.numColegiado = numColegiado;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.datosfallecimiento.registro_civill
	 * @return  the value of cementerio.datosfallecimiento.registro_civill
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	public String getRegistroCivill() {
		return registroCivill;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.datosfallecimiento.registro_civill
	 * @param registroCivill  the value for cementerio.datosfallecimiento.registro_civill
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	public void setRegistroCivill(String registroCivill) {
		this.registroCivill = registroCivill;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.datosfallecimiento.referencia
	 * @return  the value of cementerio.datosfallecimiento.referencia
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	public String getReferencia() {
		return referencia;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.datosfallecimiento.referencia
	 * @param referencia  the value for cementerio.datosfallecimiento.referencia
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}
}