/**
 * DocumentoTipo.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.geopista.app.cementerios.business.vo;

public class DocumentoTipo {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.documento_tipos.tipo
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	private Short tipo;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.documento_tipos.extension
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	private String extension;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.documento_tipos.mime_type
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	private String mimeType;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.documento_tipos.tipo
	 * @return  the value of cementerio.documento_tipos.tipo
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	public Short getTipo() {
		return tipo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.documento_tipos.tipo
	 * @param tipo  the value for cementerio.documento_tipos.tipo
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	public void setTipo(Short tipo) {
		this.tipo = tipo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.documento_tipos.extension
	 * @return  the value of cementerio.documento_tipos.extension
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	public String getExtension() {
		return extension;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.documento_tipos.extension
	 * @param extension  the value for cementerio.documento_tipos.extension
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	public void setExtension(String extension) {
		this.extension = extension;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.documento_tipos.mime_type
	 * @return  the value of cementerio.documento_tipos.mime_type
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	public String getMimeType() {
		return mimeType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.documento_tipos.mime_type
	 * @param mimeType  the value for cementerio.documento_tipos.mime_type
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	public void setMimeType(String mimeType) {
		this.mimeType = mimeType;
	}
}