/**
 * HistoricoPropiedad.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.geopista.app.cementerios.business.vo;

import java.util.Date;

public class HistoricoPropiedad {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cementerio.historico_propiedad.id
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cementerio.historico_propiedad.dni_titular
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    private String dniTitular;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cementerio.historico_propiedad.tipo
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    private String tipo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cementerio.historico_propiedad.id_elem
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    private Integer idElem;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cementerio.historico_propiedad.fecha_operacion
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    private Date fechaOperacion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cementerio.historico_propiedad.comentario
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    private String comentario;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cementerio.historico_propiedad.id
     *
     * @return the value of cementerio.historico_propiedad.id
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cementerio.historico_propiedad.id
     *
     * @param id the value for cementerio.historico_propiedad.id
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cementerio.historico_propiedad.dni_titular
     *
     * @return the value of cementerio.historico_propiedad.dni_titular
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    public String getDniTitular() {
        return dniTitular;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cementerio.historico_propiedad.dni_titular
     *
     * @param dniTitular the value for cementerio.historico_propiedad.dni_titular
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    public void setDniTitular(String dniTitular) {
        this.dniTitular = dniTitular;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cementerio.historico_propiedad.tipo
     *
     * @return the value of cementerio.historico_propiedad.tipo
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cementerio.historico_propiedad.tipo
     *
     * @param tipo the value for cementerio.historico_propiedad.tipo
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cementerio.historico_propiedad.id_elem
     *
     * @return the value of cementerio.historico_propiedad.id_elem
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    public Integer getIdElem() {
        return idElem;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cementerio.historico_propiedad.id_elem
     *
     * @param idElem the value for cementerio.historico_propiedad.id_elem
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    public void setIdElem(Integer idElem) {
        this.idElem = idElem;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cementerio.historico_propiedad.fecha_operacion
     *
     * @return the value of cementerio.historico_propiedad.fecha_operacion
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    public Date getFechaOperacion() {
        return fechaOperacion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cementerio.historico_propiedad.fecha_operacion
     *
     * @param fechaOperacion the value for cementerio.historico_propiedad.fecha_operacion
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    public void setFechaOperacion(Date fechaOperacion) {
        this.fechaOperacion = fechaOperacion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cementerio.historico_propiedad.comentario
     *
     * @return the value of cementerio.historico_propiedad.comentario
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    public String getComentario() {
        return comentario;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cementerio.historico_propiedad.comentario
     *
     * @param comentario the value for cementerio.historico_propiedad.comentario
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
}