/**
 * Inhumacion.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

package com.geopista.app.cementerios.business.vo;

import java.util.Date;

public class Inhumacion {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.inhumacion.id
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.inhumacion.informe
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	private String informe;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.inhumacion.contenedor
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	private Integer contenedor;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.inhumacion.codigo
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	private String codigo;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.inhumacion.fecha_inhumacion
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	private Date fechaInhumacion;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.inhumacion.id_difunto
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	private Integer idDifunto;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.inhumacion.id_tarifa
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	private Integer idTarifa;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.inhumacion.tipo_inhumacion
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	private Integer tipoInhumacion;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.inhumacion.precio_final
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	private String precioFinal;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.inhumacion.bonificacion
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	private String bonificacion;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.inhumacion.id
	 * @return  the value of cementerio.inhumacion.id
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.inhumacion.id
	 * @param id  the value for cementerio.inhumacion.id
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.inhumacion.informe
	 * @return  the value of cementerio.inhumacion.informe
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	public String getInforme() {
		return informe;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.inhumacion.informe
	 * @param informe  the value for cementerio.inhumacion.informe
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	public void setInforme(String informe) {
		this.informe = informe;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.inhumacion.contenedor
	 * @return  the value of cementerio.inhumacion.contenedor
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	public Integer getContenedor() {
		return contenedor;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.inhumacion.contenedor
	 * @param contenedor  the value for cementerio.inhumacion.contenedor
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	public void setContenedor(Integer contenedor) {
		this.contenedor = contenedor;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.inhumacion.codigo
	 * @return  the value of cementerio.inhumacion.codigo
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	public String getCodigo() {
		return codigo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.inhumacion.codigo
	 * @param codigo  the value for cementerio.inhumacion.codigo
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.inhumacion.fecha_inhumacion
	 * @return  the value of cementerio.inhumacion.fecha_inhumacion
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	public Date getFechaInhumacion() {
		return fechaInhumacion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.inhumacion.fecha_inhumacion
	 * @param fechaInhumacion  the value for cementerio.inhumacion.fecha_inhumacion
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	public void setFechaInhumacion(Date fechaInhumacion) {
		this.fechaInhumacion = fechaInhumacion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.inhumacion.id_difunto
	 * @return  the value of cementerio.inhumacion.id_difunto
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	public Integer getIdDifunto() {
		return idDifunto;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.inhumacion.id_difunto
	 * @param idDifunto  the value for cementerio.inhumacion.id_difunto
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	public void setIdDifunto(Integer idDifunto) {
		this.idDifunto = idDifunto;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.inhumacion.id_tarifa
	 * @return  the value of cementerio.inhumacion.id_tarifa
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	public Integer getIdTarifa() {
		return idTarifa;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.inhumacion.id_tarifa
	 * @param idTarifa  the value for cementerio.inhumacion.id_tarifa
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	public void setIdTarifa(Integer idTarifa) {
		this.idTarifa = idTarifa;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.inhumacion.tipo_inhumacion
	 * @return  the value of cementerio.inhumacion.tipo_inhumacion
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	public Integer getTipoInhumacion() {
		return tipoInhumacion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.inhumacion.tipo_inhumacion
	 * @param tipoInhumacion  the value for cementerio.inhumacion.tipo_inhumacion
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	public void setTipoInhumacion(Integer tipoInhumacion) {
		this.tipoInhumacion = tipoInhumacion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.inhumacion.precio_final
	 * @return  the value of cementerio.inhumacion.precio_final
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	public String getPrecioFinal() {
		return precioFinal;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.inhumacion.precio_final
	 * @param precioFinal  the value for cementerio.inhumacion.precio_final
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	public void setPrecioFinal(String precioFinal) {
		this.precioFinal = precioFinal;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.inhumacion.bonificacion
	 * @return  the value of cementerio.inhumacion.bonificacion
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	public String getBonificacion() {
		return bonificacion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.inhumacion.bonificacion
	 * @param bonificacion  the value for cementerio.inhumacion.bonificacion
	 * @ibatorgenerated  Thu Jul 28 10:27:59 CEST 2011
	 */
	public void setBonificacion(String bonificacion) {
		this.bonificacion = bonificacion;
	}
}
