/**
 * Intervencion.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.geopista.app.cementerios.business.vo;

import java.util.Date;

public class Intervencion {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.intervencion.id
	 * @ibatorgenerated  Fri Jul 08 14:28:21 CEST 2011
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.intervencion.informe
	 * @ibatorgenerated  Fri Jul 08 14:28:21 CEST 2011
	 */
	private String informe;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.intervencion.fecha_fin
	 * @ibatorgenerated  Fri Jul 08 14:28:21 CEST 2011
	 */
	private Date fechaFin;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.intervencion.fecha_inicio
	 * @ibatorgenerated  Fri Jul 08 14:28:21 CEST 2011
	 */
	private Date fechaInicio;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.intervencion.localizacion
	 * @ibatorgenerated  Fri Jul 08 14:28:21 CEST 2011
	 */
	private String localizacion;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.intervencion.codigo
	 * @ibatorgenerated  Fri Jul 08 14:28:21 CEST 2011
	 */
	private String codigo;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.intervencion.estado
	 * @ibatorgenerated  Fri Jul 08 14:28:21 CEST 2011
	 */
	private String estado;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.intervencion.id
	 * @return  the value of cementerio.intervencion.id
	 * @ibatorgenerated  Fri Jul 08 14:28:21 CEST 2011
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.intervencion.id
	 * @param id  the value for cementerio.intervencion.id
	 * @ibatorgenerated  Fri Jul 08 14:28:21 CEST 2011
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.intervencion.informe
	 * @return  the value of cementerio.intervencion.informe
	 * @ibatorgenerated  Fri Jul 08 14:28:21 CEST 2011
	 */
	public String getInforme() {
		return informe;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.intervencion.informe
	 * @param informe  the value for cementerio.intervencion.informe
	 * @ibatorgenerated  Fri Jul 08 14:28:21 CEST 2011
	 */
	public void setInforme(String informe) {
		this.informe = informe;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.intervencion.fecha_fin
	 * @return  the value of cementerio.intervencion.fecha_fin
	 * @ibatorgenerated  Fri Jul 08 14:28:21 CEST 2011
	 */
	public Date getFechaFin() {
		return fechaFin;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.intervencion.fecha_fin
	 * @param fechaFin  the value for cementerio.intervencion.fecha_fin
	 * @ibatorgenerated  Fri Jul 08 14:28:21 CEST 2011
	 */
	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.intervencion.fecha_inicio
	 * @return  the value of cementerio.intervencion.fecha_inicio
	 * @ibatorgenerated  Fri Jul 08 14:28:21 CEST 2011
	 */
	public Date getFechaInicio() {
		return fechaInicio;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.intervencion.fecha_inicio
	 * @param fechaInicio  the value for cementerio.intervencion.fecha_inicio
	 * @ibatorgenerated  Fri Jul 08 14:28:21 CEST 2011
	 */
	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.intervencion.localizacion
	 * @return  the value of cementerio.intervencion.localizacion
	 * @ibatorgenerated  Fri Jul 08 14:28:21 CEST 2011
	 */
	public String getLocalizacion() {
		return localizacion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.intervencion.localizacion
	 * @param localizacion  the value for cementerio.intervencion.localizacion
	 * @ibatorgenerated  Fri Jul 08 14:28:21 CEST 2011
	 */
	public void setLocalizacion(String localizacion) {
		this.localizacion = localizacion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.intervencion.codigo
	 * @return  the value of cementerio.intervencion.codigo
	 * @ibatorgenerated  Fri Jul 08 14:28:21 CEST 2011
	 */
	public String getCodigo() {
		return codigo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.intervencion.codigo
	 * @param codigo  the value for cementerio.intervencion.codigo
	 * @ibatorgenerated  Fri Jul 08 14:28:21 CEST 2011
	 */
	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.intervencion.estado
	 * @return  the value of cementerio.intervencion.estado
	 * @ibatorgenerated  Fri Jul 08 14:28:21 CEST 2011
	 */
	public String getEstado() {
		return estado;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.intervencion.estado
	 * @param estado  the value for cementerio.intervencion.estado
	 * @ibatorgenerated  Fri Jul 08 14:28:21 CEST 2011
	 */
	public void setEstado(String estado) {
		this.estado = estado;
	}


}