/**
 * RelTitularKey.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.geopista.app.cementerios.business.vo;

public class RelTitularKey {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.reltitular.dni_persona
	 * @ibatorgenerated  Tue May 03 16:38:46 CEST 2011
	 */
	private String dniPersona;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.reltitular.id_concesion
	 * @ibatorgenerated  Tue May 03 16:38:46 CEST 2011
	 */
	private Integer idConcesion;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.reltitular.dni_persona
	 * @return  the value of cementerio.reltitular.dni_persona
	 * @ibatorgenerated  Tue May 03 16:38:46 CEST 2011
	 */
	public String getDniPersona() {
		return dniPersona;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.reltitular.dni_persona
	 * @param dniPersona  the value for cementerio.reltitular.dni_persona
	 * @ibatorgenerated  Tue May 03 16:38:46 CEST 2011
	 */
	public void setDniPersona(String dniPersona) {
		this.dniPersona = dniPersona;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.reltitular.id_concesion
	 * @return  the value of cementerio.reltitular.id_concesion
	 * @ibatorgenerated  Tue May 03 16:38:46 CEST 2011
	 */
	public Integer getIdConcesion() {
		return idConcesion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.reltitular.id_concesion
	 * @param idConcesion  the value for cementerio.reltitular.id_concesion
	 * @ibatorgenerated  Tue May 03 16:38:46 CEST 2011
	 */
	public void setIdConcesion(Integer idConcesion) {
		this.idConcesion = idConcesion;
	}
}