/**
 * RelTitular.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.geopista.app.cementerios.business.vo;

public class RelTitular extends RelTitularKey {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.reltitular.esprincipal
	 * @ibatorgenerated  Tue May 03 16:38:46 CEST 2011
	 */
	private Boolean esprincipal;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.reltitular.esprincipal
	 * @return  the value of cementerio.reltitular.esprincipal
	 * @ibatorgenerated  Tue May 03 16:38:46 CEST 2011
	 */
	public Boolean getEsprincipal() {
		return esprincipal;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.reltitular.esprincipal
	 * @param esprincipal  the value for cementerio.reltitular.esprincipal
	 * @ibatorgenerated  Tue May 03 16:38:46 CEST 2011
	 */
	public void setEsprincipal(Boolean esprincipal) {
		this.esprincipal = esprincipal;
	}
}