/**
 * JFrameInformesArbolado.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.geopista.app.contaminantes;
import java.awt.Cursor;
import java.awt.Dimension;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.sql.Driver;
import java.sql.DriverManager;
import java.util.HashMap;
import java.util.Map;
import java.util.ResourceBundle;
import java.util.Vector;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableColumn;

import org.apache.log4j.Logger;

import com.geopista.app.AppContext;
import com.geopista.app.reports.GenerarInformeExterno;
import com.geopista.app.utilidades.TableSorted;
import com.geopista.protocol.contaminantes.Arbolado;
import com.geopista.protocol.contaminantes.CConstantes;
import com.geopista.protocol.contaminantes.OperacionesContaminantes;


/**
 *
 * @author  charo
 */
public class JFrameInformesArbolado extends javax.swing.JInternalFrame{

	Logger logger = Logger.getLogger(JFrameInformesArbolado.class);
	private ResourceBundle messages;
	private JFrame frame;
	ArboladoTableModel modelArbolado;
	Vector _vArbolado= null;
	private TableSorted sorter;

	private static AppContext aplicacion = (AppContext) AppContext.getApplicationContext();
	/*
	 * Almacenamos el listado con el num_expediente que utilizaremos en el ireport:
	 * */
	private String lista_expedientes = "";

	/** Creates new form JFrameInformes */
	public JFrameInformesArbolado(ResourceBundle messages, JFrame frame) {
		this.frame=frame;
		this.messages = messages;
		initComponents();
		initComboBoxesEstructuras();

		String[] columnNames = {messages.getString("jMenuItemArboladoInformes.jTableListado.column1"),
				messages.getString("jMenuItemArboladoInformes.jTableListado.column2"),
				messages.getString("jMenuItemArboladoInformes.jTableListado.column3")};

		ArboladoTableModel.setColumnNames(columnNames);
		modelArbolado= new ArboladoTableModel();
		jTableListado.setModel(modelArbolado);
		cargarArbolado();
		UtilsContaminantes.cargarPlantillas(CConstantes.PLANTILLAS_PATH_ARBOLADO, plantillaJCBox);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents() {//GEN-BEGIN:initComponents
		jPanelPrincipal = new javax.swing.JPanel();
		jPanelTotal = new javax.swing.JPanel();
		//jPanelBotonera = new javax.swing.JPanel();
		jButtonGenerarInformes= new javax.swing.JButton();
		jButtonSalir = new javax.swing.JButton();
		jTabbedPaneDatos = new javax.swing.JTabbedPane();
		jPanelDatos = new javax.swing.JPanel();
		jPanelListado = new javax.swing.JPanel();
		jScrollPaneListado = new javax.swing.JScrollPane();
		jTableListado = new javax.swing.JTable();
		/*
        nombreInformeJLabel= new javax.swing.JLabel();
        nombreInformeJTField= new javax.swing.JTextField();
		 */
		plantillaJCBox = new javax.swing.JComboBox();
		plantillaJLabel= new javax.swing.JLabel();
		//        formatoJLabel= new javax.swing.JLabel();
		//formatoSalidaEJCBox= new ComboBoxEstructuras(Estructuras.getListaFormatosSalida(), null, com.geopista.app.contaminantes.init.Constantes.Locale, false);


		jPanelPrincipal.setLayout(new java.awt.BorderLayout());
		/*
        jPanelBotonera.add(jButtonGenerarInformes);
        jButtonGenerarInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarInforme();
            }
        });
		 */

		jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				salir();
			}
		});
		jPanelTotal.add(jButtonSalir);
		//jPanelPrincipal.add(jPanelBotonera, java.awt.BorderLayout.SOUTH);
		jTabbedPaneDatos.setBorder(new javax.swing.border.EtchedBorder());
		jPanelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		/*
        nombreInformeJLabel.setText(messages.getString("jMenuItemArboladoInformes.nombreInformeJLabel"));
        jPanelDatos.add(nombreInformeJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
        jPanelDatos.add(nombreInformeJTField, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 30, 290, -1));
		 */
		jPanelDatos.add(jButtonGenerarInformes, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));
		jButtonGenerarInformes.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				generarInforme();
			}
		});

		plantillaJLabel.setText(messages.getString("jMenuItemArboladoInformes.plantillaJLabel"));
		jPanelDatos.add(plantillaJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
		jPanelDatos.add(plantillaJCBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 30, 290, -1));

		//        formatoJLabel.setText(messages.getString("jMenuItemArboladoInformes.formatoJLabel"));
		//        jPanelDatos.add(formatoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
		//jPanelDatos.add(formatoSalidaEJCBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 290, -1));

		jPanelListado.setLayout(new java.awt.BorderLayout());
		jScrollPaneListado.setViewportView(jTableListado);
		jPanelListado.add(jScrollPaneListado, java.awt.BorderLayout.CENTER);
		JPanel auxPanel= new JPanel();
		auxPanel.setLayout(new java.awt.BorderLayout());
		auxPanel.add(jPanelDatos,java.awt.BorderLayout.SOUTH);
		auxPanel.add(jPanelListado,java.awt.BorderLayout.CENTER);
		jTabbedPaneDatos.addTab(messages.getString("jMenuItemArboladoInformes.jTabbedPaneDatos"), auxPanel);
		jPanelPrincipal.add(jTabbedPaneDatos, java.awt.BorderLayout.CENTER);
		changeScreenLang(messages);
		jPanelPrincipal.setMinimumSize(new Dimension(600,600));

		//getContentPane().add(jPanelPrincipal, java.awt.BorderLayout.WEST);
		getContentPane().add(jPanelPrincipal, java.awt.BorderLayout.CENTER);
		getContentPane().add(jPanelTotal, java.awt.BorderLayout.SOUTH);

		pack();
	}//GEN-END:initComponents


	private void cargarArbolado(){

		try{
			_vArbolado= (new OperacionesContaminantes(com.geopista.app.contaminantes.Constantes.url)).getArbolados();
			if (_vArbolado == null){
				logger.warn("No existen zonas arboladas en el sistema");
				UtilsContaminantes.mostrarMensaje(jPanelDatos, messages.getString("jMenuItemArboladoInformes.mensaje1"), messages.getString("jMenuItemArboladoInformes.mensajeTittle1"));
				jButtonGenerarInformes.setEnabled(false);
			}else{
				lista_expedientes = "";
				for (int i = 0; i < _vArbolado.size(); i++) {
					Arbolado arbolado = (Arbolado) _vArbolado.elementAt(i);
					lista_expedientes += "'"+arbolado.getId()+"'";
					if (i < _vArbolado.size()-1){
						lista_expedientes += ", ";
					}
				}     
				actualizarModelo();
			}

		}catch(Exception e){
			StringWriter sw = new StringWriter();
			PrintWriter pw = new PrintWriter(sw);
			e.printStackTrace(pw);
			logger.error("Exception: " + sw.toString());
		}
	}


	private void salir(){
		/** volvemos a registrar el driver GEOPISTADriver */
		String classForName= "com.geopista.sql.GEOPISTADriver";
		try{
			Driver dPista= (Driver)Class.forName(classForName).newInstance();
			DriverManager.registerDriver(dPista);
		}catch(Exception e){
			logger.debug(".................Class.forNmae " + classForName + " " + e.getMessage());
		}

		dispose();
	}

	public void changeScreenLang(ResourceBundle messages){
		try
		{
			this.messages=messages;
			setTitle(messages.getString("jMenuItemArboladoInformes.tittle"));
			jButtonGenerarInformes.setText(messages.getString("jMenuItemArboladoInformes.jButtonGenerarInformes"));
			jButtonSalir.setText(messages.getString("jMenuItemArboladoInformes.jButtonSalir"));

			jButtonGenerarInformes.setToolTipText(messages.getString("jMenuItemArboladoInformes.jButtonGenerarInformes"));
			jButtonSalir.setToolTipText(messages.getString("jMenuItemArboladoInformes.jButtonSalir"));

			plantillaJLabel.setText(messages.getString("jMenuItemArboladoInformes.plantillaJLabel"));
			//             formatoJLabel.setText(messages.getString("jMenuItemArboladoInformes.formatoJLabel"));

			/** Headers de la tabla eventos */
			TableColumn tableColumn= jTableListado.getColumnModel().getColumn(0);
			tableColumn.setHeaderValue(messages.getString("jMenuItemArboladoInformes.jTableListado.column1"));
			tableColumn= jTableListado.getColumnModel().getColumn(1);
			tableColumn.setHeaderValue(messages.getString("jMenuItemArboladoInformes.jTableListado.column2"));
			tableColumn= jTableListado.getColumnModel().getColumn(2);
			tableColumn.setHeaderValue(messages.getString("jMenuItemArboladoInformes.jTableListado.column3"));

			jTabbedPaneDatos.setTitleAt(0, messages.getString("jMenuItemArboladoInformes.jTabbedPaneDatos"));
		}catch(Exception e)
		{}
	}

	private void actualizarModelo(){
		modelArbolado.setModelData(_vArbolado);
		sorter = new TableSorted(modelArbolado);
		sorter.setTableHeader(jTableListado.getTableHeader());
		jTableListado.setModel(sorter);
		jTableListado.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
	}


	
	private void generarInforme() {
		this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
		try {
			if ((_vArbolado != null) && (_vArbolado.size() > 0) )
			{
				String report = ((String)plantillaJCBox.getSelectedItem());
				if (report != null && !report.equals("")){    
					Map parametros = obtenerParametros();
					String reportFile = UtilsContaminantes.getLocalPathPlantillas() + report;
					GenerarInformeExterno giep=new GenerarInformeExterno(reportFile, parametros);
				}
			}
			else
				UtilsContaminantes.mostrarMensaje(jPanelDatos, messages.getString("jMenuItemArboladoInformes.mensaje4"), messages.getString("jMenuItemArboladoInformes.mensajeTittle1"));
		}catch(Exception e){
			this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
			UtilsContaminantes.mostrarMensaje(jPanelDatos, messages.getString("jMenuItemArboladoInformes.mensaje2"), messages.getString("jMenuItemArboladoInformes.mensajeTittle1"));
			StringWriter sw = new StringWriter();
			PrintWriter pw = new PrintWriter(sw);
			e.printStackTrace(pw);
			logger.error("Exception: " + sw.toString());
		}
		this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
	}

	public void initComboBoxesEstructuras(){
		while (!Estructuras.isCargada())
		{
			if (!Estructuras.isIniciada()) Estructuras.cargarEstructuras();
			try {Thread.sleep(500);}catch(Exception e){}
		}

		//        formatoSalidaEJCBox= new ComboBoxEstructuras(Estructuras.getListaFormatosSalida(), null, com.geopista.app.contaminantes.init.Constantes.Locale, false);
		//        jPanelDatos.add(formatoSalidaEJCBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 50, 290, -1));

	}


	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonGenerarInformes;
	private javax.swing.JButton jButtonSalir;
	private javax.swing.JLabel plantillaJLabel;
	private javax.swing.JComboBox plantillaJCBox;
	//    private javax.swing.JLabel formatoJLabel;
	//    private ComboBoxEstructuras formatoSalidaEJCBox ;
	/*
    private javax.swing.JLabel nombreInformeJLabel;
    private javax.swing.JTextField nombreInformeJTField;
	 */

	//private javax.swing.JPanel jPanelBotonera;
	private javax.swing.JPanel jPanelDatos;
	private javax.swing.JPanel jPanelListado;
	private javax.swing.JPanel jPanelPrincipal;
	private javax.swing.JPanel jPanelTotal;
	private javax.swing.JScrollPane jScrollPaneListado;
	private javax.swing.JTabbedPane jTabbedPaneDatos;
	private javax.swing.JTable jTableListado;
	// End of variables declaration//GEN-END:variables

	private Map obtenerParametros(){

		Map parametros = new HashMap();
		parametros.put("lista_expedientes", lista_expedientes);
		parametros.put("locale", aplicacion.getI18NResource().getLocale().toString());
		parametros.put("id_municipio", aplicacion.getIdMunicipio());
		return parametros;
	}

}
