/**
 * GeopistaEditorDatos.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.geopista.app.catastro;
import java.awt.Dimension;
import java.awt.Rectangle;

import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;

public class GeopistaEditorDatos extends JPanel 
{
  private JTabbedPane jTabbedPane1 = new JTabbedPane();
  private JPanel parcelapanel = new JPanel();
  private JPanel jPanel1 = new JPanel();
  private JLabel entmenorprlbl = new JLabel();
  private JTextField txtentmenorpar = new JTextField();
  private JTextField txtcodviapar = new JTextField();
  private JLabel entmenorprlbl1 = new JLabel();
  private JTextField txttipovia = new JTextField();
  private JLabel tipoviaparlbl = new JLabel();
  private JTextField txtnombreviapar = new JTextField();
  private JLabel nombreviaparlbl = new JLabel();
  private JTextField txtcodigopostalpar = new JTextField();
  private JLabel codigopostalparlbl = new JLabel();
  private JTextField txtnumero1par = new JTextField();
  private JLabel numero1parlbl = new JLabel();
  private JTextField txtletra1par = new JTextField();
  private JLabel letra1parlbl = new JLabel();
  private JTextField txtletra2par = new JTextField();
  private JTextField txtnumero2par = new JTextField();
  private JLabel numero2parlbl = new JLabel();
  private JLabel letra2parlbl = new JLabel();
  private JLabel dirnoestrucparlbl = new JLabel();
  private JTextField txtkilometropar = new JTextField();
  private JTextField txtbloquepar = new JTextField();
  private JLabel bloqueparlbl = new JLabel();
  private JLabel kmparlbl = new JLabel();
  private JTextField txtdirnoestrucpar = new JTextField();
  private JPanel jPanel2 = new JPanel();
  private JLabel numero2parlbl1 = new JLabel();
  private JLabel formacalculoparlbl = new JLabel();
  private JTextField txtformacalculopar = new JTextField();
  private JLabel aprobacionparlbl = new JLabel();
  private JTextField txtaprobacionpar = new JTextField();
  private JLabel codigopostalparlbl1 = new JLabel();
  private JTextField txtsupBRpar = new JTextField();
  private JLabel supSRparlbl = new JLabel();
  private JTextField txtsupSRpar = new JTextField();
  private JLabel supcubiertaparlbl = new JLabel();
  private JTextField txtsupcubiertapar = new JTextField();
  private JLabel supconsparlbl = new JLabel();
  private JTextField txtsuptotalcos = new JTextField();
  private JTextField txtsupsolar = new JTextField();
  private JLabel supsolarlbl = new JLabel();
  private JComboBox cmbmodrepartopar = new JComboBox();
  private JPanel jPanel3 = new JPanel();
  private JLabel alterparlbl = new JLabel();
  private JTextField txtinfocarpar = new JTextField();
  private JLabel infocarparlbl = new JLabel();
  private JTextField txtalterpar = new JTextField();
  private JPanel jPanel4 = new JPanel();
  private JLabel supcubiertaparlbl1 = new JLabel();
  private JTextField txtrefexp = new JTextField();
  private JLabel annoexpparlbl = new JLabel();
  private JTextField txtannoexppar = new JTextField();
  private JButton btnaceptar = new JButton();
  private JButton btncancelar = new JButton();
  private JPanel subparcelapanel = new JPanel();
  private JPanel jPanel9 = new JPanel();
  private JLabel supcubiertaparlbl4 = new JLabel();
  private JTextField txtrefexpsubpar = new JTextField();
  private JLabel annoexpparlbl2 = new JLabel();
  private JTextField txtannoexpsubpar = new JTextField();
  private JPanel jPanel10 = new JPanel();
  private JLabel fondosubparlbl = new JLabel();
  private JTextField txtfondosubpar = new JTextField();
  private JLabel superficiesubparlbl = new JLabel();
  private JTextField txtsuperficiesubpar = new JTextField();
  private JLabel tipofachadasubparlbl = new JLabel();
  private JTextField txtlongfachadasubpar = new JTextField();
  private JLabel longfachadasubparlbl = new JLabel();
  private JPanel jPanel11 = new JPanel();
  private JLabel ordensubparlbl = new JLabel();
  private JTextField txtordensubpar = new JTextField();
  private JPanel jPanel12 = new JPanel();
  private JLabel coef1lbl = new JLabel();
  String[] data = {"0001", "0002", "0003"};
  private JList lstsubparcela = new JList(data);
  private JComboBox cmbtipofachadasubpar = new JComboBox();
  private JTextField txttramoviasubpar = new JTextField();
  private JLabel tipoviaparlbl1 = new JLabel();
  private JTextField txtcodviasubpar = new JTextField();
  private JLabel entmenorprlbl2 = new JLabel();
  private JComboBox cmbtipovalorsubpar = new JComboBox();
  private JLabel tipovalorsubparlbl = new JLabel();
  private JCheckBox chknumfachadasubpar = new JCheckBox();
  private JCheckBox chklongfachadasubpar = new JCheckBox();
  private JCheckBox chkirregularsubpar = new JCheckBox();
  private JCheckBox chkdesmontesubpar = new JCheckBox();
  private JCheckBox chkprofundidadsubpar = new JCheckBox();
  private JCheckBox chkvposubpar = new JCheckBox();
  private JCheckBox chkinedificabilidadsubpar = new JCheckBox();
  private JCheckBox chksuperficiesubpar = new JCheckBox();
  private JCheckBox chkfondosubpar = new JCheckBox();
  private JCheckBox chknolucrativosubpar = new JCheckBox();
  private JCheckBox chkdepreciacionsubpar = new JCheckBox();
  private JCheckBox chkespecialsubpar = new JCheckBox();
  private JCheckBox chkcargassubpar = new JCheckBox();
  private JLabel coef1lbl1 = new JLabel();
  private JLabel apreciacionlbl = new JLabel();
  private JTextField txtapreciacionsubpar = new JTextField();
  private JLabel coef1lbl2 = new JLabel();
  private JComboBox cmbpavimentacionsubpar = new JComboBox();
  private JLabel pavimentacionsubparlbl = new JLabel();
  private JComboBox cmbalcantarilladosubpar = new JComboBox();
  private JLabel alcantarilladosubparlb = new JLabel();
  private JComboBox cmbdesmontesubpar = new JComboBox();
  private JLabel desmontesubparlb = new JLabel();
  private JComboBox cmbalumbradosubpar = new JComboBox();
  private JLabel alumbradosubparlb = new JLabel();
  private JComboBox cmbelectricidadsubpar = new JComboBox();
  private JLabel Electricidadsubparlb = new JLabel();
  private JComboBox cmbaguasubpar = new JComboBox();
  private JLabel aguasubparlb5 = new JLabel();
  private JPanel unidadconstructivapanel = new JPanel();
  private JPanel jPanel15 = new JPanel();
  private JList lstuc = new JList(data);
  private JLabel ordenuclbl = new JLabel();
  private JTextField txtordenuc = new JTextField();
  private JPanel jPanel16 = new JPanel();
  private JLabel alumbradosubparlb1 = new JLabel();
  private JComboBox cmbalumbradouc = new JComboBox();
  private JLabel desmontesubparlb1 = new JLabel();
  private JComboBox cmbdesmonteuc = new JComboBox();
  private JLabel alcantarilladosubparlb1 = new JLabel();
  private JComboBox cmbalcantarilladouc = new JComboBox();
  private JLabel pavimentacionsubparlbl1 = new JLabel();
  private JComboBox cmbpavimentacionuc = new JComboBox();
  private JTextField txtapreciacionuc = new JTextField();
  private JLabel apreciacionlbl1 = new JLabel();
  private JCheckBox chkcargasuc = new JCheckBox();
  private JCheckBox chkespecialuc = new JCheckBox();
  private JCheckBox chknolucrativouc = new JCheckBox();
  private JCheckBox chkconservacionuc = new JCheckBox();
  private JCheckBox chklongfachadauc = new JCheckBox();
  private JCheckBox chknumfachadauc = new JCheckBox();
  private JLabel entmenorprlbl3 = new JLabel();
  private JTextField txtcodviaDGCuc = new JTextField();
  private JLabel tipoviaparlbl2 = new JLabel();
  private JTextField txttramoviauc = new JTextField();
  private JLabel coef1lbl5 = new JLabel();
  private JComboBox cmbelectricidaduc = new JComboBox();
  private JLabel Electricidadsubparlb1 = new JLabel();
  private JComboBox cmbaguauc = new JComboBox();
  private JLabel aguasubparlb6 = new JLabel();
  private JPanel jPanel5 = new JPanel();
  private JTextField txtdirnoestrucuc = new JTextField();
  private JLabel kmparlbl1 = new JLabel();
  private JLabel bloqueparlbl1 = new JLabel();
  private JTextField txtbloqueuc = new JTextField();
  private JTextField txtkilometrouc = new JTextField();
  private JLabel dirnoestrucparlbl1 = new JLabel();
  private JLabel letra2parlbl1 = new JLabel();
  private JLabel numero2parlbl2 = new JLabel();
  private JTextField txtnumero2uc = new JTextField();
  private JTextField txtletra2uc = new JTextField();
  private JLabel letra1parlbl1 = new JLabel();
  private JTextField txtletra1uc = new JTextField();
  private JLabel numero1parlbl1 = new JLabel();
  private JTextField txtnumero1uc = new JTextField();
  private JLabel codigopostaluclbl = new JLabel();
  private JTextField txtcodigopostaluc = new JTextField();
  private JLabel nombreviauclbl = new JLabel();
  private JTextField txtnombreviauc = new JTextField();
  private JLabel tipoviauclbl = new JLabel();
  private JTextField txttipoviauc = new JTextField();
  private JLabel viapublicauclbl = new JLabel();
  private JTextField txtcodviauc = new JTextField();
  private JTextField txtentmenoruc = new JTextField();
  private JLabel entmenoruclbl = new JLabel();
  private JPanel jPanel14 = new JPanel();
  private JComboBox cmbusoagrariouc = new JComboBox();
  private JLabel annoconstuclbl = new JLabel();
  private JTextField txtannoconsuc = new JTextField();
  private JLabel usoagrariouclbl = new JLabel();
  private JTextField txtlongfachadauc = new JTextField();
  private JLabel longfachadasubparlbl1 = new JLabel();
  private JLabel exactannouclbl = new JLabel();
  private JComboBox cmbexactitudannouc = new JComboBox();
  private JPanel jPanel13 = new JPanel();
  private JLabel supcubiertaparlbl5 = new JLabel();
  private JTextField txtrefexpuc = new JTextField();
  private JLabel annoexpparlbl3 = new JLabel();
  private JTextField txtannoexpuc = new JTextField();
  private JPanel construccionespanel = new JPanel();
  private JPanel jPanel7 = new JPanel();
  private JLabel supcubiertaparlbl3 = new JLabel();
  private JTextField txtsupimputablecons = new JTextField();
  private JLabel supconsparlbl1 = new JLabel();
  private JTextField txtsupterrazascons = new JTextField();
  private JTextField txtsuptotalcon = new JTextField();
  private JLabel supsolarlbl1 = new JLabel();
  private JPanel jPanel8 = new JPanel();
  private JLabel escaleralbl = new JLabel();
  private JLabel bloqueparlbl2 = new JLabel();
  private JTextField txtbloquecons = new JTextField();
  private JTextField txtescaleracons = new JTextField();
  private JLabel plantaconslbl = new JLabel();
  private JTextField txtplantacons = new JTextField();
  private JLabel puertaconslbl = new JLabel();
  private JTextField txtpuertacons = new JTextField();
  private JPanel jPanel18 = new JPanel();
  private JList lstcons = new JList(data);
  private JLabel ordenconslbl = new JLabel();
  private JTextField txtordencons = new JTextField();
  private JComboBox cmbreformacons = new JComboBox();
  private JLabel reformaconslbl = new JLabel();
  private JTextField txtannoreforma = new JTextField();
  private JLabel annoreformalbl = new JLabel();
  private JTextField txtdestinocons = new JTextField();
  private JLabel destinoconslbl = new JLabel();
  private JCheckBox chklocalcons = new JCheckBox();
  private JPanel jPanel17 = new JPanel();
  private JTextField txtapreciacioncons = new JTextField();
  private JLabel apreciacionconslbl = new JLabel();
  private JLabel coef1lbl4 = new JLabel();
  private JCheckBox chkviviendacons = new JCheckBox();
  private JComboBox cmbusocons = new JComboBox();
  private JLabel TIPOLOGIACONSLBL = new JLabel();
  private JTextField txttipologiacons = new JTextField();
  private JLabel tipoviaparlbl3 = new JLabel();
  private JTextField txtcategoriacons = new JTextField();
  private JLabel categoriaconslbl = new JLabel();
  private JComboBox cmbreparto1cons = new JComboBox();
  private JLabel tipoviaparlbl4 = new JLabel();
  private JComboBox cmbreparto2cons = new JComboBox();
  private JComboBox cmbreparto3cons = new JComboBox();
  private JComboBox cmbtipovalorcons = new JComboBox();
  private JLabel tipovalorconslbl = new JLabel();
  private JPanel jPanel19 = new JPanel();
  private JLabel referenciaconslbl = new JLabel();
  private JTextField txtreferenciacons = new JTextField();
  private JLabel annoexpconslbl = new JLabel();
  private JTextField txtannoexpcons = new JTextField();
  private JTextField txtcargocons = new JTextField();
  private JLabel cargoconslbl = new JLabel();
  private JTextField txtuccons = new JTextField();
  private JLabel ucconslbl = new JLabel();
  private JPanel cargopanel = new JPanel();
  private JPanel jPanel110 = new JPanel();
  private JLabel supcubiertaparlbl6 = new JLabel();
  private JTextField txtrefexpcargo = new JTextField();
  private JLabel annoexpparlbl4 = new JLabel();
  private JTextField txtannoexpcargo = new JTextField();
  private JPanel jPanel6 = new JPanel();
  private JTextField txtdirnoestruccargo = new JTextField();
  private JLabel kmparlbl2 = new JLabel();
  private JLabel bloqueparlbl3 = new JLabel();
  private JTextField txtbloquecargo = new JTextField();
  private JTextField txtkilometrocargo = new JTextField();
  private JLabel dirnoestrucparlbl2 = new JLabel();
  private JLabel letra2parlbl2 = new JLabel();
  private JLabel numero2parlbl3 = new JLabel();
  private JTextField txtnumero2cargo = new JTextField();
  private JTextField txtletra2cargo = new JTextField();
  private JLabel letra1parlbl2 = new JLabel();
  private JTextField txtletra1cargo = new JTextField();
  private JLabel numero1cargolbl = new JLabel();
  private JTextField txtnumero1cargo = new JTextField();
  private JLabel codigopostalcargolbl = new JLabel();
  private JTextField txtcodigopostalcargo = new JTextField();
  private JLabel nombreviacargolbl = new JLabel();
  private JTextField txtnombreviacargo = new JTextField();
  private JLabel tipoviacargolbl = new JLabel();
  private JTextField txttipoviacargo = new JTextField();
  private JLabel viapublicacargolbl = new JLabel();
  private JTextField txtcodviacargo = new JTextField();
  private JTextField txtentmenorcargo = new JTextField();
  private JLabel entmenorcargolbl = new JLabel();
  private JPanel jPanel112 = new JPanel();
  private JLabel participacioncargolbl = new JLabel();
  private JTextField txtparticipacioncargo = new JTextField();
  private JLabel fijocargolbl = new JLabel();
  private JTextField txtfijocargo = new JTextField();
  private JList lstcargo = new JList(data);
  private JLabel cargocargolbl = new JLabel();
  private JTextField txcargo = new JTextField();
  private JTextField control1cargotxt = new JTextField();
  private JLabel controlcargolbl = new JLabel();
  private JTextField txtcontrol2cargo = new JTextField();
  private JTextField txtcontrolfijocargo = new JTextField();
  private JLabel controlfijocargolbl = new JLabel();
  private JTextField txtdistritocargo = new JTextField();
  private JLabel distritocargolbl = new JLabel();
  private JTextField txtpuertacargo = new JTextField();
  private JLabel puertaconslbl1 = new JLabel();
  private JTextField txtplantacargo = new JTextField();
  private JLabel plantaconslbl1 = new JLabel();
  private JTextField txtescaleracargo = new JTextField();
  private JLabel escaleralbl1 = new JLabel();
  private JPanel jPanel20 = new JPanel();
  private JLabel numero2parlbl4 = new JLabel();
  private JLabel formacalculoparlbl1 = new JLabel();
  private JTextField txtannonotificacion = new JTextField();
  private JLabel aprobacionparlbl1 = new JLabel();
  private JTextField txtannorevision = new JTextField();
  private JLabel supconsparlbl2 = new JLabel();
  private JTextField txtvalorcatastralcargo = new JTextField();
  private JTextField txtannovalorcargo = new JTextField();
  private JLabel supsolarlbl2 = new JLabel();
  private JTextField txtvalorsuelocargo = new JTextField();
  private JLabel supconsparlbl3 = new JLabel();
  private JTextField txtbaseliquidablecargo = new JTextField();
  private JLabel supconsparlbl4 = new JLabel();
  private JTextField txtvalorconstruccioncargo = new JTextField();
  private JLabel valorconstruccioncargolbl = new JLabel();
  private JTextField txtclaveusocargo = new JTextField();
  private JLabel tipoviacargolbl1 = new JLabel();
  private JTextField txtnotificacioncargo = new JTextField();
  private JTextField txtcoeficientepropcargo = new JTextField();
  private JLabel supcubiertaparlbl7 = new JLabel();
  private JTextField txtsupsuelocargo = new JTextField();
  private JLabel supconsparlbl5 = new JLabel();
  private JTextField txtsupconstruccioncargo = new JTextField();
  private JLabel supsolarlbl3 = new JLabel();
  private JTextField txtannofinvalorcargo = new JTextField();
  private JLabel supsolarlbl4 = new JLabel();
  private JCheckBox chkpreciocargo = new JCheckBox();
  private JLabel supcubiertaparlbl8 = new JLabel();
  private JComboBox cmbtipopropiedadcargo = new JComboBox();
  private JPanel cargopanel1 = new JPanel();
  private JPanel jPanel113 = new JPanel();
  private JTextField txtcontrol2titular = new JTextField();
  private JLabel controlcargolbl1 = new JLabel();
  private JTextField txtcontrol1itular = new JTextField();
  private JList lsttitular = new JList(data);
  private JLabel cargocargolbl1 = new JLabel();
  private JTextField txtcargotitular = new JTextField();
  private JPanel jPanel22 = new JPanel();
  private JLabel escaleralbl2 = new JLabel();
  private JTextField txtescaleratitular = new JTextField();
  private JLabel plantaconslbl2 = new JLabel();
  private JTextField txtplantatitular = new JTextField();
  private JLabel puertaconslbl2 = new JLabel();
  private JTextField txtpuertatitular = new JTextField();
  private JTextField txtdirnoestructitular = new JTextField();
  private JLabel kmparlbl3 = new JLabel();
  private JLabel bloqueparlbl4 = new JLabel();
  private JTextField txtbloquetitular = new JTextField();
  private JTextField txtkilometrotitular = new JTextField();
  private JLabel dirnoestrucparlbl3 = new JLabel();
  private JLabel letra2parlbl3 = new JLabel();
  private JLabel numero2parlbl6 = new JLabel();
  private JTextField txtnumero2titular = new JTextField();
  private JTextField txtletra2titular = new JTextField();
  private JLabel letra1parlbl3 = new JLabel();
  private JTextField txtletra1titular = new JTextField();
  private JLabel numero1cargolbl1 = new JLabel();
  private JTextField txtnumero1titular = new JTextField();
  private JLabel codigopostalcargolbl1 = new JLabel();
  private JTextField txtcodigopostaltitular = new JTextField();
  private JLabel nombreviacargolbl1 = new JLabel();
  private JTextField txtnombreviatitular = new JTextField();
  private JLabel tipoviacargolbl3 = new JLabel();
  private JTextField txttipoviatitular = new JTextField();
  private JLabel viapublicacargolbl1 = new JLabel();
  private JTextField txtcodviatitular = new JTextField();
  private JTextField txtmunicipiotitular = new JTextField();
  private JLabel entmenorcargolbl1 = new JLabel();
  private JPanel jPanel111 = new JPanel();
  private JComboBox cmbpersonalidadtitular = new JComboBox();
  private JLabel fondosubparlbl1 = new JLabel();
  private JTextField txtcomplementotitular = new JTextField();
  private JLabel superficiesubparlbl1 = new JLabel();
  private JTextField txtnombretitular = new JTextField();
  private JLabel personalidadtitularlbl = new JLabel();
  private JTextField txtniftitular = new JTextField();
  private JLabel niftitularlbl = new JLabel();
  private JTextField txtcontrolniftitular = new JTextField();
  private JTextField txttitularcomponentes = new JTextField();
  private JLabel tipoviacargolbl4 = new JLabel();
  private JTextField txtprovinciainetitular = new JTextField();
  private JLabel tipoviacargolbl5 = new JLabel();
  private JTextField txtmunicipiodgctitular = new JTextField();
  private JLabel viapublicacargolbl2 = new JLabel();
  private JTextField txtdelegaciontitular = new JTextField();
  private JLabel entmenorcargolbl2 = new JLabel();
  private JTextField txtapartadocorreostitular = new JTextField();
  private JLabel apartadocorreostitularlbl = new JLabel();
  private JTextField txtpaistitular = new JTextField();
  private JLabel nombrepaistitulartxt = new JLabel();
  private JTextField txtnombreprovinciatitular = new JTextField();
  private JLabel nombrepaistitulartxt1 = new JLabel();
  private JTextField txtnombremunicipiotitular = new JTextField();
  private JLabel nombrepaistitulartxt2 = new JLabel();
  private JTextField txtrefpar = new JTextField();
  private JLabel referencialbl = new JLabel();
  private JTextField txtrefpla = new JTextField();
  private JTextField txtmunicipio = new JTextField();
  private JLabel municipiolbl = new JLabel();
  private JButton btneditsubpar = new JButton();
  Icon Add = new ImageIcon("E:/Trabajos/SIT FEMP/Interfaces/temp/icos/add.jpg");
  Icon Edit = new ImageIcon("E:/Trabajos/SIT FEMP/Interfaces/temp/icos/edit.jpg");
  Icon Del = new ImageIcon("E:/Trabajos/SIT FEMP/Interfaces/temp/icos/del.jpg");
  private JButton btnaddsubpar = new JButton();
  private JButton btndelsubpar = new JButton();
  private JButton btndeluc = new JButton();
  private JButton btnedituc = new JButton();
  private JButton btnadduc = new JButton();
  private JButton btndelcons = new JButton();
  private JButton btneditcons = new JButton();
  private JButton btnaddcons = new JButton();
  private JButton btndelcargo = new JButton();
  private JButton btneditcargo = new JButton();
  private JButton btnaddcargo = new JButton();
  public GeopistaEditorDatos()
  {
    try
    {
      jbInit();
    }
    catch(Exception e)
    {
      e.printStackTrace();
    }

  }

 public static void main(String[] args)
  {
    JFrame frame1 = new JFrame("Edición Datos");
    
    GeopistaEditorDatos geopistaEditarDatos = new GeopistaEditorDatos();

    frame1.getContentPane().add(geopistaEditarDatos);
    frame1.setSize(675, 725);
    frame1.setVisible(true); 
    frame1.setLocation(150, 90);
    
  }
  private void jbInit() throws Exception
  {
    this.setLayout(null);
    this.setSize(new Dimension(676, 800));
  
		parcelapanel.setLayout( null );
    jPanel1.setBounds(new Rectangle(5, 10, 625,160));
    jPanel1.setLayout(null);
    jPanel1.setBorder(BorderFactory.createTitledBorder("Domicilio Tributario"));
    entmenorprlbl.setText("Código Entidad Menor:");
    entmenorprlbl.setBounds(new Rectangle(5, 15, 145, 40));
    txtentmenorpar.setText("PP");
    txtentmenorpar.setBounds(new Rectangle(150, 25, 35, 20));
    txtcodviapar.setText("55555");
    txtcodviapar.setBounds(new Rectangle(345, 25, 50, 20));
    entmenorprlbl1.setText("Código Vía Pública:");
    entmenorprlbl1.setBounds(new Rectangle(205, 15, 135, 40));
    txttipovia.setText("PPPP5");
    txttipovia.setBounds(new Rectangle(510, 25, 45, 20));
    tipoviaparlbl.setText("Tipo de Vía:");
    tipoviaparlbl.setBounds(new Rectangle(420, 18, 100, 35));
    txtnombreviapar.setText("PPPPPPPPPPPPPPPPPPPPPPP25");
    txtnombreviapar.setBounds(new Rectangle(90, 55, 230, 20));
    nombreviaparlbl.setText("Nombre Vía:");
    nombreviaparlbl.setBounds(new Rectangle(5, 50, 115, 35));
    txtcodigopostalpar.setText("09001");
    txtcodigopostalpar.setBounds(new Rectangle(425, 55, 50, 20));
    codigopostalparlbl.setText("Código Postal:");
    codigopostalparlbl.setBounds(new Rectangle(330, 50, 90, 35));
    txtnumero1par.setText("4444");
    txtnumero1par.setBounds(new Rectangle(100, 85, 35, 20));
    numero1parlbl.setText("Primer Número:");
    numero1parlbl.setBounds(new Rectangle(5, 78, 100, 35));
    txtletra1par.setText("A");
    txtletra1par.setBounds(new Rectangle(245, 85, 25, 20));
    letra1parlbl.setText("Primera Letra:");
    letra1parlbl.setBounds(new Rectangle(155, 78, 95, 35));
    txtletra2par.setText("A");
    txtletra2par.setBounds(new Rectangle(565, 85, 25, 20));
    txtnumero2par.setText("4444");
    txtnumero2par.setBounds(new Rectangle(405, 85, 35, 20));
    numero2parlbl.setText("Segundo Número:");
    numero2parlbl.setBounds(new Rectangle(290, 78, 125, 35));
    letra2parlbl.setText("Segunda Letra:");
    letra2parlbl.setBounds(new Rectangle(475, 78, 95, 35));
    dirnoestrucparlbl.setText("Direccion No Estructurada:");
    dirnoestrucparlbl.setBounds(new Rectangle(255, 113, 170, 35));
    txtkilometropar.setText("A");
    txtkilometropar.setBounds(new Rectangle(165, 120, 80, 20));
    txtbloquepar.setText("4444");
    txtbloquepar.setBounds(new Rectangle(55, 120, 35, 20));
    bloqueparlbl.setText("Bloque:");
    bloqueparlbl.setBounds(new Rectangle(5, 113, 60, 35));
    kmparlbl.setText("Kilómetro:");
    kmparlbl.setBounds(new Rectangle(100, 113, 110, 35));
    txtdirnoestrucpar.setText("PPPPPPPPPPPPPPPPPPPPPPP25");
    txtdirnoestrucpar.setBounds(new Rectangle(410, 120, 205, 20));
    jPanel2.setBounds(new Rectangle(5, 165, 625, 120));
    jPanel2.setLayout(null);
    jPanel2.setBorder(BorderFactory.createTitledBorder("Datos Físicos y de Valoración"));
    numero2parlbl1.setText("Modalidad Reparto:");
    numero2parlbl1.setBounds(new Rectangle(290, 83, 125, 35));
    formacalculoparlbl.setText("Forma Cálculo:");
    formacalculoparlbl.setBounds(new Rectangle(155, 83, 95, 35));
    txtformacalculopar.setText("AA");
    txtformacalculopar.setBounds(new Rectangle(245, 90, 30, 20));
    aprobacionparlbl.setText("Año Aprobación:");
    aprobacionparlbl.setBounds(new Rectangle(5, 83, 105, 35));
    txtaprobacionpar.setText("4444");
    txtaprobacionpar.setBounds(new Rectangle(100, 90, 35, 20));
    codigopostalparlbl1.setText("Superficie Construída Bajo Rasante:");
    codigopostalparlbl1.setBounds(new Rectangle(310, 48, 220, 35));
    txtsupBRpar.setText("77777.77");
    txtsupBRpar.setBounds(new Rectangle(535, 55, 80, 20));
    txtsupBRpar.setSize(new Dimension(65, 20));
    supSRparlbl.setText("Superficie Construida Sobre Rasante:");
    supSRparlbl.setBounds(new Rectangle(5, 48, 215, 35));
    txtsupSRpar.setText("77777.77");
    txtsupSRpar.setBounds(new Rectangle(225, 55, 65, 20));
    txtsupSRpar.setSize(new Dimension(65, 20));
    supcubiertaparlbl.setText("Superficie Cubierta:");
    supcubiertaparlbl.setBounds(new Rectangle(435, 20, 125, 35));
    txtsupcubiertapar.setText("77777.77");
    txtsupcubiertapar.setBounds(new Rectangle(552, 25, 65, 20));
    txtsupcubiertapar.setSize(new Dimension(65, 20));
    supconsparlbl.setText("Superficie Total Construída:");
    supconsparlbl.setBounds(new Rectangle(175, 15, 165, 40));
    txtsuptotalcos.setText("77777.77");
    txtsuptotalcos.setBounds(new Rectangle(345, 25, 80, 20));
    txtsuptotalcos.setPreferredSize(new Dimension(53, 20));
    txtsuptotalcos.setSize(new Dimension(65, 20));
    txtsupsolar.setText("77777.77");
    txtsupsolar.setBounds(new Rectangle(105, 25, 65, 20));
    supsolarlbl.setText("Superficie Solar:");
    supsolarlbl.setBounds(new Rectangle(5, 15, 145, 40));
    cmbmodrepartopar.setBounds(new Rectangle(410, 90, 200, 20));
    cmbmodrepartopar.addItem("1- Por partes iguales");
    cmbmodrepartopar.addItem("2- Por superficie");
    cmbmodrepartopar.addItem("3- Por coeficientes");
    cmbmodrepartopar.addItem("A- Se valora por repercusión");
    cmbmodrepartopar.addItem("A- Por partes iguales");
    cmbmodrepartopar.addItem("A- Por partes iguales");    
    cmbmodrepartopar.addItem("A- Por partes iguales");
    
    jPanel3.setBounds(new Rectangle(5, 295, 625, 90));
    jPanel3.setLayout(null);
    jPanel3.setBorder(BorderFactory.createTitledBorder("Datos de la Alteración"));
    alterparlbl.setText("Descripción Alteración:");
    alterparlbl.setBounds(new Rectangle(5, 50, 215, 35));
    txtinfocarpar.setText("A");
    txtinfocarpar.setBounds(new Rectangle(275, 25, 40, 20));
    infocarparlbl.setText("Existencia de Información Cartográfica FXCU1:");
    infocarparlbl.setBounds(new Rectangle(5, 15, 320, 40));
    txtalterpar.setText("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
    txtalterpar.setBounds(new Rectangle(145, 55, 465, 20));
    jPanel4.setBounds(new Rectangle(5, 385, 625, 90));
    jPanel4.setLayout(null);
    jPanel4.setBorder(BorderFactory.createTitledBorder("Datos del Movimiento"));
    supcubiertaparlbl1.setText("Referencia Expediente:");
    supcubiertaparlbl1.setBounds(new Rectangle(185, 13, 185, 35));
    txtrefexp.setText("AAAAAAAAAAA13");
    txtrefexp.setBounds(new Rectangle(345, 20, 110, 20));
    txtrefexp.setSize(new Dimension(110, 20));
    annoexpparlbl.setText("Año Expediente:");
    annoexpparlbl.setBounds(new Rectangle(5, 10, 95, 40));
    txtannoexppar.setText("4444");
    txtannoexppar.setBounds(new Rectangle(110, 20, 40, 20));
    txtannoexppar.setPreferredSize(new Dimension(53, 20));
    txtannoexppar.setSize(new Dimension(40, 20));
    btnaceptar.setText("Aceptar");
    btnaceptar.setBounds(new Rectangle(455, 665, 95, 30));
    btncancelar.setText("Cancelar");
    btncancelar.setBounds(new Rectangle(560, 665, 95, 30));
    subparcelapanel.setLayout(null);
    jPanel9.setBounds(new Rectangle(5, 485, 625, 50));
    jPanel9.setLayout(null);
    jPanel9.setBorder(BorderFactory.createTitledBorder("Datos del Movimiento"));
    supcubiertaparlbl4.setText("Referencia Expediente:");
    supcubiertaparlbl4.setBounds(new Rectangle(185, 13, 185, 35));
    txtrefexpsubpar.setText("AAAAAAAAAAA13");
    txtrefexpsubpar.setBounds(new Rectangle(345, 20, 110, 20));
    txtrefexpsubpar.setSize(new Dimension(110, 20));
    annoexpparlbl2.setText("Año Expediente:");
    annoexpparlbl2.setBounds(new Rectangle(5, 10, 95, 40));
    txtannoexpsubpar.setText("4444");
    txtannoexpsubpar.setBounds(new Rectangle(110, 25, 40, 20));
    txtannoexpsubpar.setPreferredSize(new Dimension(53, 20));
    txtannoexpsubpar.setSize(new Dimension(40, 20));
    jPanel10.setBounds(new Rectangle(5, 100, 625, 85));
    jPanel10.setLayout(null);
    jPanel10.setBorder(BorderFactory.createTitledBorder("Datos Físicos"));
    fondosubparlbl.setText("Fondo del Elemento Suelo (m):");
    fondosubparlbl.setBounds(new Rectangle(265, 50, 195, 35));
    txtfondosubpar.setText("333");
    txtfondosubpar.setBounds(new Rectangle(440, 55, 40, 20));
    superficiesubparlbl.setText("Superficie Subparcela (m2):");
    superficiesubparlbl.setBounds(new Rectangle(5, 48, 215, 35));
    txtsuperficiesubpar.setText("77777.77");
    txtsuperficiesubpar.setBounds(new Rectangle(180, 55, 65, 20));
    txtsuperficiesubpar.setSize(new Dimension(65, 20));
    tipofachadasubparlbl.setText("Tipo Fachada:");
    tipofachadasubparlbl.setBounds(new Rectangle(260, 15, 125, 40));
    txtlongfachadasubpar.setText("55555");
    txtlongfachadasubpar.setBounds(new Rectangle(165, 25, 65, 20));
    longfachadasubparlbl.setText("Longitud Fachada (cm):");
    longfachadasubparlbl.setBounds(new Rectangle(5, 15, 145, 40));
    jPanel11.setBounds(new Rectangle(5, 10, 625, 90));
    jPanel11.setLayout(null);
    jPanel11.setBorder(BorderFactory.createTitledBorder("Identificación"));
    ordensubparlbl.setText("Número Orden Subparcela:");
    ordensubparlbl.setBounds(new Rectangle(275, 20, 185, 40));
    txtordensubpar.setText("4444");
    txtordensubpar.setBounds(new Rectangle(445, 30, 50, 20));
    jPanel12.setBounds(new Rectangle(5, 190, 625, 290));
    jPanel12.setLayout(null);
    jPanel12.setBorder(BorderFactory.createTitledBorder("Datos de la Alteración"));
    jPanel12.setSize(new Dimension(625, 290));
    coef1lbl.setText("Coeficientes Correctores del Valor del Suelo.");
    coef1lbl.setBounds(new Rectangle(5, 50, 495, 35));
    lstsubparcela.setBounds(new Rectangle(35, 25, 105, 55));
    lstsubparcela.setAutoscrolls(false);
    cmbtipofachadasubpar.setBounds(new Rectangle(370, 25, 70, 20));
    txttramoviasubpar.setText("PP3");
    txttramoviasubpar.setBounds(new Rectangle(330, 25, 35, 20));
    tipoviaparlbl1.setText("Código Tramo Vía:");
    tipoviaparlbl1.setBounds(new Rectangle(210, 20, 115, 35));
    txtcodviasubpar.setText("55555");
    txtcodviasubpar.setBounds(new Rectangle(150, 25, 50, 20));
    entmenorprlbl2.setText("Código Vía Pública DGC:");
    entmenorprlbl2.setBounds(new Rectangle(5, 15, 135, 40));
    cmbtipovalorsubpar.setBounds(new Rectangle(515, 25, 50, 20));
    tipovalorsubparlbl.setText("Código Tipo Valor:");
    tipovalorsubparlbl.setBounds(new Rectangle(395, 15, 145, 40));
    chknumfachadasubpar.setText("Numero  Fachadas");
    chknumfachadasubpar.setBounds(new Rectangle(5, 80, 135, 20));
    chklongfachadasubpar.setText("Longitud Fachada");
    chklongfachadasubpar.setBounds(new Rectangle(145, 80, 130, 20));
    chkirregularsubpar.setText("Forma Irregular");
    chkirregularsubpar.setBounds(new Rectangle(275, 80, 105, 20));
    chkdesmontesubpar.setText("Desmonte");
    chkdesmontesubpar.setBounds(new Rectangle(390, 80, 85, 20));
    chkprofundidadsubpar.setText("Profundidad");
    chkprofundidadsubpar.setBounds(new Rectangle(480, 80, 110, 20));
    chkvposubpar.setText("V.P.O.");
    chkvposubpar.setBounds(new Rectangle(390, 110, 110, 20));
    chkinedificabilidadsubpar.setText("Inedificabilidad");
    chkinedificabilidadsubpar.setBounds(new Rectangle(275, 110, 105, 20));
    chksuperficiesubpar.setText("Superficie");
    chksuperficiesubpar.setBounds(new Rectangle(145, 110, 120, 20));
    chkfondosubpar.setText("Fondo");
    chkfondosubpar.setBounds(new Rectangle(5, 110, 135, 20));
    chknolucrativosubpar.setText("No Lucrativo");
    chknolucrativosubpar.setBounds(new Rectangle(490, 165, 110, 20));
    chkdepreciacionsubpar.setText("Depreciación");
    chkdepreciacionsubpar.setBounds(new Rectangle(385, 165, 100, 20));
    chkespecialsubpar.setText("S. Especiales");
    chkespecialsubpar.setBounds(new Rectangle(270, 165, 105, 20));
    chkcargassubpar.setText("Cargas Singulares");
    chkcargassubpar.setBounds(new Rectangle(140, 165, 125, 20));
    coef1lbl1.setText("Coeficientes Correctores Conjuntos del Valor del Suelo y de las Construcciones.");
    coef1lbl1.setBounds(new Rectangle(5, 135, 495, 35));
    apreciacionlbl.setText("Apreciación:");
    apreciacionlbl.setBounds(new Rectangle(5, 165, 80, 25));
    txtapreciacionsubpar.setText("333");
    txtapreciacionsubpar.setBounds(new Rectangle(92, 165, 40, 20));
    coef1lbl2.setText("Coeficientes Correctores del Grado de Urbanización");
    coef1lbl2.setBounds(new Rectangle(5, 190, 495, 35));
    cmbpavimentacionsubpar.setBounds(new Rectangle(260, 265, 40, 15));
    cmbpavimentacionsubpar.addItem("N");
    cmbpavimentacionsubpar.addItem("0");
    cmbpavimentacionsubpar.addItem("1");
    pavimentacionsubparlbl.setText("Pavimentación:");
    pavimentacionsubparlbl.setBounds(new Rectangle(155, 260, 100, 25));
    cmbalcantarilladosubpar.setBounds(new Rectangle(410, 265, 40, 15));
    alcantarilladosubparlb.setText("Alcantarillado:");
    alcantarilladosubparlb.setBounds(new Rectangle(320, 260, 95, 25));
    cmbdesmontesubpar.setBounds(new Rectangle(85, 265, 40, 15));
    desmontesubparlb.setText("Desmonte:");
    desmontesubparlb.setBounds(new Rectangle(5, 260, 75, 25));
    cmbalumbradosubpar.setBounds(new Rectangle(410, 230, 40, 15));
    alumbradosubparlb.setText("Alumbrado:");
    alumbradosubparlb.setBounds(new Rectangle(320, 225, 75, 25));
    cmbelectricidadsubpar.setBounds(new Rectangle(260, 230, 40, 15));
    Electricidadsubparlb.setText("Electricidad:");
    Electricidadsubparlb.setBounds(new Rectangle(155, 225, 85, 25));
    cmbaguasubpar.setBounds(new Rectangle(85, 230, 40, 15));
    aguasubparlb5.setText("Agua:");
    aguasubparlb5.setBounds(new Rectangle(5, 225, 45, 25));
    unidadconstructivapanel.setLayout(null);
    jPanel15.setBounds(new Rectangle(5, 10, 625, 90));
    jPanel15.setLayout(null);
    jPanel15.setBorder(BorderFactory.createTitledBorder("Identificación"));
    lstuc.setBounds(new Rectangle(35, 25, 105, 55));
    ordenuclbl.setText("Código Unidad Constructiva");
    ordenuclbl.setBounds(new Rectangle(245, 15, 210, 40));
    txtordenuc.setText("4444");
    txtordenuc.setBounds(new Rectangle(415, 25, 50, 20));
    jPanel16.setBounds(new Rectangle(5, 320, 625, 205));
    jPanel16.setLayout(null);
    jPanel16.setBorder(BorderFactory.createTitledBorder("Datos de Valoración"));
    jPanel16.setSize(new Dimension(625, 205));
    alumbradosubparlb1.setText("Alumbrado:");
    alumbradosubparlb1.setBounds(new Rectangle(325, 135, 75, 25));
    cmbalumbradouc.setBounds(new Rectangle(410, 140, 40, 15));
    desmontesubparlb1.setText("Desmonte:");
    desmontesubparlb1.setBounds(new Rectangle(465, 135, 75, 25));
    cmbdesmonteuc.setBounds(new Rectangle(545, 140, 40, 15));
    alcantarilladosubparlb1.setText("Alcantarillado:");
    alcantarilladosubparlb1.setBounds(new Rectangle(160, 170, 95, 25));
    cmbalcantarilladouc.setBounds(new Rectangle(260, 175, 40, 15));
    pavimentacionsubparlbl1.setText("Pavimentación:");
    pavimentacionsubparlbl1.setBounds(new Rectangle(5, 170, 100, 25));
    cmbpavimentacionuc.setBounds(new Rectangle(95, 175, 40, 15));
    txtapreciacionuc.setText("333");
    txtapreciacionuc.setBounds(new Rectangle(95, 110, 40, 20));
    apreciacionlbl1.setText("Depreciación:");
    apreciacionlbl1.setBounds(new Rectangle(5, 110, 95, 25));
    chkcargasuc.setText("Cargas Singulares");
    chkcargasuc.setBounds(new Rectangle(170, 110, 125, 20));
    chkespecialuc.setText("Situaciones Especiales");
    chkespecialuc.setBounds(new Rectangle(300, 110, 175, 20));
    chknolucrativouc.setText("No Lucrativo");
    chknolucrativouc.setBounds(new Rectangle(480, 110, 110, 20));
    chkconservacionuc.setText("Estado de Conservación");
    chkconservacionuc.setBounds(new Rectangle(275, 80, 230, 20));
    chklongfachadauc.setText("Longitud Fachada");
    chklongfachadauc.setBounds(new Rectangle(145, 80, 130, 20));
    chknumfachadauc.setText("Numero  Fachadas");
    chknumfachadauc.setBounds(new Rectangle(5, 80, 135, 20));
    entmenorprlbl3.setText("Código Vía Pública DGC:");
    entmenorprlbl3.setBounds(new Rectangle(5, 15, 135, 40));
    txtcodviaDGCuc.setText("55555");
    txtcodviaDGCuc.setBounds(new Rectangle(145, 25, 50, 20));
    tipoviaparlbl2.setText("Código Tramo Vía:");
    tipoviaparlbl2.setBounds(new Rectangle(225, 20, 115, 35));
    txttramoviauc.setText("PP3");
    txttramoviauc.setBounds(new Rectangle(350, 25, 35, 20));
    coef1lbl5.setText("Coeficientes Correctores del Valor del Suelo y del Valor de las Constucciones");
    coef1lbl5.setBounds(new Rectangle(5, 50, 595, 35));
    cmbelectricidaduc.setBounds(new Rectangle(265, 140, 40, 15));
    Electricidadsubparlb1.setText("Electricidad:");
    Electricidadsubparlb1.setBounds(new Rectangle(160, 135, 85, 25));
    cmbaguauc.setBounds(new Rectangle(95, 140, 40, 15));
    aguasubparlb6.setText("Agua:");
    aguasubparlb6.setBounds(new Rectangle(5, 135, 45, 25));
    jPanel5.setBounds(new Rectangle(5, 100, 625, 160));
    jPanel5.setLayout(null);
    jPanel5.setBorder(BorderFactory.createTitledBorder("Domicilio Tributario de la Unidad Constructiva"));
    txtdirnoestrucuc.setText("PPPPPPPPPPPPPPPPPPPPPPP25");
    txtdirnoestrucuc.setBounds(new Rectangle(410, 120, 205, 20));
    kmparlbl1.setText("Kilómetro:");
    kmparlbl1.setBounds(new Rectangle(100, 113, 110, 35));
    bloqueparlbl1.setText("Bloque:");
    bloqueparlbl1.setBounds(new Rectangle(5, 113, 60, 35));
    txtbloqueuc.setText("4444");
    txtbloqueuc.setBounds(new Rectangle(55, 120, 35, 20));
    txtkilometrouc.setText("A");
    txtkilometrouc.setBounds(new Rectangle(165, 120, 80, 20));
    dirnoestrucparlbl1.setText("Direccion No Estructurada:");
    dirnoestrucparlbl1.setBounds(new Rectangle(255, 113, 170, 35));
    letra2parlbl1.setText("Segunda Letra:");
    letra2parlbl1.setBounds(new Rectangle(475, 78, 95, 35));
    numero2parlbl2.setText("Segundo Número:");
    numero2parlbl2.setBounds(new Rectangle(290, 78, 125, 35));
    txtnumero2uc.setText("4444");
    txtnumero2uc.setBounds(new Rectangle(405, 85, 35, 20));
    txtletra2uc.setText("A");
    txtletra2uc.setBounds(new Rectangle(565, 85, 25, 20));
    letra1parlbl1.setText("Primera Letra:");
    letra1parlbl1.setBounds(new Rectangle(155, 78, 95, 35));
    txtletra1uc.setText("A");
    txtletra1uc.setBounds(new Rectangle(245, 85, 25, 20));
    numero1parlbl1.setText("Primer Número:");
    numero1parlbl1.setBounds(new Rectangle(5, 78, 100, 35));
    txtnumero1uc.setText("4444");
    txtnumero1uc.setBounds(new Rectangle(100, 85, 35, 20));
    codigopostaluclbl.setText("Código Postal:");
    codigopostaluclbl.setBounds(new Rectangle(330, 50, 90, 35));
    txtcodigopostaluc.setText("09001");
    txtcodigopostaluc.setBounds(new Rectangle(425, 55, 50, 20));
    nombreviauclbl.setText("Nombre Vía:");
    nombreviauclbl.setBounds(new Rectangle(5, 50, 115, 35));
    txtnombreviauc.setText("PPPPPPPPPPPPPPPPPPPPPPP25");
    txtnombreviauc.setBounds(new Rectangle(90, 55, 230, 20));
    tipoviauclbl.setText("Tipo de Vía:");
    tipoviauclbl.setBounds(new Rectangle(420, 18, 100, 35));
    txttipoviauc.setText("PPPP5");
    txttipoviauc.setBounds(new Rectangle(510, 25, 45, 20));
    viapublicauclbl.setText("Código Vía Pública:");
    viapublicauclbl.setBounds(new Rectangle(205, 15, 135, 40));
    txtcodviauc.setText("55555");
    txtcodviauc.setBounds(new Rectangle(345, 25, 50, 20));
    txtentmenoruc.setText("PP");
    txtentmenoruc.setBounds(new Rectangle(150, 25, 35, 20));
    entmenoruclbl.setText("Código Entidad Menor:");
    entmenoruclbl.setBounds(new Rectangle(5, 15, 145, 40));
    jPanel14.setBounds(new Rectangle(5, 260, 625, 50));
    jPanel14.setLayout(null);
    jPanel14.setBorder(BorderFactory.createTitledBorder("Datos Físicos"));
    cmbusoagrariouc.setBounds(new Rectangle(530, 20, 45, 20));
    annoconstuclbl.setText("Año de la Construcción:");
    annoconstuclbl.setBounds(new Rectangle(5, 15, 165, 35));
    txtannoconsuc.setText("2004");
    txtannoconsuc.setBounds(new Rectangle(150, 20, 40, 20));
    txtannoconsuc.setSize(new Dimension(40, 20));
    usoagrariouclbl.setText("Uso Agrario:");
    usoagrariouclbl.setBounds(new Rectangle(430, 10, 100, 40));
    txtlongfachadauc.setText("55555");
    txtlongfachadauc.setBounds(new Rectangle(365, 20, 45, 20));
    longfachadasubparlbl1.setText("Longitud Fachada (cm):");
    longfachadasubparlbl1.setBounds(new Rectangle(210, 10, 145, 40));
    exactannouclbl.setText("Exactitud Año Construcción:");
    exactannouclbl.setBounds(new Rectangle(325, 170, 185, 25));
    cmbexactitudannouc.setBounds(new Rectangle(515, 175, 40, 15));
    jPanel13.setBounds(new Rectangle(5, 530, 625, 50));
    jPanel13.setLayout(null);
    jPanel13.setBorder(BorderFactory.createTitledBorder("Datos del Movimiento"));
    supcubiertaparlbl5.setText("Referencia Expediente:");
    supcubiertaparlbl5.setBounds(new Rectangle(185, 13, 185, 35));
    txtrefexpuc.setText("AAAAAAAAAAA13");
    txtrefexpuc.setBounds(new Rectangle(345, 20, 110, 20));
    txtrefexpuc.setSize(new Dimension(110, 20));
    annoexpparlbl3.setText("Año Expediente:");
    annoexpparlbl3.setBounds(new Rectangle(5, 10, 95, 40));
    txtannoexpuc.setText("4444");
    txtannoexpuc.setBounds(new Rectangle(110, 20, 40, 20));
    txtannoexpuc.setPreferredSize(new Dimension(53, 20));
    txtannoexpuc.setSize(new Dimension(40, 20));
    construccionespanel.setLayout(null);
    jPanel7.setBounds(new Rectangle(5, 155, 625, 85));
    jPanel7.setLayout(null);
    jPanel7.setBorder(BorderFactory.createTitledBorder("Datos Físicos"));
    supcubiertaparlbl3.setText("Superficie Imputable:");
    supcubiertaparlbl3.setBounds(new Rectangle(430, 45, 125, 35));
    txtsupimputablecons.setText("77777.77");
    txtsupimputablecons.setBounds(new Rectangle(555, 50, 65, 20));
    txtsupimputablecons.setSize(new Dimension(65, 20));
    supconsparlbl1.setText("Superficie Porches/Terrazas:");
    supconsparlbl1.setBounds(new Rectangle(185, 40, 200, 40));
    txtsupterrazascons.setText("77777.77");
    txtsupterrazascons.setBounds(new Rectangle(345, 50, 65, 20));
    txtsupterrazascons.setPreferredSize(new Dimension(53, 20));
    txtsupterrazascons.setSize(new Dimension(65, 20));
    txtsuptotalcon.setText("77777.77");
    txtsuptotalcon.setBounds(new Rectangle(105, 50, 65, 20));
    supsolarlbl1.setText("Superficie Total:");
    supsolarlbl1.setBounds(new Rectangle(5, 40, 145, 40));
    jPanel8.setBounds(new Rectangle(5, 100, 625, 55));
    jPanel8.setLayout(null);
    jPanel8.setBorder(BorderFactory.createTitledBorder("Domicilio Tributario"));
    escaleralbl.setText("Escalera:");
    escaleralbl.setBounds(new Rectangle(100, 13, 70, 35));
    bloqueparlbl2.setText("Bloque:");
    bloqueparlbl2.setBounds(new Rectangle(5, 13, 60, 35));
    txtbloquecons.setText("4444");
    txtbloquecons.setBounds(new Rectangle(55, 20, 35, 20));
    txtescaleracons.setText("AA");
    txtescaleracons.setBounds(new Rectangle(165, 20, 40, 20));
    plantaconslbl.setText("Planta:");
    plantaconslbl.setBounds(new Rectangle(220, 15, 70, 35));
    txtplantacons.setText("4444");
    txtplantacons.setBounds(new Rectangle(280, 20, 35, 20));
    puertaconslbl.setText("Puerta:");
    puertaconslbl.setBounds(new Rectangle(335, 13, 70, 35));
    txtpuertacons.setText("AAA");
    txtpuertacons.setBounds(new Rectangle(390, 20, 40, 20));
    jPanel18.setBounds(new Rectangle(5, 10, 625, 90));
    jPanel18.setLayout(null);
    jPanel18.setBorder(BorderFactory.createTitledBorder("Identificación"));
    lstcons.setBounds(new Rectangle(35, 25, 105, 55));
    ordenconslbl.setText("Nº Orden Construcción:");
    ordenconslbl.setBounds(new Rectangle(290, 0, 210, 40));
    txtordencons.setText("4444");
    txtordencons.setBounds(new Rectangle(475, 10, 50, 20));
    cmbreformacons.setBounds(new Rectangle(265, 20, 45, 20));
    reformaconslbl.setText("Tipo Reforma:");
    reformaconslbl.setBounds(new Rectangle(165, 10, 120, 40));
    txtannoreforma.setText("2004");
    txtannoreforma.setBounds(new Rectangle(415, 20, 45, 20));
    annoreformalbl.setText("Año Reforma:");
    annoreformalbl.setBounds(new Rectangle(335, 10, 105, 40));
    txtdestinocons.setText("VVV");
    txtdestinocons.setBounds(new Rectangle(100, 20, 40, 20));
    txtdestinocons.setSize(new Dimension(40, 20));
    destinoconslbl.setText("Código Destino:");
    destinoconslbl.setBounds(new Rectangle(5, 15, 95, 35));
    chklocalcons.setText("Local Interior");
    chklocalcons.setBounds(new Rectangle(480, 20, 110, 20));
    jPanel17.setBounds(new Rectangle(5, 235, 625, 150));
    jPanel17.setLayout(null);
    jPanel17.setBorder(BorderFactory.createTitledBorder("Datos de Valoración"));
    jPanel17.setSize(new Dimension(625, 150));
    txtapreciacioncons.setText("333");
    txtapreciacioncons.setBounds(new Rectangle(245, 120, 40, 20));
    apreciacionconslbl.setText("Apreciación / Depreciación Económica:");
    apreciacionconslbl.setBounds(new Rectangle(5, 120, 230, 25));
    coef1lbl4.setText("Coeficientes Correctores Conjuntos del Valor del Suelo y de las Construcciones.");
    coef1lbl4.setBounds(new Rectangle(5, 90, 495, 35));
    chkviviendacons.setText("Vivienda / Local Interior");
    chkviviendacons.setBounds(new Rectangle(355, 120, 195, 20));
    cmbusocons.setBounds(new Rectangle(305, 30, 170, 20));
    TIPOLOGIACONSLBL.setText("Tipología Constructiva:");
    TIPOLOGIACONSLBL.setBounds(new Rectangle(5, 15, 135, 40));
    txttipologiacons.setText("55555");
    txttipologiacons.setBounds(new Rectangle(135, 25, 50, 20));
    tipoviaparlbl3.setText("Uso Predominante:");
    tipoviaparlbl3.setBounds(new Rectangle(195, 20, 115, 35));
    txtcategoriacons.setText("A");
    txtcategoriacons.setBounds(new Rectangle(565, 30, 25, 20));
    categoriaconslbl.setText("Categoría:");
    categoriaconslbl.setBounds(new Rectangle(490, 20, 95, 40));
    cmbreparto1cons.setBounds(new Rectangle(125, 60, 115, 20));
    tipoviaparlbl4.setText("Modalidad Reparto:");
    tipoviaparlbl4.setBounds(new Rectangle(5, 50, 115, 35));
    cmbreparto2cons.setBounds(new Rectangle(250, 60, 115, 20));
    cmbreparto3cons.setBounds(new Rectangle(375, 60, 115, 20));
    cmbtipovalorcons.setBounds(new Rectangle(560, 60, 50, 20));
    tipovalorconslbl.setText("Tipo Valor:");
    tipovalorconslbl.setBounds(new Rectangle(495, 50, 75, 40));
    jPanel19.setBounds(new Rectangle(5, 390, 625, 50));
    jPanel19.setLayout(null);
    jPanel19.setBorder(BorderFactory.createTitledBorder("Datos del Movimiento"));
    referenciaconslbl.setText("Referencia Expediente:");
    referenciaconslbl.setBounds(new Rectangle(185, 13, 185, 35));
    txtreferenciacons.setText("AAAAAAAAAAA13");
    txtreferenciacons.setBounds(new Rectangle(345, 20, 110, 20));
    txtreferenciacons.setSize(new Dimension(110, 20));
    annoexpconslbl.setText("Año Expediente:");
    annoexpconslbl.setBounds(new Rectangle(5, 10, 95, 40));
    txtannoexpcons.setText("4444");
    txtannoexpcons.setBounds(new Rectangle(110, 20, 40, 20));
    txtannoexpcons.setPreferredSize(new Dimension(53, 20));
    txtannoexpcons.setSize(new Dimension(40, 20));
    txtcargocons.setText("4444");
    txtcargocons.setBounds(new Rectangle(475, 35, 50, 20));
    cargoconslbl.setText("Nº Cargo al que se imputa:");
    cargoconslbl.setBounds(new Rectangle(290, 25, 210, 40));
    txtuccons.setText("4444");
    txtuccons.setBounds(new Rectangle(475, 60, 50, 20));
    ucconslbl.setText("Código Unidad Constructiva");
    ucconslbl.setBounds(new Rectangle(290, 50, 210, 40));
    cargopanel.setLayout(null);
    jPanel110.setBounds(new Rectangle(5, 480, 625, 50));
    jPanel110.setLayout(null);
    jPanel110.setBorder(BorderFactory.createTitledBorder("Datos del Movimiento"));
    supcubiertaparlbl6.setText("Referencia Expediente:");
    supcubiertaparlbl6.setBounds(new Rectangle(185, 13, 185, 35));
    txtrefexpcargo.setText("AAAAAAAAAAA13");
    txtrefexpcargo.setBounds(new Rectangle(345, 20, 110, 20));
    txtrefexpcargo.setSize(new Dimension(110, 20));
    annoexpparlbl4.setText("Año Expediente:");
    annoexpparlbl4.setBounds(new Rectangle(5, 10, 95, 40));
    txtannoexpcargo.setText("4444");
    txtannoexpcargo.setBounds(new Rectangle(110, 20, 40, 20));
    txtannoexpcargo.setPreferredSize(new Dimension(53, 20));
    txtannoexpcargo.setSize(new Dimension(40, 20));
    jPanel6.setBounds(new Rectangle(5, 100, 625, 185));
    jPanel6.setLayout(null);
    jPanel6.setBorder(BorderFactory.createTitledBorder("Domicilio Tributario del Elemento"));
    txtdirnoestruccargo.setText("PPPPPPPPPPPPPPPPPPPPPPP25");
    txtdirnoestruccargo.setBounds(new Rectangle(410, 120, 205, 20));
    kmparlbl2.setText("Kilómetro:");
    kmparlbl2.setBounds(new Rectangle(100, 113, 110, 35));
    bloqueparlbl3.setText("Bloque:");
    bloqueparlbl3.setBounds(new Rectangle(5, 113, 60, 35));
    txtbloquecargo.setText("4444");
    txtbloquecargo.setBounds(new Rectangle(55, 120, 35, 20));
    txtkilometrocargo.setText("A");
    txtkilometrocargo.setBounds(new Rectangle(165, 120, 80, 20));
    dirnoestrucparlbl2.setText("Direccion No Estructurada:");
    dirnoestrucparlbl2.setBounds(new Rectangle(255, 113, 170, 35));
    letra2parlbl2.setText("Segunda Letra:");
    letra2parlbl2.setBounds(new Rectangle(475, 78, 95, 35));
    numero2parlbl3.setText("Segundo Número:");
    numero2parlbl3.setBounds(new Rectangle(290, 78, 125, 35));
    txtnumero2cargo.setText("4444");
    txtnumero2cargo.setBounds(new Rectangle(405, 85, 35, 20));
    txtletra2cargo.setText("A");
    txtletra2cargo.setBounds(new Rectangle(565, 85, 25, 20));
    letra1parlbl2.setText("Primera Letra:");
    letra1parlbl2.setBounds(new Rectangle(155, 78, 95, 35));
    txtletra1cargo.setText("A");
    txtletra1cargo.setBounds(new Rectangle(245, 85, 25, 20));
    numero1cargolbl.setText("Primer Número:");
    numero1cargolbl.setBounds(new Rectangle(5, 78, 100, 35));
    txtnumero1cargo.setText("4444");
    txtnumero1cargo.setBounds(new Rectangle(100, 85, 35, 20));
    codigopostalcargolbl.setText("Código Postal:");
    codigopostalcargolbl.setBounds(new Rectangle(330, 50, 90, 35));
    txtcodigopostalcargo.setText("09001");
    txtcodigopostalcargo.setBounds(new Rectangle(425, 55, 50, 20));
    nombreviacargolbl.setText("Nombre Vía:");
    nombreviacargolbl.setBounds(new Rectangle(5, 50, 115, 35));
    txtnombreviacargo.setText("PPPPPPPPPPPPPPPPPPPPPPP25");
    txtnombreviacargo.setBounds(new Rectangle(90, 55, 230, 20));
    tipoviacargolbl.setText("Tipo de Vía:");
    tipoviacargolbl.setBounds(new Rectangle(420, 18, 100, 35));
    txttipoviacargo.setText("PPPP5");
    txttipoviacargo.setBounds(new Rectangle(510, 25, 45, 20));
    viapublicacargolbl.setText("Código Vía Pública:");
    viapublicacargolbl.setBounds(new Rectangle(200, 15, 135, 40));
    txtcodviacargo.setText("55555");
    txtcodviacargo.setBounds(new Rectangle(345, 25, 50, 20));
    txtentmenorcargo.setText("PP");
    txtentmenorcargo.setBounds(new Rectangle(150, 25, 35, 20));
    entmenorcargolbl.setText("Código Entidad Menor:");
    entmenorcargolbl.setBounds(new Rectangle(5, 15, 145, 40));
    jPanel112.setBounds(new Rectangle(5, 10, 625, 90));
    jPanel112.setLayout(null);
    jPanel112.setBorder(BorderFactory.createTitledBorder("Identificación"));
    participacioncargolbl.setText("Coeficiente Paticipación:");
    participacioncargolbl.setBounds(new Rectangle(210, 50, 175, 40));
    txtparticipacioncargo.setText("55555");
    txtparticipacioncargo.setBounds(new Rectangle(355, 60, 60, 20));
    fijocargolbl.setText("Nº Fijo Bien Inmueble:");
    fijocargolbl.setBounds(new Rectangle(210, 25, 145, 40));
    txtfijocargo.setText("88888888");
    txtfijocargo.setBounds(new Rectangle(335, 35, 95, 20));
    lstcargo.setBounds(new Rectangle(5, 25, 105, 55));
    cargocargolbl.setText("Nº Cargo:");
    cargocargolbl.setBounds(new Rectangle(210, 0, 85, 40));
    txcargo.setText("4444");
    txcargo.setBounds(new Rectangle(285, 10, 50, 20));
    control1cargotxt.setText("A");
    control1cargotxt.setBounds(new Rectangle(470, 10, 25, 20));
    controlcargolbl.setText("Caracteres Control:");
    controlcargolbl.setBounds(new Rectangle(355, 0, 135, 40));
    txtcontrol2cargo.setText("A");
    txtcontrol2cargo.setBounds(new Rectangle(505, 10, 25, 20));
    txtcontrolfijocargo.setText("A");
    txtcontrolfijocargo.setBounds(new Rectangle(550, 35, 25, 20));
    controlfijocargolbl.setText("Carácter Control:");
    controlfijocargolbl.setBounds(new Rectangle(440, 25, 105, 40));
    txtdistritocargo.setText("22");
    txtdistritocargo.setBounds(new Rectangle(535, 60, 40, 20));
    distritocargolbl.setText("Distrito Censal:");
    distritocargolbl.setBounds(new Rectangle(435, 50, 105, 40));
    txtpuertacargo.setText("AAA");
    txtpuertacargo.setBounds(new Rectangle(305, 150, 40, 20));
    puertaconslbl1.setText("Puerta:");
    puertaconslbl1.setBounds(new Rectangle(240, 145, 70, 35));
    txtplantacargo.setText("4444");
    txtplantacargo.setBounds(new Rectangle(180, 150, 35, 20));
    plantaconslbl1.setText("Planta:");
    plantaconslbl1.setBounds(new Rectangle(125, 145, 70, 35));
    txtescaleracargo.setText("AA");
    txtescaleracargo.setBounds(new Rectangle(70, 150, 40, 20));
    escaleralbl1.setText("Escalera:");
    escaleralbl1.setBounds(new Rectangle(5, 145, 70, 35));
    jPanel20.setBounds(new Rectangle(5, 290, 625, 185));
    jPanel20.setLayout(null);
    jPanel20.setBorder(BorderFactory.createTitledBorder("Datos Económicos Valorativos del Bien Inmueble"));
    numero2parlbl4.setText("Nº Última Notificación:");
    numero2parlbl4.setBounds(new Rectangle(290, 83, 125, 35));
    formacalculoparlbl1.setText("Año Notificación:");
    formacalculoparlbl1.setBounds(new Rectangle(135, 85, 105, 35));
    txtannonotificacion.setText("4444");
    txtannonotificacion.setBounds(new Rectangle(235, 90, 40, 20));
    aprobacionparlbl1.setText("Año Revisión:");
    aprobacionparlbl1.setBounds(new Rectangle(5, 83, 105, 35));
    txtannorevision.setText("4444");
    txtannorevision.setBounds(new Rectangle(90, 90, 35, 20));
    supconsparlbl2.setText("Valor Catastral:");
    supconsparlbl2.setBounds(new Rectangle(185, 15, 120, 40));
    txtvalorcatastralcargo.setText("9999999999.12");
    txtvalorcatastralcargo.setBounds(new Rectangle(290, 25, 95, 20));
    txtvalorcatastralcargo.setPreferredSize(new Dimension(53, 20));
    txtvalorcatastralcargo.setSize(new Dimension(95, 20));
    txtannovalorcargo.setText("2004");
    txtannovalorcargo.setBounds(new Rectangle(125, 25, 45, 20));
    supsolarlbl2.setText("Año Valor Catastral:");
    supsolarlbl2.setBounds(new Rectangle(5, 15, 145, 40));
    txtvalorsuelocargo.setText("9999999999.12");
    txtvalorsuelocargo.setBounds(new Rectangle(520, 25, 95, 20));
    txtvalorsuelocargo.setPreferredSize(new Dimension(53, 20));
    txtvalorsuelocargo.setSize(new Dimension(95, 20));
    supconsparlbl3.setText("Valor Suelo:");
    supconsparlbl3.setBounds(new Rectangle(410, 15, 120, 40));
    txtbaseliquidablecargo.setText("9999999999.12");
    txtbaseliquidablecargo.setBounds(new Rectangle(380, 60, 95, 20));
    txtbaseliquidablecargo.setPreferredSize(new Dimension(53, 20));
    txtbaseliquidablecargo.setSize(new Dimension(95, 20));
    supconsparlbl4.setText("Base Liquidable:");
    supconsparlbl4.setBounds(new Rectangle(275, 50, 120, 40));
    txtvalorconstruccioncargo.setText("9999999999.12");
    txtvalorconstruccioncargo.setBounds(new Rectangle(150, 60, 95, 20));
    txtvalorconstruccioncargo.setPreferredSize(new Dimension(53, 20));
    txtvalorconstruccioncargo.setSize(new Dimension(95, 20));
    valorconstruccioncargolbl.setText("Valor  Construcción:");
    valorconstruccioncargolbl.setBounds(new Rectangle(5, 50, 145, 40));
    txtclaveusocargo.setText("A");
    txtclaveusocargo.setBounds(new Rectangle(570, 60, 45, 20));
    tipoviacargolbl1.setText("Clave Uso:");
    tipoviacargolbl1.setBounds(new Rectangle(495, 55, 100, 35));
    txtnotificacioncargo.setText("666666");
    txtnotificacioncargo.setBounds(new Rectangle(425, 90, 95, 20));
    txtnotificacioncargo.setPreferredSize(new Dimension(53, 20));
    txtnotificacioncargo.setSize(new Dimension(95, 20));
    txtcoeficientepropcargo.setText("77777.77");
    txtcoeficientepropcargo.setBounds(new Rectangle(555, 120, 65, 20));
    txtcoeficientepropcargo.setSize(new Dimension(65, 20));
    supcubiertaparlbl7.setText("Coef. Propiedad:");
    supcubiertaparlbl7.setBounds(new Rectangle(440, 115, 125, 35));
    txtsupsuelocargo.setText("77777.77");
    txtsupsuelocargo.setBounds(new Rectangle(360, 120, 65, 20));
    txtsupsuelocargo.setPreferredSize(new Dimension(53, 20));
    txtsupsuelocargo.setSize(new Dimension(65, 20));
    supconsparlbl5.setText("Superficie Suelo:");
    supconsparlbl5.setBounds(new Rectangle(255, 110, 120, 40));
    txtsupconstruccioncargo.setText("77777.77");
    txtsupconstruccioncargo.setBounds(new Rectangle(175, 120, 65, 20));
    supsolarlbl3.setText("Sup. Elementos Constructivos:");
    supsolarlbl3.setBounds(new Rectangle(5, 110, 175, 40));
    txtannofinvalorcargo.setText("2004");
    txtannofinvalorcargo.setBounds(new Rectangle(290, 150, 45, 20));
    supsolarlbl4.setText("Año Finalización Valoración:");
    supsolarlbl4.setBounds(new Rectangle(120, 140, 165, 40));
    chkpreciocargo.setText("Precio Máximo ");
    chkpreciocargo.setBounds(new Rectangle(5, 148, 110, 25));
    supcubiertaparlbl8.setText("Tipo Propiedad:");
    supcubiertaparlbl8.setBounds(new Rectangle(350, 143, 115, 35));
    cmbtipopropiedadcargo.setBounds(new Rectangle(465, 150, 155, 20));
    cargopanel1.setLayout(null);
    jPanel113.setBounds(new Rectangle(5, 10, 625, 90));
    jPanel113.setLayout(null);
    jPanel113.setBorder(BorderFactory.createTitledBorder("Identificación"));
    txtcontrol2titular.setText("A");
    txtcontrol2titular.setBounds(new Rectangle(560, 30, 25, 20));
    controlcargolbl1.setText("Caracteres Control:");
    controlcargolbl1.setBounds(new Rectangle(410, 20, 135, 40));
    txtcontrol1itular.setText("A");
    txtcontrol1itular.setBounds(new Rectangle(525, 30, 25, 20));
    lsttitular.setBounds(new Rectangle(35, 25, 145, 55));
    cargocargolbl1.setText("Nº Cargo:");
    cargocargolbl1.setBounds(new Rectangle(265, 20, 85, 40));
    txtcargotitular.setText("4444");
    txtcargotitular.setBounds(new Rectangle(340, 30, 50, 20));
    jPanel22.setBounds(new Rectangle(5, 220, 625, 260));
    jPanel22.setLayout(null);
    jPanel22.setBorder(BorderFactory.createTitledBorder("Domicilio Fiscal del Titular"));
    escaleralbl2.setText("Escalera:");
    escaleralbl2.setBounds(new Rectangle(5, 165, 70, 35));
    txtescaleratitular.setText("AA");
    txtescaleratitular.setBounds(new Rectangle(70, 170, 40, 20));
    plantaconslbl2.setText("Planta:");
    plantaconslbl2.setBounds(new Rectangle(125, 165, 70, 35));
    txtplantatitular.setText("4444");
    txtplantatitular.setBounds(new Rectangle(180, 170, 35, 20));
    puertaconslbl2.setText("Puerta:");
    puertaconslbl2.setBounds(new Rectangle(240, 165, 70, 35));
    txtpuertatitular.setText("AAA");
    txtpuertatitular.setBounds(new Rectangle(305, 170, 40, 20));
    txtdirnoestructitular.setText("PPPPPPPPPPPPPPPPPPPPPPP25");
    txtdirnoestructitular.setBounds(new Rectangle(410, 140, 205, 20));
    kmparlbl3.setText("Kilómetro:");
    kmparlbl3.setBounds(new Rectangle(100, 135, 110, 35));
    bloqueparlbl4.setText("Bloque:");
    bloqueparlbl4.setBounds(new Rectangle(5, 135, 60, 35));
    txtbloquetitular.setText("4444");
    txtbloquetitular.setBounds(new Rectangle(55, 140, 35, 20));
    txtkilometrotitular.setText("A");
    txtkilometrotitular.setBounds(new Rectangle(165, 140, 80, 20));
    dirnoestrucparlbl3.setText("Direccion No Estructurada:");
    dirnoestrucparlbl3.setBounds(new Rectangle(255, 135, 170, 35));
    letra2parlbl3.setText("Segunda Letra:");
    letra2parlbl3.setBounds(new Rectangle(475, 100, 95, 35));
    numero2parlbl6.setText("Segundo Número:");
    numero2parlbl6.setBounds(new Rectangle(290, 100, 125, 35));
    txtnumero2titular.setText("4444");
    txtnumero2titular.setBounds(new Rectangle(405, 105, 35, 20));
    txtletra2titular.setText("A");
    txtletra2titular.setBounds(new Rectangle(565, 105, 25, 20));
    letra1parlbl3.setText("Primera Letra:");
    letra1parlbl3.setBounds(new Rectangle(155, 100, 95, 35));
    txtletra1titular.setText("A");
    txtletra1titular.setBounds(new Rectangle(245, 105, 25, 20));
    numero1cargolbl1.setText("Primer Número:");
    numero1cargolbl1.setBounds(new Rectangle(5, 100, 100, 35));
    txtnumero1titular.setText("4444");
    txtnumero1titular.setBounds(new Rectangle(100, 105, 35, 20));
    codigopostalcargolbl1.setText("Código Postal:");
    codigopostalcargolbl1.setBounds(new Rectangle(330, 70, 90, 35));
    txtcodigopostaltitular.setText("09001");
    txtcodigopostaltitular.setBounds(new Rectangle(425, 75, 50, 20));
    nombreviacargolbl1.setText("Nombre Vía:");
    nombreviacargolbl1.setBounds(new Rectangle(5, 70, 115, 35));
    txtnombreviatitular.setText("PPPPPPPPPPPPPPPPPPPPPPP25");
    txtnombreviatitular.setBounds(new Rectangle(90, 75, 230, 20));
    tipoviacargolbl3.setText("Tipo de Vía:");
    tipoviacargolbl3.setBounds(new Rectangle(420, 40, 100, 35));
    txttipoviatitular.setText("PPPP5");
    txttipoviatitular.setBounds(new Rectangle(510, 45, 45, 20));
    viapublicacargolbl1.setText("Código Vía Pública:");
    viapublicacargolbl1.setBounds(new Rectangle(200, 35, 135, 40));
    txtcodviatitular.setText("55555");
    txtcodviatitular.setBounds(new Rectangle(345, 45, 50, 20));
    txtmunicipiotitular.setText("PP");
    txtmunicipiotitular.setBounds(new Rectangle(140, 45, 45, 20));
    entmenorcargolbl1.setText("Código Municipio INE:");
    entmenorcargolbl1.setBounds(new Rectangle(5, 35, 145, 40));
    jPanel111.setBounds(new Rectangle(5, 100, 625, 120));
    jPanel111.setLayout(null);
    jPanel111.setBorder(BorderFactory.createTitledBorder("Identificación del Titular"));
    cmbpersonalidadtitular.setBounds(new Rectangle(430, 25, 155, 20));
    fondosubparlbl1.setText("Complemento Nombre:");
    fondosubparlbl1.setBounds(new Rectangle(5, 80, 165, 35));
    txtcomplementotitular.setText("333");
    txtcomplementotitular.setBounds(new Rectangle(150, 85, 40, 20));
    txtcomplementotitular.setSize(new Dimension(290, 20));
    superficiesubparlbl1.setText("Nombre y Apellidos:");
    superficiesubparlbl1.setBounds(new Rectangle(5, 50, 140, 35));
    txtnombretitular.setText("77777.77");
    txtnombretitular.setBounds(new Rectangle(135, 55, 470, 20));
    txtnombretitular.setSize(new Dimension(565, 20));
    personalidadtitularlbl.setText("Personalidad:");
    personalidadtitularlbl.setBounds(new Rectangle(330, 15, 95, 40));
    txtniftitular.setText("55555");
    txtniftitular.setBounds(new Rectangle(85, 25, 145, 20));
    niftitularlbl.setText("NIF Titular:");
    niftitularlbl.setBounds(new Rectangle(5, 15, 80, 40));
    txtcontrolniftitular.setText("A");
    txtcontrolniftitular.setBounds(new Rectangle(240, 25, 25, 20));
    txttitularcomponentes.setText("4444");
    txttitularcomponentes.setBounds(new Rectangle(560, 85, 45, 20));
    tipoviacargolbl4.setText("Nº componentes:");
    tipoviacargolbl4.setBounds(new Rectangle(450, 80, 115, 35));
    txtprovinciainetitular.setText("22");
    txtprovinciainetitular.setBounds(new Rectangle(550, 15, 45, 20));
    tipoviacargolbl5.setText("Código Provincia INE:");
    tipoviacargolbl5.setBounds(new Rectangle(420, 10, 125, 35));
    txtmunicipiodgctitular.setText("333");
    txtmunicipiodgctitular.setBounds(new Rectangle(345, 15, 50, 20));
    viapublicacargolbl2.setText("Código Municipio DGC:");
    viapublicacargolbl2.setBounds(new Rectangle(200, 5, 135, 40));
    txtdelegaciontitular.setText("22");
    txtdelegaciontitular.setBounds(new Rectangle(140, 15, 45, 20));
    entmenorcargolbl2.setText("Código Delegación MEH:");
    entmenorcargolbl2.setBounds(new Rectangle(5, 5, 145, 40));
    txtapartadocorreostitular.setText("09001");
    txtapartadocorreostitular.setBounds(new Rectangle(495, 170, 50, 20));
    apartadocorreostitularlbl.setText("Apartado Correos:");
    apartadocorreostitularlbl.setBounds(new Rectangle(355, 165, 135, 35));
    txtpaistitular.setText("PPPPPPPPPPPPPPPPPPPPPPP25");
    txtpaistitular.setBounds(new Rectangle(85, 205, 205, 20));
    txtpaistitular.setSize(new Dimension(210, 20));
    nombrepaistitulartxt.setText("Nombre País:");
    nombrepaistitulartxt.setBounds(new Rectangle(5, 198, 115, 35));
    txtnombreprovinciatitular.setText("PPPPPPPPPPPPPPPPPPPPPPP25");
    txtnombreprovinciatitular.setBounds(new Rectangle(410, 205, 210, 20));
    txtnombreprovinciatitular.setSize(new Dimension(210, 20));
    nombrepaistitulartxt1.setText("Nombre Provincia:");
    nombrepaistitulartxt1.setBounds(new Rectangle(305, 198, 115, 35));
    txtnombremunicipiotitular.setText("PPPPPPPPPPPPPPPPPPPPPPP25");
    txtnombremunicipiotitular.setBounds(new Rectangle(115, 235, 195, 20));
    txtnombremunicipiotitular.setSize(new Dimension(210, 20));
    nombrepaistitulartxt2.setText("Nombre Municipio:");
    nombrepaistitulartxt2.setBounds(new Rectangle(5, 230, 115, 35));
    txtrefpar.setText("7777777");
    txtrefpar.setBounds(new Rectangle(150, 10, 85, 20));
    referencialbl.setText("Referencia Catastral:");
    referencialbl.setBounds(new Rectangle(5, 0, 145, 40));
    txtrefpla.setText("AAAAAA7");
    txtrefpla.setBounds(new Rectangle(245, 10, 85, 20));
    txtmunicipio.setText("7777777");
    txtmunicipio.setBounds(new Rectangle(405, 10, 170, 20));
    municipiolbl.setText("Municipio:");
    municipiolbl.setBounds(new Rectangle(340, 5, 90, 40));
    btneditsubpar.setText("Edición");
//    editsubparbtn.setIcon(Edit);
    btneditsubpar.setBounds(new Rectangle(155, 40, 78, 20));
    btnaddsubpar.setText("Alta");
//    addsubparbtn.setIcon(Add);
    btnaddsubpar.setBounds(new Rectangle(155, 20, 78, 20));
   
    btndelsubpar.setText("Baja");
//    delsubparbtn.setIcon(Del);
    btndelsubpar.setBounds(new Rectangle(155, 60, 78, 20));
    btndeluc.setText("Baja");
    btndeluc.setBounds(new Rectangle(155, 60, 78, 20));
    btnedituc.setText("Edición");
    btnedituc.setBounds(new Rectangle(155, 40, 78, 20));
    btnadduc.setText("Alta");
    btnadduc.setBounds(new Rectangle(155, 20, 78, 20));
    btndelcons.setText("Baja");
    btndelcons.setBounds(new Rectangle(155, 60, 78, 20));
    btneditcons.setText("Edición");
    btneditcons.setBounds(new Rectangle(155, 40, 78, 20));
    btnaddcons.setText("Alta");
    btnaddcons.setBounds(new Rectangle(155, 20, 78, 20));
    btndelcargo.setText("Baja");
    btndelcargo.setBounds(new Rectangle(120, 60, 78, 20));
    btneditcargo.setText("Edición");
    btneditcargo.setBounds(new Rectangle(120, 40, 78, 20));
    btnaddcargo.setText("Alta");
    btnaddcargo.setBounds(new Rectangle(120, 20, 78, 20));
    cmbtipofachadasubpar.addItem("FA");
    cmbtipofachadasubpar.addItem("FD");
    cmbtipofachadasubpar.addItem("DR");
    cmbtipofachadasubpar.addItem("IZ");
    cmbtipofachadasubpar.addItem("SI");

    jTabbedPane1.setBounds(new Rectangle(5, 40, 650, 620));
    cmbtipovalorsubpar.addItem("0");
    cmbtipovalorsubpar.addItem("1");
    cmbtipovalorsubpar.addItem("2");
    cmbtipovalorsubpar.addItem("3");
    cmbtipovalorsubpar.addItem("4");
    cmbtipovalorsubpar.addItem("5");
    cmbtipovalorsubpar.addItem("6");
    cmbtipovalorsubpar.addItem("7");
    cmbtipovalorsubpar.addItem("8");
    cmbtipovalorsubpar.addItem("9");
    cmbpavimentacionsubpar.addItem("FA");
    cmbpavimentacionsubpar.addItem("FD");
    cmbpavimentacionsubpar.addItem("DR");
    cmbpavimentacionsubpar.addItem("IZ");
    cmbpavimentacionsubpar.addItem("SI");
    cmbalcantarilladosubpar.addItem("N");
    cmbalcantarilladosubpar.addItem("0");
    cmbalcantarilladosubpar.addItem("1");
    cmbalcantarilladosubpar.addItem("1");
    cmbdesmontesubpar.addItem("N");
    cmbdesmontesubpar.addItem("0");
    cmbdesmontesubpar.addItem("1");
    cmbalumbradosubpar.addItem("N");
    cmbalumbradosubpar.addItem("0");
    cmbalumbradosubpar.addItem("1");
    cmbelectricidadsubpar.addItem("N");
    cmbelectricidadsubpar.addItem("0");
    cmbelectricidadsubpar.addItem("1");
    cmbaguasubpar.addItem("N");
    cmbaguasubpar.addItem("0");
    cmbaguasubpar.addItem("1");
    cmbexactitudannouc.addItem("E");
    cmbexactitudannouc.addItem("+");
    cmbexactitudannouc.addItem("-");
    cmbexactitudannouc.addItem("C");
    cmbreformacons.addItem("R");
    cmbreformacons.addItem("E");
    cmbreformacons.addItem("O");
    cmbreformacons.addItem("I");
    cmbreformacons.addItem(" ");
    cmbreparto1cons.addItem("T - A todos");
    cmbreparto1cons.addItem("A - A alguno");
    cmbreparto2cons.addItem("L - A locales");
    cmbreparto2cons.addItem("C - A cargos");
    cmbreparto3cons.addItem("1 - Por partes");
    cmbreparto3cons.addItem("2 - Por superficie de los locales");
    cmbreparto3cons.addItem("3 - Por coeficiente de propiedad");
    cmbreparto3cons.addItem("4 - Por coeficiente específicamente determinado");
    cmbtipovalorcons.addItem("0");
    cmbtipovalorcons.addItem("1");
    cmbtipovalorcons.addItem("2");
    cmbtipovalorcons.addItem("3");
    cmbtipovalorcons.addItem("4");
    cmbtipovalorcons.addItem("5");
    cmbtipovalorcons.addItem("6");
    cmbtipovalorcons.addItem("7");
    cmbtipovalorcons.addItem("8");
    cmbtipovalorcons.addItem("9");
    cmbtipovalorcons.addItem("N");
    cmbtipopropiedadcargo.addItem("T - Sobre Todo");
    cmbtipopropiedadcargo.addItem("S - Sobre Suelo");
    cmbtipopropiedadcargo.addItem("C - Sobre Construcción");
    cmbtipopropiedadcargo.addItem("V - Sobre Vuelo");
    cmbtipopropiedadcargo.addItem("I - Sobre Inmueble");
    cmbtipopropiedadcargo.addItem("N - No informado");            
    jPanel111.add(tipoviacargolbl4, null);
    jPanel111.add(txttitularcomponentes, null);
    jPanel111.add(txtcontrolniftitular, null);
    jPanel111.add(cmbpersonalidadtitular, null);
    jPanel111.add(fondosubparlbl1, null);
    jPanel111.add(txtcomplementotitular, null);
    jPanel111.add(superficiesubparlbl1, null);
    jPanel111.add(txtnombretitular, null);
    jPanel111.add(personalidadtitularlbl, null);
    jPanel111.add(txtniftitular, null);
    jPanel111.add(niftitularlbl, null);
    cmbpersonalidadtitular.addItem("F - Física");
    cmbpersonalidadtitular.addItem("J - Jurídica");
    cmbpersonalidadtitular.addItem("E - Entidades");
    cargopanel1.add(jPanel111, null);
    cargopanel1.add(jPanel113, null);
    cargopanel1.add(jPanel22, null);
    jPanel113.add(txtcontrol2titular, null);
    jPanel113.add(controlcargolbl1, null);
    jPanel113.add(txtcontrol1itular, null);
    jPanel113.add(lsttitular, null);
    jPanel113.add(cargocargolbl1, null);
    jPanel113.add(txtcargotitular, null);
    jPanel22.add(nombrepaistitulartxt2, null);
    jPanel22.add(txtnombremunicipiotitular, null);
    jPanel22.add(nombrepaistitulartxt1, null);
    jPanel22.add(txtnombreprovinciatitular, null);
    jPanel22.add(nombrepaistitulartxt, null);
    jPanel22.add(txtpaistitular, null);
    jPanel22.add(apartadocorreostitularlbl, null);
    jPanel22.add(txtapartadocorreostitular, null);
    jPanel22.add(entmenorcargolbl2, null);
    jPanel22.add(txtdelegaciontitular, null);
    jPanel22.add(viapublicacargolbl2, null);
    jPanel22.add(txtmunicipiodgctitular, null);
    jPanel22.add(tipoviacargolbl5, null);
    jPanel22.add(txtprovinciainetitular, null);
    jPanel22.add(escaleralbl2, null);
    jPanel22.add(txtescaleratitular, null);
    jPanel22.add(plantaconslbl2, null);
    jPanel22.add(txtplantatitular, null);
    jPanel22.add(puertaconslbl2, null);
    jPanel22.add(txtpuertatitular, null);
    jPanel22.add(txtdirnoestructitular, null);
    jPanel22.add(kmparlbl3, null);
    jPanel22.add(bloqueparlbl4, null);
    jPanel22.add(txtbloquetitular, null);
    jPanel22.add(txtkilometrotitular, null);
    jPanel22.add(dirnoestrucparlbl3, null);
    jPanel22.add(letra2parlbl3, null);
    jPanel22.add(numero2parlbl6, null);
    jPanel22.add(txtnumero2titular, null);
    jPanel22.add(txtletra2titular, null);
    jPanel22.add(letra1parlbl3, null);
    jPanel22.add(txtletra1titular, null);
    jPanel22.add(numero1cargolbl1, null);
    jPanel22.add(txtnumero1titular, null);
    jPanel22.add(codigopostalcargolbl1, null);
    jPanel22.add(txtcodigopostaltitular, null);
    jPanel22.add(nombreviacargolbl1, null);
    jPanel22.add(txtnombreviatitular, null);
    jPanel22.add(tipoviacargolbl3, null);
    jPanel22.add(txttipoviatitular, null);
    jPanel22.add(viapublicacargolbl1, null);
    jPanel22.add(txtcodviatitular, null);
    jPanel22.add(txtmunicipiotitular, null);
    jPanel22.add(entmenorcargolbl1, null);
    jPanel20.add(cmbtipopropiedadcargo, null);
    jPanel20.add(supcubiertaparlbl8, null);
    jPanel20.add(chkpreciocargo, null);
    jPanel20.add(supsolarlbl4, null);
    jPanel20.add(txtannofinvalorcargo, null);
    jPanel20.add(supsolarlbl3, null);
    jPanel20.add(txtsupconstruccioncargo, null);
    jPanel20.add(supconsparlbl5, null);
    jPanel20.add(txtsupsuelocargo, null);
    jPanel20.add(supcubiertaparlbl7, null);
    jPanel20.add(txtcoeficientepropcargo, null);
    jPanel20.add(txtnotificacioncargo, null);
    jPanel20.add(tipoviacargolbl1, null);
    jPanel20.add(txtclaveusocargo, null);
    jPanel20.add(valorconstruccioncargolbl, null);
    jPanel20.add(txtvalorconstruccioncargo, null);
    jPanel20.add(supconsparlbl4, null);
    jPanel20.add(txtbaseliquidablecargo, null);
    jPanel20.add(supconsparlbl3, null);
    jPanel20.add(txtvalorsuelocargo, null);
    jPanel20.add(numero2parlbl4, null);
    jPanel20.add(formacalculoparlbl1, null);
    jPanel20.add(txtannonotificacion, null);
    jPanel20.add(aprobacionparlbl1, null);
    jPanel20.add(txtannorevision, null);
    jPanel20.add(supconsparlbl2, null);
    jPanel20.add(txtvalorcatastralcargo, null);
    jPanel20.add(txtannovalorcargo, null);
    jPanel20.add(supsolarlbl2, null);
    jPanel112.add(btnaddcargo, null);
    jPanel112.add(btneditcargo, null);
    jPanel112.add(btndelcargo, null);
    jPanel112.add(distritocargolbl, null);
    jPanel112.add(txtdistritocargo, null);
    jPanel112.add(controlfijocargolbl, null);
    jPanel112.add(txtcontrolfijocargo, null);
    jPanel112.add(txtcontrol2cargo, null);
    jPanel112.add(controlcargolbl, null);
    jPanel112.add(control1cargotxt, null);
    jPanel112.add(participacioncargolbl, null);
    jPanel112.add(txtparticipacioncargo, null);
    jPanel112.add(fijocargolbl, null);
    jPanel112.add(txtfijocargo, null);
    jPanel112.add(lstcargo, null);
    jPanel112.add(cargocargolbl, null);
    jPanel112.add(txcargo, null);
    cargopanel.add(jPanel20, null);
    cargopanel.add(jPanel112, null);
    cargopanel.add(jPanel110, null);
    cargopanel.add(jPanel6, null);
    jPanel110.add(supcubiertaparlbl6, null);
    jPanel110.add(txtrefexpcargo, null);
    jPanel110.add(annoexpparlbl4, null);
    jPanel110.add(txtannoexpcargo, null);
    jPanel6.add(escaleralbl1, null);
    jPanel6.add(txtescaleracargo, null);
    jPanel6.add(plantaconslbl1, null);
    jPanel6.add(txtplantacargo, null);
    jPanel6.add(puertaconslbl1, null);
    jPanel6.add(txtpuertacargo, null);
    jPanel6.add(txtdirnoestruccargo, null);
    jPanel6.add(kmparlbl2, null);
    jPanel6.add(bloqueparlbl3, null);
    jPanel6.add(txtbloquecargo, null);
    jPanel6.add(txtkilometrocargo, null);
    jPanel6.add(dirnoestrucparlbl2, null);
    jPanel6.add(letra2parlbl2, null);
    jPanel6.add(numero2parlbl3, null);
    jPanel6.add(txtnumero2cargo, null);
    jPanel6.add(txtletra2cargo, null);
    jPanel6.add(letra1parlbl2, null);
    jPanel6.add(txtletra1cargo, null);
    jPanel6.add(numero1cargolbl, null);
    jPanel6.add(txtnumero1cargo, null);
    jPanel6.add(codigopostalcargolbl, null);
    jPanel6.add(txtcodigopostalcargo, null);
    jPanel6.add(nombreviacargolbl, null);
    jPanel6.add(txtnombreviacargo, null);
    jPanel6.add(tipoviacargolbl, null);
    jPanel6.add(txttipoviacargo, null);
    jPanel6.add(viapublicacargolbl, null);
    jPanel6.add(txtcodviacargo, null);
    jPanel6.add(txtentmenorcargo, null);
    jPanel6.add(entmenorcargolbl, null);
    jPanel19.add(referenciaconslbl, null);
    jPanel19.add(txtreferenciacons, null);
    jPanel19.add(annoexpconslbl, null);
    jPanel19.add(txtannoexpcons, null);
    jPanel17.add(tipovalorconslbl, null);
    jPanel17.add(cmbtipovalorcons, null);
    jPanel17.add(cmbreparto3cons, null);
    jPanel17.add(cmbreparto2cons, null);
    jPanel17.add(tipoviaparlbl4, null);
    jPanel17.add(cmbreparto1cons, null);
    jPanel17.add(categoriaconslbl, null);
    jPanel17.add(txtcategoriacons, null);
    jPanel17.add(txtapreciacioncons, null);
    jPanel17.add(apreciacionconslbl, null);
    jPanel17.add(coef1lbl4, null);
    jPanel17.add(chkviviendacons, null);
    jPanel17.add(cmbusocons, null);
    jPanel17.add(TIPOLOGIACONSLBL, null);
    jPanel17.add(txttipologiacons, null);
    jPanel17.add(tipoviaparlbl3, null);
    cmbusocons.addItem("V - Vivienda");
    jPanel18.add(btnaddcons, null);
    jPanel18.add(btneditcons, null);
    jPanel18.add(btndelcons, null);
    jPanel18.add(ucconslbl, null);
    jPanel18.add(txtuccons, null);
    jPanel18.add(cargoconslbl, null);
    jPanel18.add(txtcargocons, null);
    jPanel18.add(lstcons, null);
    jPanel18.add(ordenconslbl, null);
    jPanel18.add(txtordencons, null);
    construccionespanel.add(jPanel19, null);
    construccionespanel.add(jPanel17, null);
    construccionespanel.add(jPanel18, null);
    construccionespanel.add(jPanel7, null);
    construccionespanel.add(jPanel8, null);
    jPanel7.add(chklocalcons, null);
    jPanel7.add(destinoconslbl, null);
    jPanel7.add(txtdestinocons, null);
    jPanel7.add(annoreformalbl, null);
    jPanel7.add(txtannoreforma, null);
    jPanel7.add(reformaconslbl, null);
    jPanel7.add(cmbreformacons, null);
    jPanel7.add(supcubiertaparlbl3, null);
    jPanel7.add(txtsupimputablecons, null);
    jPanel7.add(supconsparlbl1, null);
    jPanel7.add(txtsupterrazascons, null);
    jPanel7.add(txtsuptotalcon, null);
    jPanel7.add(supsolarlbl1, null);
    jPanel8.add(txtpuertacons, null);
    jPanel8.add(puertaconslbl, null);
    jPanel8.add(txtplantacons, null);
    jPanel8.add(plantaconslbl, null);
    jPanel8.add(escaleralbl, null);
    jPanel8.add(bloqueparlbl2, null);
    jPanel8.add(txtbloquecons, null);
    jPanel8.add(txtescaleracons, null);
    jPanel13.add(supcubiertaparlbl5, null);
    jPanel13.add(txtrefexpuc, null);
    jPanel13.add(annoexpparlbl3, null);
    jPanel13.add(txtannoexpuc, null);
    jPanel14.add(cmbusoagrariouc, null);
    jPanel14.add(annoconstuclbl, null);
    jPanel14.add(txtannoconsuc, null);
    jPanel14.add(usoagrariouclbl, null);
    jPanel14.add(txtlongfachadauc, null);
    jPanel14.add(longfachadasubparlbl1, null);
    cmbusoagrariouc.addItem("Si");
    cmbusoagrariouc.addItem("No");
    jPanel5.add(txtdirnoestrucuc, null);
    jPanel5.add(kmparlbl1, null);
    jPanel5.add(bloqueparlbl1, null);
    jPanel5.add(txtbloqueuc, null);
    jPanel5.add(txtkilometrouc, null);
    jPanel5.add(dirnoestrucparlbl1, null);
    jPanel5.add(letra2parlbl1, null);
    jPanel5.add(numero2parlbl2, null);
    jPanel5.add(txtnumero2uc, null);
    jPanel5.add(txtletra2uc, null);
    jPanel5.add(letra1parlbl1, null);
    jPanel5.add(txtletra1uc, null);
    jPanel5.add(numero1parlbl1, null);
    jPanel5.add(txtnumero1uc, null);
    jPanel5.add(codigopostaluclbl, null);
    jPanel5.add(txtcodigopostaluc, null);
    jPanel5.add(nombreviauclbl, null);
    jPanel5.add(txtnombreviauc, null);
    jPanel5.add(tipoviauclbl, null);
    jPanel5.add(txttipoviauc, null);
    jPanel5.add(viapublicauclbl, null);
    jPanel5.add(txtcodviauc, null);
    jPanel5.add(txtentmenoruc, null);
    jPanel5.add(entmenoruclbl, null);
    unidadconstructivapanel.add(jPanel13, null);
    unidadconstructivapanel.add(jPanel14, null);
    unidadconstructivapanel.add(jPanel5, null);
    unidadconstructivapanel.add(jPanel15, null);
    unidadconstructivapanel.add(jPanel16, null);
    jPanel15.add(btnadduc, null);
    jPanel15.add(btnedituc, null);
    jPanel15.add(btndeluc, null);
    jPanel15.add(lstuc, null);
    jPanel15.add(ordenuclbl, null);
    jPanel15.add(txtordenuc, null);
    jPanel16.add(cmbexactitudannouc, null);
    jPanel16.add(exactannouclbl, null);
    jPanel16.add(alumbradosubparlb1, null);
    jPanel16.add(cmbalumbradouc, null);
    jPanel16.add(desmontesubparlb1, null);
    jPanel16.add(cmbdesmonteuc, null);
    jPanel16.add(alcantarilladosubparlb1, null);
    jPanel16.add(cmbalcantarilladouc, null);
    jPanel16.add(pavimentacionsubparlbl1, null);
    jPanel16.add(cmbpavimentacionuc, null);
    jPanel16.add(txtapreciacionuc, null);
    jPanel16.add(apreciacionlbl1, null);
    jPanel16.add(chkcargasuc, null);
    jPanel16.add(chkespecialuc, null);
    jPanel16.add(chknolucrativouc, null);
    jPanel16.add(chkconservacionuc, null);
    jPanel16.add(chklongfachadauc, null);
    jPanel16.add(chknumfachadauc, null);
    jPanel16.add(entmenorprlbl3, null);
    jPanel16.add(txtcodviaDGCuc, null);
    jPanel16.add(tipoviaparlbl2, null);
    jPanel16.add(txttramoviauc, null);
    jPanel16.add(coef1lbl5, null);
    jPanel16.add(cmbelectricidaduc, null);
    jPanel16.add(Electricidadsubparlb1, null);
    jPanel16.add(cmbaguauc, null);
    jPanel16.add(aguasubparlb6, null);
    cmbalumbradouc.addItem("N");
    cmbalumbradouc.addItem("0");
    cmbalumbradouc.addItem("1");
    cmbdesmonteuc.addItem("N");
    cmbdesmonteuc.addItem("0");
    cmbdesmonteuc.addItem("1");
    cmbalcantarilladouc.addItem("N");
    cmbalcantarilladouc.addItem("0");
    cmbalcantarilladouc.addItem("1");
    cmbpavimentacionuc.addItem("N");
    cmbpavimentacionuc.addItem("0");
    cmbpavimentacionuc.addItem("1");
    cmbelectricidaduc.addItem("N");
    cmbelectricidaduc.addItem("0");
    cmbelectricidaduc.addItem("1");
    cmbaguauc.addItem("N");
    cmbaguauc.addItem("0");
    cmbaguauc.addItem("1");
    subparcelapanel.add(jPanel9, null);
    subparcelapanel.add(jPanel10, null);
    subparcelapanel.add(jPanel11, null);
    subparcelapanel.add(jPanel12, null);
    jPanel9.add(supcubiertaparlbl4, null);
    jPanel9.add(txtrefexpsubpar, null);
    jPanel9.add(annoexpparlbl2, null);
    jPanel9.add(txtannoexpsubpar, null);
    jPanel10.add(cmbtipofachadasubpar, null);
    jPanel10.add(fondosubparlbl, null);
    jPanel10.add(txtfondosubpar, null);
    jPanel10.add(superficiesubparlbl, null);
    jPanel10.add(txtsuperficiesubpar, null);
    jPanel10.add(tipofachadasubparlbl, null);
    jPanel10.add(txtlongfachadasubpar, null);
    jPanel10.add(longfachadasubparlbl, null);
    jPanel11.add(btndelsubpar, null);
    jPanel11.add(btnaddsubpar, null);
    jPanel11.add(btneditsubpar, null);
    jPanel11.add(lstsubparcela, null);
    jPanel11.add(ordensubparlbl, null);
    jPanel11.add(txtordensubpar, null);
    jPanel12.add(alumbradosubparlb, null);
    jPanel12.add(cmbalumbradosubpar, null);
    jPanel12.add(desmontesubparlb, null);
    jPanel12.add(cmbdesmontesubpar, null);
    jPanel12.add(alcantarilladosubparlb, null);
    jPanel12.add(cmbalcantarilladosubpar, null);
    jPanel12.add(pavimentacionsubparlbl, null);
    jPanel12.add(cmbpavimentacionsubpar, null);
    jPanel12.add(coef1lbl2, null);
    jPanel12.add(txtapreciacionsubpar, null);
    jPanel12.add(apreciacionlbl, null);
    jPanel12.add(coef1lbl1, null);
    jPanel12.add(chkcargassubpar, null);
    jPanel12.add(chkespecialsubpar, null);
    jPanel12.add(chkdepreciacionsubpar, null);
    jPanel12.add(chknolucrativosubpar, null);
    jPanel12.add(chkfondosubpar, null);
    jPanel12.add(chksuperficiesubpar, null);
    jPanel12.add(chkinedificabilidadsubpar, null);
    jPanel12.add(chkvposubpar, null);
    jPanel12.add(chkprofundidadsubpar, null);
    jPanel12.add(chkdesmontesubpar, null);
    jPanel12.add(chkirregularsubpar, null);
    jPanel12.add(chklongfachadasubpar, null);
    jPanel12.add(chknumfachadasubpar, null);
    jPanel12.add(tipovalorsubparlbl, null);
    jPanel12.add(cmbtipovalorsubpar, null);
    jPanel12.add(entmenorprlbl2, null);
    jPanel12.add(txtcodviasubpar, null);
    jPanel12.add(tipoviaparlbl1, null);
    jPanel12.add(txttramoviasubpar, null);
    jPanel12.add(coef1lbl, null);
    jPanel12.add(cmbelectricidadsubpar, null);
    jPanel12.add(Electricidadsubparlb, null);
    jPanel12.add(cmbaguasubpar, null);
    jPanel12.add(aguasubparlb5, null);
    jPanel4.add(supcubiertaparlbl1, null);
    jPanel4.add(txtrefexp, null);
    jPanel4.add(annoexpparlbl, null);
    jPanel4.add(txtannoexppar, null);
    jPanel3.add(txtalterpar, null);
    jPanel3.add(alterparlbl, null);
    jPanel3.add(txtinfocarpar, null);
    jPanel3.add(infocarparlbl, null);
    jPanel2.add(cmbmodrepartopar, null);
    jPanel2.add(numero2parlbl1, null);
    jPanel2.add(formacalculoparlbl, null);
    jPanel2.add(txtformacalculopar, null);
    jPanel2.add(aprobacionparlbl, null);
    jPanel2.add(txtaprobacionpar, null);
    jPanel2.add(codigopostalparlbl1, null);
    jPanel2.add(txtsupBRpar, null);
    jPanel2.add(supSRparlbl, null);
    jPanel2.add(txtsupSRpar, null);
    jPanel2.add(supcubiertaparlbl, null);
    jPanel2.add(txtsupcubiertapar, null);
    jPanel2.add(supconsparlbl, null);
    jPanel2.add(txtsuptotalcos, null);
    jPanel2.add(txtsupsolar, null);
    jPanel2.add(supsolarlbl, null);
    jPanel1.add(txtdirnoestrucpar, null);
    jPanel1.add(kmparlbl, null);
    jPanel1.add(bloqueparlbl, null);
    jPanel1.add(txtbloquepar, null);
    jPanel1.add(txtkilometropar, null);
    jPanel1.add(dirnoestrucparlbl, null);
    jPanel1.add(letra2parlbl, null);
    jPanel1.add(numero2parlbl, null);
    jPanel1.add(txtnumero2par, null);
    jPanel1.add(txtletra2par, null);
    jPanel1.add(letra1parlbl, null);
    jPanel1.add(txtletra1par, null);
    jPanel1.add(numero1parlbl, null);
    jPanel1.add(txtnumero1par, null);
    jPanel1.add(codigopostalparlbl, null);
    jPanel1.add(txtcodigopostalpar, null);
    jPanel1.add(nombreviaparlbl, null);
    jPanel1.add(txtnombreviapar, null);
    jPanel1.add(tipoviaparlbl, null);
    jPanel1.add(txttipovia, null);
    jPanel1.add(entmenorprlbl1, null);
    jPanel1.add(txtcodviapar, null);
    jPanel1.add(txtentmenorpar, null);
    jPanel1.add(entmenorprlbl, null);
//    Datostb.add("Parcela", parceltb);
   

    parcelapanel.add(jPanel4, null);
    parcelapanel.add(jPanel2, null);
    parcelapanel.add(jPanel1, null);
    parcelapanel.add(jPanel3, null);
    jTabbedPane1.addTab("Parcela", parcelapanel);
    jTabbedPane1.addTab("Subparcela", subparcelapanel);
    jTabbedPane1.addTab("Unidad Constructiva", unidadconstructivapanel);
    jTabbedPane1.addTab("Construcciones", construccionespanel);
    jTabbedPane1.addTab("Cargo/Unidad Fiscal", cargopanel);
    jTabbedPane1.addTab("Titular", cargopanel1);
    this.add(municipiolbl, null);
    this.add(txtmunicipio, null);
    this.add(txtrefpla, null);
    this.add(referencialbl, null);
    this.add(txtrefpar, null);
    this.add(btncancelar, null);
    this.add(btnaceptar, null);
    this.add(jTabbedPane1, null);
  }

  
}