/**
 * AnexoFeatureDAO.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.geopista.app.cementerios.business.dao.interfaces;

import java.sql.SQLException;
import java.util.List;

import com.geopista.app.cementerios.business.vo.AnexoFeatureExample;
import com.geopista.app.cementerios.business.vo.AnexoFeatureKey;

public interface AnexoFeatureDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.anexo_feature
	 * @throws SQLException 
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	int deleteByExample(AnexoFeatureExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.anexo_feature
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	int deleteByPrimaryKey(AnexoFeatureKey key) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.anexo_feature
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	void insert(AnexoFeatureKey record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.anexo_feature
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	void insertSelective(AnexoFeatureKey record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.anexo_feature
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	List selectByExample(AnexoFeatureExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.anexo_feature
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	int updateByExampleSelective(AnexoFeatureKey record,
			AnexoFeatureExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.anexo_feature
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	int updateByExample(AnexoFeatureKey record, AnexoFeatureExample example) throws SQLException;
}