/**
 * DocumentoDAO.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.geopista.app.cementerios.business.dao.interfaces;

import java.sql.SQLException;
import java.util.List;
import java.util.Map;

import com.geopista.app.cementerios.business.vo.Documento;
import com.geopista.app.cementerios.business.vo.DocumentoExample;

public interface DocumentoDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.documento
	 * @throws SQLException 
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	int deleteByPrimaryKey(String idDocumento) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.documento
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	String insert(Documento record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.documento
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	String insertSelective(Documento record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.documento
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	List selectByExampleWithBLOBs(DocumentoExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.documento
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	List selectByExampleWithoutBLOBs(DocumentoExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.documento
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	Documento selectByPrimaryKey(String idDocumento) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.documento
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	int updateByPrimaryKeySelective(Documento record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.documento
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	int updateByPrimaryKeyWithBLOBs(Documento record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.documento
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	int updateByPrimaryKeyWithoutBLOBs(Documento record) throws SQLException;

	List selectAll() throws SQLException;
	
	List selectAttached(Map map) throws SQLException;
	
	List selectAttachedCementerio (Integer idElemCementerio, String superpatron, String patron) throws SQLException;
	
	String selectByLastSeqKey() throws SQLException;
	
	
}