/**
 * ElemFeatureDAO.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.geopista.app.cementerios.business.dao.interfaces;

import java.sql.SQLException;
import java.util.List;

import com.geopista.app.cementerios.business.vo.ElemFeature;
import com.geopista.app.cementerios.business.vo.ElemFeatureExample;

public interface ElemFeatureDAO {
    /**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.elem_feature
     * @throws SQLException 
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	int deleteByExample(ElemFeatureExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.elem_feature
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.elem_feature
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	Integer insert(ElemFeature record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.elem_feature
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	Integer insertSelective(ElemFeature record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.elem_feature
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	List selectByExample(ElemFeatureExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.elem_feature
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	ElemFeature selectByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.elem_feature
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	int updateByExampleSelective(ElemFeature record, ElemFeatureExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.elem_feature
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	int updateByExample(ElemFeature record, ElemFeatureExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.elem_feature
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	int updateByPrimaryKeySelective(ElemFeature record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.elem_feature
	 * @ibatorgenerated  Wed Jun 22 13:25:56 CEST 2011
	 */
	int updateByPrimaryKey(ElemFeature record) throws SQLException;

	int selectByLastSeqKey() throws SQLException;
	
	List selectAll() throws SQLException;
	
	ElemFeature selectByElemAndCementerio (Integer idElem, Integer idCementerio) throws SQLException;
	
	ElemFeature selectByElemCementerioLayerAndFeature (Integer idElem, Integer idCementerio, String idLayer, String idFeature) throws SQLException;

}