/**
 * HistoricoPropiedadDAO.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.geopista.app.cementerios.business.dao.interfaces;

import java.sql.SQLException;
import java.util.List;

import com.geopista.app.cementerios.business.vo.HistoricoPropiedad;
import com.geopista.app.cementerios.business.vo.HistoricoPropiedadExample;

public interface HistoricoPropiedadDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cementerio.historico_propiedad
     * @throws SQLException 
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    int deleteByExample(HistoricoPropiedadExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cementerio.historico_propiedad
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cementerio.historico_propiedad
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    Integer insert(HistoricoPropiedad record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cementerio.historico_propiedad
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    Integer insertSelective(HistoricoPropiedad record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cementerio.historico_propiedad
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    List selectByExample(HistoricoPropiedadExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cementerio.historico_propiedad
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    HistoricoPropiedad selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cementerio.historico_propiedad
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    int updateByExampleSelective(HistoricoPropiedad record, HistoricoPropiedadExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cementerio.historico_propiedad
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    int updateByExample(HistoricoPropiedad record, HistoricoPropiedadExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cementerio.historico_propiedad
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    int updateByPrimaryKeySelective(HistoricoPropiedad record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cementerio.historico_propiedad
     *
     * @ibatorgenerated Wed Jul 06 11:38:06 CEST 2011
     */
    int updateByPrimaryKey(HistoricoPropiedad record) throws SQLException;
    
	List  selectByTitular (String dniTitular) throws SQLException;
}