/**
 * LocalizacionDAO.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.geopista.app.cementerios.business.dao.interfaces;

import java.sql.SQLException;

import com.geopista.app.cementerios.business.vo.Localizacion;

public interface LocalizacionDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.localizacion
	 * @ibatorgenerated  Tue May 03 16:38:46 CEST 2011
	 */
	int deleteByPrimaryKey(Integer id)throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.localizacion
	 * @ibatorgenerated  Tue May 03 16:38:46 CEST 2011
	 */
	Integer insert(Localizacion record)throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.localizacion
	 * @ibatorgenerated  Tue May 03 16:38:46 CEST 2011
	 */
	Integer insertSelective(Localizacion record)throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.localizacion
	 * @ibatorgenerated  Tue May 03 16:38:46 CEST 2011
	 */
	Localizacion selectByPrimaryKey(Integer id)throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.localizacion
	 * @ibatorgenerated  Tue May 03 16:38:46 CEST 2011
	 */
	int updateByPrimaryKeySelective(Localizacion record)throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.localizacion
	 * @ibatorgenerated  Tue May 03 16:38:46 CEST 2011
	 */
	int updateByPrimaryKey(Localizacion record) throws SQLException;

	int selectByLastSeqKey()throws SQLException;
	
//	void setSqlMapClient(SqlMapClient sqlMapper);
}