/**
 * PlazaDAO.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.geopista.app.cementerios.business.dao.interfaces;

import java.sql.SQLException;
import java.util.List;

import com.geopista.app.cementerios.business.vo.Plaza;
import com.geopista.app.cementerios.business.vo.PlazaExample;

public interface PlazaDAO {
    /**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.plaza
	 * @ibatorgenerated  Thu May 19 17:05:05 CEST 2011
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;


	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.plaza
	 * @ibatorgenerated  Thu May 19 17:05:05 CEST 2011
	 */
	Integer insert(Plaza record) throws SQLException;


	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.plaza
	 * @ibatorgenerated  Thu May 19 17:05:05 CEST 2011
	 */
	Integer insertSelective(Plaza record)throws SQLException;


	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.plaza
	 * @ibatorgenerated  Thu May 19 17:05:05 CEST 2011
	 */
	List selectByExample(PlazaExample example) throws SQLException;


	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.plaza
	 * @ibatorgenerated  Thu May 19 17:05:05 CEST 2011
	 */
	Plaza selectByPrimaryKey(Integer id) throws SQLException;


	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.plaza
	 * @ibatorgenerated  Thu May 19 17:05:05 CEST 2011
	 */
	int updateByPrimaryKeySelective(Plaza record) throws SQLException;


	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.plaza
	 * @ibatorgenerated  Thu May 19 17:05:05 CEST 2011
	 */
	int updateByPrimaryKey(Plaza record) throws SQLException;

	/**
	 * This method returns the last id od the sequence insert in the table
	 * @return
	 */
	public int selectByLastSeqKey() throws SQLException;
	
	/**
	 * This method returns the number of plazas that has been asigned to the unit.
	 * @param record
	 * @return
	 */
	public int selectCountPlazasAsignadas(Plaza record) throws SQLException;
	
//	/**
//	 * Set the iBATIS Database Layer SqlMapClient to work with.
//	 * @param sqlMapper
//	 */
//	void setSqlMapClient(SqlMapClient sqlMapper);
	
}