/**
 * EntidadTipoMapDAOImpl.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.localgis.web.core.dao.sqlmap;

import com.ibatis.dao.client.DaoManager;
import com.ibatis.dao.client.template.SqlMapDaoTemplate;
import com.localgis.web.core.dao.EntidadTipoMapDAO;
import com.localgis.web.core.model.EntidadTipoMap;

public class EntidadTipoMapDAOImpl extends SqlMapDaoTemplate implements EntidadTipoMapDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table geowfst.entidad_tipo_map
	 * @ibatorgenerated  Thu Mar 31 17:21:03 CEST 2011
	 */
	public EntidadTipoMapDAOImpl(DaoManager daoManager) {
		super(daoManager);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table geowfst.entidad_tipo_map
	 * @ibatorgenerated  Thu Mar 31 17:21:03 CEST 2011
	 */
	public int deleteByPrimaryKey(EntidadTipoMap key) {
		int rows = delete(
				"geowfst_entidad_tipo_map.ibatorgenerated_deleteByPrimaryKey",
				key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table geowfst.entidad_tipo_map
	 * @ibatorgenerated  Thu Mar 31 17:21:03 CEST 2011
	 */
	public void insert(EntidadTipoMap record) {
		insert("geowfst_entidad_tipo_map.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table geowfst.entidad_tipo_map
	 * @ibatorgenerated  Thu Mar 31 17:21:03 CEST 2011
	 */
	public void insertSelective(EntidadTipoMap record) {
		insert("geowfst_entidad_tipo_map.ibatorgenerated_insertSelective",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table geowfst.entidad_tipo_map
	 * @ibatorgenerated  Thu Mar 31 17:21:03 CEST 2011
	 */
	public EntidadTipoMap selectByPrimaryKey(EntidadTipoMap key) {
		EntidadTipoMap record = (EntidadTipoMap) queryForObject(
				"geowfst_entidad_tipo_map.ibatorgenerated_selectByPrimaryKey",
				key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table geowfst.entidad_tipo_map
	 * @ibatorgenerated  Thu Mar 31 17:21:03 CEST 2011
	 */
	public int updateByPrimaryKeySelective(EntidadTipoMap record) {
		int rows = update(
				"geowfst_entidad_tipo_map.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table geowfst.entidad_tipo_map
	 * @ibatorgenerated  Thu Mar 31 17:21:03 CEST 2011
	 */
	public int updateByPrimaryKey(EntidadTipoMap record) {
		int rows = update(
				"geowfst_entidad_tipo_map.ibatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}
}