package com.geopista.app.cementerios.business.vo;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class ConcesionExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table cementerio.concesion
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table cementerio.concesion
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.concesion
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public ConcesionExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.concesion
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.concesion
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.concesion
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.concesion
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.concesion
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.concesion
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.concesion
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table cementerio.concesion
	 * @ibatorgenerated  Tue Jul 05 09:50:09 CEST 2011
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List dateList = new ArrayList();
			Iterator iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(((Date) iter.next()).getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return this;
		}

		public Criteria andIdIn(List values) {
			addCriterion("id in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List values) {
			addCriterion("id not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return this;
		}

		public Criteria andLocalizadoIsNull() {
			addCriterion("localizado is null");
			return this;
		}

		public Criteria andLocalizadoIsNotNull() {
			addCriterion("localizado is not null");
			return this;
		}

		public Criteria andLocalizadoEqualTo(String value) {
			addCriterion("localizado =", value, "localizado");
			return this;
		}

		public Criteria andLocalizadoNotEqualTo(String value) {
			addCriterion("localizado <>", value, "localizado");
			return this;
		}

		public Criteria andLocalizadoGreaterThan(String value) {
			addCriterion("localizado >", value, "localizado");
			return this;
		}

		public Criteria andLocalizadoGreaterThanOrEqualTo(String value) {
			addCriterion("localizado >=", value, "localizado");
			return this;
		}

		public Criteria andLocalizadoLessThan(String value) {
			addCriterion("localizado <", value, "localizado");
			return this;
		}

		public Criteria andLocalizadoLessThanOrEqualTo(String value) {
			addCriterion("localizado <=", value, "localizado");
			return this;
		}

		public Criteria andLocalizadoLike(String value) {
			addCriterion("localizado like", value, "localizado");
			return this;
		}

		public Criteria andLocalizadoNotLike(String value) {
			addCriterion("localizado not like", value, "localizado");
			return this;
		}

		public Criteria andLocalizadoIn(List values) {
			addCriterion("localizado in", values, "localizado");
			return this;
		}

		public Criteria andLocalizadoNotIn(List values) {
			addCriterion("localizado not in", values, "localizado");
			return this;
		}

		public Criteria andLocalizadoBetween(String value1, String value2) {
			addCriterion("localizado between", value1, value2, "localizado");
			return this;
		}

		public Criteria andLocalizadoNotBetween(String value1, String value2) {
			addCriterion("localizado not between", value1, value2, "localizado");
			return this;
		}

		public Criteria andFechaIniIsNull() {
			addCriterion("fecha_ini is null");
			return this;
		}

		public Criteria andFechaIniIsNotNull() {
			addCriterion("fecha_ini is not null");
			return this;
		}

		public Criteria andFechaIniEqualTo(Date value) {
			addCriterionForJDBCDate("fecha_ini =", value, "fechaIni");
			return this;
		}

		public Criteria andFechaIniNotEqualTo(Date value) {
			addCriterionForJDBCDate("fecha_ini <>", value, "fechaIni");
			return this;
		}

		public Criteria andFechaIniGreaterThan(Date value) {
			addCriterionForJDBCDate("fecha_ini >", value, "fechaIni");
			return this;
		}

		public Criteria andFechaIniGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("fecha_ini >=", value, "fechaIni");
			return this;
		}

		public Criteria andFechaIniLessThan(Date value) {
			addCriterionForJDBCDate("fecha_ini <", value, "fechaIni");
			return this;
		}

		public Criteria andFechaIniLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("fecha_ini <=", value, "fechaIni");
			return this;
		}

		public Criteria andFechaIniIn(List values) {
			addCriterionForJDBCDate("fecha_ini in", values, "fechaIni");
			return this;
		}

		public Criteria andFechaIniNotIn(List values) {
			addCriterionForJDBCDate("fecha_ini not in", values, "fechaIni");
			return this;
		}

		public Criteria andFechaIniBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("fecha_ini between", value1, value2,
					"fechaIni");
			return this;
		}

		public Criteria andFechaIniNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("fecha_ini not between", value1, value2,
					"fechaIni");
			return this;
		}

		public Criteria andFechaFinIsNull() {
			addCriterion("fecha_fin is null");
			return this;
		}

		public Criteria andFechaFinIsNotNull() {
			addCriterion("fecha_fin is not null");
			return this;
		}

		public Criteria andFechaFinEqualTo(Date value) {
			addCriterionForJDBCDate("fecha_fin =", value, "fechaFin");
			return this;
		}

		public Criteria andFechaFinNotEqualTo(Date value) {
			addCriterionForJDBCDate("fecha_fin <>", value, "fechaFin");
			return this;
		}

		public Criteria andFechaFinGreaterThan(Date value) {
			addCriterionForJDBCDate("fecha_fin >", value, "fechaFin");
			return this;
		}

		public Criteria andFechaFinGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("fecha_fin >=", value, "fechaFin");
			return this;
		}

		public Criteria andFechaFinLessThan(Date value) {
			addCriterionForJDBCDate("fecha_fin <", value, "fechaFin");
			return this;
		}

		public Criteria andFechaFinLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("fecha_fin <=", value, "fechaFin");
			return this;
		}

		public Criteria andFechaFinIn(List values) {
			addCriterionForJDBCDate("fecha_fin in", values, "fechaFin");
			return this;
		}

		public Criteria andFechaFinNotIn(List values) {
			addCriterionForJDBCDate("fecha_fin not in", values, "fechaFin");
			return this;
		}

		public Criteria andFechaFinBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("fecha_fin between", value1, value2,
					"fechaFin");
			return this;
		}

		public Criteria andFechaFinNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("fecha_fin not between", value1, value2,
					"fechaFin");
			return this;
		}

		public Criteria andUltimaRenovaIsNull() {
			addCriterion("ultima_renova is null");
			return this;
		}

		public Criteria andUltimaRenovaIsNotNull() {
			addCriterion("ultima_renova is not null");
			return this;
		}

		public Criteria andUltimaRenovaEqualTo(Date value) {
			addCriterionForJDBCDate("ultima_renova =", value, "ultimaRenova");
			return this;
		}

		public Criteria andUltimaRenovaNotEqualTo(Date value) {
			addCriterionForJDBCDate("ultima_renova <>", value, "ultimaRenova");
			return this;
		}

		public Criteria andUltimaRenovaGreaterThan(Date value) {
			addCriterionForJDBCDate("ultima_renova >", value, "ultimaRenova");
			return this;
		}

		public Criteria andUltimaRenovaGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ultima_renova >=", value, "ultimaRenova");
			return this;
		}

		public Criteria andUltimaRenovaLessThan(Date value) {
			addCriterionForJDBCDate("ultima_renova <", value, "ultimaRenova");
			return this;
		}

		public Criteria andUltimaRenovaLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ultima_renova <=", value, "ultimaRenova");
			return this;
		}

		public Criteria andUltimaRenovaIn(List values) {
			addCriterionForJDBCDate("ultima_renova in", values, "ultimaRenova");
			return this;
		}

		public Criteria andUltimaRenovaNotIn(List values) {
			addCriterionForJDBCDate("ultima_renova not in", values,
					"ultimaRenova");
			return this;
		}

		public Criteria andUltimaRenovaBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ultima_renova between", value1, value2,
					"ultimaRenova");
			return this;
		}

		public Criteria andUltimaRenovaNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ultima_renova not between", value1,
					value2, "ultimaRenova");
			return this;
		}

		public Criteria andUltimoTitularIsNull() {
			addCriterion("ultimo_titular is null");
			return this;
		}

		public Criteria andUltimoTitularIsNotNull() {
			addCriterion("ultimo_titular is not null");
			return this;
		}

		public Criteria andUltimoTitularEqualTo(String value) {
			addCriterion("ultimo_titular =", value, "ultimoTitular");
			return this;
		}

		public Criteria andUltimoTitularNotEqualTo(String value) {
			addCriterion("ultimo_titular <>", value, "ultimoTitular");
			return this;
		}

		public Criteria andUltimoTitularGreaterThan(String value) {
			addCriterion("ultimo_titular >", value, "ultimoTitular");
			return this;
		}

		public Criteria andUltimoTitularGreaterThanOrEqualTo(String value) {
			addCriterion("ultimo_titular >=", value, "ultimoTitular");
			return this;
		}

		public Criteria andUltimoTitularLessThan(String value) {
			addCriterion("ultimo_titular <", value, "ultimoTitular");
			return this;
		}

		public Criteria andUltimoTitularLessThanOrEqualTo(String value) {
			addCriterion("ultimo_titular <=", value, "ultimoTitular");
			return this;
		}

		public Criteria andUltimoTitularLike(String value) {
			addCriterion("ultimo_titular like", value, "ultimoTitular");
			return this;
		}

		public Criteria andUltimoTitularNotLike(String value) {
			addCriterion("ultimo_titular not like", value, "ultimoTitular");
			return this;
		}

		public Criteria andUltimoTitularIn(List values) {
			addCriterion("ultimo_titular in", values, "ultimoTitular");
			return this;
		}

		public Criteria andUltimoTitularNotIn(List values) {
			addCriterion("ultimo_titular not in", values, "ultimoTitular");
			return this;
		}

		public Criteria andUltimoTitularBetween(String value1, String value2) {
			addCriterion("ultimo_titular between", value1, value2,
					"ultimoTitular");
			return this;
		}

		public Criteria andUltimoTitularNotBetween(String value1, String value2) {
			addCriterion("ultimo_titular not between", value1, value2,
					"ultimoTitular");
			return this;
		}

		public Criteria andIdTarifaIsNull() {
			addCriterion("id_tarifa is null");
			return this;
		}

		public Criteria andIdTarifaIsNotNull() {
			addCriterion("id_tarifa is not null");
			return this;
		}

		public Criteria andIdTarifaEqualTo(Integer value) {
			addCriterion("id_tarifa =", value, "idTarifa");
			return this;
		}

		public Criteria andIdTarifaNotEqualTo(Integer value) {
			addCriterion("id_tarifa <>", value, "idTarifa");
			return this;
		}

		public Criteria andIdTarifaGreaterThan(Integer value) {
			addCriterion("id_tarifa >", value, "idTarifa");
			return this;
		}

		public Criteria andIdTarifaGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_tarifa >=", value, "idTarifa");
			return this;
		}

		public Criteria andIdTarifaLessThan(Integer value) {
			addCriterion("id_tarifa <", value, "idTarifa");
			return this;
		}

		public Criteria andIdTarifaLessThanOrEqualTo(Integer value) {
			addCriterion("id_tarifa <=", value, "idTarifa");
			return this;
		}

		public Criteria andIdTarifaIn(List values) {
			addCriterion("id_tarifa in", values, "idTarifa");
			return this;
		}

		public Criteria andIdTarifaNotIn(List values) {
			addCriterion("id_tarifa not in", values, "idTarifa");
			return this;
		}

		public Criteria andIdTarifaBetween(Integer value1, Integer value2) {
			addCriterion("id_tarifa between", value1, value2, "idTarifa");
			return this;
		}

		public Criteria andIdTarifaNotBetween(Integer value1, Integer value2) {
			addCriterion("id_tarifa not between", value1, value2, "idTarifa");
			return this;
		}

		public Criteria andIdUnidadIsNull() {
			addCriterion("id_unidad is null");
			return this;
		}

		public Criteria andIdUnidadIsNotNull() {
			addCriterion("id_unidad is not null");
			return this;
		}

		public Criteria andIdUnidadEqualTo(Integer value) {
			addCriterion("id_unidad =", value, "idUnidad");
			return this;
		}

		public Criteria andIdUnidadNotEqualTo(Integer value) {
			addCriterion("id_unidad <>", value, "idUnidad");
			return this;
		}

		public Criteria andIdUnidadGreaterThan(Integer value) {
			addCriterion("id_unidad >", value, "idUnidad");
			return this;
		}

		public Criteria andIdUnidadGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_unidad >=", value, "idUnidad");
			return this;
		}

		public Criteria andIdUnidadLessThan(Integer value) {
			addCriterion("id_unidad <", value, "idUnidad");
			return this;
		}

		public Criteria andIdUnidadLessThanOrEqualTo(Integer value) {
			addCriterion("id_unidad <=", value, "idUnidad");
			return this;
		}

		public Criteria andIdUnidadIn(List values) {
			addCriterion("id_unidad in", values, "idUnidad");
			return this;
		}

		public Criteria andIdUnidadNotIn(List values) {
			addCriterion("id_unidad not in", values, "idUnidad");
			return this;
		}

		public Criteria andIdUnidadBetween(Integer value1, Integer value2) {
			addCriterion("id_unidad between", value1, value2, "idUnidad");
			return this;
		}

		public Criteria andIdUnidadNotBetween(Integer value1, Integer value2) {
			addCriterion("id_unidad not between", value1, value2, "idUnidad");
			return this;
		}

		public Criteria andEstadoIsNull() {
			addCriterion("estado is null");
			return this;
		}

		public Criteria andEstadoIsNotNull() {
			addCriterion("estado is not null");
			return this;
		}

		public Criteria andEstadoEqualTo(Integer value) {
			addCriterion("estado =", value, "estado");
			return this;
		}

		public Criteria andEstadoNotEqualTo(Integer value) {
			addCriterion("estado <>", value, "estado");
			return this;
		}

		public Criteria andEstadoGreaterThan(Integer value) {
			addCriterion("estado >", value, "estado");
			return this;
		}

		public Criteria andEstadoGreaterThanOrEqualTo(Integer value) {
			addCriterion("estado >=", value, "estado");
			return this;
		}

		public Criteria andEstadoLessThan(Integer value) {
			addCriterion("estado <", value, "estado");
			return this;
		}

		public Criteria andEstadoLessThanOrEqualTo(Integer value) {
			addCriterion("estado <=", value, "estado");
			return this;
		}

		public Criteria andEstadoIn(List values) {
			addCriterion("estado in", values, "estado");
			return this;
		}

		public Criteria andEstadoNotIn(List values) {
			addCriterion("estado not in", values, "estado");
			return this;
		}

		public Criteria andEstadoBetween(Integer value1, Integer value2) {
			addCriterion("estado between", value1, value2, "estado");
			return this;
		}

		public Criteria andEstadoNotBetween(Integer value1, Integer value2) {
			addCriterion("estado not between", value1, value2, "estado");
			return this;
		}

		public Criteria andTipoConcesionIsNull() {
			addCriterion("tipo_concesion is null");
			return this;
		}

		public Criteria andTipoConcesionIsNotNull() {
			addCriterion("tipo_concesion is not null");
			return this;
		}

		public Criteria andTipoConcesionEqualTo(Integer value) {
			addCriterion("tipo_concesion =", value, "tipoConcesion");
			return this;
		}

		public Criteria andTipoConcesionNotEqualTo(Integer value) {
			addCriterion("tipo_concesion <>", value, "tipoConcesion");
			return this;
		}

		public Criteria andTipoConcesionGreaterThan(Integer value) {
			addCriterion("tipo_concesion >", value, "tipoConcesion");
			return this;
		}

		public Criteria andTipoConcesionGreaterThanOrEqualTo(Integer value) {
			addCriterion("tipo_concesion >=", value, "tipoConcesion");
			return this;
		}

		public Criteria andTipoConcesionLessThan(Integer value) {
			addCriterion("tipo_concesion <", value, "tipoConcesion");
			return this;
		}

		public Criteria andTipoConcesionLessThanOrEqualTo(Integer value) {
			addCriterion("tipo_concesion <=", value, "tipoConcesion");
			return this;
		}

		public Criteria andTipoConcesionIn(List values) {
			addCriterion("tipo_concesion in", values, "tipoConcesion");
			return this;
		}

		public Criteria andTipoConcesionNotIn(List values) {
			addCriterion("tipo_concesion not in", values, "tipoConcesion");
			return this;
		}

		public Criteria andTipoConcesionBetween(Integer value1, Integer value2) {
			addCriterion("tipo_concesion between", value1, value2,
					"tipoConcesion");
			return this;
		}

		public Criteria andTipoConcesionNotBetween(Integer value1,
				Integer value2) {
			addCriterion("tipo_concesion not between", value1, value2,
					"tipoConcesion");
			return this;
		}

		public Criteria andDescripcionIsNull() {
			addCriterion("descripcion is null");
			return this;
		}

		public Criteria andDescripcionIsNotNull() {
			addCriterion("descripcion is not null");
			return this;
		}

		public Criteria andDescripcionEqualTo(String value) {
			addCriterion("descripcion =", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionNotEqualTo(String value) {
			addCriterion("descripcion <>", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionGreaterThan(String value) {
			addCriterion("descripcion >", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionGreaterThanOrEqualTo(String value) {
			addCriterion("descripcion >=", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionLessThan(String value) {
			addCriterion("descripcion <", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionLessThanOrEqualTo(String value) {
			addCriterion("descripcion <=", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionLike(String value) {
			addCriterion("descripcion like", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionNotLike(String value) {
			addCriterion("descripcion not like", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionIn(List values) {
			addCriterion("descripcion in", values, "descripcion");
			return this;
		}

		public Criteria andDescripcionNotIn(List values) {
			addCriterion("descripcion not in", values, "descripcion");
			return this;
		}

		public Criteria andDescripcionBetween(String value1, String value2) {
			addCriterion("descripcion between", value1, value2, "descripcion");
			return this;
		}

		public Criteria andDescripcionNotBetween(String value1, String value2) {
			addCriterion("descripcion not between", value1, value2,
					"descripcion");
			return this;
		}

		public Criteria andCodigoIsNull() {
			addCriterion("codigo is null");
			return this;
		}

		public Criteria andCodigoIsNotNull() {
			addCriterion("codigo is not null");
			return this;
		}

		public Criteria andCodigoEqualTo(String value) {
			addCriterion("codigo =", value, "codigo");
			return this;
		}

		public Criteria andCodigoNotEqualTo(String value) {
			addCriterion("codigo <>", value, "codigo");
			return this;
		}

		public Criteria andCodigoGreaterThan(String value) {
			addCriterion("codigo >", value, "codigo");
			return this;
		}

		public Criteria andCodigoGreaterThanOrEqualTo(String value) {
			addCriterion("codigo >=", value, "codigo");
			return this;
		}

		public Criteria andCodigoLessThan(String value) {
			addCriterion("codigo <", value, "codigo");
			return this;
		}

		public Criteria andCodigoLessThanOrEqualTo(String value) {
			addCriterion("codigo <=", value, "codigo");
			return this;
		}

		public Criteria andCodigoLike(String value) {
			addCriterion("codigo like", value, "codigo");
			return this;
		}

		public Criteria andCodigoNotLike(String value) {
			addCriterion("codigo not like", value, "codigo");
			return this;
		}

		public Criteria andCodigoIn(List values) {
			addCriterion("codigo in", values, "codigo");
			return this;
		}

		public Criteria andCodigoNotIn(List values) {
			addCriterion("codigo not in", values, "codigo");
			return this;
		}

		public Criteria andCodigoBetween(String value1, String value2) {
			addCriterion("codigo between", value1, value2, "codigo");
			return this;
		}

		public Criteria andCodigoNotBetween(String value1, String value2) {
			addCriterion("codigo not between", value1, value2, "codigo");
			return this;
		}

		public Criteria andPrecioFinalIsNull() {
			addCriterion("precio_final is null");
			return this;
		}

		public Criteria andPrecioFinalIsNotNull() {
			addCriterion("precio_final is not null");
			return this;
		}

		public Criteria andPrecioFinalEqualTo(String value) {
			addCriterion("precio_final =", value, "precioFinal");
			return this;
		}

		public Criteria andPrecioFinalNotEqualTo(String value) {
			addCriterion("precio_final <>", value, "precioFinal");
			return this;
		}

		public Criteria andPrecioFinalGreaterThan(String value) {
			addCriterion("precio_final >", value, "precioFinal");
			return this;
		}

		public Criteria andPrecioFinalGreaterThanOrEqualTo(String value) {
			addCriterion("precio_final >=", value, "precioFinal");
			return this;
		}

		public Criteria andPrecioFinalLessThan(String value) {
			addCriterion("precio_final <", value, "precioFinal");
			return this;
		}

		public Criteria andPrecioFinalLessThanOrEqualTo(String value) {
			addCriterion("precio_final <=", value, "precioFinal");
			return this;
		}

		public Criteria andPrecioFinalLike(String value) {
			addCriterion("precio_final like", value, "precioFinal");
			return this;
		}

		public Criteria andPrecioFinalNotLike(String value) {
			addCriterion("precio_final not like", value, "precioFinal");
			return this;
		}

		public Criteria andPrecioFinalIn(List values) {
			addCriterion("precio_final in", values, "precioFinal");
			return this;
		}

		public Criteria andPrecioFinalNotIn(List values) {
			addCriterion("precio_final not in", values, "precioFinal");
			return this;
		}

		public Criteria andPrecioFinalBetween(String value1, String value2) {
			addCriterion("precio_final between", value1, value2, "precioFinal");
			return this;
		}

		public Criteria andPrecioFinalNotBetween(String value1, String value2) {
			addCriterion("precio_final not between", value1, value2,
					"precioFinal");
			return this;
		}

		public Criteria andBonificacionIsNull() {
			addCriterion("bonificacion is null");
			return this;
		}

		public Criteria andBonificacionIsNotNull() {
			addCriterion("bonificacion is not null");
			return this;
		}

		public Criteria andBonificacionEqualTo(String value) {
			addCriterion("bonificacion =", value, "bonificacion");
			return this;
		}

		public Criteria andBonificacionNotEqualTo(String value) {
			addCriterion("bonificacion <>", value, "bonificacion");
			return this;
		}

		public Criteria andBonificacionGreaterThan(String value) {
			addCriterion("bonificacion >", value, "bonificacion");
			return this;
		}

		public Criteria andBonificacionGreaterThanOrEqualTo(String value) {
			addCriterion("bonificacion >=", value, "bonificacion");
			return this;
		}

		public Criteria andBonificacionLessThan(String value) {
			addCriterion("bonificacion <", value, "bonificacion");
			return this;
		}

		public Criteria andBonificacionLessThanOrEqualTo(String value) {
			addCriterion("bonificacion <=", value, "bonificacion");
			return this;
		}

		public Criteria andBonificacionLike(String value) {
			addCriterion("bonificacion like", value, "bonificacion");
			return this;
		}

		public Criteria andBonificacionNotLike(String value) {
			addCriterion("bonificacion not like", value, "bonificacion");
			return this;
		}

		public Criteria andBonificacionIn(List values) {
			addCriterion("bonificacion in", values, "bonificacion");
			return this;
		}

		public Criteria andBonificacionNotIn(List values) {
			addCriterion("bonificacion not in", values, "bonificacion");
			return this;
		}

		public Criteria andBonificacionBetween(String value1, String value2) {
			addCriterion("bonificacion between", value1, value2, "bonificacion");
			return this;
		}

		public Criteria andBonificacionNotBetween(String value1, String value2) {
			addCriterion("bonificacion not between", value1, value2,
					"bonificacion");
			return this;
		}
	}
}