/*
 * JPanelBusqueda.java
 *
 * Created on 24 de junio de 2005, 15:04
 */

package com.geopista.app.licencias.planos;

import org.apache.log4j.Logger;

import java.util.*;
import java.awt.*;
import java.text.SimpleDateFormat;

import com.geopista.app.utilidades.estructuras.ComboBoxEstructuras;
import com.geopista.app.licencias.CMainLicencias;
import com.geopista.app.licencias.CConstantesLicencias;
import com.geopista.app.licencias.IMainLicencias;
import com.geopista.app.licencias.CUtilidadesComponentes;
import com.geopista.app.licencias.utilidades.JInternalFrameLicencias;
import com.geopista.app.licencias.actividad.MainActividad;
import com.geopista.app.licencias.estructuras.Estructuras;
import com.geopista.protocol.ListaEstructuras;
import com.geopista.protocol.CResultadoOperacion;
import com.geopista.protocol.administrador.dominios.DomainNode;
import com.geopista.protocol.licencias.COperacionesLicencias;
import com.geopista.protocol.licencias.CExpedienteLicencia;
import com.geopista.protocol.licencias.Parametro;
import com.geopista.protocol.licencias.tipos.CTipoLicencia;
import com.geopista.protocol.licencias.estados.CEstado;

import javax.swing.*;

/**
 *
 * @author  angeles
 */
public class JPanelBusqueda extends javax.swing.JPanel {
    private Logger logger=Logger.getLogger(JPanelBusqueda.class);
    private JFrame desktop;
    private JInternalFrame padre;
    private ResourceBundle literales;

    /** Creates new form JPanelBusqueda */
    public JPanelBusqueda(JFrame desktop, JInternalFrame padre,ResourceBundle literales) {
        this.desktop=desktop;
        this.literales=literales;
        this.padre=padre;
        initComponents();
        renombrarComponentes(literales);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabelTipoLicencia = new javax.swing.JLabel();
        jLabelObra = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        //jComboBoxEstado = new ComboBoxEstructuras(Estructuras.getListaEstados(), null, literales.getLocale().toString(), true);
        jComboBoxTipoObra=new ComboBoxEstructuras(new ListaEstructuras(), null, literales.getLocale().toString(), true);
        jLabelFecha = new javax.swing.JLabel();
        jLabelReferencias = new javax.swing.JLabel();
        jScrollPaneReferencias = new javax.swing.JScrollPane();
        jListReferencias = new javax.swing.JList();
        jButtonBuscar= new javax.swing.JButton();
        jTextFieldFechaDesde=new javax.swing.JFormattedTextField(new SimpleDateFormat("dd/MM/yyyy"));
        jButtonFechaDesde = new javax.swing.JButton();
        jTextFieldFechaHasta=new javax.swing.JFormattedTextField(new SimpleDateFormat("dd/MM/yyyy"));
        jButtonFechaHasta = new javax.swing.JButton();


        if (desktop instanceof CMainLicencias)
        {
                /* Estados de licencias de obra mayor y menor */
                Vector tiposLicencia= new Vector();
                CTipoLicencia tipoLicencia= new CTipoLicencia(new Integer(CConstantesLicencias.LicenciasObraMayor).intValue(), "", "");
                tiposLicencia.add(tipoLicencia);
                tipoLicencia= new CTipoLicencia(new Integer(CConstantesLicencias.LicenciasObraMenor).intValue(), "", "");
                tiposLicencia.add(tipoLicencia);
                Vector estados= COperacionesLicencias.getEstados(tiposLicencia);
                jComboBoxEstado= new ComboBoxEstructuras(getEstructurasEstado(estados), null, literales.getLocale().toString(), true);
                jComboBoxEstado.setEnabled(true);

                jComboBoxTipoLicencia= new ComboBoxEstructuras(Estructuras.getListaLicencias(), null, literales.getLocale().toString(), true);
                jComboBoxTipoLicencia.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cambiarTipoObra();

                    /** Limitamos los estados al tipo de Lincencia, debido a que todos los estados de
                     * licencias de obra y actividad estan en el mismo dominio (ESTADO). */
                    cambiarEstados();
                }});
                jComboBoxTipoLicencia.setSelectedIndex(0);
            
                jComboBoxTipoObra= new ComboBoxEstructuras(new ListaEstructuras(), null, literales.getLocale().toString(), true);
                jComboBoxTipoObra.setEnabled(false);


        } else if (desktop instanceof MainActividad)
        {

                /* Estados de licencias de actividad y actividad no calificada */
                Vector tiposLicencia= new Vector();
                CTipoLicencia tipoLicencia= new CTipoLicencia(new Integer(CConstantesLicencias.LicenciasActividad).intValue(), "", "");
                tiposLicencia.add(tipoLicencia);
                tipoLicencia= new CTipoLicencia(new Integer(CConstantesLicencias.LicenciasActividadNoCalificada).intValue(), "", "");
                tiposLicencia.add(tipoLicencia);
                Vector estados= COperacionesLicencias.getEstados(tiposLicencia);
                jComboBoxEstado= new ComboBoxEstructuras(getEstructurasEstado(estados), null, literales.getLocale().toString(), true);
                jComboBoxEstado.setEnabled(true);

                jComboBoxTipoLicencia= new ComboBoxEstructuras(Estructuras.getListaTiposLicenciaActividad(), null, literales.getLocale().toString(), true);
                jComboBoxTipoLicencia.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    /** Limitamos los estados al tipo de Lincencia, debido a que todos los estados de
                     * licencias de obra y actividad estan en el mismo dominio (ESTADO). */
                    cambiarEstados();
                }});

                jComboBoxTipoObra= new ComboBoxEstructuras(Estructuras.getListaTiposActividad(), null, literales.getLocale().toString(), true);
        }

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabelTipoLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        add(jComboBoxTipoLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 280, -1));
        add(jLabelObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        add(jComboBoxTipoObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 280, -1));
        add(jLabelEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        add(jComboBoxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 280, -1));
        add(jLabelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));
        add(jTextFieldFechaDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 115, -1));
        add(jButtonFechaDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 180, 20, 20));
        add(jTextFieldFechaHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 180, 115, -1));
        add(jButtonFechaHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 20, 20));
        add(jLabelReferencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));
        jScrollPaneReferencias.setViewportView(jListReferencias);
        add(jScrollPaneReferencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 280, 150));
        add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1,-1));
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar();
            }
        });
        jButtonFechaDesde.setIcon(com.geopista.app.licencias.CUtilidadesComponentes.iconoZoom);
        jButtonFechaDesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponerFecha(jTextFieldFechaDesde);
            }
        });
        jButtonFechaHasta.setIcon(com.geopista.app.licencias.CUtilidadesComponentes.iconoZoom);
        jButtonFechaHasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponerFecha(jTextFieldFechaHasta);
            }
        });


    }//GEN-END:initComponents
    public void renombrarComponentes(ResourceBundle literales)
    {
        this.literales=literales;
        try
        {
            jLabelTipoLicencia.setText(literales.getString("CSearchJDialog.tipoLicenciaJLabel.text"));
            jLabelReferencias.setText(literales.getString("CSearchJDialog.numeroExpedienteJLabel.text"));
            if (desktop instanceof CMainLicencias)
                jLabelObra.setText(literales.getString("CSearchJDialog.tipoObraJLabel2.text"));
            else
                jLabelObra.setText(literales.getString("CSearchJDialog.tipoObraJLabel1.text"));
            jLabelEstado.setText(literales.getString("CSearchJDialog.estadoExpedienteJLabel.text"));
            jLabelFecha.setText(literales.getString("CSearchJDialog.fechaAperturaJLabel.text"));
            jButtonBuscar.setText(literales.getString("CSearchJDialog.buscarJButton.text"));

            jButtonBuscar.setToolTipText(literales.getString("CSearchJDialog.buscarJButton.text"));
            jButtonFechaDesde.setToolTipText(literales.getString("CSearchJDialog.jButtonFechaDesde.text"));
            jButtonFechaHasta.setToolTipText(literales.getString("CSearchJDialog.jButtonFechaHasta.text"));
        }catch(Exception e)
        {
            logger.error("Excepción: ",e);
        }
    }
     private void cambiarTipoObra() {
        jComboBoxTipoObra.removeAllItems();
        if (jComboBoxTipoLicencia.getSelectedIndex() == 0) {
            jComboBoxTipoObra.setEstructuras(new ListaEstructuras(), null, literales.getLocale().toString(), true);
            jComboBoxTipoObra.setEnabled(false);
        }else if (jComboBoxTipoLicencia.getSelectedPatron().equalsIgnoreCase(new Integer(CConstantesLicencias.ObraMayor).toString())){
            jComboBoxTipoObra.setEstructuras(Estructuras.getListaTiposObra(), null, literales.getLocale().toString(), true);
            jComboBoxTipoObra.setEnabled(true);
        }else if (jComboBoxTipoLicencia.getSelectedPatron().equalsIgnoreCase(new Integer(CConstantesLicencias.ObraMenor).toString())){
            jComboBoxTipoObra.setEstructuras(Estructuras.getListaTiposObraMenor(), null, literales.getLocale().toString(), true);
            jComboBoxTipoObra.setEnabled(true);
        }
        jComboBoxTipoObra.setSelectedIndex(0);
    }
    public void setEnabled(boolean value)
    {
        jComboBoxTipoLicencia.setSelectedIndex(0);
        jComboBoxTipoLicencia.setEnabled(value);
        if (desktop instanceof CMainLicencias)
            cambiarTipoObra();
        else
        {
            jComboBoxTipoObra.setSelectedIndex(0);
            jComboBoxTipoObra.setEnabled(value);
        }
        jComboBoxEstado.setEnabled(value);
        jButtonBuscar.setEnabled(value);
        jButtonFechaDesde.setEnabled(value);
        jButtonFechaHasta.setEnabled(value);
        loadData(null);
        jTextFieldFechaDesde.setText("");
        jTextFieldFechaHasta.setText("");
    }


    private void cambiarEstados() {
       jComboBoxEstado.removeAllItems();

        if (desktop instanceof CMainLicencias){

           if (jComboBoxTipoLicencia.getSelectedIndex() == 0) {
               Vector tiposLicencia= new Vector();
               CTipoLicencia tipoLicencia= new CTipoLicencia(new Integer(CConstantesLicencias.LicenciasObraMayor).intValue(), "", "");
               tiposLicencia.add(tipoLicencia);
               tipoLicencia= new CTipoLicencia(new Integer(CConstantesLicencias.LicenciasObraMenor).intValue(), "", "");
               tiposLicencia.add(tipoLicencia);
               Vector estados= COperacionesLicencias.getEstados(tiposLicencia);
               jComboBoxEstado.setEstructuras(getEstructurasEstado(estados), null, literales.getLocale().toString(), true);
               jComboBoxEstado.setEnabled(true);
           }else if (jComboBoxTipoLicencia.getSelectedPatron().equalsIgnoreCase(new Integer(CConstantesLicencias.ObraMayor).toString())){
               Vector tiposLicencia= new Vector();
               CTipoLicencia tipoLicencia= new CTipoLicencia(new Integer(CConstantesLicencias.LicenciasObraMayor).intValue(), "", "");
               tiposLicencia.add(tipoLicencia);
               Vector estados= COperacionesLicencias.getEstados(tiposLicencia);
               jComboBoxEstado.setEstructuras(getEstructurasEstado(estados), null, literales.getLocale().toString(), true);
               jComboBoxEstado.setEnabled(true);
           }else if (jComboBoxTipoLicencia.getSelectedPatron().equalsIgnoreCase(new Integer(CConstantesLicencias.ObraMenor).toString())){
               Vector tiposLicencia= new Vector();
               CTipoLicencia tipoLicencia= new CTipoLicencia(new Integer(CConstantesLicencias.LicenciasObraMenor).intValue(), "", "");
               tiposLicencia.add(tipoLicencia);
               Vector estados= COperacionesLicencias.getEstados(tiposLicencia);
               jComboBoxEstado.setEstructuras(getEstructurasEstado(estados), null, literales.getLocale().toString(), true);
               jComboBoxEstado.setEnabled(true);
           }
           jComboBoxEstado.setSelectedIndex(0);
        }else if (desktop instanceof MainActividad){
            if (jComboBoxTipoLicencia.getSelectedIndex() == 0) {
                Vector tiposLicencia= new Vector();
                CTipoLicencia tipoLicencia= new CTipoLicencia(new Integer(CConstantesLicencias.LicenciasActividad).intValue(), "", "");
                tiposLicencia.add(tipoLicencia);
                tipoLicencia= new CTipoLicencia(new Integer(CConstantesLicencias.LicenciasActividadNoCalificada).intValue(), "", "");
                tiposLicencia.add(tipoLicencia);
                Vector estados= COperacionesLicencias.getEstados(tiposLicencia);
                jComboBoxEstado.setEstructuras(getEstructurasEstado(estados), null, literales.getLocale().toString(), true);
                jComboBoxEstado.setEnabled(true);
            }else if (jComboBoxTipoLicencia.getSelectedPatron().equalsIgnoreCase(new Integer(CConstantesLicencias.LicenciasActividad).toString())){
                Vector tiposLicencia= new Vector();
                CTipoLicencia tipoLicencia= new CTipoLicencia(new Integer(CConstantesLicencias.LicenciasActividad).intValue(), "", "");
                tiposLicencia.add(tipoLicencia);
                Vector estados= COperacionesLicencias.getEstados(tiposLicencia);
                jComboBoxEstado.setEstructuras(getEstructurasEstado(estados), null, literales.getLocale().toString(), true);
                jComboBoxEstado.setEnabled(true);
            }else if (jComboBoxTipoLicencia.getSelectedPatron().equalsIgnoreCase(new Integer(CConstantesLicencias.LicenciasActividadNoCalificada).toString())){
                Vector tiposLicencia= new Vector();
                CTipoLicencia tipoLicencia= new CTipoLicencia(new Integer(CConstantesLicencias.LicenciasActividadNoCalificada).intValue(), "", "");
                tiposLicencia.add(tipoLicencia);
                Vector estados= COperacionesLicencias.getEstados(tiposLicencia);
                jComboBoxEstado.setEstructuras(getEstructurasEstado(estados), null, literales.getLocale().toString(), true);
                jComboBoxEstado.setEnabled(true);
            }
            jComboBoxEstado.setSelectedIndex(0);
        }

   }

   private ListaEstructuras getEstructurasEstado(Vector estados){
       ListaEstructuras listaEstructuras= new ListaEstructuras();

       if ((estados != null) && (estados.size() > 0)){
           for (int i=0; i<estados.size(); i++){
               CEstado estado= (CEstado)estados.get(i);
               DomainNode domainNode= Estructuras.getListaEstados().getDomainNode(new Integer(estado.getIdEstado()).toString());
               listaEstructuras.add(domainNode);
           }
       }

       return listaEstructuras;
   }


    public void buscar()
    {
        Hashtable hash = new Hashtable();
        if (jComboBoxTipoLicencia.getSelectedIndex()!=0)
        {
           Parametro auxParametro = new Parametro();
           auxParametro.setValorString(jComboBoxTipoLicencia.getSelectedPatron());
           hash.put("E.ID_TIPO_LICENCIA = ?", auxParametro);
        }
        if (jComboBoxTipoObra.getSelectedIndex()!=0)
        {
           Parametro auxParametro = new Parametro();
           auxParametro.setValorString(jComboBoxTipoObra.getSelectedPatron());
           hash.put("E.ID_TIPO_OBRA=?", auxParametro);
        }
        if (jComboBoxEstado.getSelectedIndex()!=0)
        {
            Parametro auxParametro = new Parametro();
            auxParametro.setValorString(jComboBoxEstado.getSelectedPatron());
            hash.put("A.ID_ESTADO=?",auxParametro);
        }
        if (jTextFieldFechaDesde.getText().length()>0)
        {
           Parametro auxParametro = new Parametro();
           auxParametro.setValorDate(((Date)jTextFieldFechaDesde.getValue()));
           hash.put("A.FECHA_APERTURA>=?",auxParametro);
        }
        if (jTextFieldFechaHasta.getText().length()>0)
        {
            Parametro auxParametro = new Parametro();
            auxParametro.setValorDate(((Date)jTextFieldFechaHasta.getValue()));
            hash.put("A.FECHA_APERTURA<=?",auxParametro);
        }
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

        Vector tiposLicencia=  ((IMainLicencias)desktop).getTiposLicencia();
        CResultadoOperacion res= COperacionesLicencias.getSearchedExpedientesPlanos(hash, tiposLicencia);
        if (res.getResultado())
        {
            loadData(res.getExpedientes());
            ((JInternalFrameLicencias)padre).refreshFeatureSelection(res.getVector());
        }
        this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }
     private void loadData(Vector vectorExpedientes)
    {
        try
        {
            DefaultListModel  listModel= new DefaultListModel();
            listModel.clear();
            jListReferencias.setModel(listModel);
            jListReferencias.setCellRenderer(new CellRendererExpedientes());
            if (vectorExpedientes==null)return;
            for (Enumeration e = vectorExpedientes.elements(); e.hasMoreElements(); )
             {
                listModel.addElement(e.nextElement());
             }
        }catch(Exception e)
        {
            logger.error("Excepción: ", e);
        }
    }
    public void ponerFecha(javax.swing.JFormattedTextField jTextField)
    {
        Date fecha= CUtilidadesComponentes.showCalendarDialog(desktop);
        jTextField.setValue((fecha==null?new Date():fecha));
    }
    private ComboBoxEstructuras jComboBoxEstado;
    private ComboBoxEstructuras jComboBoxTipoLicencia;
    private ComboBoxEstructuras jComboBoxTipoObra;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelObra;
    private javax.swing.JLabel jLabelReferencias;
    private javax.swing.JLabel jLabelTipoLicencia;
    private javax.swing.JList jListReferencias;
    private javax.swing.JScrollPane jScrollPaneReferencias;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JFormattedTextField jTextFieldFechaDesde;
    private javax.swing.JButton jButtonFechaDesde;
    private javax.swing.JFormattedTextField jTextFieldFechaHasta;
    private javax.swing.JButton jButtonFechaHasta;


}

class CellRendererExpedientes extends DefaultListCellRenderer
{
       public Component getListCellRendererComponent(JList l,
                                         Object value,
                                         int i,
                                         boolean s,
                                         boolean f) {
       CExpedienteLicencia  exp = (CExpedienteLicencia)value;
       JLabel label =(JLabel) super.getListCellRendererComponent(l,exp.getNumExpediente(),
                                         i, s, f);
       return label;
       }
}