package com.geopista.app.utilidades.event;

/**
 * @(#) NumberListener.java	1.0	99/06/17
 *
 * This code is designed for JDK1.2 and JDK1.1.5
 * Use tab spacing 4. Follow JavaDoc convention while coding.
 * Mail any suggestions or bugs to unicman@iname.com
 */

/**
 * This interface is used for number filters. All the events generated by the
 * filter can be listen to using this listener.
 *
 * @version	1.0 06/17/99
 * @author	UnicMan
 */
public interface NumberListener
{
	/**
	 * Event is generated when invalid number is entered by the user.
	 *
	 * @param	neEvt	number event object
	 */
	public void gotInvalidNumber( NumberEvent neEvt );
}
