/**
 * AnexoCementerioDAOImpl.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.geopista.app.cementerios.business.dao.implementations;

import java.sql.SQLException;
import java.util.List;

import com.geopista.app.cementerios.business.dao.DAO;
import com.geopista.app.cementerios.business.dao.interfaces.AnexoCementerioDAO;
import com.geopista.app.cementerios.business.vo.AnexoCementerio;
import com.geopista.app.cementerios.business.vo.AnexoCementerioExample;
import com.geopista.app.cementerios.business.vo.AnexoCementerioKey;

public class AnexoCementerioDAOImpl extends DAO implements AnexoCementerioDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.anexo_cementerio
	 * @ibatorgenerated  Mon Jul 11 14:45:21 CEST 2011
	 */
	public AnexoCementerioDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.anexo_cementerio
	 * @throws SQLException 
	 * @ibatorgenerated  Mon Jul 11 14:45:21 CEST 2011
	 */
	public int deleteByExample(AnexoCementerioExample example) throws SQLException {
		int rows = getSqlMapClientTemplate().delete(
				"cementerio_anexo_cementerio.ibatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.anexo_cementerio
	 * @ibatorgenerated  Mon Jul 11 14:45:21 CEST 2011
	 */
	public int deleteByPrimaryKey(AnexoCementerioKey key) throws SQLException {
		int rows = getSqlMapClientTemplate()
				.delete("cementerio_anexo_cementerio.ibatorgenerated_deleteByPrimaryKey",
						key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.anexo_cementerio
	 * @ibatorgenerated  Mon Jul 11 14:45:21 CEST 2011
	 */
	public void insert(AnexoCementerio record) throws SQLException {
		getSqlMapClientTemplate().insert(
				"cementerio_anexo_cementerio.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.anexo_cementerio
	 * @ibatorgenerated  Mon Jul 11 14:45:21 CEST 2011
	 */
	public void insertSelective(AnexoCementerio record) throws SQLException {
		getSqlMapClientTemplate().insert(
				"cementerio_anexo_cementerio.ibatorgenerated_insertSelective",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.anexo_cementerio
	 * @ibatorgenerated  Mon Jul 11 14:45:21 CEST 2011
	 */
	public List selectByExample(AnexoCementerioExample example) throws SQLException {
		List list = getSqlMapClientTemplate().queryForList(
				"cementerio_anexo_cementerio.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.anexo_cementerio
	 * @ibatorgenerated  Mon Jul 11 14:45:21 CEST 2011
	 */
	public AnexoCementerio selectByPrimaryKey(AnexoCementerioKey key) throws SQLException {
		AnexoCementerio record = (AnexoCementerio) getSqlMapClientTemplate()
				.queryForObject(
						"cementerio_anexo_cementerio.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.anexo_cementerio
	 * @ibatorgenerated  Mon Jul 11 14:45:21 CEST 2011
	 */
	public int updateByExampleSelective(AnexoCementerio record,
			AnexoCementerioExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("cementerio_anexo_cementerio.ibatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.anexo_cementerio
	 * @ibatorgenerated  Mon Jul 11 14:45:21 CEST 2011
	 */
	public int updateByExample(AnexoCementerio record,
			AnexoCementerioExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"cementerio_anexo_cementerio.ibatorgenerated_updateByExample",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.anexo_cementerio
	 * @ibatorgenerated  Mon Jul 11 14:45:21 CEST 2011
	 */
	public int updateByPrimaryKeySelective(AnexoCementerio record) throws SQLException {
		int rows = getSqlMapClientTemplate()
				.update("cementerio_anexo_cementerio.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.anexo_cementerio
	 * @ibatorgenerated  Mon Jul 11 14:45:21 CEST 2011
	 */
	public int updateByPrimaryKey(AnexoCementerio record) throws SQLException {
		int rows = getSqlMapClientTemplate()
				.update("cementerio_anexo_cementerio.ibatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table cementerio.anexo_cementerio
	 * @ibatorgenerated  Mon Jul 11 14:45:21 CEST 2011
	 */
	private static class UpdateByExampleParms extends AnexoCementerioExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				AnexoCementerioExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}