/**
 * BloqueDAOImpl.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.geopista.app.cementerios.business.dao.implementations;

import java.sql.SQLException;
import java.util.List;

import com.geopista.app.cementerios.business.dao.DAO;
import com.geopista.app.cementerios.business.dao.interfaces.BloqueDAO;
import com.geopista.app.cementerios.business.vo.Bloque;
import com.geopista.app.cementerios.business.vo.BloqueExample;

public class BloqueDAOImpl extends DAO  implements BloqueDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.bloque
	 * @ibatorgenerated  Wed Jun 01 17:30:57 CEST 2011
	 */
	public BloqueDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.bloque
	 * @throws SQLException 
	 * @ibatorgenerated  Wed Jun 01 17:30:57 CEST 2011
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		Bloque key = new Bloque();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"cementerio_bloque.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.bloque
	 * @throws SQLException 
	 * @ibatorgenerated  Wed Jun 01 17:30:57 CEST 2011
	 */
	public Integer insert(Bloque record) throws SQLException {
		Object newKey = getSqlMapClientTemplate().insert(
				"cementerio_bloque.ibatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.bloque
	 * @throws SQLException 
	 * @ibatorgenerated  Wed Jun 01 17:30:57 CEST 2011
	 */
	public Integer insertSelective(Bloque record) throws SQLException {
		Object newKey = getSqlMapClientTemplate().insert(
				"cementerio_bloque.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.bloque
	 * @throws SQLException 
	 * @ibatorgenerated  Wed Jun 01 17:30:57 CEST 2011
	 */
	public List selectByExample(BloqueExample example) throws SQLException {
		List list = getSqlMapClientTemplate().queryForList(
				"cementerio_bloque.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.bloque
	 * @throws SQLException 
	 * @ibatorgenerated  Wed Jun 01 17:30:57 CEST 2011
	 */
	public Bloque selectByPrimaryKey(Integer id) throws SQLException {
		Bloque key = new Bloque();
		key.setId(id);
		Bloque record = (Bloque) getSqlMapClientTemplate().queryForObject(
				"cementerio_bloque.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.bloque
	 * @throws SQLException 
	 * @ibatorgenerated  Wed Jun 01 17:30:57 CEST 2011
	 */
	public int updateByPrimaryKeySelective(Bloque record) throws SQLException {
		int rows = getSqlMapClientTemplate()
				.update("cementerio_bloque.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.bloque
	 * @throws SQLException 
	 * @ibatorgenerated  Wed Jun 01 17:30:57 CEST 2011
	 */
	public int updateByPrimaryKey(Bloque record) throws SQLException {
		int rows = getSqlMapClientTemplate().update(
				"cementerio_bloque.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	public int selectByLastSeqKey() throws SQLException {
		Integer lastKey = (Integer) getSqlMapClientTemplate()
				.queryForObject(
						"cementerio_bloque.selectByLastSeqKey",
						null);
		return lastKey.intValue();
	}
	
	public List selectAll () throws SQLException{
		List list = getSqlMapClientTemplate()
		.queryForList(
				"cementerio_bloque.selectAll",
				null);
		return list;
	}
	
	public Bloque selectByFeature(Integer idFeature) throws SQLException {
		Bloque record = (Bloque) getSqlMapClientTemplate().queryForObject(
				"cementerio_bloque.selectByFeature", idFeature);
		return record;
	}	
	
}