/**
 * DatosFallecimientoDAOImpl.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.geopista.app.cementerios.business.dao.implementations;

import java.sql.SQLException;
import java.util.List;

import com.geopista.app.cementerios.business.dao.DAO;
import com.geopista.app.cementerios.business.dao.interfaces.DatosFallecimientoDAO;
import com.geopista.app.cementerios.business.vo.DatosFallecimiento;
import com.geopista.app.cementerios.business.vo.DatosFallecimientoExample;

public class DatosFallecimientoDAOImpl extends DAO implements DatosFallecimientoDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.datosfallecimiento
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	public DatosFallecimientoDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.datosfallecimiento
	 * @throws SQLException 
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	public int deleteByExample(DatosFallecimientoExample example) throws SQLException {
		int rows = getSqlMapClientTemplate()
				.delete("cementerio_datosfallecimiento.ibatorgenerated_deleteByExample",
						example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.datosfallecimiento
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		DatosFallecimiento key = new DatosFallecimiento();
		key.setId(id);
		int rows = getSqlMapClientTemplate()
				.delete("cementerio_datosfallecimiento.ibatorgenerated_deleteByPrimaryKey",
						key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.datosfallecimiento
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	public Integer insert(DatosFallecimiento record) throws SQLException {
		Object newKey = getSqlMapClientTemplate().insert(
				"cementerio_datosfallecimiento.ibatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.datosfallecimiento
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	public Integer insertSelective(DatosFallecimiento record) throws SQLException {
		Object newKey = getSqlMapClientTemplate()
				.insert("cementerio_datosfallecimiento.ibatorgenerated_insertSelective",
						record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.datosfallecimiento
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	public List selectByExample(DatosFallecimientoExample example) throws SQLException {
		List list = getSqlMapClientTemplate()
				.queryForList(
						"cementerio_datosfallecimiento.ibatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.datosfallecimiento
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	public DatosFallecimiento selectByPrimaryKey(Integer id) throws SQLException {
		DatosFallecimiento key = new DatosFallecimiento();
		key.setId(id);
		DatosFallecimiento record = (DatosFallecimiento) getSqlMapClientTemplate()
				.queryForObject(
						"cementerio_datosfallecimiento.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.datosfallecimiento
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	public int updateByExampleSelective(DatosFallecimiento record,
			DatosFallecimientoExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("cementerio_datosfallecimiento.ibatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.datosfallecimiento
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	public int updateByExample(DatosFallecimiento record,
			DatosFallecimientoExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("cementerio_datosfallecimiento.ibatorgenerated_updateByExample",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.datosfallecimiento
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	public int updateByPrimaryKeySelective(DatosFallecimiento record) throws SQLException {
		int rows = getSqlMapClientTemplate()
				.update("cementerio_datosfallecimiento.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.datosfallecimiento
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	public int updateByPrimaryKey(DatosFallecimiento record) throws SQLException {
		int rows = getSqlMapClientTemplate()
				.update("cementerio_datosfallecimiento.ibatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table cementerio.datosfallecimiento
	 * @ibatorgenerated  Wed Jul 27 11:11:23 CEST 2011
	 */
	private static class UpdateByExampleParms extends DatosFallecimientoExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				DatosFallecimientoExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	public int selectByLastSeqKey() throws SQLException {
		Integer lastKey = (Integer) getSqlMapClientTemplate()
				.queryForObject(
						"cementerio_datosfallecimiento.selectByLastSeqKey",
						null);
		return lastKey.intValue();
	}	
	
}