/**
 * PlazaDAOImpl.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.geopista.app.cementerios.business.dao.implementations;

import java.sql.SQLException;
import java.util.List;

import com.geopista.app.cementerios.business.dao.DAO;
import com.geopista.app.cementerios.business.dao.interfaces.PlazaDAO;
import com.geopista.app.cementerios.business.vo.Plaza;
import com.geopista.app.cementerios.business.vo.PlazaExample;

public class PlazaDAOImpl extends DAO implements PlazaDAO {

    /**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.plaza
	 * @ibatorgenerated  Thu May 19 17:05:05 CEST 2011
	 */
	public PlazaDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.plaza
	 * @ibatorgenerated  Thu May 19 17:05:05 CEST 2011
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		Plaza key = new Plaza();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"cementerio_plaza.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.plaza
	 * @ibatorgenerated  Thu May 19 17:05:05 CEST 2011
	 */
	public Integer insert(Plaza record) throws SQLException {
		Object newKey = getSqlMapClientTemplate().insert(
				"cementerio_plaza.ibatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.plaza
	 * @ibatorgenerated  Thu May 19 17:05:05 CEST 2011
	 */
	public Integer insertSelective(Plaza record) throws SQLException {
		Object newKey = getSqlMapClientTemplate().insert(
				"cementerio_plaza.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.plaza
	 * @ibatorgenerated  Thu May 19 17:05:05 CEST 2011
	 */
	public List selectByExample(PlazaExample example) throws SQLException {
		List list = getSqlMapClientTemplate().queryForList(
				"cementerio_plaza.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.plaza
	 * @ibatorgenerated  Thu May 19 17:05:05 CEST 2011
	 */
	public Plaza selectByPrimaryKey(Integer id) throws SQLException {
		Plaza key = new Plaza();
		key.setId(id);
		Plaza record = (Plaza) getSqlMapClientTemplate().queryForObject(
				"cementerio_plaza.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.plaza
	 * @ibatorgenerated  Thu May 19 17:05:05 CEST 2011
	 */
	public int updateByPrimaryKeySelective(Plaza record) throws SQLException {
		int rows = getSqlMapClientTemplate().update(
				"cementerio_plaza.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.plaza
	 * @ibatorgenerated  Thu May 19 17:05:05 CEST 2011
	 */
	public int updateByPrimaryKey(Plaza record) throws SQLException {
		int rows = getSqlMapClientTemplate().update(
				"cementerio_plaza.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	public int selectByLastSeqKey() throws SQLException {
		Integer lastKey = (Integer) getSqlMapClientTemplate()
				.queryForObject(
						"cementerio_plaza.selectByLastSeqKey",
						null);
		return lastKey.intValue();
	}
	
	public int selectCountPlazasAsignadas(Plaza record) throws SQLException {
		Integer numPlazas = (Integer) getSqlMapClientTemplate().
		queryForObject(
				"cementerio_plaza.selectCountPlazasAsignadas",
				record);
		return numPlazas.intValue();
	}
}



