package com.geopista.app.cementerios.business.vo;

public class elem_cementerio {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.elem_cementerio.id
	 * @ibatorgenerated  Fri Jun 10 13:12:03 CEST 2011
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.elem_cementerio.id_municipio
	 * @ibatorgenerated  Fri Jun 10 13:12:03 CEST 2011
	 */
	private Integer idMunicipio;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.elem_cementerio.tipo
	 * @ibatorgenerated  Fri Jun 10 13:12:03 CEST 2011
	 */
	private String tipo;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.elem_cementerio.nombre
	 * @ibatorgenerated  Fri Jun 10 13:12:03 CEST 2011
	 */
	private String nombre;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.elem_cementerio.entidad
	 * @ibatorgenerated  Fri Jun 10 13:12:03 CEST 2011
	 */
	private String entidad;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.elem_cementerio.id_cementerio
	 * @ibatorgenerated  Fri Jun 10 13:12:03 CEST 2011
	 */
	private Integer idCementerio;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column cementerio.elem_cementerio.subtipo
	 * @ibatorgenerated  Fri Jun 10 13:12:03 CEST 2011
	 */
	private String subtipo;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.elem_cementerio.id
	 * @return  the value of cementerio.elem_cementerio.id
	 * @ibatorgenerated  Fri Jun 10 13:12:03 CEST 2011
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.elem_cementerio.id
	 * @param id  the value for cementerio.elem_cementerio.id
	 * @ibatorgenerated  Fri Jun 10 13:12:03 CEST 2011
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.elem_cementerio.id_municipio
	 * @return  the value of cementerio.elem_cementerio.id_municipio
	 * @ibatorgenerated  Fri Jun 10 13:12:03 CEST 2011
	 */
	public Integer getIdMunicipio() {
		return idMunicipio;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.elem_cementerio.id_municipio
	 * @param idMunicipio  the value for cementerio.elem_cementerio.id_municipio
	 * @ibatorgenerated  Fri Jun 10 13:12:03 CEST 2011
	 */
	public void setIdMunicipio(Integer idMunicipio) {
		this.idMunicipio = idMunicipio;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.elem_cementerio.tipo
	 * @return  the value of cementerio.elem_cementerio.tipo
	 * @ibatorgenerated  Fri Jun 10 13:12:03 CEST 2011
	 */
	public String getTipo() {
		return tipo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.elem_cementerio.tipo
	 * @param tipo  the value for cementerio.elem_cementerio.tipo
	 * @ibatorgenerated  Fri Jun 10 13:12:03 CEST 2011
	 */
	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.elem_cementerio.nombre
	 * @return  the value of cementerio.elem_cementerio.nombre
	 * @ibatorgenerated  Fri Jun 10 13:12:03 CEST 2011
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.elem_cementerio.nombre
	 * @param nombre  the value for cementerio.elem_cementerio.nombre
	 * @ibatorgenerated  Fri Jun 10 13:12:03 CEST 2011
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.elem_cementerio.entidad
	 * @return  the value of cementerio.elem_cementerio.entidad
	 * @ibatorgenerated  Fri Jun 10 13:12:03 CEST 2011
	 */
	public String getEntidad() {
		return entidad;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.elem_cementerio.entidad
	 * @param entidad  the value for cementerio.elem_cementerio.entidad
	 * @ibatorgenerated  Fri Jun 10 13:12:03 CEST 2011
	 */
	public void setEntidad(String entidad) {
		this.entidad = entidad;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.elem_cementerio.id_cementerio
	 * @return  the value of cementerio.elem_cementerio.id_cementerio
	 * @ibatorgenerated  Fri Jun 10 13:12:03 CEST 2011
	 */
	public Integer getIdCementerio() {
		return idCementerio;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.elem_cementerio.id_cementerio
	 * @param idCementerio  the value for cementerio.elem_cementerio.id_cementerio
	 * @ibatorgenerated  Fri Jun 10 13:12:03 CEST 2011
	 */
	public void setIdCementerio(Integer idCementerio) {
		this.idCementerio = idCementerio;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column cementerio.elem_cementerio.subtipo
	 * @return  the value of cementerio.elem_cementerio.subtipo
	 * @ibatorgenerated  Fri Jun 10 13:12:03 CEST 2011
	 */
	public String getSubtipo() {
		return subtipo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column cementerio.elem_cementerio.subtipo
	 * @param subtipo  the value for cementerio.elem_cementerio.subtipo
	 * @ibatorgenerated  Fri Jun 10 13:12:03 CEST 2011
	 */
	public void setSubtipo(String subtipo) {
		this.subtipo = subtipo;
	}
}