/*
 * TareasPendientsJInternalFrame.java
 *
 * Created on 16 de noviembre de 2004, 17:34
 */

package com.geopista.app.ocupaciones.pendientes;

import org.apache.log4j.Logger;

import javax.swing.*;

import com.geopista.app.ocupaciones.IMultilingue;
import com.geopista.app.ocupaciones.CUtilidadesComponentes;
import com.geopista.app.ocupaciones.CMainOcupaciones;
import com.geopista.app.ocupaciones.CConstantesOcupaciones;

import java.io.StringWriter;
import java.io.PrintWriter;
import java.awt.*;

/**
 *
 * @author  charo
 */
public class TareasPendientesJInternalFrame extends javax.swing.JInternalFrame implements IMultilingue{
    private JFrame desktop;
    public TareasPendientesJPanel _tareasPendientesJPanel;

    Logger logger = Logger.getLogger(TareasPendientesJInternalFrame.class);


    /** Creates new form TareasPendientesJInternalFrame */
    public TareasPendientesJInternalFrame(JFrame desktop) {
        this.desktop= desktop;
        CUtilidadesComponentes.menuLicenciasSetEnabled(false, this.desktop);
        initComponents();
        renombrarComponentes();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        templateJScrollPane = new javax.swing.JScrollPane();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        _tareasPendientesJPanel= new TareasPendientesJPanel(this, this.desktop);
        templateJScrollPane.setViewportView(_tareasPendientesJPanel);

        getContentPane().add(templateJScrollPane, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        CConstantesOcupaciones.helpSetHomeID = "ocupacionesIntro";
        CUtilidadesComponentes.menuLicenciasSetEnabled(true, this.desktop);
    }//GEN-LAST:event_formInternalFrameClosed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane templateJScrollPane;
    // End of variables declaration//GEN-END:variables

    public void renombrarComponentes() {

        try {
            setTitle(CMainOcupaciones.literales.getString("CTareasPendientes.JDialog.title"));
            _tareasPendientesJPanel.renombrarComponentes();
        } catch (Exception ex) {
            StringWriter sw = new StringWriter();
            PrintWriter pw = new PrintWriter(sw);
            ex.printStackTrace(pw);
            logger.error("Exception: " + sw.toString());
        }
    }


}
