/**
 * @(#) TimeListener.java	1.0	99/06/08
 *
 * This code is designed for JDK1.2 and JDK1.1.5
 * Use tab spacing 4. Follow JavaDoc convention while coding.
 * Mail any suggestions or bugs to unicman@iname.com
 */
package	com.geopista.app.utilidades.um.event;

/**
 * This interface is used for time filters. All the events generated by the
 * filter can be listen to using this listener.
 * 
 * @version	1.0 06/08/99
 * @author	UnicMan
 */
public interface TimeListener
{
	/**
	 * Event is generated when invalid time is entered by the user.
	 *
	 * @param	teEvt	time event object
	 */
	public void gotInvalidTime( TimeEvent teEvt );
}
