/**
 * GeopistaEntidadesMunicipiosKey.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.localgis.web.core.model;

public class GeopistaEntidadesMunicipiosKey {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column public.entidades_municipios.id_entidad
	 * @ibatorgenerated  Thu Mar 31 17:21:03 CEST 2011
	 */
	private Integer idEntidad;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column public.entidades_municipios.id_municipio
	 * @ibatorgenerated  Thu Mar 31 17:21:03 CEST 2011
	 */
	private Integer idMunicipio;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column public.entidades_municipios.id_entidad
	 * @return  the value of public.entidades_municipios.id_entidad
	 * @ibatorgenerated  Thu Mar 31 17:21:03 CEST 2011
	 */
	public Integer getIdEntidad() {
		return idEntidad;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column public.entidades_municipios.id_entidad
	 * @param idEntidad  the value for public.entidades_municipios.id_entidad
	 * @ibatorgenerated  Thu Mar 31 17:21:03 CEST 2011
	 */
	public void setIdEntidad(Integer idEntidad) {
		this.idEntidad = idEntidad;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column public.entidades_municipios.id_municipio
	 * @return  the value of public.entidades_municipios.id_municipio
	 * @ibatorgenerated  Thu Mar 31 17:21:03 CEST 2011
	 */
	public Integer getIdMunicipio() {
		return idMunicipio;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column public.entidades_municipios.id_municipio
	 * @param idMunicipio  the value for public.entidades_municipios.id_municipio
	 * @ibatorgenerated  Thu Mar 31 17:21:03 CEST 2011
	 */
	public void setIdMunicipio(Integer idMunicipio) {
		this.idMunicipio = idMunicipio;
	}
}