/**
 * GeopistaEntidadSupramunicipal.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.localgis.web.core.model;

public class GeopistaEntidadSupramunicipal {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column public.entidad_supramunicipal.id_entidad
     *
     * @ibatorgenerated Thu Jul 09 10:50:43 CEST 2009
     */
    private Integer idEntidad;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column public.entidad_supramunicipal.nombreoficial
     *
     * @ibatorgenerated Thu Jul 09 10:50:43 CEST 2009
     */
    private String nombreoficial;

    private Integer srid;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column public.entidad_supramunicipal.id_entidad
     *
     * @return the value of public.entidad_supramunicipal.id_entidad
     *
     * @ibatorgenerated Thu Jul 09 10:50:43 CEST 2009
     */
    public Integer getIdEntidad() {
        return idEntidad;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column public.entidad_supramunicipal.id_entidad
     *
     * @param idEntidad the value for public.entidad_supramunicipal.id_entidad
     *
     * @ibatorgenerated Thu Jul 09 10:50:43 CEST 2009
     */
    public void setIdEntidad(Integer idEntidad) {
        this.idEntidad = idEntidad;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column public.entidad_supramunicipal.nombreoficial
     *
     * @return the value of public.entidad_supramunicipal.nombreoficial
     *
     * @ibatorgenerated Thu Jul 09 10:50:43 CEST 2009
     */
    public String getNombreoficial() {
        return nombreoficial;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column public.entidad_supramunicipal.nombreoficial
     *
     * @param nombreoficial the value for public.entidad_supramunicipal.nombreoficial
     *
     * @ibatorgenerated Thu Jul 09 10:50:43 CEST 2009
     */
    public void setNombreoficial(String nombreoficial) {
        this.nombreoficial = nombreoficial;
    }

    public String getSrid() {
    	if (srid != null) return srid.toString();
    	return null;
    }

    public void setSrid(Integer srid) {
        this.srid = srid;
    }
    
}