/**
 * LocalgisLegend.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.localgis.web.core.model;

import java.io.Serializable;

public class LocalgisLegend extends LocalgisLegendKey implements Serializable {

	private static final long serialVersionUID = 1L;
	
	private byte[] img;

    public LocalgisLegend() {
    }
    
    public LocalgisLegend(Integer layeridgeopista, Integer identidad, Short mappublic, byte[] img) {
        super(layeridgeopista, identidad, mappublic);
        this.img = img;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column localgisguiaurbana.legend.img
     * @return  the value of localgisguiaurbana.legend.img
     * @abatorgenerated  Thu Oct 25 10:57:24 CEST 2007
     */
    public byte[] getImg() {
	return img;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column localgisguiaurbana.legend.img
     * @param img  the value for localgisguiaurbana.legend.img
     * @abatorgenerated  Thu Oct 25 10:57:24 CEST 2007
     */
    public void setImg(byte[] img) {
	this.img = img;
    }
}