/**
 * LocalgisCSS.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.localgis.web.core.model;

public class LocalgisCSS {
    
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column localgisguiaurbana.css.identidad
     *
     * @abatorgenerated Tue Nov 13 08:59:50 CET 2007
     */
    private Integer identidad;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column localgisguiaurbana.css.content
     *
     * @abatorgenerated Tue Nov 13 08:59:50 CET 2007
     */
    private String content;

    public LocalgisCSS() {
    }
    
    public LocalgisCSS(Integer identidad, String content) {
        super();
        this.identidad = identidad;
        this.content = content;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column localgisguiaurbana.css.identidad
     *
     * @return the value of localgisguiaurbana.css.idmunicipio
     *
     * @abatorgenerated Tue Nov 13 08:59:50 CET 2007
     */
    public Integer getIdentidad() {
        return identidad;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column localgisguiaurbana.css.identidad
     *
     * @param identidad the value for localgisguiaurbana.css.identidad
     *
     * @abatorgenerated Tue Nov 13 08:59:50 CET 2007
     */
    public void setIdentidad(Integer identidad) {
        this.identidad = identidad;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column localgisguiaurbana.css.content
     *
     * @return the value of localgisguiaurbana.css.content
     *
     * @abatorgenerated Tue Nov 13 08:59:50 CET 2007
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column localgisguiaurbana.css.content
     *
     * @param content the value for localgisguiaurbana.css.content
     *
     * @abatorgenerated Tue Nov 13 08:59:50 CET 2007
     */
    public void setContent(String content) {
        this.content = content;
    }

}