/**
 * LocalgisLegendKey.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.localgis.web.core.model;

import com.localgis.web.core.ConstantesSQL;

public class LocalgisLegendKey {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column localgisguiaurbana.legend.layeridgeopista
     * @abatorgenerated  Thu Oct 25 10:57:24 CEST 2007
     */
    private Integer layeridgeopista;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column localgisguiaurbana.legend.identidad
     * @abatorgenerated  Thu Oct 25 10:57:24 CEST 2007
     */
    private Integer identidad;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column localgisguiaurbana.legend.mappublic
     * @abatorgenerated  Thu Oct 25 10:57:24 CEST 2007
     */
    private Short mappublic;

    public LocalgisLegendKey() {
    }
    
    public LocalgisLegendKey(Integer layeridgeopista, Integer identidad, Short mappublic) {
        super();
        this.layeridgeopista = layeridgeopista;
        this.identidad = identidad;
        this.mappublic = mappublic;
    }

    /*
     * El metodo no es sobrecargado para evitar problemas con ibatis a la hora de devolver un resultMap
     */
    public void setMappublicBoolean(Boolean mappublic) {
        if (mappublic != null && mappublic.booleanValue()) {
            this.mappublic = ConstantesSQL.TRUE;
        } else {
            this.mappublic = ConstantesSQL.FALSE;
        }
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column localgisguiaurbana.legend.layeridgeopista
     * @return  the value of localgisguiaurbana.legend.layeridgeopista
     * @abatorgenerated  Thu Oct 25 10:57:24 CEST 2007
     */
    public Integer getLayeridgeopista() {
	return layeridgeopista;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column localgisguiaurbana.legend.layeridgeopista
     * @param layeridgeopista  the value for localgisguiaurbana.legend.layeridgeopista
     * @abatorgenerated  Thu Oct 25 10:57:24 CEST 2007
     */
    public void setLayeridgeopista(Integer layeridgeopista) {
	this.layeridgeopista = layeridgeopista;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column localgisguiaurbana.legend.identidad
     * @return  the value of localgisguiaurbana.legend.identidad
     * @abatorgenerated  Thu Oct 25 10:57:24 CEST 2007
     */
    public Integer getIdentidad() {
	return identidad;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column localgisguiaurbana.legend.identidad
     * @param identidad  the value for localgisguiaurbana.legend.identidad
     * @abatorgenerated  Thu Oct 25 10:57:24 CEST 2007
     */
    public void setIdentidad(Integer identidad) {
	this.identidad = identidad;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column localgisguiaurbana.legend.mappublic
     * @return  the value of localgisguiaurbana.legend.mappublic
     * @abatorgenerated  Thu Oct 25 10:57:24 CEST 2007
     */
    public Short getMappublic() {
	return mappublic;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column localgisguiaurbana.legend.mappublic
     * @param mappublic  the value for localgisguiaurbana.legend.mappublic
     * @abatorgenerated  Thu Oct 25 10:57:24 CEST 2007
     */
    public void setMappublic(Short mappublic) {
	this.mappublic = mappublic;
    }
}