/**
 * HistoricoDifuntoJDialog.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.geopista.app.cementerios.panel;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.Vector;

import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableColumn;

import com.geopista.app.AppContext;
import com.geopista.app.cementerios.Constantes;
import com.geopista.app.cementerios.ElemJTableModel;
import com.geopista.app.utilidades.TableSorted;
import com.geopista.protocol.cementerios.DatosFallecimientoBean;
import com.geopista.protocol.cementerios.DifuntoBean;
import com.geopista.protocol.cementerios.HistoricoDifuntoBean;
import com.geopista.protocol.cementerios.PersonaBean;
import com.geopista.util.ApplicationContext;

/**
 *
 * @author yraton
 */
public class HistoricoDifuntoJDialog extends javax.swing.JDialog {

	private org.apache.log4j.Logger logger= org.apache.log4j.Logger.getLogger(HistoricoDifuntoJDialog.class);

	private static final long serialVersionUID = 1L;

	
	private String operacion;
	private String tipo;
    private ApplicationContext aplicacion;
    private javax.swing.JFrame desktop;
    private DifuntoBean difuntoSelected;

	private BotoneraAceptarCancelarJPanel botoneraAceptarCancelarJPanel;
	

	public static final String DOBLE_CLICK="DOBLE_CLICK";

	/**Difuntos**/
	private ArrayList listaHistorico;
    private ArrayList<HistoricoDifuntoBean> listaHistoricoTabla;
    
    private ElemJTableModel historicoDifuntosJTableModel;
    private TableSorted tableHistoricoDifuntosSorted;
    private int selectedHistoricoDifuntoRow= -1;
	private HistoricoDifuntoBean historicoSelected;

	private Vector vgrupos = new Vector();
	
	private int patronContenedor = 1;
	
	private ArrayList actionListeners= new ArrayList();
    private String locale;
    

    /** Creates new form InhumacionJDialog */
    public HistoricoDifuntoJDialog (JFrame desktop, String locale, String operacion,String tipo, DifuntoBean difuntoSelected, ArrayList listaHistorico) throws Exception{
    	super(desktop);
        this.desktop= desktop;
        this.locale= locale;
        this.operacion= operacion;
        this.tipo=tipo;
        this.listaHistorico = listaHistorico;
        this.difuntoSelected = difuntoSelected;
        inicializar();
    }

    /** Creates new form BloqueJDialog */
    public HistoricoDifuntoJDialog(JFrame desktop, String locale) throws Exception{
        super(desktop);
        this.desktop= desktop;
        this.locale= locale;
        inicializar();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
 
    private void inicializar() {

    	this.aplicacion = (AppContext) AppContext.getApplicationContext();
        getContentPane().setLayout(new BorderLayout());
        renombrarComponentes();
        setModal(true);

        desktop = new javax.swing.JFrame();

        DefuncionJPanel = new javax.swing.JPanel();
        DatosGeneralesComunesJPanel = new javax.swing.JPanel();
        entidadJLabel = new javax.swing.JLabel();
        cementerioJLabel = new javax.swing.JLabel();
        entidadJTextField = new javax.swing.JTextField();
        cementerioJTextField = new javax.swing.JTextField();
        DatosDifuntoJPanel = new javax.swing.JPanel();
        DNIJLabel = new javax.swing.JLabel();
        DNIJTextField = new javax.swing.JTextField();
        NombreJLabel = new javax.swing.JLabel();
        codigoJLabel = new javax.swing.JLabel();
        codigoJTextField = new javax.swing.JTextField();
        grupoJLabel = new javax.swing.JLabel();
        grupoJComboBox = new javax.swing.JComboBox();
        medicoJLabel = new javax.swing.JLabel();
        medicoJTextField = new javax.swing.JTextField();
        domicilioJLabel = new javax.swing.JLabel();
        domicilioJTextField = new javax.swing.JTextField();
        poblacionDifuntoJLabel = new javax.swing.JLabel();
        poblacionDifuntoJTextField = new javax.swing.JTextField();
        datosDifuntoJSeparator = new javax.swing.JSeparator();
        nombreJTextField = new javax.swing.JTextField();
        numColegiadoJLabel = new javax.swing.JLabel();
        numColegiadoJTextField = new javax.swing.JTextField();
        regCivilJTextField = new javax.swing.JTextField();
        regiCivilJLabel = new javax.swing.JLabel();
        apellido2JTextField = new javax.swing.JTextField();
        apellido2JLabel = new javax.swing.JLabel();
        apellido1JTextField = new javax.swing.JTextField();
        apellido1JLabel = new javax.swing.JLabel();
        sexolJLabel = new javax.swing.JLabel();
        mujerJCheckBox = new javax.swing.JCheckBox();
        hombreJCheckBox = new javax.swing.JCheckBox();
        estadoCivilJLabel1 = new javax.swing.JLabel();
        solteroJCheckBox = new javax.swing.JCheckBox();
        casadoJCheckBox = new javax.swing.JCheckBox();
        DPersonaFisicaJPanel = new javax.swing.JPanel();
        fNacimientoJLabel = new javax.swing.JLabel();
        fechaFallecimientoJLabel = new javax.swing.JLabel();
        
        fNacimientoJLabel = new javax.swing.JLabel();
        fNacimientoJTextField = new JDateChooser(new Date());
        fNacimientoJTextField.setDateFormatString("dd/MM/yyyy");
        
        fechaFallecimientoJLabel = new javax.swing.JLabel();
        fFallecimientoJTextField = new JDateChooser(new Date());
        fFallecimientoJTextField.setDateFormatString("dd/MM/yyyy");
        
        RefFallecimientoJLabel = new javax.swing.JLabel();
        RefFallecimientoJTextField = new javax.swing.JTextField();
        edadDifuntoJLabel2 = new javax.swing.JLabel();
        edadDifuntoJTextField1 = new javax.swing.JTextField();
        DFallecimientoJPanel = new javax.swing.JPanel();
        causaFundamentalJLabel = new javax.swing.JLabel();
        causaFundamentalJTextField = new javax.swing.JTextField();
        causaInmediataJLabel = new javax.swing.JLabel();
        causaInmediataJTextField = new javax.swing.JTextField();
        lugarDefuncionJLabel = new javax.swing.JLabel();
        lugarDefuncionJTextField = new javax.swing.JTextField();
        
        historicosJPanel = new javax.swing.JPanel();
        historicoJScrollPane = new javax.swing.JScrollPane();
        historicosTableJTable = new javax.swing.JTable();
        
        DefuncionJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DatosGeneralesComunesJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        DatosGeneralesComunesJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entidadJLabel.setText("Entidad");
        DatosGeneralesComunesJPanel.add(entidadJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        cementerioJLabel.setText("Cementerio");
        DatosGeneralesComunesJPanel.add(cementerioJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        entidadJTextField.setText("");
        DatosGeneralesComunesJPanel.add(entidadJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 780, -1));

        cementerioJTextField.setText("");
        DatosGeneralesComunesJPanel.add(cementerioJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 780, -1));

        DefuncionJPanel.add(DatosGeneralesComunesJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 870, 70));

        DatosDifuntoJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        DatosDifuntoJPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DatosDifuntoJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DNIJLabel.setText("DNI/NIF");
        DatosDifuntoJPanel.add(DNIJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 24, -1, -1));

        DNIJTextField.setText("");
        DatosDifuntoJPanel.add(DNIJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 21, 94, -1));

        NombreJLabel.setText("Nombre");
        DatosDifuntoJPanel.add(NombreJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 24, -1, -1));

        codigoJLabel.setText("Codigo");
        DatosDifuntoJPanel.add(codigoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 53, -1, -1));

        codigoJTextField.setText("");
        DatosDifuntoJPanel.add(codigoJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 150, -1));

        grupoJLabel.setText("Grupo");
        DatosDifuntoJPanel.add(grupoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 53, 30, -1));

        //botonera, tamaño por defecto y 
        
        botoneraAceptarCancelarJPanel= new BotoneraAceptarCancelarJPanel();
        botoneraAceptarCancelarJPanel.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(ActionEvent e){
  				botoneraAceptarCancelarJPanel_actionPerformed();
  			}
  		});

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        
        setSize(820, 820);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        grupoJLabel.setText("grupo");
        
        vgrupos.add(new String("Grupo 1"));
        vgrupos.add(new String("Grupo 2"));
        grupoJComboBox = new JComboBox(vgrupos);
        grupoJComboBox.setSelectedIndex(1);
        
        grupoJComboBox.addActionListener(new java.awt.event.ActionListener(){
  		public void actionPerformed(ActionEvent e){
  			JComboBox cb = (JComboBox)e.getSource();
  			String strgrupo  =  (String) cb.getSelectedItem();
  			int grupo; 
  			if (strgrupo.equalsIgnoreCase("Grupo 1")){
  				grupo = 1;
  			}else{
  				grupo = 2;
  			}
        	if (difuntoSelected == null) difuntoSelected = new DifuntoBean(); 
        		difuntoSelected.setGrupo(grupo);
  			}
        });
        
        DatosDifuntoJPanel.add(grupoJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 48, 151, -1));

        medicoJLabel.setText("Médico");
        DatosDifuntoJPanel.add(medicoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 120, 36, -1));
        DatosDifuntoJPanel.add(medicoJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 120, 297, -1));

        domicilioJLabel.setText("Domicilio");
        DatosDifuntoJPanel.add(domicilioJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 84, -1, -1));

        domicilioJTextField.setText("");
        DatosDifuntoJPanel.add(domicilioJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 81, 338, -1));

        poblacionDifuntoJLabel.setText("Poblacion");
        DatosDifuntoJPanel.add(poblacionDifuntoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 81, -1, -1));

        poblacionDifuntoJTextField.setText("");
        DatosDifuntoJPanel.add(poblacionDifuntoJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 81, 391, -1));
        DatosDifuntoJPanel.add(datosDifuntoJSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 112, 824, -1));

        nombreJTextField.setText("Nombre");
        DatosDifuntoJPanel.add(nombreJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 150, -1));

        numColegiadoJLabel.setText("Num Colegiado");
        DatosDifuntoJPanel.add(numColegiadoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 123, -1, -1));
        DatosDifuntoJPanel.add(numColegiadoJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 120, 156, -1));
        DatosDifuntoJPanel.add(regCivilJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(706, 120, 150, -1));

        regiCivilJLabel.setText("Registro Civil");
        DatosDifuntoJPanel.add(regiCivilJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 123, 68, -1));
        DatosDifuntoJPanel.add(apellido2JTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 150, -1));

        apellido2JLabel.setText("2º Apellido");
        DatosDifuntoJPanel.add(apellido2JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 24, 60, -1));
        DatosDifuntoJPanel.add(apellido1JTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 150, -1));

        apellido1JLabel.setText("1º Apellido");
        DatosDifuntoJPanel.add(apellido1JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 24, 60, -1));

        sexolJLabel.setText("Sexo: ");
        DatosDifuntoJPanel.add(sexolJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 55, -1, -1));

        mujerJCheckBox.setText("Mujer");
        mujerJCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mujerJCheckBoxActionPerformed(evt);
            }
        });
        DatosDifuntoJPanel.add(mujerJCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 51, -1, -1));

        hombreJCheckBox.setText("Hombre");
        hombreJCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hombreJCheckBoxActionPerformed(evt);
            }
        });
        DatosDifuntoJPanel.add(hombreJCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 51, -1, -1));

        estadoCivilJLabel1.setText("EstadoCivil:");
        DatosDifuntoJPanel.add(estadoCivilJLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 55, -1, -1));

        solteroJCheckBox.setText("Soltero");
        solteroJCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solteroJCheckBoxActionPerformed(evt);
            }
        });
        DatosDifuntoJPanel.add(solteroJCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 51, -1, -1));

        casadoJCheckBox.setText("Casado");
        casadoJCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casadoJCheckBoxActionPerformed(evt);
            }
        });
        DatosDifuntoJPanel.add(casadoJCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 51, -1, -1));

        DefuncionJPanel.add(DatosDifuntoJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 870, 150));

        DPersonaFisicaJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        DPersonaFisicaJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fNacimientoJLabel.setText("Fecha Nacimiento");
        DPersonaFisicaJPanel.add(fNacimientoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 20, -1, -1));
        DPersonaFisicaJPanel.add(fNacimientoJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 17, 173, -1));

        fechaFallecimientoJLabel.setText("Fecha Fallecimiento");
        DPersonaFisicaJPanel.add(fechaFallecimientoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 44, -1, -1));

        DPersonaFisicaJPanel.add(fFallecimientoJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 41, 173, -1));

        RefFallecimientoJLabel.setText("Ref. Fallecimiento");
        DPersonaFisicaJPanel.add(RefFallecimientoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        DPersonaFisicaJPanel.add(RefFallecimientoJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 67, 173, -1));

        edadDifuntoJLabel2.setText("Edad difunto");
        DPersonaFisicaJPanel.add(edadDifuntoJLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 36, 70, 20));

        edadDifuntoJTextField1.setText("");
        DPersonaFisicaJPanel.add(edadDifuntoJTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 40, 20));

        DefuncionJPanel.add(DPersonaFisicaJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 410, 110));

        DFallecimientoJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        DFallecimientoJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        causaFundamentalJLabel.setText("Causa Fundamental");
        DFallecimientoJPanel.add(causaFundamentalJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 22, -1, -1));
        DFallecimientoJPanel.add(causaFundamentalJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 19, 311, -1));

        causaInmediataJLabel.setText("Causa Inmediata");
        DFallecimientoJPanel.add(causaInmediataJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 48, -1, -1));
        DFallecimientoJPanel.add(causaInmediataJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 45, 311, -1));

        lugarDefuncionJLabel.setText("Lugar defunción");
        DFallecimientoJPanel.add(lugarDefuncionJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 74, -1, -1));
        DFallecimientoJPanel.add(lugarDefuncionJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 71, 311, -1));

        DefuncionJPanel.add(DFallecimientoJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 450, 110));

        //PANEL Historico
        listaHistoricoTabla = new ArrayList<HistoricoDifuntoBean>();
        
        historicosJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Histórico Operaciones"));
        historicosJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        historicosTableJTable = new ElemTableRender(6); 
        historicosTableJTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        
        initHeadersHistoricoDifuntoJTable();
        
        /* Ordenacion de la tabla */
        tableHistoricoDifuntosSorted= new TableSorted(historicoDifuntosJTableModel);
        historicoDifuntosJTableModel.setTableSorted(tableHistoricoDifuntosSorted);
        tableHistoricoDifuntosSorted.setTableHeader(historicosTableJTable.getTableHeader());
        historicosTableJTable.setModel(tableHistoricoDifuntosSorted);
        historicosTableJTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        historicosTableJTable.setCellSelectionEnabled(false);
        historicosTableJTable.setColumnSelectionAllowed(false);
        historicosTableJTable.setRowSelectionAllowed(true);
        historicosTableJTable.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

        historicosTableJTable.getTableHeader().setReorderingAllowed(false);
        
        setInvisible(historicoDifuntosJTableModel.getColumnCount()-1,historicosTableJTable);
        historicoDifuntosJTableModel.setTable(historicosTableJTable);
        
        if (listaHistorico != null){
        	historicoDifuntosJTableModel.setModelData(listaHistorico);      	
  	  	}
        
        historicosTableJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
            	elemHistoricosJTableMouseReleased();
            }
            public void mouseClicked(java.awt.event.MouseEvent evt){
            	if(evt.getClickCount() == 2) {
            		getHistoricoSeleccionado();
            		for (Iterator <ActionListener>i = actionListeners.iterator(); i.hasNext();) {
                        ActionListener l = (ActionListener) i.next();
                        l.actionPerformed(new ActionEvent(this, 0, DOBLE_CLICK));
                    }
                }
            }
        });

        historicoJScrollPane.setViewportView(historicosTableJTable);
        
        
        historicoJScrollPane.setViewportView(historicosTableJTable);
        historicosJPanel.add(historicoJScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 860, 120)); //(10, 10, 860, 100)
        
        DefuncionJPanel.add(historicosJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 880, 150)); //(10, 260, 880, 150));
        
        getContentPane().add(DefuncionJPanel, java.awt.BorderLayout.CENTER);
        getContentPane().add(botoneraAceptarCancelarJPanel, java.awt.BorderLayout.SOUTH);

        pack();
        
    }


    private void mujerJCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {
        if (mujerJCheckBox.isSelected()){
        	PersonaBean dif;
        	if (difuntoSelected.getPersona() != null){
        		dif = difuntoSelected.getPersona();
        	}else{
        		dif = new PersonaBean();
        	}
        	dif.setSexo(Constantes.SEXO_MUJER);
        	difuntoSelected.setPersona(dif);
        }
    }

    private void hombreJCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {
        if (hombreJCheckBox.isSelected()){
        	PersonaBean dif;
        	if (difuntoSelected.getPersona() != null){
        		dif = difuntoSelected.getPersona();
        	}else{
        		dif = new PersonaBean();
        	}
        	dif.setSexo(Constantes.SEXO_HOMBRE);
        	difuntoSelected.setPersona(dif);
        }
    }

    private void solteroJCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {
        if (solteroJCheckBox.isSelected()){
        	PersonaBean dif;
        	if (difuntoSelected.getPersona() != null){
        		dif = difuntoSelected.getPersona();
        	}else{
        		dif = new PersonaBean();
        	}
        	dif.setEstado_civil(Constantes.ESTADO_CIVIL_SOLTERO);
        	difuntoSelected.setPersona(dif);
        }
    }


    private void casadoJCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {
        if (casadoJCheckBox.isSelected()){
        	PersonaBean dif;
        	if (difuntoSelected.getPersona() != null){
        		dif = difuntoSelected.getPersona();
        	}else{
        		dif = new PersonaBean();
        	}
        	dif.setEstado_civil(Constantes.ESTADO_CIVIL_CASADO);
        	difuntoSelected.setPersona(dif);
        }
    }
    

	public void load(DifuntoBean defuncionElem, boolean editable) {
		if (defuncionElem == null)
			return;
		
		cementerioJTextField.setText(defuncionElem.getNombreCementerio() != null ?  defuncionElem.getNombreCementerio() : "");
		entidadJTextField.setText(defuncionElem.getEntidad() != null ?  defuncionElem.getEntidad() : "");
		
        if(operacion == null) return;

        loadDatosDifunto(defuncionElem, editable);
        loadDatosDefuncion(defuncionElem, editable);
        	
    	fFallecimientoJTextField.setDate(defuncionElem.getFecha_defuncion()!= null ? defuncionElem.getFecha_defuncion() : new Date());
    	fFallecimientoJTextField.setEnabled(editable);
    	
    	String strgrupo;
    	int grupo = defuncionElem.getGrupo();
    	if (grupo == 1){ strgrupo = "Grupo 1";}else{strgrupo= "Grupo 2";}
    	
		for (int i = 0; i < vgrupos.size(); i++) {
			String node = (String) vgrupos.get(i);
			if (node.equalsIgnoreCase(strgrupo)){
				grupoJComboBox.setSelectedIndex(i);
			}
		}
		grupoJComboBox.setEnabled(editable);
		
		
		edadDifuntoJTextField1.setText(defuncionElem.getEdad()!= 0 ? String.valueOf(defuncionElem.getEdad()): "");
        edadDifuntoJTextField1.setEditable(editable);
        
        cementerioJTextField.setEditable(false);
        entidadJTextField.setEditable(false);
        
        codigoJTextField.setText(defuncionElem.getCodigo()!= null ? defuncionElem.getCodigo() : "");
        codigoJTextField.setEditable(editable);
        
        DatosDifuntoJPanel.setEnabled(editable);
		
	}
    
    public void loadDatosDefuncion(DifuntoBean defuncionElem, boolean editable){
    	
    	if (defuncionElem == null ) return ;
    	
    	DatosFallecimientoBean datosFallecimiento = defuncionElem.getDatosFallecimiento();
    	if (datosFallecimiento != null){
    		
        	causaFundamentalJTextField.setText(datosFallecimiento.getCausa_fundamental()!= null ? datosFallecimiento.getCausa_fundamental() : "");
    		causaFundamentalJTextField.setEditable(editable);
    		
    		causaInmediataJTextField.setText(datosFallecimiento.getCausa_inmediata()!= null ? datosFallecimiento.getCausa_inmediata() : "");
    		causaInmediataJTextField.setEditable(editable);
    		
    		fFallecimientoJTextField.setDate(datosFallecimiento.getFecha()!= null ? datosFallecimiento.getFecha() : new Date());
    		fFallecimientoJTextField.setEnabled(editable);
    		
    		medicoJTextField.setText(datosFallecimiento.getMedico()!= null ? datosFallecimiento.getMedico() : "");
    		medicoJTextField.setEditable(editable);
    		
    		numColegiadoJTextField.setText(datosFallecimiento.getNumColegiado()!= null ? datosFallecimiento.getNumColegiado() : "");
    		numColegiadoJTextField.setEditable(editable);
    			
    		regCivilJTextField.setText(datosFallecimiento.getRegistro_civil()!= null ? datosFallecimiento.getRegistro_civil() : "");
    		regCivilJTextField.setEditable(editable);
    		
    		RefFallecimientoJTextField.setText(datosFallecimiento.getReferencia_fallecimiento()!= null ? datosFallecimiento.getReferencia_fallecimiento() : "");
    		RefFallecimientoJTextField.setEditable(editable);
    	
    		lugarDefuncionJTextField.setText(datosFallecimiento.getLugar()!= null ? datosFallecimiento.getLugar(): "");
    		lugarDefuncionJTextField.setEditable(editable);

    		poblacionDifuntoJTextField.setText(datosFallecimiento.getPoblacion()!= null ? datosFallecimiento.getPoblacion() : "");
    		poblacionDifuntoJTextField.setEditable(editable);
    	}
    }   
	
    public void loadDatosDifunto(DifuntoBean defuncionElem, boolean editable){
    	
    	if (defuncionElem == null ) return ;
    	
    	PersonaBean persona = defuncionElem.getPersona();
    	if (persona != null){
    		
    		DNIJTextField.setText(persona.getDNI() != null ? persona.getDNI(): "");
    		DNIJTextField.setEditable(editable);
    		
    		nombreJTextField.setText(persona.getNombre() != null ? persona.getNombre() : "");
    		nombreJTextField.setEditable(editable);
    		
    		apellido1JTextField.setText(persona.getApellido1()!= null ? persona.getApellido1() : "");
    		apellido1JTextField.setEditable(editable);
    		
    		apellido2JTextField.setText(persona.getApellido2()!= null ? persona.getApellido2() : "");
    		apellido2JTextField.setEditable(editable);
    		
    		domicilioJTextField.setText(persona.getDomicilio()!= null ? persona.getDomicilio() : "");
    		domicilioJTextField.setEditable(editable);
    		
    		poblacionDifuntoJTextField.setText(persona.getPoblacion()!= null ? persona.getPoblacion() : "");
    		poblacionDifuntoJTextField.setEditable(editable);
    		
    		if ((persona.getSexo()!= null) && (persona.getSexo().equalsIgnoreCase(Constantes.SEXO_HOMBRE))){
    			hombreJCheckBox.setSelected(true);			
    		}else{
    			mujerJCheckBox.setSelected(true);
    		}
    		hombreJCheckBox.setEnabled(editable);
    		mujerJCheckBox.setEnabled(editable);
    		
    		if ((persona.getEstado_civil()!= null) && (persona.getEstado_civil().equalsIgnoreCase(Constantes.ESTADO_CIVIL_SOLTERO))){
    			solteroJCheckBox.setSelected(true);
    		}else{
    			casadoJCheckBox.setSelected(true);
    		}
    		
    		solteroJCheckBox.setEnabled(editable);
    		casadoJCheckBox.setEnabled(editable);
    		
    		fNacimientoJTextField.setDate(persona.getFecha_nacimiento()!= null ? persona.getFecha_nacimiento() : new Date());
    		fNacimientoJTextField.setEnabled(editable);

    		
    	}
    }
    

    public void renombrarComponentes(){
  }
    
    private void initHeadersHistoricoDifuntoJTable(){
	   	this.historicoDifuntosJTableModel= new ElemJTableModel(new String[]{"Operación", "Tipo", "Contenedor", "Fecha Operación", "Comentario", "HIDDEN"},
	   																	new boolean[]{false, false, false, false, false, false}, locale);		
	   }

    public Object getHistoricoSeleccionado(){
        
    	selectedHistoricoDifuntoRow= historicosTableJTable.getSelectedRow();
	    if (selectedHistoricoDifuntoRow == -1){ 
	        	return null;
        }else{
        	historicoDifuntosJTableModel.setTableSorted(historicoDifuntosJTableModel.getTableSorted());
        	historicoDifuntosJTableModel.setRows(historicoDifuntosJTableModel.getRows());
        	return historicoDifuntosJTableModel.getObjetAt(selectedHistoricoDifuntoRow);
        }
    }
 
    public void addActionListener(ActionListener l) {
        this.actionListeners.add(l);
    }

    public void removeActionListener(ActionListener l) {
        this.actionListeners.remove(l);
    }

    
    private void fireActionPerformed() {
        for (Iterator i = actionListeners.iterator(); i.hasNext();) {
            ActionListener l = (ActionListener) i.next();
            l.actionPerformed(new ActionEvent(this, 0, null));
        }
    }

    
    /* Método que abre una ventana de confirmacion sobre la operacion que se esta llevando a cabo
    */
   private boolean confirmOption(){
       int ok= -1;
       ok= JOptionPane.showConfirmDialog(this, aplicacion.getI18nString("cementerio.optionpane.tag1"), aplicacion.getI18nString("cementerio.optionpane.tag2"), JOptionPane.YES_NO_OPTION);
       if (ok == JOptionPane.NO_OPTION){
           return false;
       }
       return true;
   }

   private void exitForm(java.awt.event.WindowEvent evt) {
  	   fireActionPerformed();
   }

   private void elemHistoricosJTableMouseReleased() {
   	
       Object obj = getHistoricoSeleccionado();
       if (obj instanceof HistoricoDifuntoBean){
       	setHistoricoSelected((HistoricoDifuntoBean) getHistoricoSeleccionado());
       }
   }
   
   private void setInvisible(int column, JTable jTable){
       /** columna hidden no visible */
       TableColumn col= jTable.getColumnModel().getColumn(column);
       col.setResizable(false);
       col.setWidth(0);
       col.setMaxWidth(0);
       col.setMinWidth(0);
       col.setPreferredWidth(0);
   }
   
	public HistoricoDifuntoBean getHistoricoSelected() {
		return historicoSelected;
	}

	public void setHistoricoSelected(HistoricoDifuntoBean historicoSelected) {
		this.historicoSelected = historicoSelected;
	}
	
    public void botoneraAceptarCancelarJPanel_actionPerformed(){
  	
  	 if((!botoneraAceptarCancelarJPanel.aceptarPressed()) ||
          (botoneraAceptarCancelarJPanel.aceptarPressed() && operacion.equalsIgnoreCase(Constantes.OPERACION_MODIFICAR)?!confirmOption():false)){
      	historicoSelected= null;
      }
      else{
//      		actualizarDatosHistorico(historicoSelected);
        }
        fireActionPerformed();
    }    
    
    // Variables declaration - do not modify
    private javax.swing.JLabel DNIJLabel;
    private javax.swing.JPanel DatosDifuntoJPanel;
    private javax.swing.JTextField DNIJTextField;
    private javax.swing.JPanel DatosGeneralesComunesJPanel;
    private javax.swing.JLabel NombreJLabel;
    private javax.swing.JLabel apellido1JLabel;
    private javax.swing.JTextField apellido1JTextField;
    private javax.swing.JLabel apellido2JLabel;
    private javax.swing.JTextField apellido2JTextField;
    private javax.swing.JCheckBox casadoJCheckBox;
    private javax.swing.JLabel cementerioJLabel;
    private javax.swing.JLabel codigoJLabel;
    private javax.swing.JTextField codigoJTextField;
    private javax.swing.JSeparator datosDifuntoJSeparator;
    private javax.swing.JLabel domicilioJLabel;
    private javax.swing.JTextField domicilioJTextField;
    private javax.swing.JLabel entidadJLabel;
    private javax.swing.JLabel estadoCivilJLabel1;
    private javax.swing.JComboBox grupoJComboBox;
    private javax.swing.JLabel grupoJLabel;
    private javax.swing.JCheckBox hombreJCheckBox;
    private javax.swing.JTextField cementerioJTextField;
    private javax.swing.JTextField entidadJTextField;
    private javax.swing.JLabel medicoJLabel;
    private javax.swing.JTextField medicoJTextField;
    private javax.swing.JCheckBox mujerJCheckBox;
    private javax.swing.JTextField nombreJTextField;
    private javax.swing.JLabel numColegiadoJLabel;
    private javax.swing.JTextField numColegiadoJTextField;
    private javax.swing.JLabel poblacionDifuntoJLabel;
    private javax.swing.JTextField poblacionDifuntoJTextField;
    private javax.swing.JTextField regCivilJTextField;
    private javax.swing.JLabel regiCivilJLabel;
    private javax.swing.JLabel sexolJLabel;
    private javax.swing.JCheckBox solteroJCheckBox;

    private javax.swing.JScrollPane historicoJScrollPane;
    private javax.swing.JTable historicosTableJTable;
    private javax.swing.JPanel historicosJPanel;
    
    private javax.swing.JPanel DFallecimientoJPanel;
    private javax.swing.JPanel DPersonaFisicaJPanel;
    private javax.swing.JPanel DefuncionJPanel;
    private javax.swing.JLabel RefFallecimientoJLabel;
    private javax.swing.JTextField RefFallecimientoJTextField;
    private javax.swing.JLabel causaFundamentalJLabel;
    private javax.swing.JTextField causaFundamentalJTextField;
    private javax.swing.JLabel causaInmediataJLabel;
    private javax.swing.JTextField causaInmediataJTextField;
    private javax.swing.JLabel edadDifuntoJLabel2;
    private javax.swing.JTextField edadDifuntoJTextField1;
    private JDateChooser fFallecimientoJTextField;
    private javax.swing.JLabel fNacimientoJLabel;
    private JDateChooser fNacimientoJTextField;
    private javax.swing.JLabel fechaFallecimientoJLabel;
    private javax.swing.JLabel lugarDefuncionJLabel;
    private javax.swing.JTextField lugarDefuncionJTextField;
    // End of variables declaration
}
