package com.geopista.app.cementerios.business.dao.implementations;

import java.sql.SQLException;

import com.geopista.app.cementerios.business.dao.DAO;
import com.geopista.app.cementerios.business.dao.interfaces.LocalizacionDAO;
import com.geopista.app.cementerios.business.vo.Localizacion;

public class LocalizacionDAOImpl extends DAO implements LocalizacionDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.localizacion
	 * @ibatorgenerated  Tue May 03 16:38:46 CEST 2011
	 */
	public LocalizacionDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.localizacion
	 * @ibatorgenerated  Tue May 03 16:38:46 CEST 2011
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		Localizacion key = new Localizacion();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"cementerio_localizacion.ibatorgenerated_deleteByPrimaryKey",
				key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.localizacion
	 * @ibatorgenerated  Tue May 03 16:38:46 CEST 2011
	 */
	public Integer insert(Localizacion record) throws SQLException {
		Object newKey = getSqlMapClientTemplate().insert(
				"cementerio_localizacion.ibatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.localizacion
	 * @ibatorgenerated  Tue May 03 16:38:46 CEST 2011
	 */
	public Integer insertSelective(Localizacion record) throws SQLException {
		Object newKey = getSqlMapClientTemplate().insert(
				"cementerio_localizacion.ibatorgenerated_insertSelective",
				record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.localizacion
	 * @ibatorgenerated  Tue May 03 16:38:46 CEST 2011
	 */
	public Localizacion selectByPrimaryKey(Integer id) throws SQLException {
		Localizacion key = new Localizacion();
		key.setId(id);
		Localizacion record = (Localizacion) getSqlMapClientTemplate()
				.queryForObject(
						"cementerio_localizacion.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.localizacion
	 * @ibatorgenerated  Tue May 03 16:38:46 CEST 2011
	 */
	public int updateByPrimaryKeySelective(Localizacion record)  throws SQLException {
		int rows = getSqlMapClientTemplate()
				.update("cementerio_localizacion.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.localizacion
	 * @ibatorgenerated  Tue May 03 16:38:46 CEST 2011
	 */
	public int updateByPrimaryKey(Localizacion record)  throws SQLException {
		int rows = getSqlMapClientTemplate().update(
				"cementerio_localizacion.ibatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	public int selectByLastSeqKey() throws SQLException {
		Integer lastKey = (Integer) getSqlMapClientTemplate()
				.queryForObject(
						"cementerio_localizacion.selectByLastSeqKey",
						null);
		return lastKey.intValue();
	}

}