/**
 * EntidadlocalgisEntidadextKey.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.localgis.web.core.model;


public class EntidadlocalgisEntidadextKey {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column geowfst.entidadlocalgis_entidadext.id_entidad
	 * @ibatorgenerated  Mon Mar 28 17:18:31 CEST 2011
	 */
	private Integer idEntidad;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column geowfst.entidadlocalgis_entidadext.id_entidadext
	 * @ibatorgenerated  Mon Mar 28 17:18:31 CEST 2011
	 */
	private Integer idEntidadext;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column geowfst.entidadlocalgis_entidadext.id_entidad
	 * @return  the value of geowfst.entidadlocalgis_entidadext.id_entidad
	 * @ibatorgenerated  Mon Mar 28 17:18:31 CEST 2011
	 */
	public Integer getIdEntidad() {
		return idEntidad;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column geowfst.entidadlocalgis_entidadext.id_entidad
	 * @param idEntidad  the value for geowfst.entidadlocalgis_entidadext.id_entidad
	 * @ibatorgenerated  Mon Mar 28 17:18:31 CEST 2011
	 */
	public void setIdEntidad(Integer idEntidad) {
		this.idEntidad = idEntidad;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column geowfst.entidadlocalgis_entidadext.id_entidadext
	 * @return  the value of geowfst.entidadlocalgis_entidadext.id_entidadext
	 * @ibatorgenerated  Mon Mar 28 17:18:31 CEST 2011
	 */
	public Integer getIdEntidadext() {
		return idEntidadext;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column geowfst.entidadlocalgis_entidadext.id_entidadext
	 * @param idEntidadExt  the value for geowfst.entidadlocalgis_entidadext.id_entidadext
	 * @ibatorgenerated  Mon Mar 28 17:18:31 CEST 2011
	 */
	public void setIdEntidadext(Integer idEntidadExt) {
		this.idEntidadext = idEntidadExt;
	}
}