/**
 * ProcedurePropertyKey.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.localgis.web.core.model;

import java.io.Serializable;

public class ProcedurePropertyKey implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column geowfst.procedure_properties.id
     *
     * @ibatorgenerated Thu Mar 14 10:24:30 CET 2013
     */
    private String id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column geowfst.procedure_properties.property
     *
     * @ibatorgenerated Thu Mar 14 10:24:30 CET 2013
     */
    private String property;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column geowfst.procedure_properties.id
     *
     * @return the value of geowfst.procedure_properties.id
     *
     * @ibatorgenerated Thu Mar 14 10:24:30 CET 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column geowfst.procedure_properties.id
     *
     * @param id the value for geowfst.procedure_properties.id
     *
     * @ibatorgenerated Thu Mar 14 10:24:30 CET 2013
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column geowfst.procedure_properties.property
     *
     * @return the value of geowfst.procedure_properties.property
     *
     * @ibatorgenerated Thu Mar 14 10:24:30 CET 2013
     */
    public String getProperty() {
        return property;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column geowfst.procedure_properties.property
     *
     * @param property the value for geowfst.procedure_properties.property
     *
     * @ibatorgenerated Thu Mar 14 10:24:30 CET 2013
     */
    public void setProperty(String property) {
        this.property = property;
    }
}