/**
 * ProcedureDefaults.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.localgis.web.core.model;

import java.io.Serializable;

public class ProcedureDefaults implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column geowfst.procedure_defaults.id
     *
     * @ibatorgenerated Thu Mar 14 10:24:30 CET 2013
     */
    private String id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column geowfst.procedure_defaults.feature_name
     *
     * @ibatorgenerated Thu Mar 14 10:24:30 CET 2013
     */
    private String featureName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column geowfst.procedure_defaults.feature_toolbarname
     *
     * @ibatorgenerated Thu Mar 14 10:24:30 CET 2013
     */
    private String featureToolbarname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column geowfst.procedure_defaults.style_property
     *
     * @ibatorgenerated Thu Mar 14 10:24:30 CET 2013
     */
    private String styleProperty;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column geowfst.procedure_defaults.address_property
     *
     * @ibatorgenerated Thu Mar 14 10:24:30 CET 2013
     */
    private String addressProperty;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column geowfst.procedure_defaults.onfeatureunselecttext
     *
     * @ibatorgenerated Thu Mar 14 10:24:30 CET 2013
     */
    private String onfeatureunselecttext;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column geowfst.procedure_defaults.onnotfeatureinfotext
     *
     * @ibatorgenerated Thu Mar 14 10:24:30 CET 2013
     */
    private String onnotfeatureinfotext;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column geowfst.procedure_defaults.onnotfeaturesearchtext
     *
     * @ibatorgenerated Thu Mar 14 10:24:30 CET 2013
     */
    private String onnotfeaturesearchtext;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column geowfst.procedure_defaults.id
     *
     * @return the value of geowfst.procedure_defaults.id
     *
     * @ibatorgenerated Thu Mar 14 10:24:30 CET 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column geowfst.procedure_defaults.id
     *
     * @param id the value for geowfst.procedure_defaults.id
     *
     * @ibatorgenerated Thu Mar 14 10:24:30 CET 2013
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column geowfst.procedure_defaults.feature_name
     *
     * @return the value of geowfst.procedure_defaults.feature_name
     *
     * @ibatorgenerated Thu Mar 14 10:24:30 CET 2013
     */
    public String getFeatureName() {
        return featureName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column geowfst.procedure_defaults.feature_name
     *
     * @param featureName the value for geowfst.procedure_defaults.feature_name
     *
     * @ibatorgenerated Thu Mar 14 10:24:30 CET 2013
     */
    public void setFeatureName(String featureName) {
        this.featureName = featureName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column geowfst.procedure_defaults.feature_toolbarname
     *
     * @return the value of geowfst.procedure_defaults.feature_toolbarname
     *
     * @ibatorgenerated Thu Mar 14 10:24:30 CET 2013
     */
    public String getFeatureToolbarname() {
        return featureToolbarname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column geowfst.procedure_defaults.feature_toolbarname
     *
     * @param featureToolbarname the value for geowfst.procedure_defaults.feature_toolbarname
     *
     * @ibatorgenerated Thu Mar 14 10:24:30 CET 2013
     */
    public void setFeatureToolbarname(String featureToolbarname) {
        this.featureToolbarname = featureToolbarname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column geowfst.procedure_defaults.style_property
     *
     * @return the value of geowfst.procedure_defaults.style_property
     *
     * @ibatorgenerated Thu Mar 14 10:24:30 CET 2013
     */
    public String getStyleProperty() {
        return styleProperty;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column geowfst.procedure_defaults.style_property
     *
     * @param styleProperty the value for geowfst.procedure_defaults.style_property
     *
     * @ibatorgenerated Thu Mar 14 10:24:30 CET 2013
     */
    public void setStyleProperty(String styleProperty) {
        this.styleProperty = styleProperty;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column geowfst.procedure_defaults.address_property
     *
     * @return the value of geowfst.procedure_defaults.address_property
     *
     * @ibatorgenerated Thu Mar 14 10:24:30 CET 2013
     */
    public String getAddressProperty() {
        return addressProperty;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column geowfst.procedure_defaults.address_property
     *
     * @param addressProperty the value for geowfst.procedure_defaults.address_property
     *
     * @ibatorgenerated Thu Mar 14 10:24:30 CET 2013
     */
    public void setAddressProperty(String addressProperty) {
        this.addressProperty = addressProperty;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column geowfst.procedure_defaults.onfeatureunselecttext
     *
     * @return the value of geowfst.procedure_defaults.onfeatureunselecttext
     *
     * @ibatorgenerated Thu Mar 14 10:24:30 CET 2013
     */
    public String getOnfeatureunselecttext() {
        return onfeatureunselecttext;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column geowfst.procedure_defaults.onfeatureunselecttext
     *
     * @param onfeatureunselecttext the value for geowfst.procedure_defaults.onfeatureunselecttext
     *
     * @ibatorgenerated Thu Mar 14 10:24:30 CET 2013
     */
    public void setOnfeatureunselecttext(String onfeatureunselecttext) {
        this.onfeatureunselecttext = onfeatureunselecttext;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column geowfst.procedure_defaults.onnotfeatureinfotext
     *
     * @return the value of geowfst.procedure_defaults.onnotfeatureinfotext
     *
     * @ibatorgenerated Thu Mar 14 10:24:30 CET 2013
     */
    public String getOnnotfeatureinfotext() {
        return onnotfeatureinfotext;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column geowfst.procedure_defaults.onnotfeatureinfotext
     *
     * @param onnotfeatureinfotext the value for geowfst.procedure_defaults.onnotfeatureinfotext
     *
     * @ibatorgenerated Thu Mar 14 10:24:30 CET 2013
     */
    public void setOnnotfeatureinfotext(String onnotfeatureinfotext) {
        this.onnotfeatureinfotext = onnotfeatureinfotext;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column geowfst.procedure_defaults.onnotfeaturesearchtext
     *
     * @return the value of geowfst.procedure_defaults.onnotfeaturesearchtext
     *
     * @ibatorgenerated Thu Mar 14 10:24:30 CET 2013
     */
    public String getOnnotfeaturesearchtext() {
        return onnotfeaturesearchtext;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column geowfst.procedure_defaults.onnotfeaturesearchtext
     *
     * @param onnotfeaturesearchtext the value for geowfst.procedure_defaults.onnotfeaturesearchtext
     *
     * @ibatorgenerated Thu Mar 14 10:24:30 CET 2013
     */
    public void setOnnotfeaturesearchtext(String onnotfeaturesearchtext) {
        this.onnotfeaturesearchtext = onnotfeaturesearchtext;
    }
}