package com.geopista.app.contaminantes;

import com.geopista.protocol.contaminantes.Historico;
import com.geopista.app.utilidades.TextPane;
import com.geopista.app.utilidades.estructuras.ComboBoxEstructuras;

import javax.swing.*;
import java.util.ResourceBundle;
import java.awt.*;

import org.apache.log4j.Logger;

/**
 * The GEOPISTA project is a set of tools and applications to manage
 * geographical data for local administrations.
 *
 * Copyright (C) 2004 INZAMAC-SATEC UTE
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
 USA.
 *
 * For more information, contact:
 *
 *
 * www.geopista.com
 *
 *
 */


/**
 *
 * @author  angeles
 */
public class JDialogApunte extends javax.swing.JDialog {
    public static Logger logger= Logger.getLogger(JDialogApunte.class);
    private boolean aceptado=false;
    private ResourceBundle messages;
    private Historico historico;
    private Frame parent;
    /** Creates new form JDialogInspeccion */
    public JDialogApunte(java.awt.Frame parent, boolean modal,ResourceBundle messages,Historico historico) {
        super(parent, modal);
        this.messages= messages;
        this.historico=historico;
        this.parent=parent;
        initComponents();
        load(historico);
        changeScreenLang(messages);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanelBotonera = new javax.swing.JPanel();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        cancelar();
                    }
                });
        jPanelApunte = new JPanel();
        jLabelApunte = new javax.swing.JLabel();
        jScrollPaneApunte = new javax.swing.JScrollPane();
        jTextAreaApunte = new TextPane(253);
        jLabelTipo = new javax.swing.JLabel();
        jComboBoxTipo = new ComboBoxEstructuras(com.geopista.app.contaminantes.estructuras.Estructuras.getListaTipoMedioambiental(),null,
                com.geopista.app.contaminantes.init.Constantes.Locale);
        JPanel panelTipo = new JPanel();
        panelTipo.add(jLabelTipo);
        panelTipo.add(jComboBoxTipo);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jPanelBotonera.add(jButtonAceptar);
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        aceptar();
                    }
                });


        jPanelBotonera.add(jButtonCancelar);
        jScrollPaneApunte.setViewportView(jTextAreaApunte);
        jPanelApunte.setLayout(new BorderLayout());
        jPanelApunte.add(jLabelApunte, BorderLayout.NORTH);
        jPanelApunte.add(jScrollPaneApunte, BorderLayout.CENTER);
        jPanelApunte.add(panelTipo, BorderLayout.SOUTH);
        getContentPane().add(jPanelApunte, java.awt.BorderLayout.CENTER);
        getContentPane().add(jPanelBotonera, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents
    private void aceptar()
    {
        /** chequeamos que el tamanno de los anexos para la inspeccion no exceda el tamanno maximo */
       aceptado=true;
       historico.setApunte(jTextAreaApunte.getText());
       historico.setTipo_medioambiental(-1);
       if (jComboBoxTipo.getSelectedIndex()>0)
          try {historico.setTipo_medioambiental(new Integer(jComboBoxTipo.getSelectedPatron()).intValue());}catch(Exception e){}
       dispose();
    }
    public void load(Historico historico)
    {
        jTextAreaApunte.setText((historico.getApunte()!=null?historico.getApunte():""));
        if (historico.getTipo_medioambiental()>=0)
            jComboBoxTipo.setSelectedPatron(new Integer(historico.getTipo_medioambiental()).toString());
    }
    public Historico getHistorico() {
        return historico;
    }

    public void setInspeccion(Historico historico) {
        this.historico= historico;
    }

    private void cancelar()
    {
        aceptado=false;
        dispose();
    }

    public boolean isAceptado() {
        return aceptado;
    }

    public void setAceptado(boolean aceptado) {
        this.aceptado = aceptado;
    }
    public void enabledCombo(boolean value)
    {
        jComboBoxTipo.setEnabled(value);
        jComboBoxTipo.setEditable(value);
    }
    private void changeScreenLang(ResourceBundle messages)
    {
        try
        {
            this.messages=messages;
            setTitle(messages.getString("JFrameHistorico.jLabelApunte"));
            jButtonCancelar.setText(messages.getString("JFrameHistorico.jButtonCancelar"));
            jButtonAceptar.setText(messages.getString("JFrameHistorico.jButtonAceptar"));
            jLabelApunte.setText(messages.getString("JFrameHistorico.jLabelApunte")+":");
            jLabelTipo.setText(messages.getString("JFrameHistorico.jLabelTipoBusqueda"));
        }catch (Exception e)
        {
            logger.error("Error al cargar las etiquetas:", e);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JPanel jPanelBotonera;
    private JPanel jPanelApunte;
    private javax.swing.JLabel jLabelApunte;
    private TextPane jTextAreaApunte;
    private javax.swing.JScrollPane jScrollPaneApunte;
    private javax.swing.JLabel jLabelTipo;
    private ComboBoxEstructuras jComboBoxTipo;
    // End of variables declaration//GEN-END:variables

}
