/*
 * MejorasTabbedPane.java
 *
 * Created on 21 de abril de 2005, 10:52
 */

package com.geopista.app.licencias.documentacion;

import com.geopista.app.licencias.estructuras.Estructuras;
import com.geopista.app.licencias.utilidades.ComboBoxTableEditor;
import com.geopista.app.licencias.utilidades.ComboBoxRenderer;
import com.geopista.app.licencias.utilidades.TextFieldTableEditor;
import com.geopista.app.licencias.utilidades.TextFieldRenderer;
import com.geopista.app.licencias.CConstantesLicencias;
import com.geopista.app.licencias.CUtilidadesComponentes;
import com.geopista.app.licencias.CUtilidades;
import com.geopista.app.licencias.tableModels.CListaAnexosTableModel;
import com.geopista.app.utilidades.estructuras.ComboBoxEstructuras;
import com.geopista.app.utilidades.estructuras.ComboBoxRendererEstructuras;
import com.geopista.app.utilidades.TextPane;
import com.geopista.protocol.licencias.CAnexo;
import com.geopista.protocol.licencias.Mejora;
import com.geopista.protocol.licencias.tipos.CTipoAnexo;
import com.geopista.protocol.CConstantesComando;

import javax.swing.table.TableColumn;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;

import org.apache.log4j.Logger;

import java.util.*;
import java.io.StringWriter;
import java.io.PrintWriter;
import java.io.File;
import java.awt.*;

/**
 *
 * @author  charo
 */
public class MejorasJTabPanel extends javax.swing.JPanel {

    Logger logger = Logger.getLogger(MejorasJTabPanel.class);
    private javax.swing.JPanel desktop;

    /** Modelo para el componente listaAnexosJTable */
    private DefaultTableModel _listaAnexosMejoraTableModel;

    private Hashtable _hAnexosMejora= new Hashtable();
    private Hashtable _hAnexosAnnadidosMejora= new Hashtable();

    private int _indexSelected= -1;
    private int indexTab= -1;

    private Mejora mejora= new Mejora();
    private ResourceBundle literales;
    /** Creates new form MejorasJTabPanel */
    public MejorasJTabPanel(javax.swing.JPanel panel, ResourceBundle literales) {
        this.literales=literales;
        this.desktop= panel;
        initComponents();
        fechaJTextField.setEnabled(false);
        configureComponents();
        renombrarComponentes(literales);
        cargarTiposAnexosMejoraJTable();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        listaAnexosMejoraJScrollPane = new javax.swing.JScrollPane();
        listaAnexosMejoraJTable = new javax.swing.JTable();
        fechaMejoraJLabel = new javax.swing.JLabel();
        fechaJTextField = new javax.swing.JTextField();
        observacionesMejoraJLabel = new javax.swing.JLabel();
        observacionesJScrollPane = new javax.swing.JScrollPane();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaAnexosMejoraJScrollPane.setBorder(new javax.swing.border.EtchedBorder());
        listaAnexosMejoraJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Tipo", "Fichero", "Observacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });

        listaAnexosMejoraJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaAnexosMejoraJTableMouseClicked();
            }
        });

        listaAnexosMejoraJScrollPane.setViewportView(listaAnexosMejoraJTable);

        add(listaAnexosMejoraJScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 70));

        fechaMejoraJLabel.setText("Fecha:");
        add(fechaMejoraJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        add(fechaJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 120, 20));

        observacionesMejoraJLabel.setText("Observaciones:");
        add(observacionesMejoraJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 20));

        add(observacionesJScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 320, 30));

    }//GEN-END:initComponents

    private void listaAnexosMejoraJTableMouseClicked() {//GEN-FIRST:event_listaAnexosMejoraJTableMouseClicked
        int selected = listaAnexosMejoraJTable.getSelectedRow();
        _indexSelected= selected;

        ((DocumentacionLicenciasJPanel)desktop).anexoMejorasJTabPanelSelected();

    }//GEN-LAST:event_listaAnexosMejoraJTableMouseClicked


    public int getSelected(){
        return _indexSelected;

    }

    public CAnexo getAnexoSelected(){

        if (_indexSelected != -1){
            CAnexo anexo= new CAnexo();
            anexo.setFileName((String) listaAnexosMejoraJTable.getValueAt(_indexSelected, 0));
            anexo.setPath((String) listaAnexosMejoraJTable.getValueAt(_indexSelected, 0));

            ComboBoxRendererEstructuras renderBox = (ComboBoxRendererEstructuras) listaAnexosMejoraJTable.getCellRenderer(_indexSelected, 1);
            listaAnexosMejoraJTable.prepareRenderer(renderBox, _indexSelected, 1);
            int index = new Integer(renderBox.getSelectedPatron()).intValue();
            CTipoAnexo tipoAnexo = new CTipoAnexo(index, "", "");
            anexo.setTipoAnexo(tipoAnexo);

            TextFieldRenderer renderText = (TextFieldRenderer) listaAnexosMejoraJTable.getCellRenderer(_indexSelected, 2);
            listaAnexosMejoraJTable.prepareRenderer(renderText, _indexSelected, 2);
            String observacion = renderText.getText();
            anexo.setObservacion(observacion);

            return anexo;
        }else return null;
    }

    public void cargarTiposAnexosMejoraJTable() {
        if (Estructuras.getListaTiposAnexo().getLista().size() > 0){
            // Annadimos a la tabla el editor ComboBox en la segunda columna
            int vColIndexCB = 1;
            TableColumn col2 = listaAnexosMejoraJTable.getColumnModel().getColumn(vColIndexCB);
            col2.setCellEditor(new ComboBoxTableEditor(new ComboBoxEstructuras(Estructuras.getListaTiposAnexo(), null, literales.getLocale().toString(), false)));
            col2.setCellRenderer(new ComboBoxRendererEstructuras(Estructuras.getListaTiposAnexo(), null, literales.getLocale().toString(), false));

        } else {
            String[] values = {""};
            // Annadimos a la tabla el editor ComboBox en la segunda columna
            int vColIndexCB = 1;
            TableColumn col2 = listaAnexosMejoraJTable.getColumnModel().getColumn(vColIndexCB);
            col2.setCellEditor(new ComboBoxTableEditor(new JComboBox(values)));
            col2.setCellRenderer(new ComboBoxRenderer(values));
        }

        // Annadimos a la tabla el editor TextField en la tercera columna
        int vColIndexTF = 2;
        TableColumn col3 = listaAnexosMejoraJTable.getColumnModel().getColumn(vColIndexTF);
        col3.setCellEditor(new TextFieldTableEditor(254));
        col3.setCellRenderer(new TextFieldRenderer());
    }

    public void configureComponents(){
        /** Anexos Mejoras */
        String[] columnNamesAnexos= {literales.getString("DocumentacionLicenciasJPanel.listaAnexosJTable.column1"),
                                     literales.getString("DocumentacionLicenciasJPanel.listaAnexosJTable.column2"),
                                     literales.getString("DocumentacionLicenciasJPanel.listaAnexosJTable.column3")};

        CListaAnexosTableModel.setColumnNames(columnNamesAnexos);
        _listaAnexosMejoraTableModel = new CListaAnexosTableModel();
        listaAnexosMejoraJTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        listaAnexosMejoraJTable.setModel(_listaAnexosMejoraTableModel);
        listaAnexosMejoraJTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        listaAnexosMejoraJTable.getTableHeader().setReorderingAllowed(false);
        for (int j=0; j< listaAnexosMejoraJTable.getColumnCount(); j++){
            TableColumn column = listaAnexosMejoraJTable.getColumnModel().getColumn(j);
            if (j==2){
                column.setMinWidth(250);
                column.setMaxWidth(300);
                column.setWidth(250);
                column.setPreferredWidth(250);
            }else{
                column.setMinWidth(150);
                column.setMaxWidth(300);
                column.setWidth(150);
                column.setPreferredWidth(150);
            }
            column.setResizable(true);
        }
        /** Deshabilitamos el campo fecha */
        fechaJTextField.setEnabled(false);

        /* Observaciones Generales */
        observacionesTPane= new TextPane(254);
        observacionesJScrollPane.setViewportBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        observacionesJScrollPane.setViewportView(observacionesTPane);

    }

    public void renombrarComponentes(ResourceBundle literales){
        try{
            /** Anexos Mejoras */
            TableColumn tableColumn= listaAnexosMejoraJTable.getColumnModel().getColumn(0);
            tableColumn.setHeaderValue(literales.getString("DocumentacionLicenciasJPanel.listaAnexosJTable.column1"));
            tableColumn= listaAnexosMejoraJTable.getColumnModel().getColumn(1);
            tableColumn.setHeaderValue(literales.getString("DocumentacionLicenciasJPanel.listaAnexosJTable.column2"));
            tableColumn= listaAnexosMejoraJTable.getColumnModel().getColumn(2);
            tableColumn.setHeaderValue(literales.getString("DocumentacionLicenciasJPanel.listaAnexosJTable.column3"));

            observacionesMejoraJLabel.setText(literales.getString("MejorasJTabPanel.observacionesMejoraJLabel.text"));
            fechaMejoraJLabel.setText(literales.getString("MejorasJTabPanel.fechaMejoraJLabel.text"));

        }catch(Exception e){
            logger.error("Error:",e);
        }
    }

    public void clearMejora(){
        CUtilidadesComponentes.clearTable(_listaAnexosMejoraTableModel);
        _hAnexosMejora= new Hashtable();

        fechaJTextField.setText("");
        observacionesTPane.setText("");
        /** indice del anexo seleccionado */
    }


    public void cargarMejora(Mejora mejora, boolean b){
        /* Los anexos de mejoras no se presentan por vu */
        this.mejora= mejora;
        cargarAnexosJTable(mejora.getAnexos(), "0", b);
        fechaJTextField.setText(CUtilidades.formatFecha(mejora.getFecha()));
        observacionesTPane.setText(mejora.getObservaciones());
        setEnabled(b);
    }

    public void cargarAnexosJTable(Vector vAnexosMejora, String vu, boolean b) {
        try {
            // Annadimos a la tabla el editor ComboBox en la segunda columna
            int vColIndexCB = 1;
            TableColumn col2 = listaAnexosMejoraJTable.getColumnModel().getColumn(vColIndexCB);
            ComboBoxTableEditor comboBoxEditor= new ComboBoxTableEditor(new ComboBoxEstructuras(Estructuras.getListaTiposAnexo(), null, literales.getLocale().toString(), false));
            if (!((DocumentacionLicenciasJPanel)this.desktop).getOperacion().equalsIgnoreCase("CONSULTA")){
                comboBoxEditor.setEnabled(b);
            }else{
                comboBoxEditor.setEnabled(false);
            }
            col2.setCellEditor(comboBoxEditor);
            col2.setCellRenderer(new ComboBoxRendererEstructuras(Estructuras.getListaTiposAnexo(), null, literales.getLocale().toString(), false));

            // Annadimos a la tabla el editor TextField en la tercera columna
            int vColIndexTF = 2;
            TableColumn col3 = listaAnexosMejoraJTable.getColumnModel().getColumn(vColIndexTF);
            TextFieldTableEditor textFieldTableEditor= new TextFieldTableEditor();
            if (!((DocumentacionLicenciasJPanel)this.desktop).getOperacion().equalsIgnoreCase("CONSULTA")){
                textFieldTableEditor.setEnabled(b);
            }else{
                textFieldTableEditor.setEnabled(false);
            }
            col3.setCellEditor(textFieldTableEditor);
            col3.setCellRenderer(new TextFieldRenderer());

            if (vAnexosMejora != null) {
                Enumeration en = vAnexosMejora.elements();
                int row = 0;
                while (en.hasMoreElements()) {
                    CAnexo anexo = (CAnexo) en.nextElement();
                    /** Insertamos en _hAnexosSolicitud */
                    /** Esta estructura nos servira para hacer las búsquedas de los anexos por nombre,
                     *  en la construccion del vector con los anexos marcados como borrados y annadidos
                     */
                    _hAnexosMejora.put(anexo.getFileName(), anexo);
                    int tipo= 0;
                    if (!vu.equalsIgnoreCase("1")){
                        tipo= ((CTipoAnexo) anexo.getTipoAnexo()).getIdTipoAnexo();
                    }
                    ComboBoxEstructuras combox = (ComboBoxEstructuras) ((ComboBoxTableEditor) listaAnexosMejoraJTable.getCellEditor(row, 1)).getComponent();
                    combox.setSelectedPatron(new Integer(tipo).toString());

                    Object[] rowData = {anexo.getFileName(), combox.getSelectedItem(), anexo.getObservacion()};
                    _listaAnexosMejoraTableModel.addRow(rowData);
                    row++;
                }
            }
        } catch (Exception ex) {
            StringWriter sw = new StringWriter();
            PrintWriter pw = new PrintWriter(sw);
            ex.printStackTrace(pw);
            logger.error("Exception: " + sw.toString());
        }
    }

    public Vector getAnexosMejora(){
        /* Recogemos la lista de documentos anexados a la mejora */
        Vector vListaAnexos= new Vector();
        Hashtable hAnexosAux = new Hashtable();

        int numRows = _listaAnexosMejoraTableModel.getRowCount();
        //long totalSizeFilesUploaded= 0;

        for (int i = 0; i < numRows; i++) {
            try{
                String nomFichero = (String) listaAnexosMejoraJTable.getValueAt(i, 0);

                ComboBoxRendererEstructuras renderBox = (ComboBoxRendererEstructuras) listaAnexosMejoraJTable.getCellRenderer(i, 1);
                listaAnexosMejoraJTable.prepareRenderer(renderBox, i, 1);
                int index = new Integer(renderBox.getSelectedPatron()).intValue();

                TextFieldRenderer renderText = (TextFieldRenderer) listaAnexosMejoraJTable.getCellRenderer(i, 2);
                listaAnexosMejoraJTable.prepareRenderer(renderText, i, 2);
                String descripcion = renderText.getText();

                CTipoAnexo tipoAnexo = new CTipoAnexo(index, "", "");
                CAnexo anexo = new CAnexo(tipoAnexo, nomFichero, descripcion);
                anexo.setComesFrom("MEJORA");
                /** Lectura del contenido del anexo */
                File file = new File(nomFichero);
                if (file.isAbsolute()) {
                    //System.out.println("nomFichero="+nomFichero+" isAbsolute()");
                    nomFichero = file.getName();
                    anexo.setFileName(nomFichero);
                    /* MultipartPostMethod - en lugar de enviar el contenido, enviamos el path absoluto del fichero -*/
                    anexo.setPath(file.getAbsolutePath());
                    /**/
                }

                /** Comprobamos si se ha marcado como annadido o como borrado */
                if ((_hAnexosMejora.get(anexo.getFileName()) != null) && (_hAnexosAnnadidosMejora.get(anexo.getFileName()) != null)) {
                    /** Ha sido borrado y posteriormente annadido (actualizado) */
                    //System.out.println(anexo.getFileName() + " ** Ha sido borrado y posteriormente annadido (actualizado) *");
                    anexo.setEstado(CConstantesLicencias.CMD_ANEXO_DELETED);
                    /** marcado como borrado */
                    vListaAnexos.add(anexo);
                    /** Necesario, ya que te guarda una referencia al tratarse del mismo objeto*/
                    CAnexo nuevo = new CAnexo(anexo.getTipoAnexo(), anexo.getFileName(), anexo.getObservacion());
                    nuevo.setEstado(CConstantesLicencias.CMD_ANEXO_ADDED);
                    nuevo.setComesFrom("MEJORA");
                    /** -- MultipartPostMethod: comentamos para no enviar el contenido. Enviamos el file directamente. */
                    /*
                    byte[] content = getBytesFromFile(file);
                    nuevo.setContent(content);
                    */
                    /** marcado como annadido */
                    vListaAnexos.add(nuevo);
                    hAnexosAux.put(nuevo.getFileName(), nuevo);

                } else if ((_hAnexosMejora.get(anexo.getFileName()) == null) && (_hAnexosAnnadidosMejora.get(anexo.getFileName()) != null)) {
                    /** El anexo ha sido annadido */
                    //System.out.println(anexo.getFileName() + " ** El anexo ha sido annadido *");
                    anexo.setEstado(CConstantesLicencias.CMD_ANEXO_ADDED);
                    /** -- MultipartPostMethod: comentamos para no enviar el contenido. Enviamos el file directamente. */
                    /*
                    byte[] content = getBytesFromFile(file);
                    anexo.setContent(content);
                    */
                    vListaAnexos.addElement(anexo);
                    hAnexosAux.put(anexo.getFileName(), anexo);

                } else if ((_hAnexosMejora.get(anexo.getFileName()) != null) && (_hAnexosAnnadidosMejora.get(anexo.getFileName()) == null)) {
                    //System.out.println(anexo.getFileName() + " ** El anexo no ha sufrido cambios *");
                    /** El anexo no ha sufrido cambios. Puede que solo haya cambiado el tipo y la observacion. */
                    CAnexo existente= (CAnexo)_hAnexosMejora.get(anexo.getFileName());
                    anexo.setIdAnexo(existente.getIdAnexo());
                    vListaAnexos.addElement(anexo);
                    hAnexosAux.put(anexo.getFileName(), anexo);
                } else if ((_hAnexosMejora.get(anexo.getFileName()) == null) && (_hAnexosAnnadidosMejora.get(anexo.getFileName()) == null)) {
                    /** Este caso no se puede dar */
                }
            } catch (Exception ex) {
                logger.error("Exception: " + ex.toString());
            }
        }

        /** Comprobamos aquellos que han sido marcados como borrados */
        Vector vDeletedFirst= new Vector();
        Enumeration enumerationElement = _hAnexosMejora.elements();
        while (enumerationElement.hasMoreElements()) {
            CAnexo a = (CAnexo) enumerationElement.nextElement();
            if (hAnexosAux.get(a.getFileName()) == null) {
                a.setEstado(CConstantesLicencias.CMD_ANEXO_DELETED);
                vDeletedFirst.addElement(a);
            }
        }
        /** Ordenamos la lista de vectores: primero, los marcados como borrados, luego annadimos el resto */
        for (Enumeration e= vListaAnexos.elements(); e.hasMoreElements();){
            CAnexo a= (CAnexo)e.nextElement();
            vDeletedFirst.addElement(a);
        }

        return vDeletedFirst;
    }

    public Mejora getMejora(){
        mejora.setAnexos(getAnexosMejora());
        mejora.setObservaciones(observacionesTPane.getText());

        return mejora;
    }

    public void eliminarAnexoSeleccionado(){
        int selected= listaAnexosMejoraJTable.getSelectedRow();
        if (selected != -1){
            int ok= JOptionPane.showConfirmDialog(this, literales.getString("Licencias.confirmarBorrado"), literales.getString("Licencias.tittle"), JOptionPane.YES_NO_OPTION);
            if (ok == JOptionPane.NO_OPTION) return;

            /** Actualizamos el tamanno total de los ficheros a enviar */
            String nombreAnexo = (String) _listaAnexosMejoraTableModel.getValueAt(selected, 0);
            File file = new File(nombreAnexo);
            if (file.isAbsolute()) {
                long size= file.length();
                if (((DocumentacionLicenciasJPanel)this.desktop).getMaxSizeFilesUploaded() > size){
                   ((DocumentacionLicenciasJPanel)this.desktop).setMaxSizeFilesUploaded(((DocumentacionLicenciasJPanel)this.desktop).getMaxSizeFilesUploaded() - size);
                }else{
                    ((DocumentacionLicenciasJPanel)this.desktop).setMaxSizeFilesUploaded(0);
                }
            }

            _listaAnexosMejoraTableModel.removeRow(selected);
            if (listaAnexosMejoraJTable.getModel().getRowCount() > 0) {
                listaAnexosMejoraJTable.clearSelection();
            }
        }
    }

    public void annadirAnexoMejora(){

        listaAnexosMejoraJTable.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        JFileChooser chooser = new JFileChooser();
        com.geopista.app.utilidades.GeoPistaFileFilter filter = new com.geopista.app.utilidades.GeoPistaFileFilter();
        filter.addExtension("doc");
        filter.addExtension("txt");
        filter.setDescription("Fichero DOC & TXT");
        chooser.setFileFilter(filter);
        /** Permite multiples selecciones */
        chooser.setMultiSelectionEnabled(true);

        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File[] selectedFiles = chooser.getSelectedFiles();
            System.out.println("Fichero(s) seleccionado " + selectedFiles.length);
            if (selectedFiles.length > 0) {
                for (int i = 0; i < selectedFiles.length; i++) {
                    System.out.println("\t" + selectedFiles[i].getPath());
                    System.out.println("Abrimos el fichero: " + selectedFiles[i].getAbsolutePath());

                    for (int j = 0; j < _listaAnexosMejoraTableModel.getRowCount(); j++) {
                        String nombreAnexo = (String) _listaAnexosMejoraTableModel.getValueAt(j, 0);
                        File file = new File(nombreAnexo);
                        if (file.isAbsolute()) {
                            nombreAnexo = file.getName();
                        }

                        if (nombreAnexo.equalsIgnoreCase(selectedFiles[i].getName())) {
                            /** Ya existe un anexo con ese nombre */
                            mostrarMensaje(literales.getString("DocumentacionLicenciasJPanel.mensaje6"));
                            return;
                        }
                    }
                    
                    /** comprobamos que no exceda el tamanno maximo permitido */
                    if (selectedFiles[i].isAbsolute()){
                        long sizeFilesUploaded= ((DocumentacionLicenciasJPanel)this.desktop).getMaxSizeFilesUploaded();
                        sizeFilesUploaded=+selectedFiles[i].length();
                        if (sizeFilesUploaded > CConstantesLicencias.totalMaxSizeFilesUploaded){
                            JOptionPane optionPane= new JOptionPane(literales.getString("DocumentacionLicenciasJPanel.mensaje5")+": " +CConstantesLicencias.totalMaxSizeFilesUploaded+" bytes", JOptionPane.ERROR_MESSAGE);
                            JDialog dialog =optionPane.createDialog(this,"ERROR");
                            dialog.show();
                            return;
                        }else{
                            ((DocumentacionLicenciasJPanel)this.desktop).setMaxSizeFilesUploaded(sizeFilesUploaded);
                        }
                    }

                    /** Por defecto selected el primer tipo */
                    JComboBox combox = (JComboBox) ((ComboBoxTableEditor) listaAnexosMejoraJTable.getCellEditor(_listaAnexosMejoraTableModel.getRowCount(), 1)).getComponent();
                    Object[] rowData = {selectedFiles[i].getAbsolutePath(), combox.getItemAt(0), ""};
                    _listaAnexosMejoraTableModel.addRow(rowData);
                    /** Marcamos el fichero como annadido y lo insertamos en un vector auxiliar de annadidos*/

                    if ((_hAnexosAnnadidosMejora.get(selectedFiles[i].getName()) == null)) {
                        CAnexo anexo = new CAnexo(new CTipoAnexo(), selectedFiles[i].getName(), "");
                        anexo.setEstado(CConstantesLicencias.CMD_ANEXO_ADDED);
                        anexo.setComesFrom("MEJORA");
                        _hAnexosAnnadidosMejora.put(selectedFiles[i].getName(), anexo);
                    }
                }
            }
        }

        /** Solo se podra seleccionar un elemento de la lista */
        listaAnexosMejoraJTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    public void abrirAnexoMejora(long idSolicitud){

            int row = listaAnexosMejoraJTable.getSelectedRow();
            logger.info("row: " + row);

            if (row == -1) {
                mostrarMensaje(literales.getString("DocumentacionLicenciasJPanel.mensaje1"));
                return;
            }

            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

            String fileName = (String) listaAnexosMejoraJTable.getValueAt(row, 0);
            logger.info("fileName: " + fileName);

            String tmpFile= "";
            File f= new File(fileName);
            if (!f.isAbsolute()){

                /** Dialogo para seleccionar donde dejar el fichero */
                JFileChooser chooser = new JFileChooser();

                /** Permite multiples selecciones */
                chooser.setMultiSelectionEnabled(false);
                chooser.setSelectedFile(f);

                int returnVal = chooser.showSaveDialog(this);
                if (returnVal == JFileChooser.APPROVE_OPTION) {
                    File selectedFile= chooser.getSelectedFile();
                    if (selectedFile != null){
                        String tmpDir= "";
                        tmpFile= selectedFile.getAbsolutePath();
                        int index= tmpFile.lastIndexOf(selectedFile.getName());
                        if (index != -1){
                            tmpDir= tmpFile.substring(0, index);
                        }

                       /** Comprobamos si existe el directorio. */
                        try {
                            File dir = new File(tmpDir);
                            logger.info("dir: " + dir);

                            if (!dir.exists()) {
                                logger.warn("Directorio temporal creado.");
                                dir.mkdirs();
                            }
                        } catch (Exception ex) {
                            logger.error("Exception: " + ex.toString());
                        }

                        boolean resultado = CUtilidadesComponentes.GetURLFile(CConstantesComando.anexosLicenciasUrl + idSolicitud + "/" + "mejoras" + "/" + this.mejora.getIdMejora() + "/" + fileName, tmpFile, "", 0);
                        if (!resultado) {
                            mostrarMensaje(literales.getString("DocumentacionLicenciasJPanel.mensaje2"));
                            this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                            return;
                        }
                    }else{
                        this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                        return;                        
                    }
                }else{
                    this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                    return;
                }
            }else{
                tmpFile= f.getAbsolutePath();
            }

            /** Visualizamos el fichero descargado si SO es Windows. */
            if (CUtilidadesComponentes.isWindows()){

                try {
                    Runtime.getRuntime().exec("rundll32 SHELL32.DLL,ShellExec_RunDLL \"" + tmpFile + "\"");

                } catch (Exception ex) {
                    logger.warn("Exception: " + ex.toString());
                    mostrarMensaje(literales.getString("DocumentacionLicenciasJPanel.mensaje3") + " " + tmpFile);
                }
                this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            }
    }

    public boolean isFirst(){
        if (indexTab == 0) return true;
        else return false;
    }

    public void setIndexTab(int index){
        indexTab= index;
    }

    public void setEnabled(boolean b){
        observacionesTPane.setEnabled(b);
        fechaJTextField.setEnabled(false);
    }

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(desktop, mensaje);
    }


    // Variables propias
    private TextPane observacionesTPane;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fechaJTextField;
    private javax.swing.JLabel fechaMejoraJLabel;
    private javax.swing.JScrollPane listaAnexosMejoraJScrollPane;
    private javax.swing.JTable listaAnexosMejoraJTable;
    private javax.swing.JScrollPane observacionesJScrollPane;
    private javax.swing.JLabel observacionesMejoraJLabel;
    // End of variables declaration//GEN-END:variables
    
}
