package com.geopista.app.administrador.dominios;

import org.apache.log4j.Logger;
import javax.swing.*;
import java.util.*;



/**
 * The GEOPISTA project is a set of tools and applications to manage
 * geographical data for local administrations.
 *
 * Copyright (C) 2004 INZAMAC-SATEC UTE
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
 USA.
 *
 * For more information, contact:
 *
 *
 * www.geopista.com
 *
 *
 */


/**
 * Created by IntelliJ IDEA.
 * User: angeles
 * Date: 02-jun-2004
 * Time: 18:49:47
 */
public class CDominiosFrame extends javax.swing.JInternalFrame
{
   	Logger logger = Logger.getLogger(CDominiosFrame.class);
    private ResourceBundle messages;
    private JFrame frame;



    	/**

	/**
	 * Creates new form CCreacionLicencias
	 */
	public CDominiosFrame(ResourceBundle messages, JFrame frame) {
        this.frame=frame;
        initComponents(messages);
	}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    private void initComponents(ResourceBundle messages) {//GEN-BEGIN:initComponents
        templateJScrollPane = new javax.swing.JScrollPane();
        templateJPanel = new javax.swing.JPanel();
        JPanelBotonera = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();
        JTabbedPaneDominios = new javax.swing.JTabbedPane();
         jPanelDominios = new JPanelDominios(messages,frame);
        //Ejemplo de como mostrar sólo una categoría
        //jPanelDominios = new JPanelDominios(messages,frame,"1");
        //jPanelDominios.hideLeyenda();




        templateJPanel.setLayout(new java.awt.BorderLayout());
        templateJPanel.add(JTabbedPaneDominios, java.awt.BorderLayout.CENTER);

        JPanelBotonera.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 1, 1, 1)));
        JPanelBotonera.setMinimumSize(new java.awt.Dimension(67, 50));
        JPanelBotonera.setPreferredSize(new java.awt.Dimension(87, 50));
        jButtonSalir.setMaximumSize(new java.awt.Dimension(100, 25));
        jButtonSalir.setPreferredSize(new java.awt.Dimension(75, 25));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed();
            }
        });
        JTabbedPaneDominios.addTab("Dominios", jPanelDominios);

        JPanelBotonera.add(jButtonSalir);

        templateJPanel.add(JPanelBotonera, java.awt.BorderLayout.SOUTH);

        JTabbedPaneDominios.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        JTabbedPaneDominios.setFont(new java.awt.Font("Arial", 0, 10));
        templateJScrollPane.setViewportView(templateJPanel);
        getContentPane().add(templateJScrollPane, java.awt.BorderLayout.CENTER);
        changeScreenLang(messages);
    }//GEN-END:initComponents


      private void jButtonSalirActionPerformed()
      {//GEN-FIRST:event_jButtonSalirActionPerformed
        if (jPanelDominios.isModoNuevo())
             {
                    int n = JOptionPane.showOptionDialog(this,
                                                     messages.getString("CDominiosFrame.mensaje.modonuevo"),
                                                     "",
                                                     JOptionPane.YES_NO_OPTION,
                                                     JOptionPane.QUESTION_MESSAGE,null,null,null);
                    if (n==JOptionPane.NO_OPTION) return;
             }
         jPanelDominios.dispose();
         dispose();
         System.gc();
       }//GEN-LAST:event_jButtonSalirActionPerformed

    public void editable(boolean b)
    {
        jPanelDominios.editable(b);
    }
    public void changeScreenLang(ResourceBundle messages) {
        this.messages=messages;
        setTitle(messages.getString("CDominiosFrame.title"));
        jButtonSalir.setText(messages.getString("CDominiosFrame.jButtonSalir"));
        jPanelDominios.changeScreenLang(messages);

    }

    private JPanelDominios jPanelDominios;
    private javax.swing.JTabbedPane JTabbedPaneDominios;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JPanel JPanelBotonera;
    private javax.swing.JPanel templateJPanel;
    private javax.swing.JScrollPane templateJScrollPane;


}
