package com.geopista.app.cementerios.business.dao.implementations;

import com.geopista.app.cementerios.business.dao.DAO;
import com.geopista.app.cementerios.business.dao.interfaces.DocumentoTipoDAO;
import com.geopista.app.cementerios.business.vo.DocumentoTipo;
import com.geopista.app.cementerios.business.vo.DocumentoTipoExample;

import java.sql.SQLException;
import java.util.List;

public class DocumentoTipoDAOImpl extends DAO implements DocumentoTipoDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.documento_tipos
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	public DocumentoTipoDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.documento_tipos
	 * @throws SQLException 
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	public int deleteByExample(DocumentoTipoExample example) throws SQLException {
		int rows = getSqlMapClientTemplate().delete(
				"cementerio_documento_tipos.ibatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.documento_tipos
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	public int deleteByPrimaryKey(Short tipo)  throws SQLException {
		DocumentoTipo key = new DocumentoTipo();
		key.setTipo(tipo);
		int rows = getSqlMapClientTemplate()
				.delete("cementerio_documento_tipos.ibatorgenerated_deleteByPrimaryKey",
						key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.documento_tipos
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	public void insert(DocumentoTipo record)  throws SQLException {
		getSqlMapClientTemplate().insert(
				"cementerio_documento_tipos.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.documento_tipos
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	public void insertSelective(DocumentoTipo record)  throws SQLException {
		getSqlMapClientTemplate().insert(
				"cementerio_documento_tipos.ibatorgenerated_insertSelective",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.documento_tipos
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	public List selectByExample(DocumentoTipoExample example)  throws SQLException {
		List list = getSqlMapClientTemplate().queryForList(
				"cementerio_documento_tipos.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.documento_tipos
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	public DocumentoTipo selectByPrimaryKey(Short tipo)  throws SQLException {
		DocumentoTipo key = new DocumentoTipo();
		key.setTipo(tipo);
		DocumentoTipo record = (DocumentoTipo) getSqlMapClientTemplate()
				.queryForObject(
						"cementerio_documento_tipos.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.documento_tipos
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	public int updateByExampleSelective(DocumentoTipo record,
			DocumentoTipoExample example)  throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("cementerio_documento_tipos.ibatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.documento_tipos
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	public int updateByExample(DocumentoTipo record,
			DocumentoTipoExample example)  throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"cementerio_documento_tipos.ibatorgenerated_updateByExample",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.documento_tipos
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	public int updateByPrimaryKeySelective(DocumentoTipo record)  throws SQLException {
		int rows = getSqlMapClientTemplate()
				.update("cementerio_documento_tipos.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.documento_tipos
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	public int updateByPrimaryKey(DocumentoTipo record)  throws SQLException {
		int rows = getSqlMapClientTemplate()
				.update("cementerio_documento_tipos.ibatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table cementerio.documento_tipos
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	private static class UpdateByExampleParms extends DocumentoTipoExample {
		private Object record;

		public UpdateByExampleParms(Object record, DocumentoTipoExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}