SET statement_timeout = 0;
SET client_encoding = 'UTF-8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = notice;
SET default_with_oids = true;


GRANT ALL ON TABLE eiel_t_padron_ttmm TO geopista;
GRANT SELECT ON TABLE eiel_t_padron_ttmm TO consultas;


GRANT ALL ON TABLE eiel_t_nucl_encuest_1 TO geopista;
GRANT SELECT ON TABLE eiel_t_nucl_encuest_1 TO consultas;

GRANT ALL ON TABLE eiel_t_mun_diseminados TO geopista;
GRANT SELECT ON TABLE eiel_t_mun_diseminados TO consultas;

GRANT ALL ON TABLE eiel_t_planeam_urban TO geopista;
GRANT SELECT ON TABLE eiel_t_planeam_urban TO consultas;

GRANT ALL ON TABLE eiel_t_otros_serv_munic TO geopista;
GRANT SELECT ON TABLE eiel_t_otros_serv_munic TO consultas;

GRANT ALL ON TABLE eiel_t_saneam_tem TO geopista;
GRANT SELECT ON TABLE eiel_t_saneam_tem TO consultas;

GRANT ALL ON TABLE eiel_t_rb TO geopista;
GRANT SELECT ON TABLE eiel_t_rb TO consultas;


GRANT ALL ON TABLE eiel_t_rb_serv TO geopista;
GRANT SELECT ON TABLE eiel_t_rb_serv TO consultas;


GRANT ALL ON TABLE eiel_t_inf_ttmm TO geopista;
GRANT SELECT ON TABLE eiel_t_inf_ttmm TO consultas;


GRANT ALL ON TABLE eiel_t_nucleo_aband TO geopista;
GRANT SELECT ON TABLE eiel_t_nucleo_aband TO consultas;
GRANT ALL ON TABLE eiel_c_provincia TO geopista;
GRANT SELECT ON TABLE eiel_c_provincia TO consultas;


GRANT ALL ON TABLE eiel_t_entidad_singular TO geopista;
GRANT SELECT ON TABLE eiel_t_entidad_singular TO consultas;

GRANT ALL ON TABLE eiel_t_cabildo_consejo TO geopista;
GRANT SELECT ON TABLE eiel_t_cabildo_consejo TO consultas;

CREATE OR REPLACE FUNCTION localgisDatamodelInstall() RETURNS VOID AS
$Q$
BEGIN
	IF EXISTS (SELECT conname FROM pg_constraint WHERE conname = 'eiel_t_rb_periodicidadchk' ) THEN	
		alter table eiel_t_rb drop constraint eiel_t_rb_periodicidadchk;
	END IF;	
	ALTER TABLE eiel_t_rb ADD CONSTRAINT eiel_t_rb_periodicidadchk CHECK (eiel_t_rb.periodicidad = 'AL'
		OR eiel_t_rb.periodicidad = 'DI' OR eiel_t_rb.periodicidad = 'NO' OR eiel_t_rb.periodicidad = 'OT' OR
		eiel_t_rb.periodicidad = 'QU' OR eiel_t_rb.periodicidad = 'SE' OR eiel_t_rb.periodicidad = 'ME');
	
	IF EXISTS (SELECT conname FROM pg_constraint WHERE conname = 'eiel_t_abast_ca_tipochk' ) THEN	
		alter table eiel_t_abast_ca drop constraint eiel_t_abast_ca_tipochk;
	END IF;	
	ALTER TABLE eiel_t_abast_ca ADD CONSTRAINT eiel_t_abast_ca_tipochk CHECK (eiel_t_abast_ca.tipo = 'AL' OR eiel_t_abast_ca.tipo = 'AM' OR eiel_t_abast_ca.tipo = 'AS' OR
		eiel_t_abast_ca.tipo = 'CA' OR eiel_t_abast_ca.tipo = 'EB' OR eiel_t_abast_ca.tipo = 'GA' OR eiel_t_abast_ca.tipo = 'MT' OR
		eiel_t_abast_ca.tipo = 'OT' OR eiel_t_abast_ca.tipo = 'PO' OR eiel_t_abast_ca.tipo = 'PX' OR  eiel_t_abast_ca.tipo = 'RI'  OR  eiel_t_abast_ca.tipo = 'SO');

	

END;
$Q$
LANGUAGE plpgsql;

select localgisDatamodelInstall() as "PASO1";



ALTER TABLE "public"."iusercnt" ALTER COLUMN "id" TYPE varchar(40);
ALTER TABLE "public"."session_app" ALTER COLUMN "id" TYPE varchar(40);

-- Cementerios
alter table cementerio.elem_cementerio ALTER COLUMN tipo TYPE varchar(5);

UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_alum_pl"."GEOMETRY" , ?T) as "GEOMETRY", id, id_municipio, fase, eiel_c_alum_pl.codprov, eiel_c_alum_pl.codmunic, eiel_c_alum_pl.codentidad, eiel_c_alum_pl.codpoblamiento, ah_ener_rfl, ah_ener_rfi, estado FROM "eiel_c_alum_pl", ONLY eiel_t_nucl_encuest_1,eiel_configuracion_shp WHERE "eiel_c_alum_pl"."id_municipio" in (?M) and eiel_c_alum_pl.revision_expirada = 9999999999 and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY''  and (eiel_t_nucl_encuest_1.codprov = eiel_c_alum_pl.codprov and eiel_t_nucl_encuest_1.codmunic = eiel_c_alum_pl.codmunic and eiel_t_nucl_encuest_1.codentidad = eiel_c_alum_pl.codentidad and eiel_t_nucl_encuest_1.codpoblamiento = eiel_c_alum_pl.codpoblamiento and eiel_t_nucl_encuest_1.revision_expirada  = 9999999999 and eiel_t_nucl_encuest_1.padron > eiel_configuracion_shp.padron and eiel_t_nucl_encuest_1.viviendas_total >= eiel_configuracion_shp.viviendas)' where id_layer = (SELECT id_layer from layers where name = 'ALUMBRADO_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_cc"."GEOMETRY" , ?T) as "GEOMETRY", id, id_municipio, fase, clave, eiel_c_cc.codprov, eiel_c_cc.codmunic, eiel_c_cc.codentidad, eiel_c_cc.codpoblamiento, orden_cc FROM "eiel_c_cc", ONLY eiel_t_nucl_encuest_1,eiel_configuracion_shp WHERE "eiel_c_cc"."id_municipio" in (?M) and eiel_c_cc.revision_expirada = 9999999999 and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY'' and (eiel_t_nucl_encuest_1.codprov = eiel_c_cc.codprov and eiel_t_nucl_encuest_1.codmunic = eiel_c_cc.codmunic and eiel_t_nucl_encuest_1.codentidad = eiel_c_cc.codentidad and eiel_t_nucl_encuest_1.codpoblamiento = eiel_c_cc.codpoblamiento and eiel_t_nucl_encuest_1.revision_expirada  = 9999999999 and eiel_t_nucl_encuest_1.padron > eiel_configuracion_shp.padron and eiel_t_nucl_encuest_1.viviendas_total >= eiel_configuracion_shp.viviendas)' where id_layer = (SELECT id_layer from layers where name = 'CASA_CONSISTORIAL_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_ce"."GEOMETRY" , ?T) as "GEOMETRY", id, id_municipio, fase, clave, eiel_c_ce.codprov, eiel_c_ce.codmunic, eiel_c_ce.codentidad, eiel_c_ce.codpoblamiento, orden_ce FROM "eiel_c_ce", ONLY eiel_t_nucl_encuest_1,eiel_configuracion_shp WHERE "eiel_c_ce"."id_municipio" in (?M) and eiel_c_ce.revision_expirada = 9999999999 and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY'' and (eiel_t_nucl_encuest_1.codprov = eiel_c_ce.codprov and eiel_t_nucl_encuest_1.codmunic = eiel_c_ce.codmunic and eiel_t_nucl_encuest_1.codentidad = eiel_c_ce.codentidad and eiel_t_nucl_encuest_1.codpoblamiento = eiel_c_ce.codpoblamiento and eiel_t_nucl_encuest_1.revision_expirada  = 9999999999 and eiel_t_nucl_encuest_1.padron > eiel_configuracion_shp.padron and eiel_t_nucl_encuest_1.viviendas_total >= eiel_configuracion_shp.viviendas)' where id_layer = (SELECT id_layer from layers where name = 'CEMENTERIO_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_cu"."GEOMETRY" , ?T) as "GEOMETRY", id, id_municipio, fase, clave, eiel_c_cu.codprov, eiel_c_cu.codmunic, eiel_c_cu.codentidad, eiel_c_cu.codpoblamiento, orden_cu FROM "eiel_c_cu", ONLY eiel_t_nucl_encuest_1,eiel_configuracion_shp WHERE "eiel_c_cu"."id_municipio" in (?M) and eiel_c_cu.revision_expirada = 9999999999 and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY'' and (eiel_t_nucl_encuest_1.codprov = eiel_c_cu.codprov and eiel_t_nucl_encuest_1.codmunic = eiel_c_cu.codmunic and eiel_t_nucl_encuest_1.codentidad = eiel_c_cu.codentidad and eiel_t_nucl_encuest_1.codpoblamiento = eiel_c_cu.codpoblamiento and eiel_t_nucl_encuest_1.revision_expirada  = 9999999999 and eiel_t_nucl_encuest_1.padron > eiel_configuracion_shp.padron and eiel_t_nucl_encuest_1.viviendas_total >= eiel_configuracion_shp.viviendas)' where id_layer = (SELECT id_layer from layers where name = 'CENT_CULTURAL.SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_as"."GEOMETRY" , ?T) as "GEOMETRY", id, id_municipio, fase, clave, eiel_c_as.codprov, eiel_c_as.codmunic, eiel_c_as.codentidad, eiel_c_as.codpoblamiento, orden_as FROM "eiel_c_as", ONLY eiel_t_nucl_encuest_1,eiel_configuracion_shp WHERE "eiel_c_as"."id_municipio" in (?M) and eiel_c_as.revision_expirada = 9999999999 and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY'' and (eiel_t_nucl_encuest_1.codprov = eiel_c_as.codprov and eiel_t_nucl_encuest_1.codmunic = eiel_c_as.codmunic and eiel_t_nucl_encuest_1.codentidad = eiel_c_as.codentidad and eiel_t_nucl_encuest_1.codpoblamiento = eiel_c_as.codpoblamiento and eiel_t_nucl_encuest_1.revision_expirada  = 9999999999 and eiel_t_nucl_encuest_1.padron > eiel_configuracion_shp.padron and eiel_t_nucl_encuest_1.viviendas_total >= eiel_configuracion_shp.viviendas)' where id_layer = (SELECT id_layer from layers where name = 'CENTRO_ASISTENCIAL_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_en"."GEOMETRY" , ?T) as "GEOMETRY", id, id_municipio, fase, clave, eiel_c_en.codprov, eiel_c_en.codmunic, eiel_c_en.codentidad, eiel_c_en.codpoblamiento, orden_en FROM "eiel_c_en", ONLY eiel_t_nucl_encuest_1,eiel_configuracion_shp WHERE "eiel_c_en"."id_municipio" in (?M) and eiel_c_en.revision_expirada = 9999999999 and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY'' and (eiel_t_nucl_encuest_1.codprov = eiel_c_en.codprov and eiel_t_nucl_encuest_1.codmunic = eiel_c_en.codmunic and eiel_t_nucl_encuest_1.codentidad = eiel_c_en.codentidad and eiel_t_nucl_encuest_1.codpoblamiento = eiel_c_en.codpoblamiento and eiel_t_nucl_encuest_1.revision_expirada  = 9999999999 and eiel_t_nucl_encuest_1.padron > eiel_configuracion_shp.padron and eiel_t_nucl_encuest_1.viviendas_total >= eiel_configuracion_shp.viviendas)' where id_layer = (SELECT id_layer from layers where name = 'CENTRO_ENSENANZA_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_sa"."GEOMETRY" , ?T) as "GEOMETRY", id, id_municipio, fase, clave, eiel_c_sa.codprov, eiel_c_sa.codmunic, eiel_c_sa.codentidad, eiel_c_sa.codpoblamiento, orden_sa FROM "eiel_c_sa", ONLY eiel_t_nucl_encuest_1,eiel_configuracion_shp WHERE "eiel_c_sa"."id_municipio" in (?M) and eiel_c_sa.revision_expirada = 9999999999 and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY'' and (eiel_t_nucl_encuest_1.codprov = eiel_c_sa.codprov and eiel_t_nucl_encuest_1.codmunic = eiel_c_sa.codmunic and eiel_t_nucl_encuest_1.codentidad = eiel_c_sa.codentidad and eiel_t_nucl_encuest_1.codpoblamiento = eiel_c_sa.codpoblamiento and eiel_t_nucl_encuest_1.revision_expirada  = 9999999999 and eiel_t_nucl_encuest_1.padron > eiel_configuracion_shp.padron and eiel_t_nucl_encuest_1.viviendas_total >= eiel_configuracion_shp.viviendas)' where id_layer = (SELECT id_layer from layers where name = 'CENTRO_SANITARIO_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_su"."GEOMETRY" , ?T) as "GEOMETRY", id, id_municipio, fase, clave, eiel_c_su.codprov, eiel_c_su.codmunic, eiel_c_su.codentidad, eiel_c_su.codpoblamiento, orden_su FROM "eiel_c_su", ONLY eiel_t_nucl_encuest_1,eiel_configuracion_shp WHERE "eiel_c_su"."id_municipio" in (?M) and eiel_c_su.revision_expirada = 9999999999 and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY'' and (eiel_t_nucl_encuest_1.codprov = eiel_c_su.codprov and eiel_t_nucl_encuest_1.codmunic = eiel_c_su.codmunic and eiel_t_nucl_encuest_1.codentidad = eiel_c_su.codentidad and eiel_t_nucl_encuest_1.codpoblamiento = eiel_c_su.codpoblamiento and eiel_t_nucl_encuest_1.revision_expirada  = 9999999999 and eiel_t_nucl_encuest_1.padron > eiel_configuracion_shp.padron and eiel_t_nucl_encuest_1.viviendas_total >= eiel_configuracion_shp.viviendas)' where id_layer = (SELECT id_layer from layers where name = 'EDIF_PUB_SIN_USO_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_redviaria_tu"."GEOMETRY" , ?T) as "GEOMETRY", id, id_municipio, fase, eiel_c_redviaria_tu.codprov, eiel_c_redviaria_tu.codmunic, eiel_c_redviaria_tu.codentidad, eiel_c_redviaria_tu.codpoblamiento, tipo, estado FROM "eiel_c_redviaria_tu", ONLY eiel_t_nucl_encuest_1,eiel_configuracion_shp WHERE "eiel_c_redviaria_tu"."id_municipio" in (?M) and eiel_c_redviaria_tu.revision_expirada = 9999999999 and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY'' and (eiel_t_nucl_encuest_1.codprov = eiel_c_redviaria_tu.codprov and eiel_t_nucl_encuest_1.codmunic = eiel_c_redviaria_tu.codmunic and eiel_t_nucl_encuest_1.codentidad = eiel_c_redviaria_tu.codentidad and eiel_t_nucl_encuest_1.codpoblamiento = eiel_c_redviaria_tu.codpoblamiento and eiel_t_nucl_encuest_1.revision_expirada  = 9999999999 and eiel_t_nucl_encuest_1.padron > eiel_configuracion_shp.padron and eiel_t_nucl_encuest_1.viviendas_total >= eiel_configuracion_shp.viviendas)' where id_layer = (SELECT id_layer from layers where name = 'INFRAESTR_VIARIA_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_id"."GEOMETRY" , ?T) as "GEOMETRY", id, id_municipio, fase, clave, eiel_c_id.codprov, eiel_c_id.codmunic, eiel_c_id.codentidad, eiel_c_id.codpoblamiento, orden_id FROM "eiel_c_id", ONLY eiel_t_nucl_encuest_1,eiel_configuracion_shp WHERE "eiel_c_id"."id_municipio" in (?M) and eiel_c_id.revision_expirada = 9999999999 and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY'' and (eiel_t_nucl_encuest_1.codprov = eiel_c_id.codprov and eiel_t_nucl_encuest_1.codmunic = eiel_c_id.codmunic and eiel_t_nucl_encuest_1.codentidad = eiel_c_id.codentidad and eiel_t_nucl_encuest_1.codpoblamiento = eiel_c_id.codpoblamiento and eiel_t_nucl_encuest_1.revision_expirada  = 9999999999 and eiel_t_nucl_encuest_1.padron > eiel_configuracion_shp.padron and eiel_t_nucl_encuest_1.viviendas_total >= eiel_configuracion_shp.viviendas)' where id_layer = (SELECT id_layer from layers where name = 'INSTAL_DEPORTIVA_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_lm"."GEOMETRY" , ?T) as "GEOMETRY", id, id_municipio, fase, clave, eiel_c_lm.codprov, eiel_c_lm.codmunic, eiel_c_lm.codentidad, eiel_c_lm.codpoblamiento, orden_lm FROM "eiel_c_lm", ONLY eiel_t_nucl_encuest_1,eiel_configuracion_shp WHERE "eiel_c_lm"."id_municipio" in (?M) and eiel_c_lm.revision_expirada = 9999999999 and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY'' and (eiel_t_nucl_encuest_1.codprov = eiel_c_lm.codprov and eiel_t_nucl_encuest_1.codmunic = eiel_c_lm.codmunic and eiel_t_nucl_encuest_1.codentidad = eiel_c_lm.codentidad and eiel_t_nucl_encuest_1.codpoblamiento = eiel_c_lm.codpoblamiento and eiel_t_nucl_encuest_1.revision_expirada  = 9999999999 and eiel_t_nucl_encuest_1.padron > eiel_configuracion_shp.padron and eiel_t_nucl_encuest_1.viviendas_total >= eiel_configuracion_shp.viviendas)' where id_layer = (SELECT id_layer from layers where name = 'LONJA_MERC_FERIA_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_mt"."GEOMETRY" , ?T) as "GEOMETRY", id, id_municipio, fase, clave, eiel_c_mt.codprov, eiel_c_mt.codmunic, eiel_c_mt.codentidad, eiel_c_mt.codpoblamiento, orden_mt FROM "eiel_c_mt", ONLY eiel_t_nucl_encuest_1,eiel_configuracion_shp WHERE "eiel_c_mt"."id_municipio" in (?M) and eiel_c_mt.revision_expirada = 9999999999 and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY'' and (eiel_t_nucl_encuest_1.codprov = eiel_c_mt.codprov and eiel_t_nucl_encuest_1.codmunic = eiel_c_mt.codmunic and eiel_t_nucl_encuest_1.codentidad = eiel_c_mt.codentidad and eiel_t_nucl_encuest_1.codpoblamiento = eiel_c_mt.codpoblamiento and eiel_t_nucl_encuest_1.revision_expirada  = 9999999999 and eiel_t_nucl_encuest_1.padron > eiel_configuracion_shp.padron and eiel_t_nucl_encuest_1.viviendas_total >= eiel_configuracion_shp.viviendas)' where id_layer = (SELECT id_layer from layers where name = 'MATADERO_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_nucleo_poblacion"."GEOMETRY" , ?T) as "GEOMETRY", id, id_municipio, fase, eiel_c_nucleo_poblacion.codprov, eiel_c_nucleo_poblacion.codmunic, eiel_c_nucleo_poblacion.codentidad, nombre_oficial FROM "eiel_c_nucleo_poblacion", ONLY eiel_t_nucl_encuest_1,eiel_configuracion_shp WHERE "eiel_c_nucleo_poblacion"."id_municipio" in (?M) and eiel_c_nucleo_poblacion.revision_expirada = 9999999999 and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY'' and (eiel_t_nucl_encuest_1.codprov = eiel_c_nucleo_poblacion.codprov and eiel_t_nucl_encuest_1.codmunic = eiel_c_nucleo_poblacion.codmunic and eiel_t_nucl_encuest_1.codentidad = eiel_c_nucleo_poblacion.codentidad and eiel_t_nucl_encuest_1.codpoblamiento = eiel_c_nucleo_poblacion.codpoblamiento and eiel_t_nucl_encuest_1.revision_expirada  = 9999999999 and eiel_t_nucl_encuest_1.padron > eiel_configuracion_shp.padron and eiel_t_nucl_encuest_1.viviendas_total >= eiel_configuracion_shp.viviendas)' where id_layer = (SELECT id_layer from layers where name = 'NUCLEO_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_saneam_ali"."GEOMETRY" , ?T) as "GEOMETRY", id, id_municipio, fase, eiel_c_saneam_ali.codprov, eiel_c_saneam_ali.codmunic, eiel_c_saneam_ali.codentidad, eiel_c_saneam_ali.codpoblamiento FROM "eiel_c_saneam_ali", ONLY eiel_t_nucl_encuest_1,eiel_configuracion_shp WHERE "eiel_c_saneam_ali"."id_municipio" in (?M) and eiel_c_saneam_ali.revision_expirada = 9999999999 and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY'' and (eiel_t_nucl_encuest_1.codprov = eiel_c_saneam_ali.codprov and eiel_t_nucl_encuest_1.codmunic = eiel_c_saneam_ali.codmunic and eiel_t_nucl_encuest_1.codentidad = eiel_c_saneam_ali.codentidad and eiel_t_nucl_encuest_1.codpoblamiento = eiel_c_saneam_ali.codpoblamiento and eiel_t_nucl_encuest_1.revision_expirada  = 9999999999 and eiel_t_nucl_encuest_1.padron > eiel_configuracion_shp.padron and eiel_t_nucl_encuest_1.viviendas_total >= eiel_configuracion_shp.viviendas)' where id_layer = (SELECT id_layer from layers where name = 'ALIVIADERO_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_pj"."GEOMETRY" , ?T) as "GEOMETRY", eiel_c_pj.id, eiel_c_pj.id_municipio, fase, eiel_c_pj.clave, eiel_c_pj.codprov, eiel_c_pj.codmunic, eiel_c_pj.codentidad, eiel_c_pj.codpoblamiento, eiel_c_pj.orden_pj FROM eiel_configuracion_shp, ONLY eiel_t_nucl_encuest_1,"eiel_c_pj", eiel_t_pj  where (tipo = ''JA'' or tipo = ''PI'' or tipo = ''PN'' or tipo = ''PU'') and eiel_t_pj.clave = eiel_c_pj.clave AND eiel_t_pj.codprov = eiel_c_pj.codprov AND eiel_t_pj.codmunic = eiel_c_pj.codmunic AND eiel_t_pj.codentidad = eiel_c_pj.codentidad AND eiel_t_pj.codpoblamiento = eiel_c_pj.codpoblamiento AND eiel_t_pj.orden_pj = eiel_c_pj.orden_pj and eiel_t_pj.revision_expirada = 9999999999 and eiel_c_pj.revision_expirada = 9999999999 and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY'' and "eiel_c_pj"."id_municipio" in (?M) and (eiel_t_nucl_encuest_1.codprov = eiel_c_pj.codprov and eiel_t_nucl_encuest_1.codmunic = eiel_c_pj.codmunic and eiel_t_nucl_encuest_1.codentidad = eiel_c_pj.codentidad and eiel_t_nucl_encuest_1.codpoblamiento = eiel_c_pj.codpoblamiento and eiel_t_nucl_encuest_1.revision_expirada  = 9999999999 and eiel_t_nucl_encuest_1.padron > eiel_configuracion_shp.padron and eiel_t_nucl_encuest_1.viviendas_total >= eiel_configuracion_shp.viviendas)' where id_layer = (SELECT id_layer from layers where name = 'PARQUE_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_pj"."GEOMETRY" , ?T) as "GEOMETRY", eiel_c_pj.id, eiel_c_pj.id_municipio, fase, eiel_c_pj.clave, eiel_c_pj.codprov, eiel_c_pj.codmunic, eiel_c_pj.codentidad, eiel_c_pj.codpoblamiento, eiel_c_pj.orden_pj FROM eiel_configuracion_shp, ONLY eiel_t_nucl_encuest_1,"eiel_c_pj", eiel_t_pj where (tipo = ''AN'' or tipo = ''ZR'') and eiel_t_pj.clave = eiel_c_pj.clave AND eiel_t_pj.codprov = eiel_c_pj.codprov AND eiel_t_pj.codmunic = eiel_c_pj.codmunic AND eiel_t_pj.codentidad = eiel_c_pj.codentidad AND eiel_t_pj.codpoblamiento = eiel_c_pj.codpoblamiento AND eiel_t_pj.orden_pj = eiel_c_pj.orden_pj and eiel_t_pj.revision_expirada = 9999999999 and eiel_c_pj.revision_expirada = 9999999999  and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY'' and "eiel_c_pj"."id_municipio" in (?M) and (eiel_t_nucl_encuest_1.codprov = eiel_c_pj.codprov and eiel_t_nucl_encuest_1.codmunic = eiel_c_pj.codmunic and eiel_t_nucl_encuest_1.codentidad = eiel_c_pj.codentidad and eiel_t_nucl_encuest_1.codpoblamiento = eiel_c_pj.codpoblamiento and eiel_t_nucl_encuest_1.revision_expirada  = 9999999999 and eiel_t_nucl_encuest_1.padron > eiel_configuracion_shp.padron and eiel_t_nucl_encuest_1.viviendas_total >= eiel_configuracion_shp.viviendas)' where id_layer = (SELECT id_layer from layers where name = 'ZONAS_NATURALES_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_ip"."GEOMETRY" , ?T) as "GEOMETRY", id, id_municipio, fase, clave, eiel_c_ip.codprov, eiel_c_ip.codmunic, eiel_c_ip.codentidad, eiel_c_ip.codpoblamiento, orden_ip FROM "eiel_c_ip", ONLY eiel_t_nucl_encuest_1,eiel_configuracion_shp WHERE "eiel_c_ip"."id_municipio" in (?M) and eiel_c_ip.revision_expirada = 9999999999 and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY'' and (eiel_t_nucl_encuest_1.codprov = eiel_c_ip.codprov and eiel_t_nucl_encuest_1.codmunic = eiel_c_ip.codmunic and eiel_t_nucl_encuest_1.codentidad = eiel_c_ip.codentidad and eiel_t_nucl_encuest_1.codpoblamiento = eiel_c_ip.codpoblamiento and eiel_t_nucl_encuest_1.revision_expirada  = 9999999999 and eiel_t_nucl_encuest_1.padron > eiel_configuracion_shp.padron and eiel_t_nucl_encuest_1.viviendas_total >= eiel_configuracion_shp.viviendas)' where id_layer = (SELECT id_layer from layers where name = 'PROTECCION_CIVIL_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_saneam_rs"."GEOMETRY" , ?T) as "GEOMETRY", id, id_municipio, fase, eiel_c_saneam_rs.codprov, eiel_c_saneam_rs.codmunic, eiel_c_saneam_rs.codentidad, eiel_c_saneam_rs.codpoblamiento, tramo_rs, sist_impulsion, estado, tipo_red_interior, titular, gestor FROM "eiel_c_saneam_rs",ONLY eiel_t_nucl_encuest_1, eiel_configuracion_shp WHERE "eiel_c_saneam_rs"."id_municipio" in (?M) and eiel_c_saneam_rs.revision_expirada = 9999999999 and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY'' and (eiel_t_nucl_encuest_1.codprov = eiel_c_saneam_rs.codprov and eiel_t_nucl_encuest_1.codmunic = eiel_c_saneam_rs.codmunic and eiel_t_nucl_encuest_1.codentidad = eiel_c_saneam_rs.codentidad and eiel_t_nucl_encuest_1.codpoblamiento = eiel_c_saneam_rs.codpoblamiento and eiel_t_nucl_encuest_1.revision_expirada  = 9999999999 and eiel_t_nucl_encuest_1.padron > eiel_configuracion_shp.padron and eiel_t_nucl_encuest_1.viviendas_total >= eiel_configuracion_shp.viviendas)' where id_layer = (SELECT id_layer from layers where name = 'RAMAL_SANEAMIENTO_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_abast_rd"."GEOMETRY" , ?T) as "GEOMETRY", id, id_municipio, fase, eiel_c_abast_rd.codprov, eiel_c_abast_rd.codmunic, eiel_c_abast_rd.codentidad, eiel_c_abast_rd.codpoblamiento, tramo_rd, sist_trans, estado, titular, gestor FROM "eiel_c_abast_rd", ONLY eiel_t_nucl_encuest_1,eiel_configuracion_shp WHERE "eiel_c_abast_rd"."id_municipio" in (?M) and eiel_c_abast_rd.revision_expirada = 9999999999  and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY'' and (eiel_t_nucl_encuest_1.codprov = eiel_c_abast_rd.codprov and eiel_t_nucl_encuest_1.codmunic = eiel_c_abast_rd.codmunic and eiel_t_nucl_encuest_1.codentidad = eiel_c_abast_rd.codentidad and eiel_t_nucl_encuest_1.codpoblamiento = eiel_c_abast_rd.codpoblamiento and eiel_t_nucl_encuest_1.revision_expirada  = 9999999999 and eiel_t_nucl_encuest_1.padron > eiel_configuracion_shp.padron and eiel_t_nucl_encuest_1.viviendas_total >= eiel_configuracion_shp.viviendas)' where id_layer = (SELECT id_layer from layers where name = 'RED_DISTRIBUCION_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_ta"."GEOMETRY" , ?T) as "GEOMETRY", id, id_municipio, fase, clave, eiel_c_ta.codprov, eiel_c_ta.codmunic, eiel_c_ta.codentidad, eiel_c_ta.codpoblamiento, orden_ta FROM "eiel_c_ta", ONLY eiel_t_nucl_encuest_1,eiel_configuracion_shp WHERE "eiel_c_ta"."id_municipio" in (?M) and eiel_c_ta.revision_expirada = 9999999999 and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY'' and (eiel_t_nucl_encuest_1.codprov = eiel_c_ta.codprov and eiel_t_nucl_encuest_1.codmunic = eiel_c_ta.codmunic and eiel_t_nucl_encuest_1.codentidad = eiel_c_ta.codentidad and eiel_t_nucl_encuest_1.codpoblamiento = eiel_c_ta.codpoblamiento and eiel_t_nucl_encuest_1.revision_expirada  = 9999999999 and eiel_t_nucl_encuest_1.padron > eiel_configuracion_shp.padron and eiel_t_nucl_encuest_1.viviendas_total >= eiel_configuracion_shp.viviendas)' where id_layer = (SELECT id_layer from layers where name = 'TANATORIO_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_abast_ca"."GEOMETRY" , ?T) as "GEOMETRY", eiel_c_abast_ca.id, eiel_c_abast_ca.id_municipio, eiel_configuracion_shp.fase, eiel_c_abast_ca.clave, eiel_c_abast_ca.codprov, eiel_c_abast_ca.codmunic, eiel_c_abast_ca.orden_ca FROM eiel_configuracion_shp,"eiel_c_abast_ca" LEFT JOIN eiel_t_padron_ttmm ON eiel_t_padron_ttmm.codprov::text = eiel_c_abast_ca.codprov::text AND eiel_t_padron_ttmm.codmunic::text = eiel_c_abast_ca.codmunic::text WHERE eiel_t_padron_ttmm.total_poblacion_a1 < 50000 AND (eiel_c_abast_ca.codmunic::text || eiel_c_abast_ca.orden_ca::text IN ( SELECT DISTINCT v_cap_agua_nucleo.c_municip::text || v_cap_agua_nucleo.orden_capt::text FROM v_cap_agua_nucleo ORDER BY v_cap_agua_nucleo.c_municip::text || v_cap_agua_nucleo.orden_capt::text))  and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY'' AND eiel_c_abast_ca.revision_expirada = 9999999999::bigint::numeric AND eiel_t_padron_ttmm.revision_expirada = 9999999999::bigint::numeric AND id_municipio IN (?M)' where id_layer = (SELECT id_layer from layers where name = 'CAPTACION_ENC_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_abast_ca"."GEOMETRY" , ?T) as "GEOMETRY", eiel_c_abast_ca.id, eiel_c_abast_ca.id_municipio, eiel_configuracion_shp.fase, eiel_c_abast_ca.clave, eiel_c_abast_ca.codprov, eiel_c_abast_ca.codmunic, eiel_c_abast_ca.orden_ca FROM eiel_configuracion_shp,"eiel_c_abast_ca" LEFT JOIN eiel_t_padron_ttmm ON eiel_t_padron_ttmm.codprov::text = eiel_c_abast_ca.codprov::text AND eiel_t_padron_ttmm.codmunic::text = eiel_c_abast_ca.codmunic::text WHERE eiel_t_padron_ttmm.total_poblacion_a1 >= 50000 AND (eiel_c_abast_ca.codmunic::text || eiel_c_abast_ca.orden_ca::text IN ( SELECT DISTINCT v_cap_agua_nucleo.c_municip::text || v_cap_agua_nucleo.orden_capt::text FROM v_cap_agua_nucleo ORDER BY v_cap_agua_nucleo.c_municip::text || v_cap_agua_nucleo.orden_capt::text))  and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY'' AND eiel_c_abast_ca.revision_expirada = 9999999999::bigint::numeric AND eiel_t_padron_ttmm.revision_expirada = 9999999999::bigint::numeric AND id_municipio IN (?M)' where id_layer = (SELECT id_layer from layers where name = 'CAPTACION_ENC_M50_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_abast_de"."GEOMETRY" , ?T) as "GEOMETRY", eiel_c_abast_de.id, eiel_c_abast_de.id_municipio, eiel_configuracion_shp.fase, eiel_c_abast_de.clave, eiel_c_abast_de.codprov, eiel_c_abast_de.codmunic, eiel_c_abast_de.orden_de FROM eiel_configuracion_shp,"eiel_c_abast_de" LEFT JOIN eiel_t_padron_ttmm ON eiel_t_padron_ttmm.codprov::text = eiel_c_abast_de.codprov::text AND eiel_t_padron_ttmm.codmunic::text = eiel_c_abast_de.codmunic::text WHERE eiel_t_padron_ttmm.total_poblacion_a1 < 50000 AND (eiel_c_abast_de.codmunic::text || eiel_c_abast_de.orden_de::text IN ( SELECT DISTINCT v_deposito_agua_nucleo.de_municip::text || v_deposito_agua_nucleo.orden_depo::text FROM v_deposito_agua_nucleo ORDER BY v_deposito_agua_nucleo.de_municip::text || v_deposito_agua_nucleo.orden_depo::text)) AND eiel_t_padron_ttmm.revision_expirada = 9999999999::bigint::numeric AND eiel_c_abast_de.revision_expirada = 9999999999::bigint::numeric  AND id_municipio IN (?M)  and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY''' where id_layer = (SELECT id_layer from layers where name = 'DEPOSITO_ENC_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_abast_de"."GEOMETRY" , ?T) as "GEOMETRY", eiel_c_abast_de.id, eiel_c_abast_de.id_municipio, eiel_configuracion_shp.fase, eiel_c_abast_de.clave, eiel_c_abast_de.codprov, eiel_c_abast_de.codmunic, eiel_c_abast_de.orden_de FROM eiel_configuracion_shp,"eiel_c_abast_de" LEFT JOIN eiel_t_padron_ttmm ON eiel_t_padron_ttmm.codprov::text = eiel_c_abast_de.codprov::text AND eiel_t_padron_ttmm.codmunic::text = eiel_c_abast_de.codmunic::text WHERE eiel_t_padron_ttmm.total_poblacion_a1 >= 50000 AND (eiel_c_abast_de.codmunic::text || eiel_c_abast_de.orden_de::text IN ( SELECT DISTINCT v_deposito_agua_nucleo.de_municip::text || v_deposito_agua_nucleo.orden_depo::text FROM v_deposito_agua_nucleo ORDER BY v_deposito_agua_nucleo.de_municip::text || v_deposito_agua_nucleo.orden_depo::text)) AND eiel_t_padron_ttmm.revision_expirada = 9999999999::bigint::numeric AND eiel_c_abast_de.revision_expirada = 9999999999::bigint::numeric  AND id_municipio IN (?M)  and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY''' where id_layer = (SELECT id_layer from layers where name = 'DEPOSITO_ENC_M50_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_saneam_ed"."GEOMETRY" , ?T) as "GEOMETRY", eiel_c_saneam_ed.id, eiel_c_saneam_ed.id_municipio, eiel_configuracion_shp.fase, eiel_c_saneam_ed.clave, eiel_c_saneam_ed.codprov, eiel_c_saneam_ed.codmunic, eiel_c_saneam_ed.orden_ed FROM eiel_configuracion_shp,"eiel_c_saneam_ed" LEFT JOIN eiel_t_padron_ttmm ON eiel_t_padron_ttmm.codprov::text = eiel_c_saneam_ed.codprov::text AND eiel_t_padron_ttmm.codmunic::text = eiel_c_saneam_ed.codmunic::text WHERE eiel_t_padron_ttmm.total_poblacion_a1 < 50000 AND (eiel_c_saneam_ed.codmunic::text || eiel_c_saneam_ed.orden_ed::text IN ( SELECT DISTINCT v_dep_agua_nucleo.de_municip::text || v_dep_agua_nucleo.orden_depu::text FROM v_dep_agua_nucleo ORDER BY v_dep_agua_nucleo.de_municip::text || v_dep_agua_nucleo.orden_depu::text)) AND eiel_c_saneam_ed.revision_expirada = 9999999999::bigint::numeric AND eiel_t_padron_ttmm.revision_expirada = 9999999999::bigint::numeric  AND id_municipio IN (?M)  and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY''' where id_layer = (SELECT id_layer from layers where name = 'DEPURADORA_ENC_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_saneam_ed"."GEOMETRY" , ?T) as "GEOMETRY", eiel_c_saneam_ed.id, eiel_c_saneam_ed.id_municipio, eiel_configuracion_shp.fase, eiel_c_saneam_ed.clave, eiel_c_saneam_ed.codprov, eiel_c_saneam_ed.codmunic, eiel_c_saneam_ed.orden_ed FROM eiel_configuracion_shp,"eiel_c_saneam_ed" LEFT JOIN eiel_t_padron_ttmm ON eiel_t_padron_ttmm.codprov::text = eiel_c_saneam_ed.codprov::text AND eiel_t_padron_ttmm.codmunic::text = eiel_c_saneam_ed.codmunic::text WHERE eiel_t_padron_ttmm.total_poblacion_a1 >= 50000 AND (eiel_c_saneam_ed.codmunic::text || eiel_c_saneam_ed.orden_ed::text IN ( SELECT DISTINCT v_dep_agua_nucleo.de_municip::text || v_dep_agua_nucleo.orden_depu::text FROM v_dep_agua_nucleo ORDER BY v_dep_agua_nucleo.de_municip::text || v_dep_agua_nucleo.orden_depu::text)) AND eiel_c_saneam_ed.revision_expirada = 9999999999::bigint::numeric AND eiel_t_padron_ttmm.revision_expirada = 9999999999::bigint::numeric  AND id_municipio IN (?M)  and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY''' where id_layer = (SELECT id_layer from layers where name = 'DEPURADORA_ENC_M50_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_saneam_tem"."GEOMETRY" , ?T) as "GEOMETRY", eiel_c_saneam_tem.id, eiel_c_saneam_tem.id_municipio, eiel_configuracion_shp.fase, eiel_c_saneam_tem.clave, eiel_c_saneam_tem.codprov, eiel_c_saneam_tem.codmunic, eiel_c_saneam_tem.tramo_em FROM eiel_configuracion_shp,"eiel_c_saneam_tem" LEFT JOIN eiel_t_padron_ttmm ON eiel_t_padron_ttmm.codprov::text = eiel_c_saneam_tem.codprov::text AND eiel_t_padron_ttmm.codmunic::text = eiel_c_saneam_tem.codmunic::text WHERE eiel_t_padron_ttmm.total_poblacion_a1 < 50000 AND (eiel_c_saneam_tem.codmunic::text || eiel_c_saneam_tem.tramo_em::text IN ( SELECT DISTINCT v_emisario_nucleo.em_municip::text || v_emisario_nucleo.orden_emis::text FROM v_emisario_nucleo ORDER BY v_emisario_nucleo.em_municip::text || v_emisario_nucleo.orden_emis::text)) AND eiel_t_padron_ttmm.revision_expirada = 9999999999::bigint::numeric AND eiel_c_saneam_tem.revision_expirada = 9999999999::bigint::numeric  AND id_municipio IN (?M)  and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY''' where id_layer = (SELECT id_layer from layers where name = 'EMISARIO_ENC_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_saneam_tem"."GEOMETRY" , ?T) as "GEOMETRY", eiel_c_saneam_tem.id, eiel_c_saneam_tem.id_municipio, eiel_configuracion_shp.fase, eiel_c_saneam_tem.clave, eiel_c_saneam_tem.codprov, eiel_c_saneam_tem.codmunic, eiel_c_saneam_tem.tramo_em FROM eiel_configuracion_shp,"eiel_c_saneam_tem" LEFT JOIN eiel_t_padron_ttmm ON eiel_t_padron_ttmm.codprov::text = eiel_c_saneam_tem.codprov::text AND eiel_t_padron_ttmm.codmunic::text = eiel_c_saneam_tem.codmunic::text WHERE eiel_t_padron_ttmm.total_poblacion_a1 >= 50000 AND (eiel_c_saneam_tem.codmunic::text || eiel_c_saneam_tem.tramo_em::text IN ( SELECT DISTINCT v_emisario_nucleo.em_municip::text || v_emisario_nucleo.orden_emis::text FROM v_emisario_nucleo ORDER BY v_emisario_nucleo.em_municip::text || v_emisario_nucleo.orden_emis::text)) AND eiel_t_padron_ttmm.revision_expirada = 9999999999::bigint::numeric AND eiel_c_saneam_tem.revision_expirada = 9999999999::bigint::numeric  AND id_municipio IN (?M)  and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY''' where id_layer = (SELECT id_layer from layers where name = 'EMISARIO_ENC_M50_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_abast_tp"."GEOMETRY" , ?T) as "GEOMETRY", "eiel_c_abast_tp".id, "eiel_c_abast_tp".id_municipio, eiel_configuracion_shp.fase, "eiel_c_abast_tp".clave, "eiel_c_abast_tp".codprov, "eiel_c_abast_tp".codmunic, "eiel_c_abast_tp".orden_tp FROM eiel_configuracion_shp,"eiel_c_abast_tp" LEFT JOIN eiel_t_padron_ttmm ON eiel_t_padron_ttmm.codprov::text = eiel_c_abast_tp.codprov::text AND eiel_t_padron_ttmm.codmunic::text = eiel_c_abast_tp.codmunic::text WHERE eiel_t_padron_ttmm.total_poblacion_a1 < 50000 AND (eiel_c_abast_tp.codmunic::text || eiel_c_abast_tp.orden_tp::text IN ( SELECT DISTINCT v_trat_pota_nucleo.po_munipi::text || v_trat_pota_nucleo.orden_trat::text FROM v_trat_pota_nucleo ORDER BY v_trat_pota_nucleo.po_munipi::text || v_trat_pota_nucleo.orden_trat::text)) AND eiel_c_abast_tp.revision_expirada = 9999999999::bigint::numeric AND eiel_t_padron_ttmm.revision_expirada = 9999999999::bigint::numeric AND id_municipio IN (?M)  and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY''' where id_layer = (SELECT id_layer from layers where name = 'POTABILIZACION_ENC_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_abast_tp"."GEOMETRY" , ?T) as "GEOMETRY", "eiel_c_abast_tp".id, "eiel_c_abast_tp".id_municipio, eiel_configuracion_shp.fase, "eiel_c_abast_tp".clave, "eiel_c_abast_tp".codprov, "eiel_c_abast_tp".codmunic, "eiel_c_abast_tp".orden_tp FROM eiel_configuracion_shp,"eiel_c_abast_tp" LEFT JOIN eiel_t_padron_ttmm ON eiel_t_padron_ttmm.codprov::text = eiel_c_abast_tp.codprov::text AND eiel_t_padron_ttmm.codmunic::text = eiel_c_abast_tp.codmunic::text WHERE eiel_t_padron_ttmm.total_poblacion_a1 < 50000 AND (eiel_c_abast_tp.codmunic::text || eiel_c_abast_tp.orden_tp::text IN ( SELECT DISTINCT v_trat_pota_nucleo.po_munipi::text || v_trat_pota_nucleo.orden_trat::text FROM v_trat_pota_nucleo ORDER BY v_trat_pota_nucleo.po_munipi::text || v_trat_pota_nucleo.orden_trat::text)) AND eiel_c_abast_tp.revision_expirada = 9999999999::bigint::numeric AND eiel_t_padron_ttmm.revision_expirada = 9999999999::bigint::numeric AND id_municipio IN (?M)  and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY''' where id_layer = (SELECT id_layer from layers where name = 'POTABILIZACION_ENC_M50_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_saneam_tcl"."GEOMETRY" , ?T) as "GEOMETRY", "eiel_c_saneam_tcl".id, "eiel_c_saneam_tcl".id_municipio, eiel_configuracion_shp.fase, "eiel_c_saneam_tcl".clave, "eiel_c_saneam_tcl".codprov, "eiel_c_saneam_tcl".codmunic, "eiel_c_saneam_tcl".tramo_cl, tipo_red_interior, sist_impulsion, estado, titular, gestor FROM eiel_configuracion_shp,"eiel_c_saneam_tcl", eiel_t_saneam_tcl LEFT JOIN eiel_t_padron_ttmm ON eiel_t_padron_ttmm.codprov::text = eiel_t_saneam_tcl.codprov::text AND eiel_t_padron_ttmm.codmunic::text = eiel_t_saneam_tcl.codmunic::text WHERE eiel_t_padron_ttmm.total_poblacion_a1 < 50000 AND (eiel_t_saneam_tcl.codmunic::text || eiel_t_saneam_tcl.tramo_cl::text IN ( SELECT DISTINCT v_colector_nucleo.c_municip::text || v_colector_nucleo.orden_cole::text FROM v_colector_nucleo  ORDER BY v_colector_nucleo.c_municip::text || v_colector_nucleo.orden_cole::text)) AND eiel_t_padron_ttmm.revision_expirada = 9999999999::bigint::numeric AND eiel_t_saneam_tcl.tramo_cl::text = eiel_c_saneam_tcl.tramo_cl::text AND eiel_t_saneam_tcl.revision_expirada = 9999999999::bigint::numeric and eiel_t_saneam_tcl.clave::text = eiel_c_saneam_tcl.clave::text AND eiel_t_saneam_tcl.codprov::text = eiel_c_saneam_tcl.codprov::text AND eiel_t_saneam_tcl.codmunic::text = eiel_c_saneam_tcl.codmunic::text AND eiel_t_saneam_tcl.tramo_cl::text = eiel_c_saneam_tcl.tramo_cl::text AND eiel_c_saneam_tcl.revision_expirada = 9999999999::bigint::numeric AND id_municipio IN (?M)  and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY''' where id_layer = (SELECT id_layer from layers where name = 'TRAMO_COLECTOR_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_saneam_tcl"."GEOMETRY" , ?T) as "GEOMETRY", "eiel_c_saneam_tcl".id, "eiel_c_saneam_tcl".id_municipio, eiel_configuracion_shp.fase, "eiel_c_saneam_tcl".clave, "eiel_c_saneam_tcl".codprov, "eiel_c_saneam_tcl".codmunic, "eiel_c_saneam_tcl".tramo_cl, tipo_red_interior, sist_impulsion, estado, titular, gestor FROM eiel_configuracion_shp,"eiel_c_saneam_tcl", eiel_t_saneam_tcl LEFT JOIN eiel_t_padron_ttmm ON eiel_t_padron_ttmm.codprov::text = eiel_t_saneam_tcl.codprov::text AND eiel_t_padron_ttmm.codmunic::text = eiel_t_saneam_tcl.codmunic::text WHERE eiel_t_padron_ttmm.total_poblacion_a1 >= 50000 AND (eiel_t_saneam_tcl.codmunic::text || eiel_t_saneam_tcl.tramo_cl::text IN ( SELECT DISTINCT v_colector_nucleo.c_municip::text || v_colector_nucleo.orden_cole::text FROM v_colector_nucleo  ORDER BY v_colector_nucleo.c_municip::text || v_colector_nucleo.orden_cole::text)) AND eiel_t_padron_ttmm.revision_expirada = 9999999999::bigint::numeric AND eiel_t_saneam_tcl.tramo_cl::text = eiel_c_saneam_tcl.tramo_cl::text AND eiel_t_saneam_tcl.revision_expirada = 9999999999::bigint::numeric and eiel_t_saneam_tcl.clave::text = eiel_c_saneam_tcl.clave::text AND eiel_t_saneam_tcl.codprov::text = eiel_c_saneam_tcl.codprov::text AND eiel_t_saneam_tcl.codmunic::text = eiel_c_saneam_tcl.codmunic::text AND eiel_t_saneam_tcl.tramo_cl::text = eiel_c_saneam_tcl.tramo_cl::text AND eiel_c_saneam_tcl.revision_expirada = 9999999999::bigint::numeric AND id_municipio IN (?M)  and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY''' where id_layer = (SELECT id_layer from layers where name = 'TRAMO_COLECTOR_M50_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_abast_tcn"."GEOMETRY" , ?T) as "GEOMETRY", id, id_municipio, eiel_configuracion_shp.fase, eiel_c_abast_tcn.clave, eiel_c_abast_tcn.codprov, eiel_c_abast_tcn.codmunic, eiel_c_abast_tcn.tramo_cn, eiel_t_abast_tcn.material, eiel_t_abast_tcn.estado, eiel_t_abast_tcn.titular, eiel_t_abast_tcn.gestor FROM eiel_configuracion_shp,"eiel_c_abast_tcn", eiel_t_abast_tcn LEFT JOIN eiel_t_padron_ttmm ON eiel_t_padron_ttmm.codprov::text = eiel_t_abast_tcn.codprov::text AND eiel_t_padron_ttmm.codmunic::text = eiel_t_abast_tcn.codmunic::text WHERE eiel_t_padron_ttmm.total_poblacion_a1 < 50000 AND (eiel_t_abast_tcn.codmunic::text || eiel_t_abast_tcn.tramo_cn::text IN ( SELECT DISTINCT v_cond_agua_nucleo.cond_munic::text || v_cond_agua_nucleo.orden_cond::text  FROM v_cond_agua_nucleo  ORDER BY v_cond_agua_nucleo.cond_munic::text || v_cond_agua_nucleo.orden_cond::text)) AND eiel_t_padron_ttmm.revision_expirada = 9999999999::bigint::numeric AND eiel_t_abast_tcn.revision_expirada = 9999999999::bigint::numeric and eiel_c_abast_tcn.revision_expirada = 9999999999 and eiel_c_abast_tcn.clave::text = eiel_t_abast_tcn.clave::text AND eiel_c_abast_tcn.codprov::text = eiel_t_abast_tcn.codprov::text AND eiel_c_abast_tcn.codmunic::text = eiel_t_abast_tcn.codmunic::text AND eiel_c_abast_tcn.tramo_cn::text = eiel_t_abast_tcn.tramo_cn::text   AND id_municipio IN (?M)  and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY''' where id_layer = (SELECT id_layer from layers where name = 'TRAMO_CONDUCCION_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_abast_tcn"."GEOMETRY" , ?T) as "GEOMETRY", id, id_municipio, eiel_configuracion_shp.fase, eiel_c_abast_tcn.clave, eiel_c_abast_tcn.codprov, eiel_c_abast_tcn.codmunic, eiel_c_abast_tcn.tramo_cn, eiel_t_abast_tcn.material, eiel_t_abast_tcn.estado, eiel_t_abast_tcn.titular, eiel_t_abast_tcn.gestor FROM eiel_configuracion_shp,"eiel_c_abast_tcn", eiel_t_abast_tcn LEFT JOIN eiel_t_padron_ttmm ON eiel_t_padron_ttmm.codprov::text = eiel_t_abast_tcn.codprov::text AND eiel_t_padron_ttmm.codmunic::text = eiel_t_abast_tcn.codmunic::text WHERE eiel_t_padron_ttmm.total_poblacion_a1 >= 50000 AND (eiel_t_abast_tcn.codmunic::text || eiel_t_abast_tcn.tramo_cn::text IN ( SELECT DISTINCT v_cond_agua_nucleo.cond_munic::text || v_cond_agua_nucleo.orden_cond::text  FROM v_cond_agua_nucleo  ORDER BY v_cond_agua_nucleo.cond_munic::text || v_cond_agua_nucleo.orden_cond::text)) AND eiel_t_padron_ttmm.revision_expirada = 9999999999::bigint::numeric AND eiel_t_abast_tcn.revision_expirada = 9999999999::bigint::numeric and eiel_c_abast_tcn.revision_expirada = 9999999999 and eiel_c_abast_tcn.clave::text = eiel_t_abast_tcn.clave::text AND eiel_c_abast_tcn.codprov::text = eiel_t_abast_tcn.codprov::text AND eiel_c_abast_tcn.codmunic::text = eiel_t_abast_tcn.codmunic::text AND eiel_c_abast_tcn.tramo_cn::text = eiel_t_abast_tcn.tramo_cn::text   AND id_municipio IN (?M)  and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY''' where id_layer = (SELECT id_layer from layers where name = 'TRAMO_CONDUCCION_M50_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_saneam_tem"."GEOMETRY" , ?T) as "GEOMETRY", id, id_municipio, eiel_configuracion_shp.fase, eiel_c_saneam_tem.clave, eiel_c_saneam_tem.codprov, eiel_c_saneam_tem.codmunic, eiel_c_saneam_tem.tramo_em, material, estado FROM eiel_configuracion_shp,"eiel_c_saneam_tem", eiel_t_saneam_tem LEFT JOIN eiel_t_padron_ttmm ON eiel_t_padron_ttmm.codprov::text = eiel_t_saneam_tem.codprov::text AND eiel_t_padron_ttmm.codmunic::text = eiel_t_saneam_tem.codmunic::text WHERE eiel_t_padron_ttmm.total_poblacion_a1 < 50000 AND (eiel_t_saneam_tem.codmunic::text || eiel_t_saneam_tem.tramo_em::text IN ( SELECT DISTINCT v_emisario_nucleo.em_municip::text || v_emisario_nucleo.orden_emis::text FROM v_emisario_nucleo ORDER BY v_emisario_nucleo.em_municip::text || v_emisario_nucleo.orden_emis::text)) AND eiel_t_padron_ttmm.revision_expirada = 9999999999::bigint::numeric AND eiel_t_saneam_tem.tramo_em::text = eiel_c_saneam_tem.tramo_em::text AND eiel_t_saneam_tem.revision_expirada = 9999999999::bigint::numeric and eiel_t_saneam_tem.clave::text = eiel_c_saneam_tem.clave::text AND eiel_t_saneam_tem.codprov::text = eiel_c_saneam_tem.codprov::text AND eiel_t_saneam_tem.codmunic::text = eiel_c_saneam_tem.codmunic::text AND eiel_c_saneam_tem.revision_expirada = 9999999999::bigint::numeric AND id_municipio IN (?M)  and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY''' where id_layer = (SELECT id_layer from layers where name = 'TRAMO_EMISARIO_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_saneam_tem"."GEOMETRY" , ?T) as "GEOMETRY", id, id_municipio, eiel_configuracion_shp.fase, eiel_c_saneam_tem.clave, eiel_c_saneam_tem.codprov, eiel_c_saneam_tem.codmunic, eiel_c_saneam_tem.tramo_em, material, estado FROM eiel_configuracion_shp,"eiel_c_saneam_tem", eiel_t_saneam_tem LEFT JOIN eiel_t_padron_ttmm ON eiel_t_padron_ttmm.codprov::text = eiel_t_saneam_tem.codprov::text AND eiel_t_padron_ttmm.codmunic::text = eiel_t_saneam_tem.codmunic::text WHERE eiel_t_padron_ttmm.total_poblacion_a1 < 50000 AND (eiel_t_saneam_tem.codmunic::text || eiel_t_saneam_tem.tramo_em::text IN ( SELECT DISTINCT v_emisario_nucleo.em_municip::text || v_emisario_nucleo.orden_emis::text FROM v_emisario_nucleo ORDER BY v_emisario_nucleo.em_municip::text || v_emisario_nucleo.orden_emis::text)) AND eiel_t_padron_ttmm.revision_expirada = 9999999999::bigint::numeric AND eiel_t_saneam_tem.tramo_em::text = eiel_c_saneam_tem.tramo_em::text AND eiel_t_saneam_tem.revision_expirada = 9999999999::bigint::numeric and eiel_t_saneam_tem.clave::text = eiel_c_saneam_tem.clave::text AND eiel_t_saneam_tem.codprov::text = eiel_c_saneam_tem.codprov::text AND eiel_t_saneam_tem.codmunic::text = eiel_c_saneam_tem.codmunic::text AND eiel_c_saneam_tem.revision_expirada = 9999999999::bigint::numeric AND id_municipio IN (?M)  and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY''' where id_layer = (SELECT id_layer from layers where name = 'TRAMO_EMISARIO_M50_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_vt"."GEOMETRY" , ?T) as "GEOMETRY", id, id_municipio, fase, clave, codprov, codmunic, orden_vt FROM "eiel_c_vt", eiel_configuracion_shp WHERE "eiel_c_vt"."id_municipio" in (SELECT distinct eiel_t_padron_ttmm.codprov||eiel_t_padron_ttmm.codmunic FROM public.eiel_t_padron_ttmm WHERE TOTAL_POBLACION_A1 < 50000) and revision_expirada = 9999999999 and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY'' and id_municipio IN (?M)' where id_layer = (SELECT id_layer from layers where name = 'VERT_ENCUESTADO_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_vt"."GEOMETRY" , ?T) as "GEOMETRY", id, id_municipio, fase, clave, codprov, codmunic, orden_vt FROM "eiel_c_vt", eiel_configuracion_shp WHERE "eiel_c_vt"."id_municipio" in (SELECT distinct eiel_t_padron_ttmm.codprov||eiel_t_padron_ttmm.codmunic FROM public.eiel_t_padron_ttmm WHERE TOTAL_POBLACION_A1 >= 50000) and revision_expirada = 9999999999 and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY'' and id_municipio IN (?M)' where id_layer = (SELECT id_layer from layers where name = 'VERT_ENCUESTADO_M50_SHP');
--UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_tramos_carreteras"."GEOMETRY", ?T) as "GEOMETRY", id, id_municipio, fase, eiel_c_tramos_carreteras.codprov, eiel_c_tramos_carreteras.cod_carrt, eiel_c_tramos_carreteras.codmunic, pki FROM eiel_configuracion_shp, "eiel_c_tramos_carreteras" LEFT JOIN eiel_t_padron_ttmm ON eiel_t_padron_ttmm.codprov::text = eiel_c_tramos_carreteras.codprov::text AND eiel_t_padron_ttmm.codmunic::text = eiel_c_tramos_carreteras.codmunic::text WHERE eiel_t_padron_ttmm.total_poblacion_a1 < 50000 AND eiel_t_padron_ttmm.revision_expirada = 9999999999::bigint::numeric AND eiel_c_tramos_carreteras.revision_expirada = 9999999999::bigint::numeric and "eiel_c_tramos_carreteras"."id_municipio" in (?M) and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY''' where id_layer = (SELECT id_layer from layers where name = 'TRAMO_CARRETERA_SHP');
UPDATE QUERIES SET selectquery = 'SELECT transform("eiel_c_tramos_carreteras"."GEOMETRY" , ?T) as "GEOMETRY", id, id_municipio, fase, codprov, cod_carrt, codmunic, pki FROM "eiel_c_tramos_carreteras", eiel_configuracion_shp WHERE "eiel_c_tramos_carreteras"."id_municipio" in (?M) and revision_expirada = 9999999999 and "GEOMETRY" is not null AND astext("GEOMETRY") != ''GEOMETRYCOLLECTION EMPTY''' where id_layer = (SELECT id_layer from layers where name = 'TRAMO_CARRETERA_SHP');
