/**
 * CSigmFrame.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package com.geopista.app.administrador.sigm;

import java.awt.BorderLayout;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.ResourceBundle;

import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

import org.apache.log4j.Logger;

import com.geopista.app.administrador.init.Constantes;
import com.geopista.global.ServletConstants;
import com.geopista.protocol.administrador.Entidad;
import com.geopista.protocol.administrador.ListaAcl;
import com.geopista.protocol.administrador.ListaApp;
import com.geopista.protocol.administrador.ListaEntidades;
import com.geopista.protocol.administrador.ListaRoles;
import com.geopista.protocol.administrador.ListaUsuarios;
import com.geopista.protocol.administrador.OperacionesAdministrador;
import com.localgis.client.sigm.SigmClient;
import com.localgis.web.core.model.Procedure;


public class CSigmFrame extends javax.swing.JInternalFrame {
	Logger logger = Logger.getLogger(CSigmFrame.class);
    private ListaRoles listaRoles= null;
    private ListaAcl listaAcl=null;
    private ListaApp listaApp=null;
    private List<Procedure> procedures;
    private ListaEntidades listaEntidades;
    private JFrame framePadre;

	public CSigmFrame(ResourceBundle messages, JFrame framePadre) {
        this.framePadre = framePadre;
        initListas();
		initComponents(messages);

    }
    public void editable(boolean b)
    {
        jPanelSigm.editable(b);
    }
    
    
  
    
  
    
    
    public boolean changeScreenLang(ResourceBundle messages) {
        setTitle(messages.getString("CSigmFrame.title"));

        salirJButton.setText(messages.getString("CSigmFrame.salirJButton"));
        salirJButton.setToolTipText(messages.getString("CSigmFrame.salirJButton"));
        jPanelSigm.changeScreenLang(messages);
        return true;
	}
	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    private void initComponents(ResourceBundle messages) {//GEN-BEGIN:initComponents



        templateJScrollPane = new javax.swing.JScrollPane();
        templateJPanel = new javax.swing.JPanel();
        salirJButton = new javax.swing.JButton();
        jPanelSigm = new JPanelSigm(messages, framePadre);
        botoneraJPanel = new javax.swing.JPanel();
       

        templateJPanel.setLayout(new BorderLayout());
        botoneraJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botoneraJPanel.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 1, 1, 1)));
        salirJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir();
            }
        });

        botoneraJPanel.add(salirJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 90, -1));

        //templateJPanel.add(botoneraJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 990, 40));
        templateJPanel.add(botoneraJPanel, java.awt.BorderLayout.SOUTH);

      

        //templateJPanel.add(usuariosRolesJTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 580));
        //templateJPanel.add(sigmJTabbedPane, java.awt.BorderLayout.CENTER);
        templateJPanel.add(jPanelSigm, java.awt.BorderLayout.CENTER);

        templateJScrollPane.setViewportView(templateJPanel);

        getContentPane().add(templateJScrollPane, java.awt.BorderLayout.CENTER);

        jPanelSigm.pintarProcedures(procedureListToMap(procedures));
        changeScreenLang(messages);
    }//GEN-END:initComponents
    
    private void initListas()
    {
        try
        {
        	procedures = new SigmClient(Constantes.url + ServletConstants.SIGM_SERVLET).getAllProcedures();
        }catch(Exception e)
		 {
		       logger.error("Error al inicializa las listas: ", e);
               JOptionPane optionPane= new JOptionPane(e.getMessage(),JOptionPane.ERROR_MESSAGE);
               JDialog dialog =optionPane.createDialog(this,"");
               dialog.show();
		 }
    }

    private void salir() {
        dispose();
    }

	public boolean excedeLongitud(String campo, int maxLengthPermitida) {
		if (campo.length() > maxLengthPermitida)
			return true;
		else
			return false;
	}

	public HashMap<String, Procedure> procedureListToMap(List<Procedure> proceduresList){
		HashMap<String, Procedure> procedures = new HashMap<String, Procedure>();
		if(proceduresList!=null){
			Iterator<Procedure> it = proceduresList.iterator();
			while(it.hasNext()){
				 Procedure procedure = it.next();
				 procedures.put(procedure.getId(), procedure);
			}		
		}
		return procedures;
	}

	/*********************************************************************/

	/**
	 * Exit the Application
	 */
	private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        try
        {
              com.geopista.security.SecurityManager.logout();
        }catch(Exception ex)
        {
            logger.error("Error al realizar la desconexión:"+ex.toString());
            JOptionPane optionPane= new JOptionPane(ex.getMessage(),JOptionPane.ERROR_MESSAGE);
            JDialog dialog =optionPane.createDialog(this,"");
            dialog.show();
        }

		System.exit(0);
	}//GEN-LAST:event_exitForm

    // Variables declaration - do not modify//GEN-BEGIN:variables

    private JPanelSigm  jPanelSigm;
    private javax.swing.JButton salirJButton;
    private javax.swing.JPanel templateJPanel;
    private javax.swing.JScrollPane templateJScrollPane;
    private javax.swing.JPanel botoneraJPanel;



    // End of variables declaration//GEN-END:variables

}

