package com.geopista.app.cementerios.business.dao.interfaces;

import java.sql.SQLException;
import java.util.List;

import com.geopista.app.cementerios.business.vo.RelTitular;
import com.geopista.app.cementerios.business.vo.RelTitularKey;

public interface RelTitularDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.reltitular
	 * @ibatorgenerated  Tue May 03 16:38:46 CEST 2011
	 */
	int deleteByPrimaryKey(RelTitularKey key) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.reltitular
	 * @ibatorgenerated  Tue May 03 16:38:46 CEST 2011
	 */
	void insert(RelTitular record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.reltitular
	 * @ibatorgenerated  Tue May 03 16:38:46 CEST 2011
	 */
	void insertSelective(RelTitular record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.reltitular
	 * @ibatorgenerated  Tue May 03 16:38:46 CEST 2011
	 */
	RelTitular selectByPrimaryKey(RelTitularKey key) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.reltitular
	 * @ibatorgenerated  Tue May 03 16:38:46 CEST 2011
	 */
	int updateByPrimaryKeySelective(RelTitular record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.reltitular
	 * @ibatorgenerated  Tue May 03 16:38:46 CEST 2011
	 */
	int updateByPrimaryKey(RelTitular record) throws SQLException;

	List selectByConcesion (Integer id_concesion) throws SQLException;
	
	public List selectAll () throws SQLException;

	List selectByTitular (String dni_persona) throws SQLException;
	
//	/**
//	 * Set the iBATIS Database Layer SqlMapClient to work with.
//	 * @param sqlMapper
//	 */
//	void setSqlMapClient(SqlMapClient sqlMapper) throws SQLException;;
	
	
	
}