package com.geopista.app.cementerios.business.dao.interfaces;

import com.geopista.app.cementerios.business.vo.DocumentoTipo;
import com.geopista.app.cementerios.business.vo.DocumentoTipoExample;

import java.sql.SQLException;
import java.util.List;

public interface DocumentoTipoDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.documento_tipos
	 * @throws SQLException 
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	int deleteByExample(DocumentoTipoExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.documento_tipos
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	int deleteByPrimaryKey(Short tipo) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.documento_tipos
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	void insert(DocumentoTipo record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.documento_tipos
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	void insertSelective(DocumentoTipo record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.documento_tipos
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	List selectByExample(DocumentoTipoExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.documento_tipos
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	DocumentoTipo selectByPrimaryKey(Short tipo) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.documento_tipos
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	int updateByExampleSelective(DocumentoTipo record,
			DocumentoTipoExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.documento_tipos
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	int updateByExample(DocumentoTipo record, DocumentoTipoExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.documento_tipos
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	int updateByPrimaryKeySelective(DocumentoTipo record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.documento_tipos
	 * @ibatorgenerated  Tue Jun 07 11:18:50 CEST 2011
	 */
	int updateByPrimaryKey(DocumentoTipo record) throws SQLException;
}