package com.geopista.app.cementerios.business.dao.interfaces;

import java.sql.SQLException;
import java.util.List;

import com.geopista.app.cementerios.business.vo.elem_cementerio;
import com.geopista.app.cementerios.business.vo.elem_cementerioExample;

public interface elem_cementerioDAO {
    /**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.elem_cementerio
     * @throws SQLException 
	 * @ibatorgenerated  Fri Jun 10 13:12:03 CEST 2011
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.elem_cementerio
	 * @ibatorgenerated  Fri Jun 10 13:12:03 CEST 2011
	 */
	Integer insert(elem_cementerio record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.elem_cementerio
	 * @ibatorgenerated  Fri Jun 10 13:12:03 CEST 2011
	 */
	Integer insertSelective(elem_cementerio record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.elem_cementerio
	 * @ibatorgenerated  Fri Jun 10 13:12:03 CEST 2011
	 */
	List selectByExample(elem_cementerioExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.elem_cementerio
	 * @ibatorgenerated  Fri Jun 10 13:12:03 CEST 2011
	 */
	elem_cementerio selectByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.elem_cementerio
	 * @ibatorgenerated  Fri Jun 10 13:12:03 CEST 2011
	 */
	int updateByPrimaryKeySelective(elem_cementerio record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.elem_cementerio
	 * @ibatorgenerated  Fri Jun 10 13:12:03 CEST 2011
	 */
	int updateByPrimaryKey(elem_cementerio record) throws SQLException;

	int selectByLastSeqKey() throws SQLException;
}