package com.geopista.app.cementerios.business.dao.interfaces;

import java.sql.SQLException;
import java.util.List;

import com.geopista.app.cementerios.business.vo.Tarifa;
import com.geopista.app.cementerios.business.vo.TarifaExample;

public interface TarifaDAO {
    /**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.tarifa
     * @throws SQLException 
	 * @ibatorgenerated  Tue Jul 05 08:57:18 CEST 2011
	 */
	int deleteByExample(TarifaExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.tarifa
	 * @ibatorgenerated  Tue Jul 05 08:57:18 CEST 2011
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.tarifa
	 * @ibatorgenerated  Tue Jul 05 08:57:18 CEST 2011
	 */
	Integer insert(Tarifa record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.tarifa
	 * @ibatorgenerated  Tue Jul 05 08:57:18 CEST 2011
	 */
	Integer insertSelective(Tarifa record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.tarifa
	 * @ibatorgenerated  Tue Jul 05 08:57:18 CEST 2011
	 */
	List selectByExample(TarifaExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.tarifa
	 * @ibatorgenerated  Tue Jul 05 08:57:18 CEST 2011
	 */
	Tarifa selectByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.tarifa
	 * @ibatorgenerated  Tue Jul 05 08:57:18 CEST 2011
	 */
	int updateByExampleSelective(Tarifa record, TarifaExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.tarifa
	 * @ibatorgenerated  Tue Jul 05 08:57:18 CEST 2011
	 */
	int updateByExample(Tarifa record, TarifaExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.tarifa
	 * @ibatorgenerated  Tue Jul 05 08:57:18 CEST 2011
	 */
	int updateByPrimaryKeySelective(Tarifa record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table cementerio.tarifa
	 * @ibatorgenerated  Tue Jul 05 08:57:18 CEST 2011
	 */
	int updateByPrimaryKey(Tarifa record) throws SQLException;

	int selectByLastSeqKey()throws SQLException;
    
    List selectAll ()throws SQLException;
    
    List selectAllByCementery(Integer idCementerio) throws SQLException;
    
    List selectByCementerioAndType(Integer idCementerio, Integer tipoTarifa) throws SQLException;
    
}