package com.geopista.app.licencias.utilidades;

import com.geopista.app.utilidades.JPanelPintarImagen;

import java.awt.*;



/**
 * The GEOPISTA project is a set of tools and applications to manage
 * geographical data for local administrations.
 *
 * Copyright (C) 2004 INZAMAC-SATEC UTE
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
 USA.
 *
 * For more information, contact:
 *
 *
 * www.geopista.com
 *
 *
 */


/**
 * Created by IntelliJ IDEA.
 * User: angeles
 * Date: 31-may-2005
 * Time: 19:57:36
 */
public class JDialogWorkFlow extends javax.swing.JDialog {
    private int idEstado;
    private int idTipoLicencia;
    private final String directorio="img/workflow/";
    private final String extension=".jpg";
    /** Creates new form JDialogImagen */
    public JDialogWorkFlow(java.awt.Frame parent, int idEstado, int idTipoLicencia) {
        super(parent, false);
        this.idEstado=idEstado;
        this.idTipoLicencia=idTipoLicencia;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanelPrincipal = new javax.swing.JPanel();
        jPanelImagen = new JPanelPintarImagen(directorio+idEstado+extension);
        jPanelBotonera = new javax.swing.JPanel();
        jButtonCerrar = new javax.swing.JButton();
        jScrollPaneImagen= new javax.swing.JScrollPane();
        jScrollPaneImagen.setBackground(Color.WHITE);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jPanelPrincipal.setLayout(new java.awt.BorderLayout());
        jScrollPaneImagen.setViewportView(jPanelImagen);
        jPanelPrincipal.add(jScrollPaneImagen, java.awt.BorderLayout.CENTER);
        getContentPane().add(jPanelPrincipal, java.awt.BorderLayout.CENTER);

        jButtonCerrar.setText("Cerrar");
        setTitle("WorkFlow");
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               dispose();
            }
        });

        jPanelBotonera.add(jButtonCerrar);
        getContentPane().add(jPanelBotonera, java.awt.BorderLayout.SOUTH);

        pack();

    }
    public void setEstado(int idEstado)
    {
        this.idEstado=idEstado;
        jPanelImagen.setImage(directorio+idTipoLicencia+"_"+idEstado+extension);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JPanel jPanelBotonera;
    public  JPanelPintarImagen jPanelImagen;
    public  javax.swing.JPanel jPanelPrincipal;
    public  javax.swing.JScrollPane jScrollPaneImagen;
    // End of variables declaration//GEN-END:variables

}
