/**
 * The GEOPISTA project is a set of tools and applications to manage
 * geographical data for local administrations.
 *
 * Copyright (C) 2004 INZAMAC-SATEC UTE
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
 USA.
 *
 * For more information, contact:
 *
 *
 * www.geopista.com
 *
 *
 */

package com.geopista.app.contaminantes.panel;

import com.geopista.protocol.contaminantes.Inspeccion;
import com.geopista.protocol.contaminantes.Inspector;
import com.geopista.app.utilidades.JNumberTextField;
import com.geopista.app.utilidades.CalendarButton;


import javax.swing.*;
import java.util.ResourceBundle;
import java.util.Calendar;
import java.text.SimpleDateFormat;
import java.awt.*;

import org.apache.log4j.Logger;

/**
 *
 * @author  angeles
 */
public class JPanelInspeccion extends javax.swing.JPanel {
    public static Logger logger= Logger.getLogger(JPanelInspeccion.class);

    private ResourceBundle messages;
    private Frame parent;
    private String idInspector;
    JDialogInspectores dialogInspectores;
    AnexosJPanel anexosJPanel;
      /** Creates new form JPanelInspeccion */
    public JPanelInspeccion(ResourceBundle messages, Frame parent) {
        this.messages=messages;
        this.parent=parent;
        initComponents();
        changeScreenLang(messages);
        dialogInspectores= new JDialogInspectores(parent, true, messages);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jTextFieldNumFolios = new JNumberTextField(JNumberTextField.NUMBER,new Integer(9999));
        jPanelAnexos = new javax.swing.JPanel();
        jPanelFecha = new javax.swing.JPanel();
        jTextFieldFechaInicio = new JFormattedTextField((new SimpleDateFormat("dd-MM-yyyy")));
        jLabelFechaInicio = new javax.swing.JLabel();
        jButtonFechaInicio = new CalendarButton(jTextFieldFechaInicio);
        jTextFieldFechaFin = new JFormattedTextField((new SimpleDateFormat("dd-MM-yyyy")));
        jLabelFechaFin = new javax.swing.JLabel();
        jButtonFechaFin = new CalendarButton(jTextFieldFechaFin);
        jPanelFechaRecogida = new javax.swing.JPanel();
        jTextFieldFechaRecInicio = new JFormattedTextField((new SimpleDateFormat("dd-MM-yyyy")));
        jLabelFechaRecInicio = new javax.swing.JLabel();
        jButtonFechaRecInicio = new CalendarButton(jTextFieldFechaRecInicio);
        jTextFieldFechaRecFin = new JFormattedTextField((new SimpleDateFormat("dd-MM-yyyy")));
        jLabelFechaRecFin = new javax.swing.JLabel();
        jButtonFechaRecFin = new CalendarButton(jTextFieldFechaRecFin);
        jTextFieldRecDias = new JNumberTextField(JNumberTextField.NUMBER,new Integer(999));
        jLabelDiasRec = new javax.swing.JLabel();
        jLabelNumFolios = new javax.swing.JLabel();
        jPanelMedicion = new javax.swing.JPanel();
        jLabelFijos = new javax.swing.JLabel();
        jLabelMoviles = new javax.swing.JLabel();
        jTextFieldFijos = new com.geopista.app.utilidades.TextField(500);
        jTextFieldMoviles = new com.geopista.app.utilidades.TextField(500);
        jPanelConcentracion = new javax.swing.JPanel();
        jLabelMinimo = new javax.swing.JLabel();
        jLabelMaximas = new javax.swing.JLabel();
        jTextFieldMin = new com.geopista.app.utilidades.TextField(255);
        jTextFieldMax = new com.geopista.app.utilidades.TextField(255);
        jScrollPaneSustancias = new javax.swing.JScrollPane();
        jTextPaneSustancias = new com.geopista.app.utilidades.TextPane(500);
        jPanelZonaLantente = new javax.swing.JPanel();
        jCheckBoxZonaLatente = new javax.swing.JCheckBox();
        jScrollPaneZonaLantente = new javax.swing.JScrollPane();
        jTextPaneZonaLatente = new com.geopista.app.utilidades.TextPane(500);
        jLabelMotivo = new javax.swing.JLabel();
        jLabelInpector = new javax.swing.JLabel();
        jTextFieldInspector = new javax.swing.JTextField();
        jButtonInpector = new javax.swing.JButton();
        jPanelZonaSaturada = new javax.swing.JPanel();
        jCheckBoxZonaSaturada = new javax.swing.JCheckBox();
        jScrollPaneZonaSaturada = new javax.swing.JScrollPane();
        jTextPaneZonaSaturada = new com.geopista.app.utilidades.TextPane(500);
        jLabelMotivoSatu = new javax.swing.JLabel();
        jTabbedPaneDatos = new javax.swing.JTabbedPane();
        jPanelRiesgos = new javax.swing.JPanel();
        jScrollPaneRiesgos = new javax.swing.JScrollPane();
        jTextPaneRiesgos = new com.geopista.app.utilidades.TextPane(500);
        jPanelMedidas = new javax.swing.JPanel();
        jScrollPaneMedidas = new javax.swing.JScrollPane();
        jTextPaneMedidas = new com.geopista.app.utilidades.TextPane(500);
        jPanelResultados = new javax.swing.JPanel();
        jScrollPaneResultados = new javax.swing.JScrollPane();
        jTextPaneResultados = new com.geopista.app.utilidades.TextPane(500);
        jPanelObservaciones = new javax.swing.JPanel();
        jScrollPaneObservaciones = new javax.swing.JScrollPane();
        jTextPaneObs = new com.geopista.app.utilidades.TextPane(500);

        jPanelAnexos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        anexosJPanel= new AnexosJPanel(messages);
        jPanelAnexos.add(anexosJPanel,  new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 15, -1, -1));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jTextFieldNumFolios, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 120, -1));
        add(jPanelAnexos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 650, 100));

        jPanelFecha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTextFieldFechaInicio.setEnabled(false);
        jTextFieldFechaFin.setEnabled(false);
        jTextFieldFechaRecFin.setEnabled(false);
        jTextFieldFechaRecInicio.setEnabled(false);
        jTextFieldInspector.setEnabled(false);
        jPanelFecha.add(jTextFieldFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 110, -1));
        jPanelFecha.add(jLabelFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, -1));
        jPanelFecha.add(jButtonFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 20, 20));
        jPanelFecha.add(jTextFieldFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 110, -1));
        jPanelFecha.add(jLabelFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 50, -1));
        jPanelFecha.add(jButtonFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 20, 20));
        add(jPanelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 230, 90));
        jPanelFechaRecogida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelFechaRecogida.add(jTextFieldFechaRecInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 110, -1));
        jPanelFechaRecogida.add(jLabelFechaRecInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, -1));
        jPanelFechaRecogida.add(jButtonFechaRecInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 20, 20));
        jPanelFechaRecogida.add(jTextFieldFechaRecFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 110, -1));
        jPanelFechaRecogida.add(jLabelFechaRecFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 50, -1));
        jPanelFechaRecogida.add(jButtonFechaRecFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 20, 20));
        jPanelFechaRecogida.add(jTextFieldRecDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 50, -1));
        jPanelFechaRecogida.add(jLabelDiasRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 200, -1));
        add(jPanelFechaRecogida, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 420, 90));
        add(jLabelNumFolios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, -1));
        jPanelMedicion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelMedicion.add(jLabelFijos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, -1));
        jPanelMedicion.add(jLabelMoviles, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 50, -1));
        jPanelMedicion.add(jTextFieldFijos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 560, -1));
        jPanelMedicion.add(jTextFieldMoviles, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 560, -1));
        add(jPanelMedicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 650, 80));
        jPanelConcentracion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelConcentracion.add(jLabelMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 50, -1));
        jPanelConcentracion.add(jLabelMaximas, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 50, -1));
        jPanelConcentracion.add(jTextFieldMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 250, -1));
        jPanelConcentracion.add(jTextFieldMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 250, -1));
        jScrollPaneSustancias.setViewportView(jTextPaneSustancias);
        jPanelConcentracion.add(jScrollPaneSustancias, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 630, 40));
        add(jPanelConcentracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 650, 100));
        jPanelZonaLantente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelZonaLantente.add(jCheckBoxZonaLatente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 100, -1));
        jScrollPaneZonaLantente.setViewportView(jTextPaneZonaLatente);
        jPanelZonaLantente.add(jScrollPaneZonaLantente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 290, 50));
        jPanelZonaLantente.add(jLabelMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 90, -1));
        add(jPanelZonaLantente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 310, 100));
        add(jLabelInpector, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 100, -1));
        add(jTextFieldInspector, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 310, -1));

        jButtonInpector.setIcon(com.geopista.app.contaminantes.utils.CUtilidades.iconoBuscar);
        add(jButtonInpector, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 20, 20));
        jButtonInpector.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                         buscarInspector();
                    }
                });

        jPanelZonaSaturada.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelZonaSaturada.add(jCheckBoxZonaSaturada, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 130, -1));
        jScrollPaneZonaSaturada.setViewportView(jTextPaneZonaSaturada);
        jPanelZonaSaturada.add(jScrollPaneZonaSaturada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 290, 50));
        jPanelZonaSaturada.add(jLabelMotivoSatu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 90, -1));
        add(jPanelZonaSaturada, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 310, 100));
        jPanelRiesgos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPaneRiesgos.setViewportView(jTextPaneRiesgos);
        jPanelRiesgos.add(jScrollPaneRiesgos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 650, 50));
        jPanelMedidas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPaneMedidas.setViewportView(jTextPaneMedidas);
        jPanelMedidas.add(jScrollPaneMedidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 650, 50));
        jPanelResultados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPaneResultados.setViewportView(jTextPaneResultados);
        jPanelResultados.add(jScrollPaneResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 650, 50));
        jPanelObservaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPaneObservaciones.setViewportView(jTextPaneObs);
        jPanelObservaciones.add(jScrollPaneObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 650, 50));
        add(jTabbedPaneDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 650, 80));

    }//GEN-END:initComponents


    public void load(Inspeccion inspeccion)
    {
         jTextFieldMax.setText(inspeccion.getCmax());
         jTextFieldMin.setText(inspeccion.getCmin());
         Calendar auxCalendar =Calendar.getInstance();
         if (inspeccion.getFfin()!=null)
               auxCalendar.setTime(inspeccion.getFfin());
         else
              auxCalendar=null;
         jButtonFechaFin.setFecha(auxCalendar);
         auxCalendar =Calendar.getInstance();
         if (inspeccion.getFinicio()!=null)
               auxCalendar.setTime(inspeccion.getFinicio());
         else
              auxCalendar=null;
         jButtonFechaInicio.setFecha(auxCalendar);
        auxCalendar =Calendar.getInstance();
        if (inspeccion.getFfindatos()!=null)
               auxCalendar.setTime(inspeccion.getFfindatos());
        else
                     auxCalendar=null;
        jButtonFechaRecFin.setFecha(auxCalendar);

        auxCalendar =Calendar.getInstance();
        if (inspeccion.getFinidatos()!=null)
               auxCalendar.setTime(inspeccion.getFinidatos());
        else
               auxCalendar=null;
        jButtonFechaRecInicio.setFecha(auxCalendar);
        jTextPaneRiesgos.setText(inspeccion.getFriesgo());
        jTextPaneMedidas.setText(inspeccion.getMedidas());
        jTextPaneZonaLatente.setText(inspeccion.getMotlantente());
        jTextPaneZonaSaturada.setText(inspeccion.getMotsaturada());
        if (inspeccion.getNfolios()!=null)
            jTextFieldNumFolios.setNumber(inspeccion.getNfolios());
        else
            jTextFieldNumFolios.setText("");
        if (inspeccion.getNrec()!=null)
            jTextFieldRecDias.setNumber(inspeccion.getNrec());
        else
            jTextFieldRecDias.setText("");
        jTextPaneObs.setText(inspeccion.getObs());
        jTextFieldFijos.setText(inspeccion.getPfijos());
        jTextFieldMoviles.setText(inspeccion.getPmoviles());
        jTextPaneResultados.setText(inspeccion.getResultados());
        jTextPaneSustancias.setText(inspeccion.getSustancias());
        jCheckBoxZonaLatente.setSelected(inspeccion.isZlatente());
        jCheckBoxZonaSaturada.setSelected(inspeccion.isZsaturada());
        idInspector=inspeccion.getId_res();
        if (inspeccion.getId_res()!=null)
        {
            Inspector aux= dialogInspectores.getInspector(inspeccion.getId_res());
            if (aux!=null)
            {
                jTextFieldInspector.setText(aux.toString());
            }

        }

        anexosJPanel.setInspeccion(inspeccion);
    }


    public Inspeccion guardarCambios(Inspeccion inspeccion)
    {
         if (inspeccion==null) inspeccion=new Inspeccion();
         inspeccion.setId_res(idInspector);
         inspeccion.setCmax(jTextFieldMax.getText());
         inspeccion.setCmin(jTextFieldMin.getText());

        /** Comprobamos que la fecha de inicio de la inspeccion sea anterior o igual a la fecha fin
         * de la inspeccion. */
        if ((jTextFieldFechaFin.getText().length()>0) && (jTextFieldFechaInicio.getText().length()>0)){
            if (jButtonFechaInicio.getCalendar().getTime().compareTo(jButtonFechaFin.getCalendar().getTime()) > 0){
                JOptionPane.showMessageDialog(parent, messages.getString("jPanelInspeccion.mensaje2"));
                return null;
            }
        }
         if (jTextFieldFechaFin.getText().length()<=0)
             inspeccion.setFfin(null);
         else
             inspeccion.setFfin(jButtonFechaFin.getCalendar().getTime());

         if (jTextFieldFechaInicio.getText().length()<=0)
             inspeccion.setFinicio(null);
         else
             inspeccion.setFinicio(jButtonFechaInicio.getCalendar().getTime());

        /** Comprobamos que la fecha  de recogida de inicio sea anterior o igual a la fecha fin
         * de recogida de datos. */
         if ((jTextFieldFechaRecFin.getText().length()>0) && (jTextFieldFechaRecInicio.getText().length()>0)){
             if (jButtonFechaRecInicio.getCalendar().getTime().compareTo(jButtonFechaRecFin.getCalendar().getTime()) > 0){
                 JOptionPane.showMessageDialog(parent, messages.getString("jPanelInspeccion.mensaje1"));
                 return null;
             }
         }
         if (jTextFieldFechaRecFin.getText().length()<=0)
             inspeccion.setFfindatos(null);
         else
             inspeccion.setFfindatos(jButtonFechaRecFin.getCalendar().getTime());

         if (jTextFieldFechaRecInicio.getText().length()<=0)
             inspeccion.setFinidatos(null);
         else
             inspeccion.setFinidatos(jButtonFechaRecInicio.getCalendar().getTime());

        
         inspeccion.setFriesgo(jTextPaneRiesgos.getText());
         inspeccion.setMedidas(jTextPaneMedidas.getText());
         inspeccion.setMotlantente(jTextPaneZonaLatente.getText());
         inspeccion.setMotsaturada(jTextPaneZonaSaturada.getText());
         try{
         if(jTextFieldNumFolios.getText().length()<=0)
              inspeccion.setNfolios(null);
         else
              inspeccion.setNfolios(jTextFieldNumFolios.getNumber()==null?null:new Integer(jTextFieldNumFolios.getNumber().intValue()));
         }catch (Exception e){};

         try{
         if (jTextFieldRecDias.getText().length()<=0)
              inspeccion.setNrec(null);
         else
              inspeccion.setNrec(jTextFieldRecDias.getNumber()==null?null:new Integer(jTextFieldRecDias.getNumber().intValue()));
         }catch (Exception e){};

         inspeccion.setObs(jTextPaneObs.getText());
         inspeccion.setPfijos(jTextFieldFijos.getText());
         inspeccion.setPmoviles(jTextFieldMoviles.getText());
         inspeccion.setResultados(jTextPaneResultados.getText());
         inspeccion.setSustancias(jTextPaneSustancias.getText());
         inspeccion.setZlatente(jCheckBoxZonaLatente.isSelected());
         inspeccion.setZsaturada(jCheckBoxZonaSaturada.isSelected());
         inspeccion.setAnexos(anexosJPanel.getListaAnexos());

        return inspeccion;
    }
    private void changeScreenLang(ResourceBundle messages)
    {
        try
        {
            this.messages=messages;
            jTabbedPaneDatos.addTab(messages.getString("jPanelInspeccion.tabObservaciones"), jPanelObservaciones);//"Observaciones"
            jTabbedPaneDatos.addTab(messages.getString("jPanelInspeccion.tabResultados"), jPanelResultados);//"Resultados"
            jTabbedPaneDatos.addTab(messages.getString("jPanelInspeccion.tabMedidas"), jPanelMedidas);//"Medidas a adoptar"
            jTabbedPaneDatos.addTab(messages.getString("jPanelInspeccion.tabFactores"), jPanelRiesgos);//"Factores de riesgo"
            jLabelMotivoSatu.setText(messages.getString("jPanelInspeccion.jLabelMotivoSatu"));//Motivo:");
            jCheckBoxZonaSaturada.setText(messages.getString("jPanelInspeccion.jCheckBoxZonaSaturada"));//Es zona saturada");
            jLabelInpector.setText(messages.getString("jPanelInspeccion.jLabelInpector"));//Inspector:");
            jLabelMotivo.setText(messages.getString("jPanelInspeccion.jLabelMotivo"));//Motivo:");
            jCheckBoxZonaLatente.setText(messages.getString("jPanelInspeccion.jCheckBoxZonaLatente"));//Es zona latente");
            jLabelMaximas.setText(messages.getString("jPanelInspeccion.jLabelMaximas"));//M\u00e1ximas:");
            jLabelMinimo.setText(messages.getString("jPanelInspeccion.jLabelMinimas"));//M\u00ednimo:");
            jPanelAnexos.setBorder(new javax.swing.border.TitledBorder(messages.getString("jPanelInspeccion.jPanelAnexos")));//Anexos"));
            jPanelFechaRecogida.setBorder(new javax.swing.border.TitledBorder(messages.getString("jPanelInspeccion.jPanelFechaRecogida")));//Fecha de la recogida de datos"));
            jPanelFechaRecogida.setToolTipText(messages.getString("jPanelInspeccion.jPanelFechaRecogida"));//Fecha de la recogida de datos");
            jPanelFecha.setToolTipText(messages.getString("jPanelInspeccion.jPanelFecha"));//Fecha de la inspecci\u00f3n");
            jLabelDiasRec.setText(messages.getString("jPanelInspeccion.jLabelDiasRec"));//Numero de d\u00edas de recogida de datos:");
            jLabelNumFolios.setText(messages.getString("jPanelInspeccion.jLabelNumFolios"));//Numero de folios:");
            jPanelZonaLantente.setBorder(new javax.swing.border.TitledBorder(messages.getString("jPanelInspeccion.jPanelZonaLatente")));//Zona Latente"));
            jLabelMoviles.setText(messages.getString("jPanelInspeccion.jLabelMoviles"));//Moviles:");
            jLabelFechaRecFin.setText(messages.getString("jPanelInspeccion.jLabelFechaRecFin"));//Fin:");
            jPanelFecha.setBorder(new javax.swing.border.TitledBorder(messages.getString("jPanelInspeccion.jPanelFecha")));//Fecha de la inspecci\u00f3n"));
            jLabelFechaInicio.setText(messages.getString("jPanelInspeccion.jLabelFechaInicio"));//Inicio:");
            jLabelFechaRecInicio.setText(messages.getString("jPanelInspeccion.jLabelFechaRecInicio"));//Inicio:");
            jLabelFechaFin.setText(messages.getString("jPanelInspeccion.jLabelFechaFin"));//Fin:");
            jPanelMedicion.setBorder(new javax.swing.border.TitledBorder(messages.getString("jPanelInspeccion.jPanelMedicion")));//Puntos de medici\u00f3n"));
            jLabelFijos.setText(messages.getString("jPanelInspeccion.jLabelFijos"));//Fijos:");
            jPanelConcentracion.setBorder(new javax.swing.border.TitledBorder(messages.getString("jPanelInspeccion.jPanelConcentracion")));//Sustancias contaminantes"));
            jPanelZonaSaturada.setBorder(new javax.swing.border.TitledBorder(messages.getString("jPanelInspeccion.jPanelZonaSaturada")));//Zona Saturada"));

            jButtonFechaFin.setToolTipText(messages.getString("jPanelInspeccion.toolTip.jButtonFechaFin"));
            jButtonFechaInicio.setToolTipText(messages.getString("jPanelInspeccion.toolTip.jButtonFechaInicio"));
            jButtonFechaRecFin.setToolTipText(messages.getString("jPanelInspeccion.toolTip.jButtonFechaRecFin"));
            jButtonFechaRecInicio.setToolTipText(messages.getString("jPanelInspeccion.toolTip.jButtonFechaRecInicio"));
            jButtonInpector.setToolTipText(messages.getString("jPanelInspeccion.toolTip.jButtonInpector"));
        }catch(Exception e)
        {
           logger.error("Error al cargar las etiquetas: ",e);
        }
    }
     private void buscarInspector() {
           dialogInspectores.setLocation(50,50);
           dialogInspectores.setResizable(false);
           if (idInspector!=null) dialogInspectores.load(idInspector);
           dialogInspectores.show();
           if (dialogInspectores.isSeleccionado()&&dialogInspectores.getInspectorSelected()!=null)
           {
               Inspector inspector=dialogInspectores.getInspectorSelected();
               if (inspector!=null)
               {
                  idInspector=inspector.getId();
                  jTextFieldInspector.setText(inspector.toString());
               }
           }
           //dialogInspectores=null;
    }

    public void enabled(boolean bValor)
    {
          jTextFieldNumFolios.setEditable(bValor);
          jButtonFechaFin.setEnabled(bValor);
          jButtonFechaInicio.setEnabled(bValor);
          jButtonFechaRecFin.setEnabled(bValor);
          jButtonFechaRecInicio.setEnabled(bValor);
          jButtonInpector.setEnabled(bValor);
          jTextFieldFechaFin.setEditable(bValor);
          jTextFieldFechaInicio.setEditable(bValor);
          jTextFieldFechaRecFin.setEditable(bValor);
          jTextFieldFechaRecInicio.setEditable(bValor);
          jTextFieldFijos.setEditable(bValor);
          jTextFieldInspector.setEditable(bValor);
          jTextFieldMax.setEditable(bValor);
          jTextFieldMin.setEditable(bValor);
          jTextFieldMoviles.setEditable(bValor);
          jTextFieldRecDias.setEditable(bValor);
          jTextPaneMedidas.setEnabled(bValor);
          jTextPaneMedidas.setBackground(!bValor?Color.LIGHT_GRAY:Color.WHITE);
          jTextPaneObs.setEnabled(bValor);
          jTextPaneObs.setBackground(!bValor?Color.LIGHT_GRAY:Color.WHITE);
          jTextPaneResultados.setEnabled(bValor);
          jTextPaneResultados.setBackground(!bValor?Color.LIGHT_GRAY:Color.WHITE);
          jTextPaneRiesgos.setEnabled(bValor);
          jTextPaneRiesgos.setBackground(!bValor?Color.LIGHT_GRAY:Color.WHITE);
          jTextPaneSustancias.setEnabled(bValor);
          jTextPaneSustancias.setBackground(!bValor?Color.LIGHT_GRAY:Color.WHITE);
          jTextPaneZonaLatente.setEnabled(bValor);
          jTextPaneZonaLatente.setBackground(!bValor?Color.LIGHT_GRAY:Color.WHITE);
          jTextPaneZonaSaturada.setEnabled(bValor);
          jTextPaneZonaSaturada.setBackground(!bValor?Color.LIGHT_GRAY:Color.WHITE);
          jCheckBoxZonaLatente.setEnabled(bValor);
          jCheckBoxZonaSaturada.setEnabled(bValor);
          anexosJPanel.enabled(bValor);

    }

    public AnexosJPanel getAnexosJPanel(){
        return this.anexosJPanel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CalendarButton jButtonFechaFin;
    private CalendarButton jButtonFechaInicio;
    private CalendarButton jButtonFechaRecFin;
    private CalendarButton jButtonFechaRecInicio;
    private javax.swing.JButton jButtonInpector;
    private javax.swing.JCheckBox jCheckBoxZonaLatente;
    private javax.swing.JCheckBox jCheckBoxZonaSaturada;
    private javax.swing.JLabel jLabelDiasRec;
    private javax.swing.JLabel jLabelFechaFin;
    private javax.swing.JLabel jLabelFechaInicio;
    private javax.swing.JLabel jLabelFechaRecFin;
    private javax.swing.JLabel jLabelFechaRecInicio;
    private javax.swing.JLabel jLabelFijos;
    private javax.swing.JLabel jLabelInpector;
    private javax.swing.JLabel jLabelMaximas;
    private javax.swing.JLabel jLabelMinimo;
    private javax.swing.JLabel jLabelMotivo;
    private javax.swing.JLabel jLabelMotivoSatu;
    private javax.swing.JLabel jLabelMoviles;
    private javax.swing.JLabel jLabelNumFolios;
    private javax.swing.JPanel jPanelAnexos;
    private javax.swing.JPanel jPanelConcentracion;
    private javax.swing.JPanel jPanelFecha;
    private javax.swing.JPanel jPanelFechaRecogida;
    private javax.swing.JPanel jPanelMedicion;
    private javax.swing.JPanel jPanelMedidas;
    private javax.swing.JPanel jPanelObservaciones;
    private javax.swing.JPanel jPanelResultados;
    private javax.swing.JPanel jPanelRiesgos;
    private javax.swing.JPanel jPanelZonaLantente;
    private javax.swing.JPanel jPanelZonaSaturada;
    private javax.swing.JScrollPane jScrollPaneMedidas;
    private javax.swing.JScrollPane jScrollPaneObservaciones;
    private javax.swing.JScrollPane jScrollPaneResultados;
    private javax.swing.JScrollPane jScrollPaneRiesgos;
    private javax.swing.JScrollPane jScrollPaneSustancias;
    private javax.swing.JScrollPane jScrollPaneZonaLantente;
    private javax.swing.JScrollPane jScrollPaneZonaSaturada;
    private javax.swing.JTabbedPane jTabbedPaneDatos;
    private JFormattedTextField jTextFieldFechaFin;
    private JFormattedTextField jTextFieldFechaInicio;
    private JFormattedTextField jTextFieldFechaRecFin;
    private JFormattedTextField jTextFieldFechaRecInicio;
    private com.geopista.app.utilidades.TextField jTextFieldFijos;
    private javax.swing.JTextField jTextFieldInspector;
    private com.geopista.app.utilidades.TextField jTextFieldMax;
    private com.geopista.app.utilidades.TextField jTextFieldMin;
    private com.geopista.app.utilidades.TextField jTextFieldMoviles;
    private JNumberTextField jTextFieldNumFolios;
    private JNumberTextField jTextFieldRecDias;
    private com.geopista.app.utilidades.TextPane jTextPaneMedidas;
    private com.geopista.app.utilidades.TextPane jTextPaneObs;
    private com.geopista.app.utilidades.TextPane jTextPaneResultados;
    private com.geopista.app.utilidades.TextPane jTextPaneRiesgos;
    private com.geopista.app.utilidades.TextPane jTextPaneSustancias;
    private com.geopista.app.utilidades.TextPane jTextPaneZonaLatente;
    private com.geopista.app.utilidades.TextPane jTextPaneZonaSaturada;
    // End of variables declaration//GEN-END:variables
    
}
