/**
 * CSesionesFrame.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
/*
 * CSesionesFrame.java
 *
 * Created on 16 de junio de 2004, 15:13
 */

package com.geopista.app.administrador.sesiones;

import java.util.ResourceBundle;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableColumn;

import org.apache.log4j.Logger;

import com.geopista.app.administrador.init.Constantes;
import com.geopista.app.utilidades.TableSorted;
import com.geopista.protocol.administrador.OperacionesAdministrador;
import com.geopista.protocol.control.ListaSesionesSimple;


/**
 *
 * @author  angeles
 */
public class CSesionesFrame extends javax.swing.JInternalFrame {
    Logger logger = Logger.getLogger(CSesionesFrame.class);
    SesionesTableModel modelSesiones;
    ListaSesionesSimple listaSesiones=null;
    private TableSorted sorter;
    /** Creates new form CSesionesFrame */
    
    private boolean checkPermission;
    public CSesionesFrame(ResourceBundle messages, boolean checkPermission) {
    	this.checkPermission=checkPermission;
        initListas();
        initComponents();  

    }
    private void initListas()
    {

        try
        {
             listaSesiones= (new OperacionesAdministrador(Constantes.url)).getSesiones();

        }catch(Exception e)
		 {
		       logger.error("Error al inicializa la lista de dominios: "+e.toString());
               JOptionPane optionPane= new JOptionPane(e.getMessage(),JOptionPane.ERROR_MESSAGE);
               JDialog dialog =optionPane.createDialog(this,"ERROR al inicializar las sesiones");
               dialog.show();
		 }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanelSalir = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPaneTablaSesiones = new javax.swing.JScrollPane();
        jTableSesion = new javax.swing.JTable();

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jPanelSalir.add(jButtonSalir);

        getContentPane().add(jPanelSalir, java.awt.BorderLayout.SOUTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        actualizarModelo();
        jScrollPaneTablaSesiones.setViewportView(jTableSesion);

        jPanel1.add(jScrollPaneTablaSesiones, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
         dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed
    
     private void actualizarModelo()
    {
        modelSesiones= new SesionesTableModel(checkPermission);
        modelSesiones.setModelData(listaSesiones);
        sorter = new TableSorted(modelSesiones);
        sorter.setTableHeader(jTableSesion.getTableHeader());
        jTableSesion.setModel(sorter);
        jTableSesion.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public void changeScreenLang(ResourceBundle messages) {
        jButtonSalir.setText(messages.getString("CSesionesFrame.jButtonSalir"));//"Desmarcar todos");
        jButtonSalir.setToolTipText(messages.getString("CSesionesFrame.jButtonSalir"));

        TableColumn tableColumn= jTableSesion.getColumnModel().getColumn(0);
        tableColumn.setHeaderValue(messages.getString("CSesionesFrame.col0"));
        tableColumn= jTableSesion.getColumnModel().getColumn(1);
        tableColumn.setHeaderValue(messages.getString("CSesionesFrame.col1"));
        tableColumn= jTableSesion.getColumnModel().getColumn(2);
        tableColumn.setHeaderValue(messages.getString("CSesionesFrame.col2"));
        tableColumn= jTableSesion.getColumnModel().getColumn(3);
        tableColumn.setHeaderValue(messages.getString("CSesionesFrame.col3"));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelSalir;
    private javax.swing.JScrollPane jScrollPaneTablaSesiones;
    private javax.swing.JTable jTableSesion;
	
    // End of variables declaration//GEN-END:variables
    
}
