/**
 * CDatosReferenciaCatastralJDialog.java
 * © MINETUR, Government of Spain
 * This program is part of LocalGIS
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
/*
 * JSearch.java
 *
 * Created on 4 de mayo de 2004, 12:04
 */

package com.geopista.app.licencias;

import java.io.PrintWriter;
import java.io.StringWriter;
import java.util.ResourceBundle;

import javax.swing.table.DefaultTableModel;

import org.apache.log4j.Logger;

import com.geopista.protocol.licencias.CReferenciaCatastral;

/**
 * @author avivar
 */
public class CDatosReferenciaCatastralJDialog extends javax.swing.JDialog {
    private CReferenciaCatastral _referencia= new CReferenciaCatastral();

	Logger logger = Logger.getLogger(CDatosReferenciaCatastralJDialog.class);
    private ResourceBundle literales;
	/**
	 * Creates new form JSearch
	 */
	public CDatosReferenciaCatastralJDialog(java.awt.Frame parent, boolean modal, boolean mostrarCheck,
                                            ResourceBundle literales) {
		super(parent, modal);
        this.literales=literales;
		initComponents();
		configureComponents(mostrarCheck);
	}

	private void configureComponents(boolean b) {
        tipoViaJTextField.setText(CConstantesLicencias_LCGIII.referencia.getTipoVia());
        nombreViaJTextField.setText(CConstantesLicencias_LCGIII.referencia.getNombreVia());
        numeroViaJTextField.setText(CConstantesLicencias_LCGIII.referencia.getPrimerNumero());
        puertaJTextField.setText(CConstantesLicencias_LCGIII.referencia.getPuerta());
        plantaJTextField.setText(CConstantesLicencias_LCGIII.referencia.getPlanta());
        letraJTextField.setText(CConstantesLicencias_LCGIII.referencia.getPrimeraLetra());
        referenciaJTextField.setText(CConstantesLicencias_LCGIII.referencia.getReferenciaCatastral());
        bloqueJTextField.setText(CConstantesLicencias_LCGIII.referencia.getBloque());
        escaleraJTextField.setText(CConstantesLicencias_LCGIII.referencia.getEscalera());

        esDirEmplazamientoJCheckBox.setVisible(b);
        esDirEmplazamientoJCheckBox.setEnabled(b);
        esDirEmplazamientoJCheckBox.setSelected(false);

		renombrarComponentes();
}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    private void initComponents() {//GEN-BEGIN:initComponents
        datosCatastralesJPanel = new javax.swing.JPanel();
        nombreViaJLabel = new javax.swing.JLabel();
        tipoViaJTextField = new javax.swing.JTextField();
        nombreViaJTextField = new javax.swing.JTextField();
        numeroViaJLabel = new javax.swing.JLabel();
        numeroViaJTextField = new javax.swing.JTextField();
        puertaJTextField = new javax.swing.JTextField();
        plantaJTextField = new javax.swing.JTextField();
        letraJTextField = new javax.swing.JTextField();
        referenciaJLabel = new javax.swing.JLabel();
        referenciaJTextField = new javax.swing.JTextField();
        bloqueJTextField = new javax.swing.JTextField();
        escaleraJTextField = new javax.swing.JTextField();
        escaleraJLabel = new javax.swing.JLabel();
        separadorJLabel = new javax.swing.JLabel();
        separadorJLabel1 = new javax.swing.JLabel();
        separadorJLabel2 = new javax.swing.JLabel();
        separadorJLabel3 = new javax.swing.JLabel();
        separadorJLabel4 = new javax.swing.JLabel();
        salirJButton = new javax.swing.JButton();
        esDirEmplazamientoJCheckBox = new javax.swing.JCheckBox();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Referencia Catastral");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        datosCatastralesJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        datosCatastralesJPanel.setBorder(new javax.swing.border.TitledBorder("Datos Referencia Catastral"));
        nombreViaJLabel.setText("Tipo v\u00eda / Nombre V\u00eda:");
        datosCatastralesJPanel.add(nombreViaJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 170, 20));

        tipoViaJTextField.setEditable(false);
        tipoViaJTextField.setBorder(null);
        datosCatastralesJPanel.add(tipoViaJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 110, 20));

        nombreViaJTextField.setEditable(false);
        nombreViaJTextField.setBorder(null);
        datosCatastralesJPanel.add(nombreViaJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 260, 20));

        numeroViaJLabel.setText("N\u00ba / Letra / Bloque:");
        datosCatastralesJPanel.add(numeroViaJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 170, 20));

        numeroViaJTextField.setEditable(false);
        numeroViaJTextField.setBorder(null);
        datosCatastralesJPanel.add(numeroViaJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 110, 20));

        puertaJTextField.setEditable(false);
        puertaJTextField.setBorder(null);
        datosCatastralesJPanel.add(puertaJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 110, 20));

        plantaJTextField.setEditable(false);
        plantaJTextField.setBorder(null);
        datosCatastralesJPanel.add(plantaJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 120, 20));

        letraJTextField.setEditable(false);
        letraJTextField.setBorder(null);
        datosCatastralesJPanel.add(letraJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 120, 20));

        referenciaJLabel.setText("Referencia Catastral:");
        datosCatastralesJPanel.add(referenciaJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 150, 20));

        referenciaJTextField.setEditable(false);
        referenciaJTextField.setBorder(null);
        datosCatastralesJPanel.add(referenciaJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 380, 20));

        bloqueJTextField.setEditable(false);
        bloqueJTextField.setBorder(null);
        datosCatastralesJPanel.add(bloqueJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 110, 20));

        escaleraJTextField.setEditable(false);
        escaleraJTextField.setBorder(null);
        datosCatastralesJPanel.add(escaleraJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 110, 20));

        escaleraJLabel.setText("Escalera / Planta / Puerta:");
        datosCatastralesJPanel.add(escaleraJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, 20));

        separadorJLabel.setText("/");
        datosCatastralesJPanel.add(separadorJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 10, 20));

        separadorJLabel1.setText("/");
        datosCatastralesJPanel.add(separadorJLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 10, 20));

        separadorJLabel2.setText("/");
        datosCatastralesJPanel.add(separadorJLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 10, 20));

        separadorJLabel3.setText("/");
        datosCatastralesJPanel.add(separadorJLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 10, 20));

        separadorJLabel4.setText("/");
        datosCatastralesJPanel.add(separadorJLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 10, 20));

        getContentPane().add(datosCatastralesJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 600, 150));

        salirJButton.setText("Salir");
        salirJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirJButtonActionPerformed(evt);
            }
        });

        getContentPane().add(salirJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, -1, -1));

        esDirEmplazamientoJCheckBox.setText("Dir. Emplazamiento");
        getContentPane().add(esDirEmplazamientoJCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 460, -1));

        pack();
    }//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (esDirEmplazamientoJCheckBox.isSelected()){
            CConstantesLicencias.esDireccionEmplazamiento= true;
        }else{
            CConstantesLicencias.esDireccionEmplazamiento= false;
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void salirJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirJButtonActionPerformed
        // TODO add your handling code here:
        if (esDirEmplazamientoJCheckBox.isSelected()){
            CConstantesLicencias.esDireccionEmplazamiento= true;
        }else{
            CConstantesLicencias.esDireccionEmplazamiento= false;
        }
        this.dispose();
    }//GEN-LAST:event_salirJButtonActionPerformed


	private DefaultTableModel expedientesJTableModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bloqueJTextField;
    private javax.swing.JPanel datosCatastralesJPanel;
    private javax.swing.JCheckBox esDirEmplazamientoJCheckBox;
    private javax.swing.JLabel escaleraJLabel;
    private javax.swing.JTextField escaleraJTextField;
    private javax.swing.JTextField letraJTextField;
    private javax.swing.JLabel nombreViaJLabel;
    private javax.swing.JTextField nombreViaJTextField;
    private javax.swing.JLabel numeroViaJLabel;
    private javax.swing.JTextField numeroViaJTextField;
    private javax.swing.JTextField plantaJTextField;
    private javax.swing.JTextField puertaJTextField;
    private javax.swing.JLabel referenciaJLabel;
    private javax.swing.JTextField referenciaJTextField;
    private javax.swing.JButton salirJButton;
    private javax.swing.JLabel separadorJLabel;
    private javax.swing.JLabel separadorJLabel1;
    private javax.swing.JLabel separadorJLabel2;
    private javax.swing.JLabel separadorJLabel3;
    private javax.swing.JLabel separadorJLabel4;
    private javax.swing.JTextField tipoViaJTextField;
    // End of variables declaration//GEN-END:variables



		private void renombrarComponentes() {

		try {

			setTitle(literales.getString("CDatosReferenciaCatastralJDialog.JInternalFrame.title"));
			datosCatastralesJPanel.setBorder(new javax.swing.border.TitledBorder(literales.getString("CDatosReferenciaCatastralJDialog.datosCatastralesJPanel.TitleBorder")));
			referenciaJLabel.setText(literales.getString("CDatosReferenciaCatastralJDialog.referenciaJLabel.text"));
			nombreViaJLabel.setText(literales.getString("CDatosReferenciaCatastralJDialog.nombreViaJLabel.text"));
			numeroViaJLabel.setText(literales.getString("CDatosReferenciaCatastralJDialog.numeroViaJLabel.text"));
			escaleraJLabel.setText(literales.getString("CDatosReferenciaCatastralJDialog.escaleraJLabel.text"));
			salirJButton.setText(literales.getString("CDatosReferenciaCatastralJDialog.salirJButton.text"));
            esDirEmplazamientoJCheckBox.setText(literales.getString("CDatosReferenciaCatastralJDialog.DirEmplazamientoJCheckBox.text"));

		} catch (Exception ex) {
			StringWriter sw = new StringWriter();
			PrintWriter pw = new PrintWriter(sw);
			ex.printStackTrace(pw);
			logger.error("Exception: " + sw.toString());
		}
	}
}
